<?xml version="1.0" encoding="utf-8"?>
<!-- Uzyj xsd.exe do wygenerowania z tego kodu -->
<xs:schema 
  xmlns:xs="http://www.w3.org/2001/XMLSchema" 
  elementFormDefault="qualified" 
  xmlns="http://schemas.insert.com.pl/2025/dokumentyDoKsiegowania/rozrachunki" 
  targetNamespace="http://schemas.insert.com.pl/2025/dokumentyDoKsiegowania/rozrachunki" 
  xmlns:ddk="http://schemas.insert.com.pl/2012/dokumentyDoKsiegowania">
  <xs:annotation>
    <xs:documentation>Dane cesji.</xs:documentation>
  </xs:annotation>
  
  <xs:import id="TypyDanychPart" namespace="http://schemas.insert.com.pl/2012/dokumentyDoKsiegowania" schemaLocation="./TypyDanych_2012.xsd" />
  <xs:import id="PolaWlasnePart" namespace="http://schemas.insert.com.pl/2012/dokumentyDoKsiegowania" schemaLocation="./Dane_2012_PolaWlasnePart.xsd" />
  
  <xs:complexType name="TNaglowekCesji">
    <xs:annotation>
      <xs:documentation>Zbiór pól nagłówkowych cesji.</xs:documentation>
    </xs:annotation>
    <xs:sequence>
		<xs:element name="Numer" type="xs:string" nillable="false">
			<xs:annotation>
				<xs:documentation>Numer cesji.</xs:documentation>
			</xs:annotation>
		</xs:element>
		<xs:element name="Kwota" type="xs:decimal" nillable="false">
			<xs:annotation>
				<xs:documentation>Kwota cesji.</xs:documentation>
			</xs:annotation>
		</xs:element>
		<xs:element name="Waluta" type="ddk:TGuid" nillable="false">
			<xs:annotation>
				<xs:documentation>Waluta.</xs:documentation>
			</xs:annotation>
		</xs:element>
      <xs:element name="DataPowstania" type="xs:date" nillable="false">
        <xs:annotation>
          <xs:documentation>Data powstania cesji.</xs:documentation>
        </xs:annotation>
      </xs:element>
		<xs:element name="TerminPlatnosci" type="xs:date" nillable="false">
			<xs:annotation>
				<xs:documentation>Termin płatności cesji.</xs:documentation>
			</xs:annotation>
		</xs:element>
      <xs:element name="Cesjonariusz" type="ddk:TPositiveInt" nillable="false">
        <xs:annotation>
          <xs:documentation>Cesjonariusz którego dotyczy cesja.</xs:documentation>
        </xs:annotation>
      </xs:element>

		<xs:element name="Dokument" type="xs:string" nillable="false">
			<xs:annotation>
				<xs:documentation>Dokument źródłowy rozrachunku.</xs:documentation>
			</xs:annotation>
		</xs:element>
		<xs:element name="DataDokumentu" type="xs:date" nillable="false">
			<xs:annotation>
				<xs:documentation>Data dokumetu źródłowego.</xs:documentation>
			</xs:annotation>
		</xs:element>
		<xs:element name="Wystawiajacy" type="ddk:TPositiveInt" nillable="false">
			<xs:annotation>
				<xs:documentation>Wystawiający dokument cesji.</xs:documentation>
			</xs:annotation>
		</xs:element>
		<xs:element name="Tytulem" type="xs:string" nillable="true">
			<xs:annotation>
				<xs:documentation>Tytułem</xs:documentation>
			</xs:annotation>
		</xs:element>
    <xs:element name="FormaPlatnosci" type="ddk:TPositiveInt" nillable="true">
        <xs:annotation>
          <xs:documentation>Forma płatności.</xs:documentation>
        </xs:annotation>
    </xs:element>
		<xs:element name="DokumentSplatyCesyjnej" type="xs:string" nillable="false">
			<xs:annotation>
				<xs:documentation>Dokument spłaty cesyjnej.</xs:documentation>
			</xs:annotation>
		</xs:element>
		<xs:element name="PodmiotSplatyCesyjnej" type="ddk:TPositiveInt" nillable="true">
			<xs:annotation>
				<xs:documentation>Podmiot spłaty cesyjnej.</xs:documentation>
			</xs:annotation>
		</xs:element>
		<xs:element name="DataDokumentuSplatyCesyjnej" type="xs:date" nillable="false">
			<xs:annotation>
				<xs:documentation>Data dokumetu źródłowego spłaty cesyjnej.</xs:documentation>
			</xs:annotation>
		</xs:element>
		<xs:element name="DataPowstaniaSplatyCesyjnej" type="xs:date" nillable="false">
			<xs:annotation>
				<xs:documentation>Data powstania spłaty cesjnej.</xs:documentation>
			</xs:annotation>
		</xs:element>
		<xs:element name="KwotaSplatyCesyjnej" type="xs:decimal" nillable="false">
			<xs:annotation>
				<xs:documentation>Kwota spłaty cesyjnej.</xs:documentation>
			</xs:annotation>
		</xs:element>
		<xs:element name="WalutaSplatyCesyjnej" type="ddk:TGuid" nillable="false">
			<xs:annotation>
				<xs:documentation>Waluta spłaty cesyjnej.</xs:documentation>
			</xs:annotation>
		</xs:element>

	</xs:sequence>
	  <xs:attribute name="CesjonariuszAdresHistoria" type="ddk:TPositiveInt" use="optional">
		  <xs:annotation>
			  <xs:documentation>Adres cesjonariusza.</xs:documentation>
		  </xs:annotation>
	  </xs:attribute>
	  <xs:attribute name="PodmiotSplatyCesyjnejAdresHistoria" type="ddk:TPositiveInt" use="optional">
		  <xs:annotation>
			  <xs:documentation>Adres podmiotu spłaty cesyjnej.</xs:documentation>
		  </xs:annotation>
	  </xs:attribute>
	  <xs:attribute name="TypRozrachunkuCesyjnego" type="xs:unsignedByte" use="optional">
		  <xs:annotation>
			  <xs:documentation>Typ rozrachunku cesyjnego (1 - należność, 2 - zobowiązanie).</xs:documentation>
		  </xs:annotation>
	  </xs:attribute>
	  <xs:attribute name="IdDokumentuRozliczanego" type="ddk:TGuid" use="optional">
		  <xs:annotation>
			  <xs:documentation>Identyfikator dokumentu rozliczanego przez rozrachunek.</xs:documentation>
		  </xs:annotation>
	  </xs:attribute>
	  <xs:attribute name="RodzajRozrachunkuCesyjnego" type="ddk:TGuid" use="optional">
		  <xs:annotation>
			  <xs:documentation>Rodzaj rozrachunku cesyjnego (identyfikator obiektu ze słownika).</xs:documentation>
		  </xs:annotation>
	  </xs:attribute>
  </xs:complexType>
	
	<xs:complexType name="TPozycjaSplatyCesyjnej">
		<xs:annotation>
			<xs:documentation>Zbiór pól pozycji rozliczeń spłaty cesyjnej.</xs:documentation>
		</xs:annotation>
		<xs:sequence>
			<xs:element name="Kwota" type="xs:decimal" nillable="false">
				<xs:annotation>
					<xs:documentation>Kwota pozycji spłaty cesyjnej.</xs:documentation>
				</xs:annotation>
			</xs:element>
			<xs:element name="DataPowstania" type="xs:date" nillable="false">
				<xs:annotation>
					<xs:documentation>Data powstania spłaty cesyjnej.</xs:documentation>
				</xs:annotation>
			</xs:element>
			<xs:element name="Dokument" type="xs:string" nillable="false">
				<xs:annotation>
					<xs:documentation>Dokument źródłowy spłaty cesyjnej.</xs:documentation>
				</xs:annotation>
			</xs:element>
			<xs:element name="DataDokumentu" type="xs:date" nillable="false">
				<xs:annotation>
					<xs:documentation>Data dokumentu źródłowego spłaty cesyjnej.</xs:documentation>
				</xs:annotation>
			</xs:element>
			<xs:element name="WalutaDokumentu" type="ddk:TGuid" nillable="false">
				<xs:annotation>
					<xs:documentation>Waluta dokumentu.</xs:documentation>
				</xs:annotation>
			</xs:element>
			<xs:element name="KursDokumentu" type="xs:decimal" nillable="true">
				<xs:annotation>
					<xs:documentation>Kurs dokumentu.</xs:documentation>
				</xs:annotation>
			</xs:element>
			<xs:element name="KursDokumentuLiczbaJednostek" type="xs:int" nillable="true">
				<xs:annotation>
					<xs:documentation>Liczba jednostek dla kursu dokumentu.</xs:documentation>
				</xs:annotation>
			</xs:element>
			<xs:element name="Waluta" type="ddk:TGuid" nillable="false">
				<xs:annotation>
					<xs:documentation>Waluta pozycji.</xs:documentation>
				</xs:annotation>
			</xs:element>
			<xs:element name="Kurs" type="xs:decimal" nillable="true">
				<xs:annotation>
					<xs:documentation>Kurs pozycji.</xs:documentation>
				</xs:annotation>
			</xs:element>
			<xs:element name="KursLiczbaJednostek" type="xs:int" nillable="true">
				<xs:annotation>
					<xs:documentation>Liczba jednostek dla kursu pozycji.</xs:documentation>
				</xs:annotation>
			</xs:element>
			<xs:element name="IdDokumentuRozliczanego" type="ddk:TGuid" nillable="true">
				<xs:annotation>
					<xs:documentation>Identyfikator dokumentu rozliczanego przez rozrachunek.</xs:documentation>
				</xs:annotation>
			</xs:element>
		</xs:sequence>
		<xs:attribute name="Index" type="xs:int" use="required">
			<xs:annotation>
				<xs:documentation>Indeks pozycji.</xs:documentation>
			</xs:annotation>
		</xs:attribute>
	</xs:complexType>

	<xs:complexType name="TPozycjeSplatyCesyjnej">
		<xs:annotation>
			<xs:documentation>Kolekcja pozycji rozliczenia spłaty cesyjenje.</xs:documentation>
		</xs:annotation>
		<xs:sequence>
			<xs:element minOccurs="0" maxOccurs="unbounded" name="Pozycja" type="TPozycjaSplatyCesyjnej">
				<xs:annotation>
					<xs:documentation>Węzeł pozycji rozliczeń spłaty cesyjenej.</xs:documentation>
				</xs:annotation>
			</xs:element>
		</xs:sequence>
	</xs:complexType>
	
  <xs:complexType name="TCesja">
    <xs:annotation>
      <xs:documentation>Cesja wraz z wersją schematu.</xs:documentation>
    </xs:annotation>
    <xs:sequence>
      <xs:element name="Wersja" type="xs:string" nillable="false" fixed="2025">
        <xs:annotation>
          <xs:documentation>Wersja schematu.</xs:documentation>
        </xs:annotation>
      </xs:element>
      <xs:element name="Naglowek" type="TNaglowekCesji" nillable="false">
        <xs:annotation>
          <xs:documentation>Nagłówek cesji.</xs:documentation>
        </xs:annotation>
      </xs:element>
		<xs:element name="Splaty" type="TPozycjeSplatyCesyjnej" nillable="true">
			<xs:annotation>
				<xs:documentation>Pozycje rozliczeń spłaty cesyjnej kompensaty.</xs:documentation>
			</xs:annotation>
		</xs:element>
    </xs:sequence>
  </xs:complexType>
  
  <xs:element name="Dokument" type="TCesja">
    <xs:annotation>
      <xs:documentation>Główny węzeł opakowujący cesję.</xs:documentation>
    </xs:annotation>
  </xs:element>
</xs:schema>