<?xml version="1.0" encoding="utf-8"?>
<xs:schema
  id="DaneBR_KategorieKsiegowePart"
  elementFormDefault="qualified"
  xmlns:xs="http://www.w3.org/2001/XMLSchema"
  xmlns="http://schemas.insert.com.pl/2024/dokumentyDoKsiegowania"
  targetNamespace="http://schemas.insert.com.pl/2024/dokumentyDoKsiegowania"
  xmlns:ddk2012="http://schemas.insert.com.pl/2012/dokumentyDoKsiegowania">
  <xs:annotation>
    <xs:documentation>Słownik kategorii księgowych.</xs:documentation>
  </xs:annotation>

  <xs:import id="TypyDanychPart" namespace="http://schemas.insert.com.pl/2012/dokumentyDoKsiegowania" schemaLocation="./TypyDanych_2012.xsd" />

  <xs:complexType name="TKategoriaKsiegowa">
    <xs:annotation>
      <xs:documentation>Obiekt kategorii księgowej.</xs:documentation>
    </xs:annotation>
    <xs:sequence>
      <xs:element name="KategorieDokumentowDlaKtorychDomyslna" type="TKategorieDokumentowHandlowych" minOccurs="0" maxOccurs="1">
        <xs:annotation>
          <xs:documentation>Kategorie dokumentów, dla których dana kategoria księgowa jest domyślna.</xs:documentation>
        </xs:annotation>
      </xs:element>
    </xs:sequence>
    <xs:attribute name="Nazwa" type="xs:string" use="required">
      <xs:annotation>
        <xs:documentation>Nazwa kategorii księgowych.</xs:documentation>
      </xs:annotation>
    </xs:attribute>
    <xs:attribute name="DozwoloneElementyDokumentow" type="xs:long" use="required">
      <xs:annotation>
        <xs:documentation>Dozwolone elementy dokumentów w postaci maski bitowej.</xs:documentation>
      </xs:annotation>
    </xs:attribute>
	<xs:attribute name="DozwoloneElementyDokumentow2" type="xs:long" use="optional">
		<xs:annotation>
			<xs:documentation>Dozwolone elementy dokumentów w postaci maski bitowej (ciąg dalszy).</xs:documentation>
		</xs:annotation>
	</xs:attribute>
    <xs:attribute name="Id" type="ddk2012:TGuid" use="required">
      <xs:annotation>
        <xs:documentation>Identyfikator kategorii księgowej.</xs:documentation>
      </xs:annotation>
    </xs:attribute>
  </xs:complexType>

  <xs:complexType name="TKategorieKsiegowe">
    <xs:annotation>
      <xs:documentation>Kolekcja kategorii księgowych.</xs:documentation>
    </xs:annotation>
    <xs:sequence>
      <xs:element name="KategoriaKsiegowa" type="TKategoriaKsiegowa" maxOccurs="unbounded">
        <xs:annotation>
          <xs:documentation>Kategoria księgowa.</xs:documentation>
        </xs:annotation>
      </xs:element>
    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="TKategorieDokumentowHandlowych">
    <xs:annotation>
      <xs:documentation>Kolekcja kategorii dokumentów.</xs:documentation>
    </xs:annotation>
    <xs:sequence>
      <xs:element name="KategoriaDokumentu" type="TKategoriaDokumentuHandlowego" minOccurs="0" maxOccurs="unbounded">
        <xs:annotation>
          <xs:documentation>Kategoria dokumentu.</xs:documentation>
        </xs:annotation>
      </xs:element>
    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="TKategoriaDokumentuHandlowego">
    <xs:annotation>
      <xs:documentation>Obiekt kategorii dokumentu.</xs:documentation>
    </xs:annotation>
    <xs:attribute name="KategoriaDokumentuId" type="xs:int" use="required">
      <xs:annotation>
        <xs:documentation>Identyfikator kategorii dokumentu.</xs:documentation>
      </xs:annotation>
    </xs:attribute>
  </xs:complexType>
</xs:schema>