<?xml version="1.0" encoding="utf-8"?>
<xs:schema 
  id="Dane_WalutyPart" 
  elementFormDefault="qualified"
  xmlns:xs="http://www.w3.org/2001/XMLSchema"
  xmlns="http://schemas.insert.com.pl/2025/dokumentyDoKsiegowania"
  targetNamespace="http://schemas.insert.com.pl/2025/dokumentyDoKsiegowania"
  xmlns:ddk2012="http://schemas.insert.com.pl/2012/dokumentyDoKsiegowania">
  <xs:annotation>
    <xs:documentation>Dane walut.</xs:documentation>
  </xs:annotation>
  
  <xs:import id="TypyDanychPart" namespace="http://schemas.insert.com.pl/2012/dokumentyDoKsiegowania" schemaLocation="./TypyDanych_2012.xsd" />
  
  <xs:complexType name="TWaluta">
    <xs:annotation>
      <xs:documentation>Obiekt waluty.</xs:documentation>
    </xs:annotation>
    <xs:attribute name="Symbol" type="xs:string" use="required">
      <xs:annotation>
        <xs:documentation>Symbol waluty.</xs:documentation>
      </xs:annotation>
    </xs:attribute>
    <xs:attribute name="Precyzja" type="xs:unsignedByte" use="required">
      <xs:annotation>
        <xs:documentation>Precyzja waluty.</xs:documentation>
      </xs:annotation>
    </xs:attribute>
    <xs:attribute name="Nazwa" type="xs:string">
      <xs:annotation>
        <xs:documentation>Nazwa waluty.</xs:documentation>
      </xs:annotation>
    </xs:attribute>
    <xs:attribute name="Id" type="xs:ID" use="required">
      <xs:annotation>
        <xs:documentation>Identyfikator jednoznacznie identyfikujący w ramach pliku XML dla waluty.</xs:documentation>
      </xs:annotation>
    </xs:attribute>
    <xs:attribute name="BId" type="xs:string" use="required">
      <xs:annotation>
        <xs:documentation>Identyfikator bazodanowy waluty.</xs:documentation>
      </xs:annotation>
    </xs:attribute>
  </xs:complexType>
  
  <xs:complexType name="TWaluty">
    <xs:annotation>
      <xs:documentation>Kolekcja walut.</xs:documentation>
    </xs:annotation>
    <xs:sequence>
      <xs:element name="Waluta" type="TWaluta" maxOccurs="unbounded">
        <xs:annotation>
          <xs:documentation>Waluta.</xs:documentation>
        </xs:annotation>
      </xs:element>
    </xs:sequence>
  </xs:complexType>
</xs:schema>