<?xml version="1.0" encoding="utf-8"?>
<xs:schema 
  id="Dane_AdresyPart" 
  elementFormDefault="qualified" 
  xmlns="http://schemas.insert.com.pl/2025/dokumentyDoKsiegowania"
  targetNamespace="http://schemas.insert.com.pl/2025/dokumentyDoKsiegowania" 
  xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:annotation>
    <xs:documentation>Dane adresowe podmiotów.</xs:documentation>
  </xs:annotation>
  
  <xs:import id="TypyDanychPart" namespace="http://schemas.insert.com.pl/2012/dokumentyDoKsiegowania" schemaLocation="./TypyDanych_2012.xsd" />
  
  <xs:complexType name="TTypAdresu">
    <xs:annotation>
      <xs:documentation>Typ adresu.</xs:documentation>
    </xs:annotation>
    <xs:attribute name="Nazwa" type="xs:string" use="required">
      <xs:annotation>
        <xs:documentation>Nazwa typu adresu.</xs:documentation>
      </xs:annotation>
    </xs:attribute>
    <xs:attribute name="Id" type="xs:ID" use="required">
      <xs:annotation>
        <xs:documentation>Identyfikator typu adresu.</xs:documentation>
      </xs:annotation>
    </xs:attribute>
  </xs:complexType>
  
  <xs:complexType name="TTypyAdresu">
    <xs:annotation>
      <xs:documentation>Kolekcja typów adresu.</xs:documentation>
    </xs:annotation>
    <xs:sequence>
      <xs:element name="TypAdresy" type="TTypAdresu" maxOccurs="unbounded">
        <xs:annotation>
          <xs:documentation>Typ adresu.</xs:documentation>
        </xs:annotation>
      </xs:element>
    </xs:sequence>
  </xs:complexType>
  
  <xs:complexType name="TAdresSzczegoly">
    <xs:annotation>
      <xs:documentation>Szczegóły adresu.</xs:documentation>
    </xs:annotation>
    <xs:attribute name="Ulica" type="xs:string">
      <xs:annotation>
        <xs:documentation>Ulica.</xs:documentation>
      </xs:annotation>
    </xs:attribute>
    <xs:attribute name="NrDomu" type="xs:string">
      <xs:annotation>
        <xs:documentation>Numer domu.</xs:documentation>
      </xs:annotation>
    </xs:attribute>
    <xs:attribute name="NrLokalu" type="xs:string">
      <xs:annotation>
        <xs:documentation>Numer lokalu.</xs:documentation>
      </xs:annotation>
    </xs:attribute>
    <xs:attribute name="KodPocztowy" type="xs:string">
      <xs:annotation>
        <xs:documentation>Kod pocztowy.</xs:documentation>
      </xs:annotation>
    </xs:attribute>
    <xs:attribute name="Miejscowosc" type="xs:string">
      <xs:annotation>
        <xs:documentation>Miejscowość.</xs:documentation>
      </xs:annotation>
    </xs:attribute>
    <xs:attribute name="Poczta" type="xs:string">
      <xs:annotation>
        <xs:documentation>Poczta.</xs:documentation>
      </xs:annotation>
    </xs:attribute>
  </xs:complexType>
  
  <xs:complexType name="TAdresySzczegoly">
    <xs:annotation>
      <xs:documentation>Kolekcja obiektów szczegółów adresu.</xs:documentation>
    </xs:annotation>
    <xs:sequence>
      <xs:element name="AdresSzczegoly" type="TAdresSzczegoly" maxOccurs="unbounded">
        <xs:annotation>
          <xs:documentation>Szczegóły adresu.</xs:documentation>
        </xs:annotation>
      </xs:element>
    </xs:sequence>
  </xs:complexType>
  
  <xs:complexType name="TAdres">
    <xs:annotation>
      <xs:documentation>Obiekt adresu.</xs:documentation>
    </xs:annotation>
    <xs:sequence maxOccurs="1">
      <xs:element name="AdresSzczegoly" type="TAdresSzczegoly" minOccurs="0" maxOccurs="1">
        <xs:annotation>
          <xs:documentation>Szczegóły adresu.</xs:documentation>
        </xs:annotation>
      </xs:element>
    </xs:sequence>
    <xs:attribute name="Linia1" type="xs:string">
      <xs:annotation>
        <xs:documentation>Pierwsza linia adresu w postaci opisowej.</xs:documentation>
      </xs:annotation>
    </xs:attribute>
    <xs:attribute name="Linia2" type="xs:string">
      <xs:annotation>
        <xs:documentation>Druga linia adresu w postaci opisowej.</xs:documentation>
      </xs:annotation>
    </xs:attribute>
    <xs:attribute name="Linia3" type="xs:string">
      <xs:annotation>
        <xs:documentation>Trzecia linia adresu w postaci opisowej.</xs:documentation>
      </xs:annotation>
    </xs:attribute>
    <xs:attribute name="TypAdresuId" type="xs:IDREF" use="required">
      <xs:annotation>
        <xs:documentation>Identyfikator typu adresu.</xs:documentation>
      </xs:annotation>
    </xs:attribute>
    <xs:attribute name="Id" type="xs:ID" use="required">
      <xs:annotation>
        <xs:documentation>Identyfikator jednoznacznie identyfikujący w ramach pliku XML dla adresu.</xs:documentation>
      </xs:annotation>
    </xs:attribute>
    <xs:attribute name="BId" type="xs:string" use="required">
      <xs:annotation>
        <xs:documentation>Identyfikator bazodanowy adresu.</xs:documentation>
      </xs:annotation>
    </xs:attribute>
    <xs:attribute name="PodmiotId" type="xs:IDREF" use="required">
      <xs:annotation>
        <xs:documentation>Identyfikator podmiotu, którego adres dotyczy.</xs:documentation>
      </xs:annotation>
    </xs:attribute>
    <xs:attribute name="GminaId" type="xs:IDREF">
      <xs:annotation>
        <xs:documentation>Identyfikator gminy.</xs:documentation>
      </xs:annotation>
    </xs:attribute>
    <xs:attribute name="PanstwoId" type="xs:IDREF">
      <xs:annotation>
        <xs:documentation>Identyfikator państwa.</xs:documentation>
      </xs:annotation>
    </xs:attribute>
    <xs:attribute name="WojewodztwoId" type="xs:IDREF" use="optional">
      <xs:annotation>
        <xs:documentation>Identyfikator województwa.</xs:documentation>
      </xs:annotation>
    </xs:attribute>
  </xs:complexType>
  
  <xs:complexType name="TAdresy">
    <xs:annotation>
      <xs:documentation>Kolekcja adresów.</xs:documentation>
    </xs:annotation>
    <xs:sequence>
      <xs:element name="Adres" type="TAdres" maxOccurs="unbounded">
        <xs:annotation>
          <xs:documentation>Adres.</xs:documentation>
        </xs:annotation>
      </xs:element>
    </xs:sequence>
  </xs:complexType>
  
  <xs:complexType name="TAdresHistoria">
    <xs:annotation>
      <xs:documentation>Obiekt wpisu historycznego adresu.</xs:documentation>
    </xs:annotation>
    <xs:attribute name="Nazwa" type="xs:string" use="optional">
      <xs:annotation>
        <xs:documentation>Nazwa podmiotu.</xs:documentation>
      </xs:annotation>
    </xs:attribute>
    <xs:attribute name="Linia1" type="xs:string" use="optional">
      <xs:annotation>
        <xs:documentation>Pierwsza linia adresu w postaci opisowej.</xs:documentation>
      </xs:annotation>
    </xs:attribute>
    <xs:attribute name="Linia2" type="xs:string" use="optional">
      <xs:annotation>
        <xs:documentation>Druga linia adresu w postaci opisowej.</xs:documentation>
      </xs:annotation>
    </xs:attribute>
    <xs:attribute name="Linia3" type="xs:string" use="optional">
      <xs:annotation>
        <xs:documentation>Trzecia linia adresu w postaci opisowej.</xs:documentation>
      </xs:annotation>
    </xs:attribute>
    <xs:attribute name="PanstwoId" type="xs:IDREF">
      <xs:annotation>
        <xs:documentation>Identyfikator państwa.</xs:documentation>
      </xs:annotation>
    </xs:attribute>
    <xs:attribute name="TypAdresuId" type="xs:IDREF" use="required">
      <xs:annotation>
        <xs:documentation>Identyfikator typu adresu.</xs:documentation>
      </xs:annotation>
    </xs:attribute>
    <xs:attribute name="PodmiotId" type="xs:IDREF" use="optional"> <!-- optional, bo dodany do nexo 55.0.0; 
	                                                                    niezbędny do deserializacji danych historycznych w przypadku skasowaniu adresu
																		ale pozostawieniu w bazie danych historycznych -->
      <xs:annotation>
        <xs:documentation>Identyfikator adresu, którego dany wpis historyczny dotyczy.</xs:documentation>
      </xs:annotation>
    </xs:attribute>
    <xs:attribute name="AdresId" type="xs:IDREF" use="optional"> <!-- optional, bo w nexo adres historyczny może pozostać w bazie po skasowaniu adresu -->
      <xs:annotation>
        <xs:documentation>Identyfikator adresu, którego dany wpis historyczny dotyczy.</xs:documentation>
      </xs:annotation>
    </xs:attribute>
    <xs:attribute name="AdresDlaKtoregoNajnowszaId" type="xs:IDREF" use="optional">
      <xs:annotation>
        <xs:documentation>Identyfikator wpisu historycznego aktualnego dla adresu, do którego dany wpis historyczny się odnosi.</xs:documentation>
      </xs:annotation>
    </xs:attribute>
    <xs:attribute name="Id" type="xs:ID" use="required">
      <xs:annotation>
        <xs:documentation>Identyfikator jednoznacznie identyfikujący w ramach pliku XML dla adresu.</xs:documentation>
      </xs:annotation>
    </xs:attribute>
    <xs:attribute name="BId" type="xs:string" use="required">
      <xs:annotation>
        <xs:documentation>Identyfikator bazodanowy adresu.</xs:documentation>
      </xs:annotation>
    </xs:attribute>
  </xs:complexType>
  
  <xs:complexType name="TAdresyHistoria">
    <xs:annotation>
      <xs:documentation>Kolekcja wpisów historycznych adresu.</xs:documentation>
    </xs:annotation>
    <xs:sequence>
      <xs:element name="AdresHistoria" type="TAdresHistoria" maxOccurs="unbounded">
        <xs:annotation>
          <xs:documentation>Wpis historyczny adresu.</xs:documentation>
        </xs:annotation>
      </xs:element>
    </xs:sequence>
  </xs:complexType>
</xs:schema>