<?xml version="1.0" encoding="utf-8"?>
<xs:schema 
  id="Dane_FormyPlatnosciPart"
  elementFormDefault="qualified"
  xmlns="http://schemas.insert.com.pl/2025/dokumentyDoKsiegowania"
  targetNamespace="http://schemas.insert.com.pl/2025/dokumentyDoKsiegowania" 
  xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:annotation>
    <xs:documentation>Dane dotyczące form płatności.</xs:documentation>
  </xs:annotation>
  
  <xs:import id="TypyDanychPart" namespace="http://schemas.insert.com.pl/2012/dokumentyDoKsiegowania" schemaLocation="./TypyDanych_2012.xsd" />
  
  <!-- Slownik Forma płatności -->
  <xs:complexType name="TFormaPlatnosci">
    <xs:annotation>
      <xs:documentation>Obiekt formy płatności.</xs:documentation>
    </xs:annotation>
    <xs:attribute name="Nazwa" type="xs:string" use="required">
      <xs:annotation>
        <xs:documentation>Nazwa formy płatności.</xs:documentation>
      </xs:annotation>
    </xs:attribute>
    <xs:attribute name="Id" type="xs:ID" use="required">
      <xs:annotation>
        <xs:documentation>Identyfikator jednoznacznie identyfikujący w ramach pliku XML dla formy płatności.</xs:documentation>
      </xs:annotation>
    </xs:attribute>
    <xs:attribute name="BId" type="xs:string" use="required">
      <xs:annotation>
        <xs:documentation>Identyfikator bazodanowy formy płatności.</xs:documentation>
      </xs:annotation>
    </xs:attribute>
    <xs:attribute name="PodmiotId" type="xs:IDREF" use="optional">
      <xs:annotation>
        <xs:documentation>Identyfikator podmiotu cesyjnego.</xs:documentation>
      </xs:annotation>
    </xs:attribute>
    <!-- Podmiot cesyjny -->
    <xs:attribute name="RachunekBankowyId" type="xs:IDREF" use="optional">
      <xs:annotation>
        <xs:documentation>Identyfikator rachunku bankowego.</xs:documentation>
      </xs:annotation>
    </xs:attribute>
    <!-- Rachunek bankowy dla płatności cesyjnej -->
    <xs:attribute name="WalutaId" type="xs:IDREF" use="optional">
      <xs:annotation>
        <xs:documentation>Identyfikator waluty formy płatności.</xs:documentation>
      </xs:annotation>
    </xs:attribute>
    <xs:attribute name="TypPlatnosciId" type="xs:IDREF" use="required">
      <xs:annotation>
        <xs:documentation>Identyfikator typu płatności.</xs:documentation>
      </xs:annotation>
    </xs:attribute>
    <xs:attribute name="MinimalnaKwotaRaty" type="xs:decimal" use="optional">
      <xs:annotation>
        <xs:documentation>Minimalna kwota raty dla formy płatności typu odroczona.</xs:documentation>
      </xs:annotation>
    </xs:attribute>
  </xs:complexType>
  
  <xs:complexType name="TFormyPlatnosci">
    <xs:annotation>
      <xs:documentation>Kolekcja form płatności.</xs:documentation>
    </xs:annotation>
    <xs:sequence>
      <xs:element name="FormaPlatnosci" type="TFormaPlatnosci" maxOccurs="unbounded">
        <xs:annotation>
          <xs:documentation>Forma płatności.</xs:documentation>
        </xs:annotation>
      </xs:element>
    </xs:sequence>
  </xs:complexType>
  
  <!-- Slownik Typo platnosci-->
  <xs:complexType name="TTypPlatnosci">
    <xs:annotation>
      <xs:documentation>Obiekt typu płatności.</xs:documentation>
    </xs:annotation>
    <xs:attribute name="Id" type="xs:ID" use="required">
      <xs:annotation>
        <xs:documentation>Identyfikator jednoznacznie identyfikujący w ramach pliku XML dla typu płatności.</xs:documentation>
      </xs:annotation>
    </xs:attribute>
    <xs:attribute name="BId" type="xs:string" use="required">
      <xs:annotation>
        <xs:documentation>Identyfikator bazodanowy typu płatności.</xs:documentation>
      </xs:annotation>
    </xs:attribute>
    <xs:attribute name="Nazwa" type="xs:string" use="required">
      <xs:annotation>
        <xs:documentation>Nazwa typu płatności.</xs:documentation>
      </xs:annotation>
    </xs:attribute>
    <xs:attribute name="Bankowy" type="xs:boolean" use="required">
      <xs:annotation>
        <xs:documentation>Czy typ płatności wymaga podania rachunku bankowego.</xs:documentation>
      </xs:annotation>
    </xs:attribute>
    <xs:attribute name="Cesyjny" type="xs:boolean" use="required">
      <xs:annotation>
        <xs:documentation>Czy typ płatności związany jest z cesją.</xs:documentation>
      </xs:annotation>
    </xs:attribute>
    <xs:attribute name="SzybkaPlatnosc" type="xs:boolean" use="optional">
      <xs:annotation>
        <xs:documentation>Czy typ płatności jest szybką sprzedażą.</xs:documentation>
      </xs:annotation>
    </xs:attribute>
  </xs:complexType>
  <xs:complexType name="TTypyPlatnosci">
    <xs:annotation>
      <xs:documentation>Kolekcja typów płatności.</xs:documentation>
    </xs:annotation>
    <xs:sequence>
      <xs:element name="TypPlatnosci" type="TTypPlatnosci" maxOccurs="unbounded">
        <xs:annotation>
          <xs:documentation>Typ płatności.</xs:documentation>
        </xs:annotation>
      </xs:element>
    </xs:sequence>
  </xs:complexType>
</xs:schema>