<?xml version="1.0" encoding="utf-8"?>
<xs:schema 
  xmlns:xs="http://www.w3.org/2001/XMLSchema"
  elementFormDefault="qualified"
  xmlns="http://schemas.insert.com.pl/2024/dokumentyDoKsiegowania"
  targetNamespace="http://schemas.insert.com.pl/2024/dokumentyDoKsiegowania"
  xmlns:ddk2012="http://schemas.insert.com.pl/2012/dokumentyDoKsiegowania"
  id="DaneBR_StatusyKsiegowe.xsd">
  <xs:annotation>
    <xs:documentation>Dane o statusach księgowych biura rachunkowego.</xs:documentation>
  </xs:annotation>

  <xs:import id="TypyDanychPart" namespace="http://schemas.insert.com.pl/2012/dokumentyDoKsiegowania" schemaLocation="./TypyDanych_2012.xsd" />

  <xs:complexType name="TStatusKsiegowy">
    <xs:annotation>
      <xs:documentation>Obiekt statusu księgowego.</xs:documentation>
    </xs:annotation>
    <xs:attribute name="DokumentKsiegowyId" type="ddk2012:TGuid" use="required">
      <xs:annotation>
        <xs:documentation>Identyfikator dokumentu księgowego.</xs:documentation>
      </xs:annotation>
    </xs:attribute>
    <xs:attribute name="StatusKsiegowy" type="xs:unsignedByte" use="required">
      <xs:annotation>
        <xs:documentation>Status księgowy.</xs:documentation>
      </xs:annotation>
    </xs:attribute>
    <xs:attribute name="TypWynikowegoDokumentuKsiegowego" type="xs:unsignedByte" use="required">
      <xs:annotation>
        <xs:documentation>Typ wynikowego dokumentu księgowego.</xs:documentation>
      </xs:annotation>
    </xs:attribute>
    <xs:attribute name="Wersja" type="xs:int" use="required">
      <xs:annotation>
        <xs:documentation>Wersja.</xs:documentation>
      </xs:annotation>
    </xs:attribute>
  </xs:complexType>
  
  <xs:complexType name="TStatusyKsiegowe">
    <xs:annotation>
      <xs:documentation>Kolekcja statusów księgowych biura rachunkowego.</xs:documentation>
    </xs:annotation>
    <xs:sequence>
      <xs:element name="StatusKsiegowy" type="TStatusKsiegowy" maxOccurs="unbounded">
        <xs:annotation>
          <xs:documentation>Status księgowy.</xs:documentation>
        </xs:annotation>
      </xs:element>
    </xs:sequence>
  </xs:complexType>
</xs:schema>