<?xml version="1.0" encoding="utf-8"?>
<xs:schema 
  id="Dane_DaneGeoraficznePart" 
  elementFormDefault="qualified" 
  xmlns="http://schemas.insert.com.pl/2025/dokumentyDoKsiegowania" 
  targetNamespace="http://schemas.insert.com.pl/2025/dokumentyDoKsiegowania" 
  xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:annotation>
    <xs:documentation>Dane geograficzne.</xs:documentation>
  </xs:annotation>
  
  <xs:import id="TypyDanychPart" namespace="http://schemas.insert.com.pl/2012/dokumentyDoKsiegowania" schemaLocation="./TypyDanych_2012.xsd" />
  
  <xs:complexType name="TPanstwo">
    <xs:annotation>
      <xs:documentation>Obiekt państwa.</xs:documentation>
    </xs:annotation>
    <xs:attribute name="Id" type="xs:ID" use="required">
      <xs:annotation>
        <xs:documentation>Identyfikator jednoznacznie identyfikujący w ramach pliku XML dla państwa.</xs:documentation>
      </xs:annotation>
    </xs:attribute>
    <xs:attribute name="BId" type="xs:int" use="required">
      <xs:annotation>
        <xs:documentation>Identyfikator bazodanowy państwa.</xs:documentation>
      </xs:annotation>
    </xs:attribute>
    <xs:attribute name="Nazwa" type="xs:string">
      <xs:annotation>
        <xs:documentation>Nazwa państwa.</xs:documentation>
      </xs:annotation>
    </xs:attribute>
	<xs:attribute name="Kod" type="xs:string" use="optional">
		<xs:annotation>
			<xs:documentation>Kod państwa</xs:documentation>
		</xs:annotation>
	</xs:attribute>
	<xs:attribute name="UE" type="xs:boolean" use="optional">
		<xs:annotation>
			<xs:documentation>Czy państwo należy do UE.</xs:documentation>
		</xs:annotation>
	</xs:attribute>
  </xs:complexType>
  
  <xs:complexType name="TPanstwa">
    <xs:annotation>
      <xs:documentation>Kolekcja państw.</xs:documentation>
    </xs:annotation>
    <xs:sequence>
      <xs:element name="Panstwo" type="TPanstwo" maxOccurs="unbounded">
        <xs:annotation>
          <xs:documentation>Państwo.</xs:documentation>
        </xs:annotation>
      </xs:element>
    </xs:sequence>
  </xs:complexType>
  
  <xs:complexType name="TWojewodztwa">
    <xs:annotation>
      <xs:documentation>Kolekcja województw.</xs:documentation>
    </xs:annotation>
    <xs:sequence>
      <xs:element name="Wojetodztwo" type="TWojewodztwo" maxOccurs="unbounded">
        <xs:annotation>
          <xs:documentation>Województwo.</xs:documentation>
        </xs:annotation>
      </xs:element>
    </xs:sequence>
  </xs:complexType>
  
  <xs:complexType name="TWojewodztwo">
    <xs:annotation>
      <xs:documentation>Obiekt województwa.</xs:documentation>
    </xs:annotation>
    <xs:attribute name="Id" type="xs:ID" use="required">
      <xs:annotation>
        <xs:documentation>Identyfikator jednoznacznie identyfikujący w ramach pliku XML dla województwa.</xs:documentation>
      </xs:annotation>
    </xs:attribute>
    <xs:attribute name="BId" type="xs:int" use="required">
      <xs:annotation>
        <xs:documentation>Identyfikator bazodanowy województwa.</xs:documentation>
      </xs:annotation>
    </xs:attribute>
    <xs:attribute name="PanstwoId" type="xs:IDREF" use="required">
      <xs:annotation>
        <xs:documentation>Identyfikator państwa, w którym leży województwo.</xs:documentation>
      </xs:annotation>
    </xs:attribute>
    <xs:attribute name="Nazwa" type="xs:string">
      <xs:annotation>
        <xs:documentation>Nazwa województwa.</xs:documentation>
      </xs:annotation>
    </xs:attribute>
  </xs:complexType>
  
  <xs:complexType name="TPowiat">
    <xs:annotation>
      <xs:documentation>Obiekt powiatu.</xs:documentation>
    </xs:annotation>
    <xs:attribute name="Id" type="xs:ID" use="required">
      <xs:annotation>
        <xs:documentation>Identyfikator jednoznacznie identyfikujący w ramach pliku XML dla powiatu.</xs:documentation>
      </xs:annotation>
    </xs:attribute>
    <xs:attribute name="BId" type="xs:int" use="required">
      <xs:annotation>
        <xs:documentation>Identyfikator bazodanowy powiatu.</xs:documentation>
      </xs:annotation>
    </xs:attribute>
    <xs:attribute name="Nazwa" type="xs:string">
      <xs:annotation>
        <xs:documentation>Nazwa powiatu.</xs:documentation>
      </xs:annotation>
    </xs:attribute>
    <xs:attribute name="WojewodztwoId" type="xs:IDREF" use="required">
      <xs:annotation>
        <xs:documentation>Identyfikator województwa, w którym leży powiat.</xs:documentation>
      </xs:annotation>
    </xs:attribute>
  </xs:complexType>
  
  <xs:complexType name="TPowiaty">
    <xs:annotation>
      <xs:documentation>Kolekcja powiatów.</xs:documentation>
    </xs:annotation>
    <xs:sequence>
      <xs:element name="Powiat" type="TPowiat" maxOccurs="unbounded">
        <xs:annotation>
          <xs:documentation>Powiat.</xs:documentation>
        </xs:annotation>
      </xs:element>
    </xs:sequence>
  </xs:complexType>
  
  <xs:complexType name="TGmina">
    <xs:annotation>
      <xs:documentation>Obiekt gminy.</xs:documentation>
    </xs:annotation>
    <xs:attribute name="Id" type="xs:ID" use="required">
      <xs:annotation>
        <xs:documentation>Identyfikator jednoznacznie identyfikujący w ramach pliku XML dla gminy.</xs:documentation>
      </xs:annotation>
    </xs:attribute>
    <xs:attribute name="BId" type="xs:int" use="required">
      <xs:annotation>
        <xs:documentation>Identyfikator bazodanowy gminy.</xs:documentation>
      </xs:annotation>
    </xs:attribute>
    <xs:attribute name="PowiatId" type="xs:IDREF" use="required">
      <xs:annotation>
        <xs:documentation>Identyfikator powiatu, w którym leży gmina.</xs:documentation>
      </xs:annotation>
    </xs:attribute>
    <xs:attribute name="Nazwa" type="xs:string">
      <xs:annotation>
        <xs:documentation>Nazwa gminy.</xs:documentation>
      </xs:annotation>
    </xs:attribute>
    <xs:attribute name="KodGUS" type="xs:string">
      <xs:annotation>
        <xs:documentation>Kod GUS gminy.</xs:documentation>
      </xs:annotation>
    </xs:attribute>
    <xs:attribute name="TypGminy" type="xs:int" use="required">
      <xs:annotation>
        <xs:documentation>Typ gminy (1 - miejska, 2 - wiejska, 3 - miejsko-wiejska, 4 - miasto, 5 - obszar wiejski, 8 - dzielnica Warszawy, 9 - delegatura).</xs:documentation>
      </xs:annotation>
    </xs:attribute>
  </xs:complexType>
  
  <xs:complexType name="TGminy">
    <xs:annotation>
      <xs:documentation>Kolekcja gmin.</xs:documentation>
    </xs:annotation>
    <xs:sequence>
      <xs:element name="Gmina" type="TGmina" maxOccurs="unbounded">
        <xs:annotation>
          <xs:documentation>Gmina.</xs:documentation>
        </xs:annotation>
      </xs:element>
    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="TRegion">
    <xs:annotation>
      <xs:documentation>Obiekt regionu.</xs:documentation>
    </xs:annotation>
    <xs:attribute name="Id" type="xs:ID" use="required">
      <xs:annotation>
        <xs:documentation>Identyfikator jednoznacznie identyfikujący w ramach pliku XML dla regionu.</xs:documentation>
      </xs:annotation>
    </xs:attribute>
    <xs:attribute name="BId" type="xs:int" use="required">
      <xs:annotation>
        <xs:documentation>Identyfikator bazodanowy regionu.</xs:documentation>
      </xs:annotation>
    </xs:attribute>
    <xs:attribute name="Nazwa" type="xs:string">
      <xs:annotation>
        <xs:documentation>Nazwa regionu.</xs:documentation>
      </xs:annotation>
    </xs:attribute>
  </xs:complexType>

  <xs:complexType name="TRegiony">
    <xs:annotation>
      <xs:documentation>Kolekcja regionów.</xs:documentation>
    </xs:annotation>
    <xs:sequence>
      <xs:element name="Region" type="TRegion" maxOccurs="unbounded">
        <xs:annotation>
          <xs:documentation>Region.</xs:documentation>
        </xs:annotation>
      </xs:element>
    </xs:sequence>
  </xs:complexType>
</xs:schema>