<?xml version="1.0" encoding="utf-8"?>
<xs:schema id="Dane_PolaWlasnePart"
    elementFormDefault="qualified"
    xmlns:xs="http://www.w3.org/2001/XMLSchema"
    xmlns="http://schemas.insert.com.pl/2012/dokumentyDoKsiegowania"
    targetNamespace="http://schemas.insert.com.pl/2012/dokumentyDoKsiegowania">
  
  <xs:complexType name="TPoleWlasne">
    <xs:attribute name="Nazwa" type="xs:string" use="required" />
    <xs:attribute name="Wartosc" type="xs:string" use="optional" />
  </xs:complexType>

  <xs:complexType name="TKolekcjaPolWlasnych">
    <xs:sequence>
      <xs:element minOccurs="0" maxOccurs="unbounded" name="PoleWlasne" type="TPoleWlasne" />
    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="TPolaWlasne">
    <xs:sequence>
      <xs:element name="Pola" type="TKolekcjaPolWlasnych" minOccurs="0" />      
    </xs:sequence>
    <xs:attribute name="Nazwa" type="xs:string" use="required"/>
  </xs:complexType>

  <xs:complexType name="TKolekcjePolWlasnych">
    <xs:sequence>
      <xs:element minOccurs="0" maxOccurs="unbounded" name="PolaWlasne" type="TPolaWlasne" />
    </xs:sequence>
  </xs:complexType>
</xs:schema>
