<?xml version="1.0" encoding="utf-8"?>
<xs:schema 
  id="Dane_RachunkiBankowePart" 
  elementFormDefault="qualified" 
  xmlns:xs="http://www.w3.org/2001/XMLSchema" 
  xmlns="http://schemas.insert.com.pl/2025/dokumentyDoKsiegowania" 
  targetNamespace="http://schemas.insert.com.pl/2025/dokumentyDoKsiegowania">
  <xs:annotation>
    <xs:documentation>Dane rachunków bankowych.</xs:documentation>
  </xs:annotation>
  
  <xs:import id="TypyDanychPart" namespace="http://schemas.insert.com.pl/2012/dokumentyDoKsiegowania" schemaLocation="./TypyDanych_2012.xsd" />
  
  <xs:complexType name="TRachunekBankowy">
    <xs:annotation>
      <xs:documentation>Obiekt rachunku bankowego.</xs:documentation>
    </xs:annotation>
    <xs:attribute name="Nazwa" type="xs:string" use="required">
      <xs:annotation>
        <xs:documentation>Nazwa rachunku bankowego.</xs:documentation>
      </xs:annotation>
    </xs:attribute>
    <xs:attribute name="Opis" type="xs:string">
      <xs:annotation>
        <xs:documentation>Opis rachunku bankowego.</xs:documentation>
      </xs:annotation>
    </xs:attribute>
    <xs:attribute name="Numer" type="xs:string" use="required">
      <xs:annotation>
        <xs:documentation>Numer rachunku bankowego.</xs:documentation>
      </xs:annotation>
    </xs:attribute>
    <xs:attribute name="NumerBezSeparatorow" type="xs:string" use="required">
      <xs:annotation>
        <xs:documentation>Numer bez separatorow rachunku bankowego.</xs:documentation>
      </xs:annotation>
    </xs:attribute>
    <xs:attribute name="Id" type="xs:ID" use="required">
      <xs:annotation>
        <xs:documentation>Identyfikator jednoznacznie identyfikujący w ramach pliku XML dla rachunku bankowego.</xs:documentation>
      </xs:annotation>
    </xs:attribute>
    <xs:attribute name="BId" type="xs:string" use="required">
      <xs:annotation>
        <xs:documentation>Identyfikator bazodanowy rachunku bankowego.</xs:documentation>
      </xs:annotation>
    </xs:attribute>
    <xs:attribute name="WalutaId" type="xs:IDREF" use="optional">
      <xs:annotation>
        <xs:documentation>Identyfikator waluty rachunku bankowego.</xs:documentation>
      </xs:annotation>
    </xs:attribute>
    <xs:attribute name="PodmiotBankowyId" type="xs:IDREF">
      <xs:annotation>
        <xs:documentation>Identyfikator podmiotu bankowego.</xs:documentation>
      </xs:annotation>
    </xs:attribute>
    <xs:attribute name="JestRachunkiemVAT" type="xs:boolean">
      <xs:annotation>
        <xs:documentation>Czy jest rachunkiem VAT.</xs:documentation>
      </xs:annotation>
    </xs:attribute>
  </xs:complexType>
  
  <xs:complexType name="TRachunkiBankowe">
    <xs:annotation>
      <xs:documentation>Kolekcja rachunków bankowych.</xs:documentation>
    </xs:annotation>
    <xs:sequence>
      <xs:element name="RachunekBankowy" type="TRachunekBankowy" maxOccurs="unbounded">
        <xs:annotation>
          <xs:documentation>Rachunek bankowy.</xs:documentation>
        </xs:annotation>
      </xs:element>
    </xs:sequence>
  </xs:complexType>
</xs:schema>