<?xml version="1.0" encoding="utf-8"?>
<xs:schema 
  id="Dane_MagazynyPart" 
  elementFormDefault="qualified" 
  xmlns="http://schemas.insert.com.pl/2025/dokumentyDoKsiegowania" 
  targetNamespace="http://schemas.insert.com.pl/2025/dokumentyDoKsiegowania"
  xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:annotation>
    <xs:documentation>Dane dotyczące magazynów i oddziałów.</xs:documentation>
  </xs:annotation>
  
  <xs:import id="TypyDanychPart" namespace="http://schemas.insert.com.pl/2012/dokumentyDoKsiegowania" schemaLocation="./TypyDanych_2012.xsd" />
  
  <xs:complexType name="TMagazyn">
    <xs:annotation>
      <xs:documentation>Obiekt magazynu.</xs:documentation>
    </xs:annotation>
    <xs:attribute name="Id" type="xs:ID" use="required">
      <xs:annotation>
        <xs:documentation>Identyfikator jednoznacznie identyfikujący w ramach pliku XML dla magazynu.</xs:documentation>
      </xs:annotation>
    </xs:attribute>
    <xs:attribute name="BId" type="xs:string" use="required">
      <xs:annotation>
        <xs:documentation>Identyfikator baz0danowy magazynu.</xs:documentation>
      </xs:annotation>
    </xs:attribute>
    <xs:attribute name="Nazwa" type="xs:string" use="required">
      <xs:annotation>
        <xs:documentation>Nazwa magazynu.</xs:documentation>
      </xs:annotation>
    </xs:attribute>
    <xs:attribute name="Symbol" type="xs:string" use="required">
      <xs:annotation>
        <xs:documentation>Symbol magazynu.</xs:documentation>
      </xs:annotation>
    </xs:attribute>
    <xs:attribute name="JednostkaOrganizacyjnaId" type="xs:IDREF" use="required">
      <xs:annotation>
        <xs:documentation>Identyfikator oddziału, do którego magazyn przynależy.</xs:documentation>
      </xs:annotation>
    </xs:attribute>
  </xs:complexType>
  
  <xs:complexType name="TMagazyny">
    <xs:annotation>
      <xs:documentation>Kolekcja magazynów.</xs:documentation>
    </xs:annotation>
    <xs:sequence>
      <xs:element name="Magazyn" type="TMagazyn" maxOccurs="unbounded">
        <xs:annotation>
          <xs:documentation>Magazyn.</xs:documentation>
        </xs:annotation>
      </xs:element>
    </xs:sequence>
  </xs:complexType>
  
  <xs:complexType name="TJednostkaOrganizacyjna">
    <xs:annotation>
      <xs:documentation>Obiekt oddziału.</xs:documentation>
    </xs:annotation>
    <xs:attribute name="Id" type="xs:ID" use="required">
      <xs:annotation>
        <xs:documentation>Identyfikator jednoznacznie identyfikujący w ramach pliku XML dla oddziału.</xs:documentation>
      </xs:annotation>
    </xs:attribute>
    <xs:attribute name="Symbol" type="xs:string" use="required">
      <xs:annotation>
        <xs:documentation>Symbol oddziału.</xs:documentation>
      </xs:annotation>
    </xs:attribute>
    <xs:attribute name="CzyOddzial" type="xs:boolean" use="required">
      <xs:annotation>
        <xs:documentation>Czy jednostka jest oddziałem. Jeśli false, to jednostka jest centralą.</xs:documentation>
      </xs:annotation>
    </xs:attribute>
    <xs:attribute name="Nazwa" type="xs:string" use="required">
      <xs:annotation>
        <xs:documentation>Nazwa oddziału.</xs:documentation>
      </xs:annotation>
    </xs:attribute>
    <xs:attribute name="BId" type="xs:string" use="required">
      <xs:annotation>
        <xs:documentation>Identyfikator bazodanowy oddziału.</xs:documentation>
      </xs:annotation>
    </xs:attribute>
  </xs:complexType>
  
  <xs:complexType name="TJednostkiOrganizacyjne">
    <xs:annotation>
      <xs:documentation>Kolekcja oddziałów.</xs:documentation>
    </xs:annotation>
    <xs:sequence>
      <xs:element name="JednostkaOrganizacyjna" type="TJednostkaOrganizacyjna" maxOccurs="unbounded">
        <xs:annotation>
          <xs:documentation>Oddział.</xs:documentation>
        </xs:annotation>
      </xs:element>
    </xs:sequence>
  </xs:complexType>
  
  <xs:complexType name="TMiejsceSprzedazy">
    <xs:annotation>
      <xs:documentation>Obiekt miejsca sprzedaży.</xs:documentation>
    </xs:annotation>
    <xs:attribute name="Id" type="xs:ID" use="required">
      <xs:annotation>
        <xs:documentation>Identyfikator jednoznacznie identyfikujący w ramach pliku XML dla miejsca sprzedaży.</xs:documentation>
      </xs:annotation>
    </xs:attribute>
    <xs:attribute name="BId" type="xs:string" use="required">
      <xs:annotation>
        <xs:documentation>Identyfikator bazodanowy miejsca sprzedaży.</xs:documentation>
      </xs:annotation>
    </xs:attribute>
    <xs:attribute name="Nazwa" type="xs:string" use="required">
      <xs:annotation>
        <xs:documentation>Nazwa miejsca sprzedaży.</xs:documentation>
      </xs:annotation>
    </xs:attribute>
    <xs:attribute name="Symbol" type="xs:string" use="required">
      <xs:annotation>
        <xs:documentation>Symbol miejsca sprzedaży.</xs:documentation>
      </xs:annotation>
    </xs:attribute>
    <xs:attribute name="JednostkaOrganizacyjnaId" type="xs:IDREF" use="required">
      <xs:annotation>
        <xs:documentation>Identyfikator oddziału.</xs:documentation>
      </xs:annotation>
    </xs:attribute>
  </xs:complexType>
  
  <xs:complexType name="TMiejscaSprzedazy">
    <xs:annotation>
      <xs:documentation>Kolekcja miejsc sprzedaży.</xs:documentation>
    </xs:annotation>
    <xs:sequence>
      <xs:element name="MiejsceSprzedazy" type="TMiejsceSprzedazy" maxOccurs="unbounded">
        <xs:annotation>
          <xs:documentation>Miejsce sprzedaży.</xs:documentation>
        </xs:annotation>
      </xs:element>
    </xs:sequence>
  </xs:complexType>
</xs:schema>