<?xml version="1.0" encoding="utf-8"?>
<!-- Uzyj xsd.exe do wygenerowania z tego kodu -->
<xs:schema
  xmlns:xs="http://www.w3.org/2001/XMLSchema"
  elementFormDefault="qualified"
  xmlns="http://schemas.insert.com.pl/2024/dokumentyDoKsiegowania"
  targetNamespace="http://schemas.insert.com.pl/2024/dokumentyDoKsiegowania"
  id="DaneBR_Nadawca">
  <xs:annotation>
    <xs:documentation>Dane nadawcy.</xs:documentation>
  </xs:annotation>

  <xs:simpleType name="TTypProduktu">
    <xs:annotation>
      <xs:documentation>Typ produktu.</xs:documentation>
    </xs:annotation>
    <xs:restriction base="xs:string">
      <xs:enumeration value="SubiektNexo">
        <xs:annotation>
          <xs:documentation>Subiekt nexo.</xs:documentation>
        </xs:annotation>
      </xs:enumeration>
      <xs:enumeration value="RachmistrzNexo">
        <xs:annotation>
          <xs:documentation>Rachmistrz nexo.</xs:documentation>
        </xs:annotation>
      </xs:enumeration>
      <xs:enumeration value="RewizorNexo">
        <xs:annotation>
          <xs:documentation>Rewizor nexo.</xs:documentation>
        </xs:annotation>
      </xs:enumeration>
      <xs:enumeration value="GratyfikantNexo">
        <xs:annotation>
          <xs:documentation>Gratyfikant nexo.</xs:documentation>
        </xs:annotation>
      </xs:enumeration>
      <xs:enumeration value="BiuroNexo">
        <xs:annotation>
          <xs:documentation>Biuro nexo.</xs:documentation>
        </xs:annotation>
      </xs:enumeration>
      <xs:enumeration value="GestorNexo">
        <xs:annotation>
          <xs:documentation>Gestor nexo.</xs:documentation>
        </xs:annotation>
      </xs:enumeration>
      <xs:enumeration value="Inny">
        <xs:annotation>
          <xs:documentation>Inny.</xs:documentation>
        </xs:annotation>
      </xs:enumeration>
    </xs:restriction>
  </xs:simpleType>

  <xs:complexType name="TProdukt">
    <xs:annotation>
      <xs:documentation>Produkt.</xs:documentation>
    </xs:annotation>
    <xs:attribute name="Typ" type="TTypProduktu" use="required">
      <xs:annotation>
        <xs:documentation>Typ produktu.</xs:documentation>
      </xs:annotation>
    </xs:attribute>
    <xs:attribute name="NazwaInnegoProduktu" type="xs:string" use="optional">
      <xs:annotation>
        <xs:documentation>Nazwa innego produktu (opcjonalna).</xs:documentation>
      </xs:annotation>
    </xs:attribute>
  </xs:complexType>

  <xs:complexType name="TProdukty">
    <xs:annotation>
      <xs:documentation>Kolekcja produktów.</xs:documentation>
    </xs:annotation>
    <xs:sequence>
      <xs:element name="Produkt" type="TProdukt" maxOccurs="unbounded">
        <xs:annotation>
          <xs:documentation>Produkt.</xs:documentation>
        </xs:annotation>
      </xs:element>
    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="TNadawca">
    <xs:annotation>
      <xs:documentation>Informacje o nadawcy.</xs:documentation>
    </xs:annotation>
    <xs:sequence>
      <xs:element name="Produkty" type="TProdukty" minOccurs="1" maxOccurs="1">
        <xs:annotation>
          <xs:documentation>Produkty.</xs:documentation>
        </xs:annotation>
      </xs:element>
    </xs:sequence>
    <xs:attribute name="Wersja" type="xs:string" use="required">
      <xs:annotation>
        <xs:documentation>Wersja programu.</xs:documentation>
      </xs:annotation>
    </xs:attribute>
    <xs:attribute name="IdentyfikatorBazyDanych" type="xs:string" use="optional">
      <xs:annotation>
        <xs:documentation>Identyfikator bazy danych.</xs:documentation>
      </xs:annotation>
    </xs:attribute>
  </xs:complexType>

</xs:schema>