<?xml version="1.0" encoding="utf-8"?>
<xs:schema 
  xmlns:xs="http://www.w3.org/2001/XMLSchema" 
  elementFormDefault="qualified" 
  xmlns="http://schemas.insert.com.pl/2024/dokumentyDoKsiegowania"
  targetNamespace="http://schemas.insert.com.pl/2024/dokumentyDoKsiegowania"
  xmlns:ddk2012="http://schemas.insert.com.pl/2012/dokumentyDoKsiegowania"
  id="DaneBR_ParametrDostepnosciAtrybutuOpisuKsiegowegoPart">
  <xs:annotation>
    <xs:documentation>Konfiguracja parametrów dostępności atrybutu opisu księgowego biura rachunkowego.</xs:documentation>
  </xs:annotation>

  <xs:import id="TypyDanychPart" namespace="http://schemas.insert.com.pl/2012/dokumentyDoKsiegowania" schemaLocation="./TypyDanych_2012.xsd" />

  <xs:complexType name="TParametrDostepnosciAtrybutuOpisuKsiegowego">
    <xs:annotation>
      <xs:documentation>Obiekt parametru dostępności atrybutu opisu księgowego.</xs:documentation>
    </xs:annotation>
    <xs:sequence>
      <xs:element name="DostepneKsiegoweSlownikiUzytkownikaBIDs" minOccurs="0" maxOccurs="unbounded" type="ddk2012:TGuid">
        <xs:annotation>
          <xs:documentation>Identyfikatory dostępnych księgowych słowników użytkownika.</xs:documentation>
        </xs:annotation>
      </xs:element>
    </xs:sequence>
    <xs:attribute name="ElementDokumentu" use="required" type="xs:unsignedByte">
      <xs:annotation>
        <xs:documentation>Opisywany księgowo element dokumentu.</xs:documentation>
      </xs:annotation>
    </xs:attribute>
    <xs:attribute name="TypDokumentuDoKsiegowaniaBID" use="optional" type="ddk2012:TGuid">
      <xs:annotation>
        <xs:documentation>Identyfikator typu dokumentu do dekretacji.</xs:documentation>
      </xs:annotation>
    </xs:attribute>
  </xs:complexType>
  
  <xs:complexType name="TParametryDostepnosciAtrybutowOpisuKsiegowego">
    <xs:annotation>
      <xs:documentation>Kolekcja parametrów dostępności atrybutu opisu księgowego biura rachunkowego.</xs:documentation>
    </xs:annotation>
    <xs:sequence>
      <xs:element name="ParametrDostepnosciAtrybutuOpisuKsiegowego" maxOccurs="unbounded" type="TParametrDostepnosciAtrybutuOpisuKsiegowego">
        <xs:annotation>
          <xs:documentation>Parametr dostępności atrybutu opisu księgowego.</xs:documentation>
        </xs:annotation>
      </xs:element>
    </xs:sequence>
  </xs:complexType>
</xs:schema>