<?xml version="1.0" encoding="utf-8"?>
<xs:schema 
  id="Dane_RodzajeOperacjibankowej" 
  xmlns:xs="http://www.w3.org/2001/XMLSchema"
  xmlns="http://schemas.insert.com.pl/2025/dokumentyDoKsiegowania" 
  targetNamespace="http://schemas.insert.com.pl/2025/dokumentyDoKsiegowania">
  <xs:annotation>
    <xs:documentation>DaneKBR_2015_RodzajOperacjiBankowejPart</xs:documentation>
  </xs:annotation>
  
  <xs:import id="TypyDanychPart" namespace="http://schemas.insert.com.pl/2012/dokumentyDoKsiegowania" schemaLocation="./TypyDanych_2012.xsd" />
  
  <!--Slownik rodzajów operacji bankowej -->
  <xs:complexType name="TRodzajOperacjiBankowej">
    <xs:annotation>
      <xs:documentation>Obiekt rodzaju operacji bankowej.</xs:documentation>
    </xs:annotation>
    <xs:attribute name="Id" type="xs:ID" use="required">
      <xs:annotation>
        <xs:documentation>Identyfikator jednoznacznie identyfikujący w ramach pliku XML dla rodzaju operacji bankowej.</xs:documentation>
      </xs:annotation>
    </xs:attribute>
    <xs:attribute name="BId" type="xs:int" use="required">
      <xs:annotation>
        <xs:documentation>Identyfikator bazodanowy rodzaju operacji bankowej.</xs:documentation>
      </xs:annotation>
    </xs:attribute>
    <xs:attribute name="Nazwa" type="xs:string" use="required">
      <xs:annotation>
        <xs:documentation>Nazwa rodzaju operacji bankowej.</xs:documentation>
      </xs:annotation>
    </xs:attribute>
    <xs:attribute name="Kontrahent" type="xs:unsignedByte" use="required">
      <xs:annotation>
        <xs:documentation>Wymagalność podania kontrahenta (1 - wymagalny, 2 - dozwolony, 3 - niedozwolony).</xs:documentation>
      </xs:annotation>
    </xs:attribute>
    <xs:attribute name="RachunekBankowy" type="xs:unsignedByte" use="required">
      <xs:annotation>
        <xs:documentation>Wymagalność podania rachunku bankowego (1 - wymagalny, 2 - dozwolony, 3 - niedozwolony).</xs:documentation>
      </xs:annotation>
    </xs:attribute>
    <xs:attribute name="KartaPlatnicza" type="xs:unsignedByte" use="required">
      <xs:annotation>
        <xs:documentation>Wymagalność podania karty płatniczej (1 - wymagalny, 2 - dozwolony, 3 - niedozwolony).</xs:documentation>
      </xs:annotation>
    </xs:attribute>
    <xs:attribute name="TypOperacji" type="xs:unsignedByte" use="required">
      <xs:annotation>
        <xs:documentation>Typ operacji bankowej (1 - przelew, 2 - gotówka, 3 - karta, 4 - pozostałe operacje, 5 - transfer).</xs:documentation>
      </xs:annotation>
    </xs:attribute>
    <xs:attribute name="ElementTransferu" type="xs:unsignedByte" use="required">
      <xs:annotation>
        <xs:documentation>Element transferu.</xs:documentation>
      </xs:annotation>
    </xs:attribute>
  </xs:complexType>
  
  <xs:complexType name="TRodzajeOperacjiBankowej">
    <xs:annotation>
      <xs:documentation>Kolekcja rodzajów operacji bankowych.</xs:documentation>
    </xs:annotation>
    <xs:sequence>
      <xs:element name="RodzajeOperacjiBankowej" type="TRodzajOperacjiBankowej" maxOccurs="unbounded">
        <xs:annotation>
          <xs:documentation>Rodzaj operacji bankowej.</xs:documentation>
        </xs:annotation>
      </xs:element>
    </xs:sequence>
  </xs:complexType>
</xs:schema>