<?xml version="1.0" encoding="utf-8"?>
<!-- Uzyj xsd.exe do wygenerowania z tego kodu -->
<xs:schema
  xmlns:xs="http://www.w3.org/2001/XMLSchema" 
  elementFormDefault="qualified" 
  xmlns="http://schemas.insert.com.pl/2025/dokumentyDoKsiegowania" 
  targetNamespace="http://schemas.insert.com.pl/2025/dokumentyDoKsiegowania" 
  id="DaneKBR">
  <xs:annotation>
    <xs:documentation>Dane słowników klienta biura rachunkowego.</xs:documentation>
  </xs:annotation>
  
  <!-- xsd z definiowanymi typami danych -->
  <xs:import id="TypyDanychPart" namespace="http://schemas.insert.com.pl/2012/dokumentyDoKsiegowania" schemaLocation="./TypyDanych_2012.xsd" />
  <xs:include id="StanowiskaKasowePart" schemaLocation="./DaneKBR_Aktualna_StanowiskaKasowePart.xsd" />
  <xs:include id="FormyPlatnosciPart" schemaLocation="./DaneKBR_Aktualna_FormyPlatnosciPart.xsd" />
  <xs:include id="PodmiotyPart" schemaLocation="./DaneKBR_Aktualna_PodmiotyHistoriaPart.xsd" />
  <xs:include id="AdresyPart" schemaLocation="./DaneKBR_Aktualna_AdresyHistoriaPart.xsd" />
  <xs:include id="WalutyPart" schemaLocation="./DaneKBR_Aktualna_Waluty.xsd" />
  <xs:include id="DaneGeoraficznePart" schemaLocation="./DaneKBR_Aktualna_DaneGeograficznePart.xsd" />
  <xs:include id="MagazynyPart" schemaLocation="./DaneKBR_Aktualna_MagazynyPart.xsd" />
  <xs:include id="StawkaVatPart" schemaLocation="./DaneKBR_Aktualna_StawkaVatPart.xsd" />
  <xs:include id="RodzajOperacjiKasowejPart" schemaLocation="./DaneKBR_Aktualna_RodzajOperacjiKasowejPart.xsd" />
  <xs:include id="RachunkiBankowePart" schemaLocation="./DaneKBR_Aktualna_RachunkiBankowePart.xsd" />
  <xs:include id="KategorieDokumentowPart" schemaLocation="./DaneKBR_Aktualna_KategorieDokumentow.xsd" />
  <xs:include id="GrupyPodmiotowPart" schemaLocation="./DaneKBR_Aktualna_GrupyPodmiotowPart.xsd" />
  <xs:include id="PodtypyRozrachunkowPart" schemaLocation="./DaneKBR_Aktualna_PodtypyRozrachunkowPart.xsd" />
  <xs:include id="RodzajeOperacjiBankowychPart" schemaLocation="./DaneKBR_Aktualna_RodzajOperacjiBankowejPart.xsd" />
  <xs:include id="AsortymentyPart" schemaLocation="./DaneKBR_Aktualna_AsortymentyPart.xsd" />
  <xs:include id="SkladnikiPlacowePart" schemaLocation="./DaneKBR_Aktualna_SlownikiKadrowoPlacowe.xsd" />
  <xs:include id="StawkaRyczaltowaPart" schemaLocation="./DaneKBR_Aktualna_StawkaRyczaltowaPart.xsd" />
  
  <!-- BEGIN Slowniki -->
  <!-- Slowniki -->
  <xs:complexType name="TSlowniki">
    <xs:annotation>
      <xs:documentation>Obiekt słowników klienta biura rachunkowego.</xs:documentation>
    </xs:annotation>
    <xs:sequence>
      <xs:element name="PodmiotyHistoria" type="TPodmiotyHistoria" minOccurs="0" maxOccurs="1">
        <xs:annotation>
          <xs:documentation>Wpisy historyczne podmiotów.</xs:documentation>
        </xs:annotation>
      </xs:element>
      <xs:element name="Podmioty" type="TPodmioty" minOccurs="0" maxOccurs="1">
        <xs:annotation>
          <xs:documentation>Podmioty.</xs:documentation>
        </xs:annotation>
      </xs:element>
      <xs:element name="StanowiskaKasowe" type="TStanowiskaKasowe" minOccurs="0" maxOccurs="1">
        <xs:annotation>
          <xs:documentation>Stanowiska kasowe.</xs:documentation>
        </xs:annotation>
      </xs:element>
      <xs:element name="Kasy" type="TKasy" minOccurs="0" maxOccurs="1">
        <xs:annotation>
          <xs:documentation>Kasy.</xs:documentation>
        </xs:annotation>
      </xs:element>
      <xs:element name="FormyPlatnosci" type="TFormyPlatnosci" minOccurs="0" maxOccurs="1">
        <xs:annotation>
          <xs:documentation>Formy płatności.</xs:documentation>
        </xs:annotation>
      </xs:element>
      <xs:element name="TypyPlatnosci" type="TTypyPlatnosci" minOccurs="0" maxOccurs="1">
        <xs:annotation>
          <xs:documentation>Typy płatności.</xs:documentation>
        </xs:annotation>
      </xs:element>
      <xs:element name="AdresyHistoria" type="TAdresyHistoria" minOccurs="0" maxOccurs="1">
        <xs:annotation>
          <xs:documentation>Wpisy historyczne adresów podmiotów.</xs:documentation>
        </xs:annotation>
      </xs:element>
      <xs:element name="TypyAdresu" type="TTypyAdresu" minOccurs="0" maxOccurs="1">
        <xs:annotation>
          <xs:documentation>Typy adresu.</xs:documentation>
        </xs:annotation>
      </xs:element>
      <xs:element name="Adresy" type="TAdresy" minOccurs="0" maxOccurs="1">
        <xs:annotation>
          <xs:documentation>Adresy.</xs:documentation>
        </xs:annotation>
      </xs:element>
      <xs:element name="Waluty" type="TWaluty" minOccurs="0" maxOccurs="1">
        <xs:annotation>
          <xs:documentation>Waluty.</xs:documentation>
        </xs:annotation>
      </xs:element>
      <xs:element name="Panstwa" type="TPanstwa" minOccurs="0" maxOccurs="1">
        <xs:annotation>
          <xs:documentation>Państwa.</xs:documentation>
        </xs:annotation>
      </xs:element>
      <xs:element name="Wojewodztwa" type="TWojewodztwa" minOccurs="0" maxOccurs="1">
        <xs:annotation>
          <xs:documentation>Województwa.</xs:documentation>
        </xs:annotation>
      </xs:element>
      <xs:element name="Powiaty" type="TPowiaty" minOccurs="0" maxOccurs="1">
        <xs:annotation>
          <xs:documentation>Powiaty.</xs:documentation>
        </xs:annotation>
      </xs:element>
      <xs:element name="Gminy" type="TGminy" minOccurs="0" maxOccurs="1">
        <xs:annotation>
          <xs:documentation>Gminy.</xs:documentation>
        </xs:annotation>
      </xs:element>
      <xs:element name="Magazyny" type="TMagazyny" minOccurs="0" maxOccurs="1">
        <xs:annotation>
          <xs:documentation>Magazyny.</xs:documentation>
        </xs:annotation>
      </xs:element>
      <xs:element name="JednostkiOrganizacyjne" type="TJednostkiOrganizacyjne" minOccurs="0" maxOccurs="1">
        <xs:annotation>
          <xs:documentation>Oddziały i centrale.</xs:documentation>
        </xs:annotation>
      </xs:element>
      <xs:element name="StawkiVat" type="TStawkiVat" minOccurs="0" maxOccurs="1">
        <xs:annotation>
          <xs:documentation>Stawki VAT.</xs:documentation>
        </xs:annotation>
      </xs:element>
      <xs:element name="RodzajeOperacjiKasowej" type="TRodzajeOperacjiKasowej" minOccurs="0" maxOccurs="1">
        <xs:annotation>
          <xs:documentation>Rodzaje operacji kasowej.</xs:documentation>
        </xs:annotation>
      </xs:element>
      <xs:element name="MiejscaSprzedazy" type="TMiejscaSprzedazy" minOccurs="0" maxOccurs="1">
        <xs:annotation>
          <xs:documentation>Miejsca sprzedaży.</xs:documentation>
        </xs:annotation>
      </xs:element>
      <xs:element name="RachunkiBankowe" type="TRachunkiBankowe" minOccurs="0" maxOccurs="1">
        <xs:annotation>
          <xs:documentation>Rachunki bankowe.</xs:documentation>
        </xs:annotation>
      </xs:element>
      <xs:element name="KategorieDokumentow" type="TKategorieDokumentow" minOccurs="0" maxOccurs="1">
        <xs:annotation>
          <xs:documentation>Kategorie dokumentów.</xs:documentation>
        </xs:annotation>
      </xs:element>
      <xs:element name="GrupyPodmiotow" type="TGrupyPodmiotow" minOccurs="0" maxOccurs="1">
        <xs:annotation>
          <xs:documentation>Grupy podmiotów.</xs:documentation>
        </xs:annotation>
      </xs:element>
      <xs:element name="PodtypyRozrachunkow" type="TPodtypyRozrachunkow" minOccurs="0" maxOccurs="1">
        <xs:annotation>
          <xs:documentation>Podtypy rozrachunków.</xs:documentation>
        </xs:annotation>
      </xs:element>
      <xs:element name="RodzajeOperacjiBankowej" type="TRodzajeOperacjiBankowej" minOccurs="0" maxOccurs="1">
        <xs:annotation>
          <xs:documentation>Rodzaje operacji bankowej.</xs:documentation>
        </xs:annotation>
      </xs:element>
      <xs:element name="GrupyAsortymentow" type="TGrupyAsortymentow" minOccurs="0" maxOccurs="1">
        <xs:annotation>
          <xs:documentation>Grupy asortymentów.</xs:documentation>
        </xs:annotation>
      </xs:element>
      <xs:element name="CechyAsortymentow" type="TCechyAsortymentow" minOccurs="0" maxOccurs="1">
        <xs:annotation>
          <xs:documentation>Cechy asortymentów.</xs:documentation>
        </xs:annotation>
      </xs:element>
      <xs:element name="Regiony" type="TRegiony" minOccurs="0" maxOccurs="1">
        <xs:annotation>
          <xs:documentation>Regiony.</xs:documentation>
        </xs:annotation>
      </xs:element>   
      <xs:element name="Cechy" type="TCechy" minOccurs="0" maxOccurs="1">
        <xs:annotation>
          <xs:documentation>Cechy.</xs:documentation>
        </xs:annotation>
      </xs:element>
      <xs:element name="GrupyCech" type="TGrupyCech" minOccurs="0" maxOccurs="1">
        <xs:annotation>
          <xs:documentation>Grupy cech.</xs:documentation>
        </xs:annotation>
      </xs:element>
      <xs:element name="Branze" type="TBranze" minOccurs="0" maxOccurs="1">
        <xs:annotation>
          <xs:documentation>Branże.</xs:documentation>
        </xs:annotation>
      </xs:element>
      <xs:element name="UczestnictwaWProgramie" type="TUczestnictwaWProgramie" minOccurs="0" maxOccurs="1">
        <xs:annotation>
          <xs:documentation>Uczestnictwa w programach lojalnościowych.</xs:documentation>
        </xs:annotation>
      </xs:element>
      <xs:element name="DzialyPodmiotu" type="TDzialyPodmiotu" minOccurs="0" maxOccurs="1">
        <xs:annotation>
          <xs:documentation>Działy podmiotu.</xs:documentation>
        </xs:annotation>
      </xs:element>
      <xs:element name="Stanowiska" type="TStanowiska" minOccurs="0" maxOccurs="1">
        <xs:annotation>
          <xs:documentation>Stanowiska.</xs:documentation>
        </xs:annotation>
      </xs:element>
      <xs:element name="Przedstawiciele" type="TPrzedstawiciele" minOccurs="0" maxOccurs="1">
        <xs:annotation>
          <xs:documentation>Przedstawiciele.</xs:documentation>
        </xs:annotation>
      </xs:element>
      <xs:element name="ProgramyLojalnosciowe" type="TProgramyLojalnosciowe" minOccurs="0" maxOccurs="1">
        <xs:annotation>
          <xs:documentation>Programy lojalnościowe.</xs:documentation>
        </xs:annotation>
      </xs:element>
      <xs:element name="SkladnikiPlacowe" type="TSkladnikiPlacowe" minOccurs="0" maxOccurs="1">
        <xs:annotation>
          <xs:documentation>Składniki płacowe.</xs:documentation>
        </xs:annotation>
      </xs:element>
      <xs:element name="RodzajePracyWSzczegolnychWarunkach" type="TRodzajePracyWSzczegolnychWarunkach" minOccurs="0" maxOccurs="1">
        <xs:annotation>
          <xs:documentation>Rodzaje pracy w szególnych warunkach.</xs:documentation>
        </xs:annotation>
      </xs:element>
      <xs:element name="KodyTutuluUbezpieczenia" type="TKodyTutuluUbezpieczenia" minOccurs="0" maxOccurs="1">
        <xs:annotation>
          <xs:documentation>Kody tytułu ubezpieczeń.</xs:documentation>
        </xs:annotation>
      </xs:element>
      <xs:element name="TypyUmowyPracowniczejHistoria" type="TTypyUmowyPracowniczejHistoria" minOccurs="0" maxOccurs="1">
        <xs:annotation>
          <xs:documentation>Typy umowy pracowniczej historia.</xs:documentation>
        </xs:annotation>
      </xs:element>
      <xs:element name="RodzajeUmowPracowniczych" type="TRodzajeUmowPracowniczych" minOccurs="0" maxOccurs="1">
        <xs:annotation>
          <xs:documentation>Rodzaje umów pracowniczych.</xs:documentation>
        </xs:annotation>
      </xs:element>
      <xs:element name="JednostkiOrganizacyjneGr" type="TJednostkiOrganizacyjneGr" minOccurs="0" maxOccurs="1">
        <xs:annotation>
          <xs:documentation>Jednostki organizacyjne (działy).</xs:documentation>
        </xs:annotation>
      </xs:element>
      <xs:element name="RodzajeWydatkowDelegacja" type="TRodzajeWydatkowDelegacji" minOccurs="0" maxOccurs="1">
        <xs:annotation>
          <xs:documentation>Rodzaje wydwtków delegacje.</xs:documentation>
        </xs:annotation>
      </xs:element>
      <xs:element name="KategoriePlacowe" type="TKategoriePlacowe" minOccurs="0" maxOccurs="1">
        <xs:annotation>
          <xs:documentation>Kategorie płacowe.</xs:documentation>
        </xs:annotation>
      </xs:element>
      <xs:element name="StawkiRyczaltowe" type="TStawkiRyczaltoweKBR" minOccurs="0" maxOccurs="1">
        <xs:annotation>
          <xs:documentation>Stawki ryczałtowe.</xs:documentation>
        </xs:annotation>
      </xs:element>
    </xs:sequence>
  </xs:complexType>
  <!-- END Slowniki -->
</xs:schema>
