<?xml version="1.0" encoding="utf-8"?>
<xs:schema 
  id="Dane_RodzajeOperacjiKasowej" 
  xmlns:xs="http://www.w3.org/2001/XMLSchema" 
  xmlns="http://schemas.insert.com.pl/2025/dokumentyDoKsiegowania" 
  targetNamespace="http://schemas.insert.com.pl/2025/dokumentyDoKsiegowania">
  <xs:annotation>
    <xs:documentation>Dane rodzajów operacji kasowych.</xs:documentation>
  </xs:annotation>
  
  <xs:import id="TypyDanychPart" namespace="http://schemas.insert.com.pl/2012/dokumentyDoKsiegowania" schemaLocation="./TypyDanych_2012.xsd" />
  
  <!--Slownik rodzajów operacji kasowej -->
  <xs:complexType name="TRodzajOperacjiKasowej">
    <xs:annotation>
      <xs:documentation>Obiekt rodzaju operacji kasowej.</xs:documentation>
    </xs:annotation>
    <xs:attribute name="Id" type="xs:ID" use="required">
      <xs:annotation>
        <xs:documentation>Identyfikator jednoznacznie identyfikujący w ramach pliku XML dla rodzaju operacji kasowej.</xs:documentation>
      </xs:annotation>
    </xs:attribute>
    <xs:attribute name="BId" type="xs:int" use="required">
      <xs:annotation>
        <xs:documentation>Identyfikator bazodanowy rodzaju operacji kasowej.</xs:documentation>
      </xs:annotation>
    </xs:attribute>
    <xs:attribute name="Typ" type="xs:short" use="required">
      <xs:annotation>
        <xs:documentation>Typ operacji kasowej (0 - zwykły, 1 - transfer, 2 - inwentaryzacja).</xs:documentation>
      </xs:annotation>
    </xs:attribute>
    <xs:attribute name="Nazwa" type="xs:string" use="required">
      <xs:annotation>
        <xs:documentation>Nazwa rodzaju operacji kasowej.</xs:documentation>
      </xs:annotation>
    </xs:attribute>
  </xs:complexType>
  
  <xs:complexType name="TRodzajeOperacjiKasowej">
    <xs:annotation>
      <xs:documentation>Kolekcja rodzajów operacji kasowej.</xs:documentation>
    </xs:annotation>
    <xs:sequence>
      <xs:element name="RodzajeOperacjiKasowej" type="TRodzajOperacjiKasowej" maxOccurs="unbounded">
        <xs:annotation>
          <xs:documentation>Rodzaje operacji kasowej.</xs:documentation>
        </xs:annotation>
      </xs:element>
    </xs:sequence>
  </xs:complexType>
</xs:schema>