<?xml version="1.0" encoding="utf-8"?>
<xs:schema 
  id="Dane_PodtypyRozrachunkowPart" 
  elementFormDefault="qualified" 
  xmlns="http://schemas.insert.com.pl/2025/dokumentyDoKsiegowania"
  targetNamespace="http://schemas.insert.com.pl/2025/dokumentyDoKsiegowania"
  xmlns:xs="http://www.w3.org/2001/XMLSchema"
  xmlns:ddk2012="http://schemas.insert.com.pl/2012/dokumentyDoKsiegowania">
  <xs:annotation>
    <xs:documentation>DaneKBR_2014_PodtypyRozrachunkowPart</xs:documentation>
  </xs:annotation>
  
  <xs:import id="TypyDanychPart" namespace="http://schemas.insert.com.pl/2012/dokumentyDoKsiegowania" schemaLocation="./TypyDanych_2012.xsd" />
  
  <xs:complexType name="TPodtypRozrachunkow">
    <xs:annotation>
      <xs:documentation>Obiekt rodzaju rozrachunków.</xs:documentation>
    </xs:annotation>
    <xs:attribute name="Id" type="xs:ID" use="required">
      <xs:annotation>
        <xs:documentation>Identyfikator jednoznacznie identyfikujący w ramach pliku XML dla rodzaju rozrachunków.</xs:documentation>
      </xs:annotation>
    </xs:attribute>
    <xs:attribute name="BId" type="ddk2012:TGuid" use="required">
      <xs:annotation>
        <xs:documentation>Identyfikator bazodanowy rodzaju rozrachunków.</xs:documentation>
      </xs:annotation>
    </xs:attribute>
    <xs:attribute name="Nazwa" type="xs:string">
      <xs:annotation>
        <xs:documentation>Nazwa rodzaju rozrachunków.</xs:documentation>
      </xs:annotation>
    </xs:attribute>
    <xs:attribute name="Typ" type="xs:unsignedByte" use="required">
      <xs:annotation>
        <xs:documentation>Typ rodzaju rozrachunków (1 - należność, 2 - zobowiązanie).</xs:documentation>
      </xs:annotation>
    </xs:attribute>
    <xs:attribute name="Rodzaj" type="xs:unsignedByte" use="required">
      <xs:annotation>
        <xs:documentation>Rodzaj (1 - przychód, 2 - koszt).</xs:documentation>
      </xs:annotation>
    </xs:attribute>
    <xs:attribute name="RodzajRK" type="xs:unsignedByte" use="required">
      <xs:annotation>
        <xs:documentation>Rodzaj różnicy kursowej (0 - nie, 1 - zrealizowana, 2 - wycena, 3 - storno).</xs:documentation>
      </xs:annotation>
    </xs:attribute>
    <xs:attribute name="Symbol" type="xs:string">
      <xs:annotation>
        <xs:documentation>Symbol rodzaju rozrachunków.</xs:documentation>
      </xs:annotation>
    </xs:attribute>
  </xs:complexType>
  
  <xs:complexType name="TPodtypyRozrachunkow">
    <xs:annotation>
      <xs:documentation>Kolekcja rodzajów rozrachunków.</xs:documentation>
    </xs:annotation>
    <xs:sequence>
      <xs:element name="PodtypRozrachunkow" type="TPodtypRozrachunkow" maxOccurs="unbounded">
        <xs:annotation>
          <xs:documentation>Rodzaj rozrachunków.</xs:documentation>
        </xs:annotation>
      </xs:element>
    </xs:sequence>
  </xs:complexType>
</xs:schema>