<?xml version="1.0" encoding="utf-8"?>
<!-- Uzyj xsd.exe do wygenerowania z tego kodu -->
<xs:schema
  xmlns:xs="http://www.w3.org/2001/XMLSchema"
  elementFormDefault="qualified"
  xmlns="http://schemas.insert.com.pl/2025/dokumentyDoKsiegowania" 
  targetNamespace="http://schemas.insert.com.pl/2025/dokumentyDoKsiegowania"
  id="DaneKBR_DokumentPart">
  <xs:annotation>
    <xs:documentation>Dane dokumentów do dekretacji.</xs:documentation>
  </xs:annotation>
  
  <!-- xsd z definiowanymi typami danych -->
  <xs:import id="TypyDanychPart" namespace="http://schemas.insert.com.pl/2012/dokumentyDoKsiegowania" schemaLocation="./TypyDanych_2012.xsd" />
  <xs:include id="NaglowekPart" schemaLocation="./DaneKBR_Aktualna_NaglowekPart.xsd" />
  <xs:include id="OpisyKsiegowePart" schemaLocation="./DaneKBR_Aktualna_OpisyKsiegowePart.xsd" />
  
  <!-- Dokument -->
  <xs:complexType name="TDokument">
    <xs:annotation>
      <xs:documentation>Obiekt dokumentu.</xs:documentation>
    </xs:annotation>
    <xs:sequence>
      <xs:element name="Naglowek" type="TNaglowek">
        <xs:annotation>
          <xs:documentation>Nagłówek dokumentu.</xs:documentation>
        </xs:annotation>
      </xs:element>
      <xs:element name="OpisyKsiegowe" type="TOpisyKsiegoweKBR" minOccurs="0" maxOccurs="1">
        <xs:annotation>
          <xs:documentation>Kolekcja opisów księgowych.</xs:documentation>
        </xs:annotation>
      </xs:element>
      <xs:element name="Tresc" type="xs:string">
        <xs:annotation>
          <xs:documentation>Treść dokumentu (np. zagnieżdżony dokument XML).</xs:documentation>
        </xs:annotation>
      </xs:element>
    </xs:sequence>
  </xs:complexType>
  
  <xs:complexType name="TDokumenty">
    <xs:annotation>
      <xs:documentation>Kolekcja dokumentów do dekretacji.</xs:documentation>
    </xs:annotation>
    <xs:sequence>
      <xs:element name="Dokument" type="TDokument" minOccurs="0" maxOccurs="unbounded">
        <xs:annotation>
          <xs:documentation>Dokument do dekretacji.</xs:documentation>
        </xs:annotation>
      </xs:element>
    </xs:sequence>
  </xs:complexType>
</xs:schema>