<?xml version="1.0" encoding="utf-8"?>
<!-- Uzyj xsd.exe do wygenerowania z tego kodu -->
<xs:schema 
  xmlns:xs="http://www.w3.org/2001/XMLSchema" 
  elementFormDefault="qualified" 
  xmlns="http://schemas.insert.com.pl/2017/dokumentyDoKsiegowania/place" 
  targetNamespace="http://schemas.insert.com.pl/2017/dokumentyDoKsiegowania/place" 
  xmlns:ddk="http://schemas.insert.com.pl/2012/dokumentyDoKsiegowania">
  <xs:annotation>
    <xs:documentation>Dane delegacji.</xs:documentation>
  </xs:annotation>
  
  <xs:import id="TypyDanychPart" namespace="http://schemas.insert.com.pl/2012/dokumentyDoKsiegowania" schemaLocation="./TypyDanych_2012.xsd" />
  <xs:import id="PolaWlasnePart" namespace="http://schemas.insert.com.pl/2012/dokumentyDoKsiegowania" schemaLocation="./Dane_2012_PolaWlasnePart.xsd" />

  <xs:complexType name="TNaglowekDelegacji">
    <xs:annotation>
      <xs:documentation>Zbiór pól nagłówkowych delegacji.</xs:documentation>
    </xs:annotation>
    <xs:sequence>
      <xs:element name="Numer" type="xs:string" nillable="false">
        <xs:annotation>
          <xs:documentation>Numer delegacji.</xs:documentation>
        </xs:annotation>
      </xs:element>
      <xs:element name="DataWystawienia" type="xs:date" nillable="false">
        <xs:annotation>
          <xs:documentation>Data wystawienia delegacji.</xs:documentation>
        </xs:annotation>
      </xs:element>
      <xs:element name="Koszt" type="xs:decimal" nillable="false">
        <xs:annotation>
          <xs:documentation>Koszt delegacji ogółem.</xs:documentation>
        </xs:annotation>
      </xs:element>
      <xs:element name="Pracownik" type="ddk:TPositiveInt" nillable="false">
        <xs:annotation>
          <xs:documentation>Pracownik delegacji.</xs:documentation>
        </xs:annotation>
      </xs:element>
      <xs:element name="Nazwa" type="xs:string" nillable="false">
        <xs:annotation>
          <xs:documentation>Nazwa delegacji.</xs:documentation>
        </xs:annotation>
      </xs:element>
      <xs:element name="Opis" type="xs:string" nillable="false">
        <xs:annotation>
          <xs:documentation>Opis delegacji.</xs:documentation>
        </xs:annotation>
      </xs:element>
      <xs:element name="CelWyjazdu" type="xs:string" nillable="false">
        <xs:annotation>
          <xs:documentation>Cel wyjazdu.</xs:documentation>
        </xs:annotation>
      </xs:element>
      <xs:element name="MiejsceDocelowe" type="xs:string" nillable="false">
        <xs:annotation>
          <xs:documentation>Miejsce docelowe.</xs:documentation>
        </xs:annotation>
      </xs:element>
      <xs:element name="DataRozpoczecia" type="xs:date" nillable="false">
        <xs:annotation>
          <xs:documentation>Data rozpoczęcia delegacji.</xs:documentation>
        </xs:annotation>
      </xs:element>
      <xs:element name="DataZakonczenia" type="xs:date" nillable="false">
        <xs:annotation>
          <xs:documentation>Data zakończenia delegacji.</xs:documentation>
        </xs:annotation>
      </xs:element>
      <xs:element name="SrodekLokomocji" type="xs:unsignedByte" nillable="false">
        <xs:annotation>
          <xs:documentation>Środek lokomocji.</xs:documentation>
        </xs:annotation>
      </xs:element>
      <xs:element name="NrRejestracyjny" type="xs:string" nillable="false">
        <xs:annotation>
          <xs:documentation>NumerRejestracyjny.</xs:documentation>
        </xs:annotation>
      </xs:element>
      <xs:element name="CzyZaliczka" type="xs:boolean" nillable="false">
        <xs:annotation>
          <xs:documentation>Czy zaliczka.</xs:documentation>
        </xs:annotation>
      </xs:element>
      <xs:element name="DataRozliczenia" type="xs:date" nillable="true">
        <xs:annotation>
          <xs:documentation>Data rozliczenia delegacji.</xs:documentation>
        </xs:annotation>
      </xs:element>
      <xs:element name="DokumentRozliczajacy" type="xs:string" nillable="false">
        <xs:annotation>
          <xs:documentation>Dokument rozliczający.</xs:documentation>
        </xs:annotation>
      </xs:element>
      <xs:element name="DojazdyRyczalt" type="xs:decimal" nillable="false">
        <xs:annotation>
          <xs:documentation>Ryczałt za dojazdy.</xs:documentation>
        </xs:annotation>
      </xs:element>
      <xs:element name="DojazdyPrzejazdyRazem" type="xs:decimal" nillable="false">
        <xs:annotation>
          <xs:documentation>RAzem przejazdy dojazdy.</xs:documentation>
        </xs:annotation>
      </xs:element>
      <xs:element name="Diety" type="xs:decimal" nillable="false">
        <xs:annotation>
          <xs:documentation>Diety.</xs:documentation>
        </xs:annotation>
      </xs:element>
      <xs:element name="NoclegiWgRachunkow" type="xs:decimal" nillable="false">
        <xs:annotation>
          <xs:documentation>Noclegi według rachunków.</xs:documentation>
        </xs:annotation>
      </xs:element>
      <xs:element name="NoclegiRyczalt" type="xs:decimal" nillable="false">
        <xs:annotation>
          <xs:documentation>Noclegi ryczałt.</xs:documentation>
        </xs:annotation>
      </xs:element>
      <xs:element name="Szpital" type="xs:decimal" nillable="true">
        <xs:annotation>
          <xs:documentation>Szpital.</xs:documentation>
        </xs:annotation>
      </xs:element>
      <xs:element name="InneWydatki" type="xs:decimal" nillable="false">
        <xs:annotation>
          <xs:documentation>inne wydatki.</xs:documentation>
        </xs:annotation>
      </xs:element>
      <xs:element name="PozostaleWydatki" type="xs:decimal" nillable="false">
        <xs:annotation>
          <xs:documentation>Pozostałe wydatki.</xs:documentation>
        </xs:annotation>
      </xs:element>
      <xs:element name="Zaliczka" type="xs:decimal" nillable="true">
        <xs:annotation>
          <xs:documentation>Zaliczka.</xs:documentation>
        </xs:annotation>
      </xs:element>
      <xs:element name="KolekcjePolWlasnych" type="ddk:TKolekcjePolWlasnych" minOccurs="0" maxOccurs="1">
        <xs:annotation>
          <xs:documentation>Zbiór pól własnych delegacji.</xs:documentation>
        </xs:annotation>
      </xs:element>
      <xs:element name="KrajDocelowy" type="xs:int" nillable="true">
        <xs:annotation>
          <xs:documentation>Kraj docelowy.</xs:documentation>
        </xs:annotation>
      </xs:element>
    <xs:element name="DoWyplaty" type="xs:decimal" nillable="false">
        <xs:annotation>
          <xs:documentation>Kwota do wypłaty.</xs:documentation>
        </xs:annotation>
      </xs:element>
    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="TWydatekWgZalacznika">
    <xs:annotation>
      <xs:documentation>Dane wydatku delegacji.</xs:documentation>
    </xs:annotation>
    <xs:sequence>
      <xs:element name="Data" type="xs:date" nillable="false">
        <xs:annotation>
          <xs:documentation>Data.</xs:documentation>
        </xs:annotation>
      </xs:element>
      <xs:element name="Zagraniczny" type="xs:boolean" nillable="false">
        <xs:annotation>
          <xs:documentation>Czy zagraniczny</xs:documentation>
        </xs:annotation>
      </xs:element>
      <xs:element name="RodzajWydatkuDelegacji" type="xs:int" nillable="false">
        <xs:annotation>
          <xs:documentation>Rodzaj wydatku delegacji</xs:documentation>
        </xs:annotation>
      </xs:element>
      <xs:element name="LiczbaNoclegow" type="xs:int" nillable="true">
        <xs:annotation>
          <xs:documentation>liczba noclegów</xs:documentation>
        </xs:annotation>
      </xs:element>
      <xs:element name="KosztPLN" type="xs:decimal" nillable="false">
        <xs:annotation>
          <xs:documentation>Koszt w PLN.</xs:documentation>
        </xs:annotation>
      </xs:element>
      <xs:element name="KosztWaluta" type="xs:decimal" nillable="true">
        <xs:annotation>
          <xs:documentation>Koszt w walucie.</xs:documentation>
        </xs:annotation>
      </xs:element>
      <xs:element name="Kurs" type="xs:decimal" nillable="true">
        <xs:annotation>
          <xs:documentation>Kurs.</xs:documentation>
        </xs:annotation>
      </xs:element>
      <xs:element name="Waluta" type="xs:string" nillable="true">
        <xs:annotation>
          <xs:documentation>Koszt.</xs:documentation>
        </xs:annotation>
      </xs:element>
    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="TWydatkiWgZalacznikow">
    <xs:annotation>
      <xs:documentation>Kolekcja wydatków według załączników.</xs:documentation>
    </xs:annotation>
    <xs:sequence>
      <xs:element minOccurs="0" maxOccurs="unbounded" name="Wydatek" type="TWydatekWgZalacznika">
        <xs:annotation>
          <xs:documentation>Wydatki według załączników.</xs:documentation>
        </xs:annotation>
      </xs:element>
    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="TPrzejazd">
    <xs:annotation>
      <xs:documentation>Dane wydatku delegacji.</xs:documentation>
    </xs:annotation>
    <xs:sequence>
      <xs:element name="Wyjazd" type="xs:date" nillable="false">
        <xs:annotation>
          <xs:documentation>Wyjazd.</xs:documentation>
        </xs:annotation>
      </xs:element>
      <xs:element name="Skad" type="xs:string" nillable="false">
        <xs:annotation>
          <xs:documentation>Skąd.</xs:documentation>
        </xs:annotation>
      </xs:element>
      <xs:element name="Przyjazd" type="xs:date" nillable="false">
        <xs:annotation>
          <xs:documentation>Przyjazd.</xs:documentation>
        </xs:annotation>
      </xs:element>
      <xs:element name="Dokad" type="xs:string" nillable="false">
        <xs:annotation>
          <xs:documentation>Dokąd.</xs:documentation>
        </xs:annotation>
      </xs:element>
      <xs:element name="Zagraniczny" type="xs:boolean" nillable="false">
        <xs:annotation>
          <xs:documentation>Czy zagraniczny</xs:documentation>
        </xs:annotation>
      </xs:element>
      <xs:element name="SrodekLokomocji" type="xs:unsignedByte" nillable="false">
        <xs:annotation>
          <xs:documentation>Środek lokomocji.</xs:documentation>
        </xs:annotation>
      </xs:element>
      <xs:element name="LiczbaKm" type="xs:int" nillable="false">
        <xs:annotation>
          <xs:documentation>Liczba kilometrów</xs:documentation>
        </xs:annotation>
      </xs:element>
       <xs:element name="KosztPLN" type="xs:decimal" nillable="false">
        <xs:annotation>
          <xs:documentation>Koszt w PLN.</xs:documentation>
        </xs:annotation>
      </xs:element>
      <xs:element name="KosztWaluta" type="xs:decimal" nillable="true">
        <xs:annotation>
          <xs:documentation>Koszt w walucie.</xs:documentation>
        </xs:annotation>
      </xs:element>
      <xs:element name="Kurs" type="xs:decimal" nillable="true">
        <xs:annotation>
          <xs:documentation>Kurs.</xs:documentation>
        </xs:annotation>
      </xs:element>
      <xs:element name="Waluta" type="xs:string" nillable="true">
        <xs:annotation>
          <xs:documentation>Koszt.</xs:documentation>
        </xs:annotation>
      </xs:element>
    </xs:sequence>
    
  </xs:complexType>

  <xs:complexType name="TPrzejazdy">
    <xs:annotation>
      <xs:documentation>Kolekcja przejazdów.</xs:documentation>
    </xs:annotation>
    <xs:sequence>
      <xs:element minOccurs="0" maxOccurs="unbounded" name="Wydatek" type="TPrzejazd">
        <xs:annotation>
          <xs:documentation>Przejazdy.</xs:documentation>
        </xs:annotation>
      </xs:element>
    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="TDietaRyczalt">
    <xs:annotation>
      <xs:documentation>Dane wydatku delegacji.</xs:documentation>
    </xs:annotation>
    <xs:sequence>
      <xs:element name="Rodzaj" type="xs:unsignedByte" nillable="false">
        <xs:annotation>
          <xs:documentation>Rodzaj.</xs:documentation>
        </xs:annotation>
      </xs:element>
      <xs:element name="Zagraniczny" type="xs:boolean" nillable="false">
        <xs:annotation>
          <xs:documentation>Czy zagraniczny</xs:documentation>
        </xs:annotation>
      </xs:element>
      <xs:element name="KosztPLN" type="xs:decimal" nillable="false">
        <xs:annotation>
          <xs:documentation>Koszt.</xs:documentation>
        </xs:annotation>
      </xs:element>
      <xs:element name="KosztWaluta" type="xs:decimal" nillable="true">
        <xs:annotation>
          <xs:documentation>Koszt.</xs:documentation>
        </xs:annotation>
      </xs:element>
      <xs:element name="Kurs" type="xs:decimal" nillable="true">
        <xs:annotation>
          <xs:documentation>Koszt.</xs:documentation>
        </xs:annotation>
      </xs:element>
      <xs:element name="Waluta" type="xs:string" nillable="true">
        <xs:annotation>
          <xs:documentation>Koszt.</xs:documentation>
        </xs:annotation>
      </xs:element>
    </xs:sequence>

  </xs:complexType>

  <xs:complexType name="TDietyRyczalty">
    <xs:annotation>
      <xs:documentation>Kolekcja przejazdów.</xs:documentation>
    </xs:annotation>
    <xs:sequence>
      <xs:element minOccurs="0" maxOccurs="unbounded" name="DietaRyczalt" type="TDietaRyczalt">
        <xs:annotation>
          <xs:documentation>Przejazdy.</xs:documentation>
        </xs:annotation>
      </xs:element>
    </xs:sequence>
  </xs:complexType>
  
  <xs:complexType name="TDelegacja">
    <xs:annotation>
      <xs:documentation>Delegacja wraz z wersją schematu.</xs:documentation>
    </xs:annotation>
    <xs:sequence>
      <xs:element name="Wersja" type="xs:string" nillable="false" fixed="2017">
        <xs:annotation>
          <xs:documentation>Wersja schematu.</xs:documentation>
        </xs:annotation>
      </xs:element>
      <xs:element name="Naglowek" type="TNaglowekDelegacji" nillable="false">
        <xs:annotation>
          <xs:documentation>Nagłówek delegacji.</xs:documentation>
        </xs:annotation>
      </xs:element>
      <xs:element name="Wydatki" type="TWydatkiWgZalacznikow" nillable="true">
        <xs:annotation>
          <xs:documentation>Pozycje wydatków według załączników.</xs:documentation>
        </xs:annotation>
      </xs:element>
      <xs:element name="Przejazdy" type="TPrzejazdy" nillable="true">
        <xs:annotation>
          <xs:documentation>Pozycje przejazdów.</xs:documentation>
        </xs:annotation>
      </xs:element>
      <xs:element name="DietyRyczalty" type="TDietyRyczalty" nillable="true">
        <xs:annotation>
          <xs:documentation>Pozycje diet i ryczałtów.</xs:documentation>
        </xs:annotation>
      </xs:element>
    </xs:sequence>
  </xs:complexType>

  <xs:element name="Dokument" type="TDelegacja">
    <xs:annotation>
      <xs:documentation>Główny węzeł opakowujący delegację.</xs:documentation>
    </xs:annotation>
  </xs:element>
</xs:schema>