<?xml version="1.0" encoding="utf-8"?>
<xs:schema id="DokumentKorektaKosztow_2018"
    xmlns:xs="http://www.w3.org/2001/XMLSchema"
    elementFormDefault="qualified"
    xmlns="http://schemas.insert.com.pl/2018/dokumentyDoKsiegowania/logistyka"
    targetNamespace="http://schemas.insert.com.pl/2018/dokumentyDoKsiegowania/logistyka"
    xmlns:ddk="http://schemas.insert.com.pl/2012/dokumentyDoKsiegowania">
  <xs:annotation>
    <xs:documentation>DokumentKorektaKosztow_2018</xs:documentation>
  </xs:annotation>

  <xs:import id="TypyDanychPart" namespace="http://schemas.insert.com.pl/2012/dokumentyDoKsiegowania" schemaLocation="./TypyDanych_2012.xsd" />
  <xs:import id="PolaWlasnePart" namespace="http://schemas.insert.com.pl/2012/dokumentyDoKsiegowania" schemaLocation="./Dane_2012_PolaWlasnePart.xsd" />

  <xs:complexType name="TNaglowekDokumentuKorektaKosztow" >
    <xs:annotation>
      <xs:documentation>Dane korekty kosztów magazynowych.</xs:documentation>
    </xs:annotation>
    <xs:sequence>
      <xs:element name="KolekcjePolWlasnych" type="ddk:TKolekcjePolWlasnych" minOccurs="0" maxOccurs="1">
        <xs:annotation>
          <xs:documentation>Zbiór pól własnych korekty kosztów magazynowych.</xs:documentation>
        </xs:annotation>
      </xs:element>
    </xs:sequence>
    <xs:attribute name="Konfiguracja" type="ddk:TGuid" use="required">
      <xs:annotation>
        <xs:documentation>Identyfikator konfiguracji dokumentu korekty kosztów magazynowych (stała).</xs:documentation>
      </xs:annotation>
    </xs:attribute>
    <xs:attribute name="Magazyn" type="xs:string" use="optional">
      <xs:annotation>
        <xs:documentation>Identyfikator magazynu dokumentu.</xs:documentation>
      </xs:annotation>
    </xs:attribute>
    <xs:attribute name="Numer" type="xs:string" use="required">
      <xs:annotation>
        <xs:documentation>Numer dokumentu.</xs:documentation>
      </xs:annotation>
    </xs:attribute>
    <xs:attribute name="DataWystawienia" type="xs:date" use="required">
      <xs:annotation>
        <xs:documentation>Data wystawienia dokumentu.</xs:documentation>
      </xs:annotation>
    </xs:attribute>
    <xs:attribute name="DataPoczatkowaOkresu" type="xs:date" use="required">
      <xs:annotation>
        <xs:documentation>Data początkowa okresu.</xs:documentation>
      </xs:annotation>
    </xs:attribute>
    <xs:attribute name="DataKoncowaOkresu" type="xs:date" use="required">
      <xs:annotation>
        <xs:documentation>Data końcowa okresu.</xs:documentation>
      </xs:annotation>
    </xs:attribute>
    
      <xs:attribute name="KorektaKosztuDokumentowSprzedazy" type="xs:decimal" use="optional">
        <xs:annotation>
          <xs:documentation>Korekta kosztu dokumentów sprzedaży.</xs:documentation>
        </xs:annotation>
      </xs:attribute>
      <xs:attribute name="KorektaKosztuDokumentowZakupu" type="xs:decimal" use="optional">
        <xs:annotation>
          <xs:documentation>Korekta kosztu dokumentów zakupu.</xs:documentation>
        </xs:annotation>
      </xs:attribute>


    <xs:attribute name="KorektaKosztuWydanZewnetrznych" type="xs:decimal" use="required">
      <xs:annotation>
        <xs:documentation>Korekta kosztu wydań zewnętrznych.</xs:documentation>
      </xs:annotation>
    </xs:attribute>
    <xs:attribute name="KorektaKosztuPrzyjecZewnetrznych" type="xs:decimal" use="required">
      <xs:annotation>
        <xs:documentation>Korekta kosztu przyjęć zewnętrznych.</xs:documentation>
      </xs:annotation>
    </xs:attribute>
    <xs:attribute name="KorektaKosztowRozchodowWewnetrznych" type="xs:decimal" use="required">
      <xs:annotation>
        <xs:documentation>Korekta kosztów rozchodów wewnętrznych.</xs:documentation>
      </xs:annotation>
    </xs:attribute>
    <xs:attribute name="KorektaKosztowPrzychodowWewnetrznych" type="xs:decimal" use="required">
      <xs:annotation>
        <xs:documentation>Korekta kosztów przychodów wewnętrznych.</xs:documentation>
      </xs:annotation>
    </xs:attribute>
    <xs:attribute name="KorektaKosztowWydanMiedzymagazynowych" type="xs:decimal" use="required">
      <xs:annotation>
        <xs:documentation>Korekta kosztów wydań międzymagazynowych.</xs:documentation>
      </xs:annotation>
    </xs:attribute>
    <xs:attribute name="KorektaKosztowPrzyjecMiedzymagazynowych" type="xs:decimal" use="required">
      <xs:annotation>
        <xs:documentation>Korekta kosztów przyjęć międzymagazynowych.</xs:documentation>
      </xs:annotation>
    </xs:attribute>
    <xs:attribute name="Oddzial" type="xs:string" use="optional">
      <xs:annotation>
        <xs:documentation>Identyfikator oddziału dokumentu.</xs:documentation>
      </xs:annotation>
    </xs:attribute>
    <xs:attribute name="KategoriaDokumentu" type="xs:string" use="optional">
      <xs:annotation>
        <xs:documentation>Identyfikator kategorii dokumentu handlowego.</xs:documentation>
      </xs:annotation>
    </xs:attribute>
    <xs:attribute name="Tytul" type="xs:string" use="optional">
      <xs:annotation>
        <xs:documentation>Tytuł dokumentu handlowego.</xs:documentation>
      </xs:annotation>
    </xs:attribute>
    <xs:attribute name="Podtytul" type="xs:string" use="optional">
      <xs:annotation>
        <xs:documentation>Podtytuł dokumentu handlowego.</xs:documentation>
      </xs:annotation>
    </xs:attribute>
    <xs:attribute name="Uwagi" type="xs:string" use="required">
      <xs:annotation>
        <xs:documentation>Uwagi z dokumentu.</xs:documentation>
      </xs:annotation>
    </xs:attribute>
  </xs:complexType>

  <xs:complexType name="TPozycjaDokumentuKorektaKosztow">
    <xs:annotation>
      <xs:documentation>Pozycja dokumentu korekty kosztów magazynowych.</xs:documentation>
    </xs:annotation>
    <xs:attribute name="Index" type="xs:int" use="required">
      <xs:annotation>
        <xs:documentation>Indeks pozycji dokumentu na potrzeby opisu księgowego.</xs:documentation>
      </xs:annotation>
    </xs:attribute>
    <xs:attribute name="DataWystawienia" type="xs:date" use="required">
      <xs:annotation>
        <xs:documentation>Data wystawienia dokumentu.</xs:documentation>
      </xs:annotation>
    </xs:attribute>
    <xs:attribute name="LP" type="xs:int" use="required">
      <xs:annotation>
        <xs:documentation>Liczba porządkowa pozycji dokumentu.</xs:documentation>
      </xs:annotation>
    </xs:attribute>
    <xs:attribute name="Numer" type="xs:string" use="required">
      <xs:annotation>
        <xs:documentation>Numer dokumentu.</xs:documentation>
      </xs:annotation>
    </xs:attribute>
    <xs:attribute name="PrzedKorekta" type="xs:decimal" use="required">
      <xs:annotation>
        <xs:documentation>Wartość pozycji przed korektą.</xs:documentation>
      </xs:annotation>
    </xs:attribute>
    <xs:attribute name="Korekta" type="xs:decimal" use="required">
      <xs:annotation>
        <xs:documentation>Wartość pozycji korekta.</xs:documentation>
      </xs:annotation>
    </xs:attribute>
    <xs:attribute name="PoKorekcie" type="xs:decimal" use="required">
      <xs:annotation>
        <xs:documentation>Wartość pozycji po korekcie.</xs:documentation>
      </xs:annotation>
    </xs:attribute>

    <xs:attribute name="PrzedKorektaD" type="xs:decimal" use="required">
      <xs:annotation>
        <xs:documentation>Wartość pozycji przed korektą (D).</xs:documentation>
      </xs:annotation>
    </xs:attribute>
    <xs:attribute name="KorektaD" type="xs:decimal" use="required">
      <xs:annotation>
        <xs:documentation>Wartość pozycji korekta (D).</xs:documentation>
      </xs:annotation>
    </xs:attribute>
    <xs:attribute name="PoKorekcieD" type="xs:decimal" use="required">
      <xs:annotation>
        <xs:documentation>Wartość pozycji po korekcie (D).</xs:documentation>
      </xs:annotation>
    </xs:attribute>

    <xs:attribute name="TypDokumentu" type="xs:string" use="required">
      <xs:annotation>
        <xs:documentation>Typ dokumentu.</xs:documentation>
      </xs:annotation>
    </xs:attribute>

    <xs:attribute name="ZyskPrzedKorekta" type="xs:decimal" use="required">
      <xs:annotation>
        <xs:documentation>Zysk przed korektą.</xs:documentation>
      </xs:annotation>
    </xs:attribute>
    <xs:attribute name="KorektaZysku" type="xs:decimal" use="required">
      <xs:annotation>
        <xs:documentation>Korekta zysku.</xs:documentation>
      </xs:annotation>
    </xs:attribute>
    <xs:attribute name="ZyskPoKorekcie" type="xs:decimal" use="required">
      <xs:annotation>
        <xs:documentation>Zysk po korekcie.</xs:documentation>
      </xs:annotation>
    </xs:attribute>

    <xs:attribute name="NarzutPrzedKorekta" type="xs:decimal" use="required">
      <xs:annotation>
        <xs:documentation>Narzut przed korektą.</xs:documentation>
      </xs:annotation>
    </xs:attribute>
    <xs:attribute name="KorektaNarzutu" type="xs:decimal" use="required">
      <xs:annotation>
        <xs:documentation>Korekta narzutu.</xs:documentation>
      </xs:annotation>
    </xs:attribute>
    <xs:attribute name="NarzutPoKorekcie" type="xs:decimal" use="required">
      <xs:annotation>
        <xs:documentation>Narzut po korekcie.</xs:documentation>
      </xs:annotation>
    </xs:attribute>

    <xs:attribute name="MarzaPrzedKorekta" type="xs:decimal" use="required">
      <xs:annotation>
        <xs:documentation>Marża przed korektą.</xs:documentation>
      </xs:annotation>
    </xs:attribute>
    <xs:attribute name="KorektaMarzy" type="xs:decimal" use="required">
      <xs:annotation>
        <xs:documentation>Korekta marży.</xs:documentation>
      </xs:annotation>
    </xs:attribute>
    <xs:attribute name="MarzaPoKorekcie" type="xs:decimal" use="required">
      <xs:annotation>
        <xs:documentation>Marża po korekcie.</xs:documentation>
      </xs:annotation>
    </xs:attribute>
  </xs:complexType>

  <xs:complexType name="TPozycjaKosztuDokumentuKorektaKosztow">
    <xs:annotation>
      <xs:documentation>Pozycja kosztu dokumentu korekty kosztów magazynowych.</xs:documentation>
    </xs:annotation>
    <xs:attribute name="Dokument" type="xs:string" use="required">
      <xs:annotation>
        <xs:documentation>Numer dokumentu na pozycji kosztu dokumentu.</xs:documentation>
      </xs:annotation>
    </xs:attribute>
    <xs:attribute name="Opis" type="xs:string" use="required">
      <xs:annotation>
        <xs:documentation>Opis pozycji kosztu dokumentu.</xs:documentation>
      </xs:annotation>
    </xs:attribute>
    <xs:attribute name="Koszt" type="xs:decimal" use="required">
      <xs:annotation>
        <xs:documentation>Wartość kosztu na pozycji kosztu dokumentu.</xs:documentation>
      </xs:annotation>
    </xs:attribute>
  </xs:complexType>

  <xs:complexType name="TDokumentKorektaKosztow">
    <xs:annotation>
      <xs:documentation>Dokument korekty kosztów magazynowych wraz z wersją schematu.</xs:documentation>
    </xs:annotation>
    <xs:sequence>
      <xs:element name="Wersja" type="xs:string" nillable="false" fixed="2018">
        <xs:annotation>
          <xs:documentation>Wersja  schematu.</xs:documentation>
        </xs:annotation>
      </xs:element>
      <xs:element name="Naglowek" type="TNaglowekDokumentuKorektaKosztow" nillable="false">
        <xs:annotation>
          <xs:documentation>Nagłówek dokumentu.</xs:documentation>
        </xs:annotation>
      </xs:element>
      <xs:element name="Koszty" minOccurs="0" maxOccurs="1">
        <xs:annotation>
          <xs:documentation>Pozycje kosztów dokumentu.</xs:documentation>
        </xs:annotation>
        <xs:complexType>
          <xs:sequence>
            <xs:element name="Koszt" type="TPozycjaKosztuDokumentuKorektaKosztow" minOccurs="0" maxOccurs="unbounded">
              <xs:annotation>
                <xs:documentation>Pozycja kosztu dokumentu.</xs:documentation>
              </xs:annotation>
            </xs:element>
          </xs:sequence>
        </xs:complexType>
      </xs:element>
      <xs:element name="Pozycje" minOccurs="0" maxOccurs="1">
        <xs:annotation>
          <xs:documentation>Pozycje dokumentu.</xs:documentation>
        </xs:annotation>
        <xs:complexType>
          <xs:sequence>
            <xs:element name="Pozycja" type="TPozycjaDokumentuKorektaKosztow" minOccurs="0" maxOccurs="unbounded">
              <xs:annotation>
                <xs:documentation>Pozycja dokumentu.</xs:documentation>
              </xs:annotation>
            </xs:element>
          </xs:sequence>
        </xs:complexType>
      </xs:element>
    </xs:sequence>
  </xs:complexType>
  <xs:element name="Dokument" type="TDokumentKorektaKosztow">
    <xs:annotation>
      <xs:documentation>Główny węzeł opakowujący dokument korekty kosztów magazynowych.</xs:documentation>
    </xs:annotation>
  </xs:element>
</xs:schema>