<?xml version="1.0" encoding="utf-8"?>
<!-- Uzyj xsd.exe do wygenerowania z tego kodu -->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" 
           elementFormDefault="qualified" 
           xmlns="http://schemas.insert.com.pl/2025/dokumentyDoKsiegowania/logistyka" 
           targetNamespace="http://schemas.insert.com.pl/2025/dokumentyDoKsiegowania/logistyka" 
           xmlns:ddk="http://schemas.insert.com.pl/2012/dokumentyDoKsiegowania">
  <xs:annotation>
    <xs:documentation>Dane dokumentu magazynowego.</xs:documentation>
  </xs:annotation>
  
  <xs:import id="TypyDanychPart" namespace="http://schemas.insert.com.pl/2012/dokumentyDoKsiegowania" schemaLocation="./TypyDanych_2012.xsd" />
  <xs:import id="PolaWlasnePart" namespace="http://schemas.insert.com.pl/2012/dokumentyDoKsiegowania" schemaLocation="./Dane_2012_PolaWlasnePart.xsd" />
  
  <xs:complexType name="TNaglowekDokumentuMagazynowego">
    <xs:annotation>
      <xs:documentation>Zbiór pól nagłówkowych dokumentu magazynowego.</xs:documentation>
    </xs:annotation>
    <xs:sequence>
      <!--<xs:element name="SkutekMagazynowy" type="xs:unsignedByte" minOccurs="0" maxOccurs="1" nillable="true" />-->
      <xs:element name="KolekcjePolWlasnych" type="ddk:TKolekcjePolWlasnych" minOccurs="0" maxOccurs="1">
        <xs:annotation>
          <xs:documentation>Zbiór pól własnych dokumentu magazynowego.</xs:documentation>
        </xs:annotation>
      </xs:element>
      <xs:element name="KursWalutyDokumentu" type="TKursWalutyDokumentuMagazynowego" minOccurs="0" maxOccurs="1">
        <xs:annotation>
          <xs:documentation>Kurs waluty dokumentu magazynowego.</xs:documentation>
        </xs:annotation>
      </xs:element>
      <xs:element name="KursWalutyVAT" type="TKursWalutyDokumentuMagazynowego" minOccurs="0" maxOccurs="1">
        <xs:annotation>
          <xs:documentation>Kurs waluty tabeli VAT dokumentu magazynowego.</xs:documentation>
        </xs:annotation>
      </xs:element>
      <xs:element name="TransakcjaHandlowa" type="ddk:TGuid" minOccurs="0" maxOccurs="1">
        <xs:annotation>
          <xs:documentation>Identyfikator transakcji handlowej dokumentu magazynowego.</xs:documentation>
        </xs:annotation>
      </xs:element>
      
    </xs:sequence>
    <xs:attribute name="Konfiguracja" type="ddk:TGuid" use="required">
      <xs:annotation>
        <xs:documentation>Identyfikator konfiguracji dokumentu magazynowego.</xs:documentation>
      </xs:annotation>
    </xs:attribute>
    <xs:attribute name="Numer" type="xs:string" use="required">
      <xs:annotation>
        <xs:documentation>Numer dokumentu magazynowego.</xs:documentation>
      </xs:annotation>
    </xs:attribute>
    <xs:attribute name="DataWprowadzenia" type="xs:date" use="required">
      <xs:annotation>
        <xs:documentation>Data wprowadzenia dokumentu magazynowego.</xs:documentation>
      </xs:annotation>
    </xs:attribute>
    <!--<xs:attribute name="DataSprzedazy" type="xs:date" use="required"/>-->
    <xs:attribute name="DataDostawy" type="xs:date" use="required">
      <xs:annotation>
        <xs:documentation>Data dostawy dokumentu magazynowego.</xs:documentation>
      </xs:annotation>
    </xs:attribute>
    <xs:attribute name="KwotaDoZaplaty" type="xs:decimal" use="required">
      <xs:annotation>
        <xs:documentation>Kwota do zapłaty dokumentu magazynowego.</xs:documentation>
      </xs:annotation>
    </xs:attribute>
    <xs:attribute name="Zysk" type="xs:decimal" use="required">
      <xs:annotation>
        <xs:documentation>Zysk dokumentu magazynowego.</xs:documentation>
      </xs:annotation>
    </xs:attribute>
    <xs:attribute name="KosztMagazynowy" type="xs:decimal" use="required">
      <xs:annotation>
        <xs:documentation>Całkowity koszt magazynowy dokumentu magazynowego.</xs:documentation>
      </xs:annotation>
    </xs:attribute>
    <xs:attribute name="KosztGratisow" type="xs:decimal" use="required">
      <xs:annotation>
        <xs:documentation>Całkowity koszt gratisów dokumentu magazynowego.</xs:documentation>
      </xs:annotation>
    </xs:attribute>
    <xs:attribute name="KosztEwidencyjny" type="xs:decimal" use="required">
      <xs:annotation>
        <xs:documentation>Całkowity koszt ewidencyjny dokumentu magazynowego.</xs:documentation>
      </xs:annotation>
    </xs:attribute>
    <xs:attribute name="WartoscOpakowanWydanych" type="xs:decimal" use="required">
      <xs:annotation>
        <xs:documentation>Suma wartości opakowań wydanych na dokumencie magazynowym.</xs:documentation>
      </xs:annotation>
    </xs:attribute>
    <xs:attribute name="WartoscOpakowanPrzyjetych" type="xs:decimal" use="required">
      <xs:annotation>
        <xs:documentation>Suma wartości opakowań przyjętych na dokumencie magazynowym.</xs:documentation>
      </xs:annotation>
    </xs:attribute>
    <xs:attribute name="WartoscNPONettoPoRabacie" type="xs:decimal" use="required">
      <xs:annotation>
        <xs:documentation>Suma wartości netto na pozycjach ze stawką NPO na dokumencie magazynowym.</xs:documentation>
      </xs:annotation>
    </xs:attribute>
    <xs:attribute name="Waluta" type="xs:string" use="required">
      <xs:annotation>
        <xs:documentation>Waluta dokumentu magazynowego.</xs:documentation>
      </xs:annotation>
    </xs:attribute>
    <xs:attribute name="WartoscNettoPoRabacie" type="xs:decimal" use="required">
      <xs:annotation>
        <xs:documentation>Wartość netto po rabacie dokumentu magazynowego.</xs:documentation>
      </xs:annotation>
    </xs:attribute>
    <xs:attribute name="WartoscBruttoPoRabacie" type="xs:decimal" use="required">
      <xs:annotation>
        <xs:documentation>Wartość brutto po rabacie dokumentu magazynowego.</xs:documentation>
      </xs:annotation>
    </xs:attribute>
    <xs:attribute name="WartoscVATPoRabacie" type="xs:decimal" use="required">
      <xs:annotation>
        <xs:documentation>Wartość VAT po rabacie dokumentu magazynowego.</xs:documentation>
      </xs:annotation>
    </xs:attribute>
    <xs:attribute name="MiejsceSprzedazy" type="ddk:TPositiveInt" use="optional">
      <xs:annotation>
        <xs:documentation>Miejsce sprzedaży dokumentu magazynowego.</xs:documentation>
      </xs:annotation>
    </xs:attribute>
    <xs:attribute name="Magazyn" type="ddk:TPositiveInt" use="optional">
      <xs:annotation>
        <xs:documentation>Identyfikator magazynu dokumentu magazynowego.</xs:documentation>
      </xs:annotation>
    </xs:attribute>
    <xs:attribute name="OdbiorcaDokumentu" type="ddk:TPositiveInt" use="optional">
      <xs:annotation>
        <xs:documentation>Identyfikator odbiorcy dokumentu magazynowego (identyfikator wpisu historycznego).</xs:documentation>
      </xs:annotation>
    </xs:attribute>
    <xs:attribute name="Nabywca" type="ddk:TPositiveInt" use="optional">
      <xs:annotation>
        <xs:documentation>Identyfikator nabywcy dokumentu magazynowego (identyfikator wpisu historycznego).</xs:documentation>
      </xs:annotation>
    </xs:attribute>
    <xs:attribute name="NabywcaAdres" type="ddk:TPositiveInt" use="optional">
      <xs:annotation>
        <xs:documentation>Identyfikator adresu nabywcy dokumentu magazynowego.</xs:documentation>
      </xs:annotation>
    </xs:attribute>
    <xs:attribute name="SumaPrzedplat" type="xs:decimal" use="optional">
      <xs:annotation>
        <xs:documentation>Suma wartości przedpłat dokumentu magazynowego.</xs:documentation>
      </xs:annotation>
    </xs:attribute>
    <xs:attribute name="SumaPrzedplatWWalucieDokumentu" type="xs:decimal" use="optional">
      <xs:annotation>
        <xs:documentation>Suma wartości przedpłat w walucie dokumentu magazynowego.</xs:documentation>
      </xs:annotation>
    </xs:attribute>
    <xs:attribute name="SumaZaplacono" type="xs:decimal" use="optional">
      <xs:annotation>
        <xs:documentation>Zapłacono (suma).</xs:documentation>
      </xs:annotation>
    </xs:attribute>
    <xs:attribute name="SumaZaplaconoWWalucieDokumentu" type="xs:decimal" use="optional">
      <xs:annotation>
        <xs:documentation>Zapłacono (suma) w walucie dokumentu.</xs:documentation>
      </xs:annotation>
    </xs:attribute>
    <xs:attribute name="SumaPozostalo" type="xs:decimal" use="optional">
      <xs:annotation>
        <xs:documentation>Pozostało do zapłaty (suma).</xs:documentation>
      </xs:annotation>
    </xs:attribute>
    <xs:attribute name="Sprzedawca" type="ddk:TPositiveInt" use="optional">
      <xs:annotation>
        <xs:documentation>Identyfikator sprzedawcy dokumentu magazynowego (identyfikator wpisu historycznego).</xs:documentation>
      </xs:annotation>
    </xs:attribute>
    <xs:attribute name="SprzedawcaAdres" type="ddk:TPositiveInt" use="optional">
      <xs:annotation>
        <xs:documentation>Identyfikator adresu sprzedawcy dokumentu magazynowego.</xs:documentation>
      </xs:annotation>
    </xs:attribute>
    <xs:attribute name="Dostawca" type="ddk:TPositiveInt" use="optional">
      <xs:annotation>
        <xs:documentation>Identyfikator dostawcy dokumentu magazynowego (identyfikator wpisu historycznego).</xs:documentation>
      </xs:annotation>
    </xs:attribute>
    <xs:attribute name="NumerZewnetrzny" type="xs:string" use="optional">
      <xs:annotation>
        <xs:documentation>Numer zewnętrzny dokumentu magazynowego.</xs:documentation>
      </xs:annotation>
    </xs:attribute>
    <xs:attribute name="DataWydaniaWystawienia" type="xs:date" use="optional">
      <xs:annotation>
        <xs:documentation>Data wydania lub wystawienia dokumentu magazynowego.</xs:documentation>
      </xs:annotation>
    </xs:attribute>
    <xs:attribute name="KategoriaDokumentu" type="xs:string" use="optional">
      <xs:annotation>
        <xs:documentation>Kategoria dokumentu magazynowego.</xs:documentation>
      </xs:annotation>
    </xs:attribute>
    <xs:attribute name="KategoriaDokumentuEncja" type="xs:string" use="optional">
      <xs:annotation>
        <xs:documentation>Identyfikator kategorii dokumentu handlowego.</xs:documentation>
      </xs:annotation>
    </xs:attribute>
    <xs:attribute name="NumerKorygowanego" type="xs:string" use="optional">
      <xs:annotation>
        <xs:documentation>Numer dokumentu korygowanego na korektach dokumentów magazynowych.</xs:documentation>
      </xs:annotation>
    </xs:attribute>
    <xs:attribute name="SprzedawcaNabywca" type="ddk:TPositiveInt" use="optional">
      <xs:annotation>
        <xs:documentation>Identyfikator sprzedawcy lub nabywcy dokumentu magazynowego (identyfikator wpisu historycznego).</xs:documentation>
      </xs:annotation>
    </xs:attribute>
    <xs:attribute name="SprzedawcaNabywcaAdres" type="ddk:TPositiveInt" use="optional">
      <xs:annotation>
        <xs:documentation>Identyfikator adresu sprzedawcy lub nabywcy dokumentu magazynowego.</xs:documentation>
      </xs:annotation>
    </xs:attribute>
    <xs:attribute name="MagazynWydaniaMM" type="ddk:TPositiveInt" use="optional">
      <xs:annotation>
        <xs:documentation>Identyfikator magazynu wydania na przesunięciu międzymagazynowym.</xs:documentation>
      </xs:annotation>
    </xs:attribute>
    <xs:attribute name="MagazynPrzyjeciaMM" type="ddk:TPositiveInt" use="optional">
      <xs:annotation>
        <xs:documentation>Identyfikator magazynu przyjęcia na przesunięciu międzymagazynowym.</xs:documentation>
      </xs:annotation>
    </xs:attribute>
    <xs:attribute name="OddzialPrzyjeciaMM" type="ddk:TPositiveInt" use="optional">
      <xs:annotation>
        <xs:documentation>Identyfikator oddziału przyjęcia na przesunięciu międzymagazynowym.</xs:documentation>
      </xs:annotation>
    </xs:attribute>
    <xs:attribute name="OddzialWydaniaMM" type="ddk:TPositiveInt" use="optional">
      <xs:annotation>
        <xs:documentation>Identyfikator oddziału wydania na przesunięciu międzymagazynowym.</xs:documentation>
      </xs:annotation>
    </xs:attribute>
    <xs:attribute name="NumerWydaniaMM" type="xs:string" use="optional">
      <xs:annotation>
        <xs:documentation>Numer wydania dokumentu przesunięcia międzymagazynowego.</xs:documentation>
      </xs:annotation>
    </xs:attribute>
    <xs:attribute name="NumerPrzyjeciaMM" type="xs:string" use="optional">
      <xs:annotation>
        <xs:documentation>Numer przyjęcia dokumentu przesunięcia międzymagazynowego.</xs:documentation>
      </xs:annotation>
    </xs:attribute>
    <xs:attribute name="DataWydaniaMM" type="xs:date" use="optional">
      <xs:annotation>
        <xs:documentation>Data wydania dokumentu przesunięcia międzymagazynowego.</xs:documentation>
      </xs:annotation>
    </xs:attribute>
    <xs:attribute name="DataPrzyjeciaMM" type="xs:date" use="optional">
      <xs:annotation>
        <xs:documentation>Data przyjęcia dokumentu przesunięcia międzymagazynowego.</xs:documentation>
      </xs:annotation>
    </xs:attribute>
    <xs:attribute name="MiejsceWydaniaMM" type="xs:string" use="optional">
      <xs:annotation>
        <xs:documentation>Miejsce wydania dokumentu przesunięcia międzymagazynowego.</xs:documentation>
      </xs:annotation>
    </xs:attribute>
    <xs:attribute name="MiejscePrzyjeciaMM" type="xs:string" use="optional">
      <xs:annotation>
        <xs:documentation>Miejsce przyjęcia dokumentu przesunięcia międzymagazynowego.</xs:documentation>
      </xs:annotation>
    </xs:attribute>
    <xs:attribute name="CzyAutomatyczny" type="xs:boolean" use="required">
      <xs:annotation>
        <xs:documentation>Czy dokument powstał automatycznie z dokumentu handlowego.</xs:documentation>
      </xs:annotation>
    </xs:attribute>
    <xs:attribute name="Tytul" type="xs:string" use="optional">
      <xs:annotation>
        <xs:documentation>Tytuł dokumentu.</xs:documentation>
      </xs:annotation>
    </xs:attribute>
    <xs:attribute name="Podtytul" type="xs:string" use="optional">
      <xs:annotation>
        <xs:documentation>Podtytuł dokumentu</xs:documentation>
      </xs:annotation>
    </xs:attribute>
    <xs:attribute name="StatusDokumentu" type="ddk:TPositiveInt" use="optional">
      <xs:annotation>
        <xs:documentation>Status dokumentu.</xs:documentation>
      </xs:annotation>
    </xs:attribute>
    <xs:attribute name="CzyWZFiskalna" type="xs:boolean" use="required">
      <xs:annotation>
        <xs:documentation>Czy dokument WZ pochodzi ze sprzedaży fiskalnej.</xs:documentation>
      </xs:annotation>
    </xs:attribute>
    <xs:attribute name="SposobWyliczaniaVAT" type="ddk:TGuid" use="optional">
      <xs:annotation>
        <xs:documentation>
          Sposób wylicznia VAT:
          * 1A2B199C-38D5-4E2D-94AC-9D9F63D2CD12 - od netto
          * 7995085B-2B24-4020-8607-6085D018B509 - od brutto
        </xs:documentation>
      </xs:annotation>
    </xs:attribute>
    <xs:attribute name="RWDoDokumentu" type="xs:string" use="optional">
      <xs:annotation>
        <xs:documentation>Numer dokumentu z którym powiazany rozchód wewnętrzny.</xs:documentation>
      </xs:annotation>
    </xs:attribute>
    <xs:attribute name="TytulemZRozrachunku" type="xs:string" use="optional">
      <xs:annotation>
        <xs:documentation>Tytułem z rozrachunku.</xs:documentation>
      </xs:annotation>
    </xs:attribute>
    <xs:attribute name="Uwagi" type="xs:string" use="required">
      <xs:annotation>
        <xs:documentation>Uwagi z dokumentu.</xs:documentation>
      </xs:annotation>
    </xs:attribute>
    <xs:attribute name="Platnik" type="ddk:TPositiveInt" use="optional">
      <xs:annotation>
        <xs:documentation>Identyfikator płatnika dokumentu handlowego (identyfikator wpisu historycznego).</xs:documentation>
      </xs:annotation>
    </xs:attribute>
    <xs:attribute name="NumerOryginaluKorygowanego" type="xs:string" use="optional">
      <xs:annotation>
        <xs:documentation>Numer oryginału dokumentu korygowanego.</xs:documentation>
      </xs:annotation>
    </xs:attribute>
    <xs:attribute name="DokumentHandlowy" type="xs:string" use="optional">
      <xs:annotation>
        <xs:documentation>Numery powiązanych dokumentów handlowych.</xs:documentation>
      </xs:annotation>
    </xs:attribute>
    <xs:attribute name="SumaOplatDodatkowych" type="xs:decimal" use="optional">
      <xs:annotation>
        <xs:documentation>Suma opłat dodatkowych.</xs:documentation>
      </xs:annotation>
    </xs:attribute>
    <xs:attribute name="VATPodlegaOdliczeniu" type="xs:boolean" use="optional">
      <xs:annotation>
        <xs:documentation>Określa czy VAT na dokumencie przyjęcia podlega odliczeniu.</xs:documentation>
      </xs:annotation>
    </xs:attribute>
	<xs:attribute name="ButelkiKaucjonowaneKwotaPobranychKaucji" type="xs:decimal" use="optional">
		<xs:annotation>
			<xs:documentation>Butelki kaucjonowane - kwota pobranej kaucji.</xs:documentation>
		</xs:annotation>
	</xs:attribute>
	<xs:attribute name="ButelkiKaucjonowaneLiczbaPobranychKaucji" type="xs:int" use="optional">
		<xs:annotation>
			<xs:documentation>Butelki kaucjonowane - liczba pobranych kaucji.</xs:documentation>
		</xs:annotation>
	</xs:attribute>
	<xs:attribute name="PETKaucjonowaneKwotaPobranychKaucji" type="xs:decimal" use="optional">
		<xs:annotation>
			<xs:documentation>PET kaucjonowane - kwota pobranej kaucji.</xs:documentation>
		</xs:annotation>
	</xs:attribute>
	<xs:attribute name="PETKaucjonowaneLiczbaPobranychKaucji" type="xs:int" use="optional">
		<xs:annotation>
			<xs:documentation>PET kaucjonowane - liczba pobranych kaucji.</xs:documentation>
		</xs:annotation>
	</xs:attribute>
	<xs:attribute name="PuszkiKaucjonowaneKwotaPobranychKaucji" type="xs:decimal" use="optional">
		<xs:annotation>
			<xs:documentation>Puszki kaucjonowane - kwota pobranej kaucji.</xs:documentation>
		</xs:annotation>
	</xs:attribute>
	<xs:attribute name="PuszkiKaucjonowaneLiczbaPobranychKaucji" type="xs:int" use="optional">
		<xs:annotation>
			<xs:documentation>Puszki kaucjonowane - liczba pobranych kaucji.</xs:documentation>
		</xs:annotation>
	</xs:attribute>
	<xs:attribute name="ButelkiKaucjonowaneKwotaZwroconychKaucji" type="xs:decimal" use="optional">
		<xs:annotation>
			<xs:documentation>Butelki kaucjonowane - kwota zwróconej kaucji.</xs:documentation>
		</xs:annotation>
	</xs:attribute>
	<xs:attribute name="ButelkiKaucjonowaneLiczbaZwroconychKaucji" type="xs:int" use="optional">
		<xs:annotation>
			<xs:documentation>Butelki kaucjonowane - liczba zwróconych kaucji.</xs:documentation>
		</xs:annotation>
	</xs:attribute>
	<xs:attribute name="PETKaucjonowaneKwotaZwroconychKaucji" type="xs:decimal" use="optional">
		<xs:annotation>
			<xs:documentation>PET kaucjonowane - kwota zwróconej kaucji.</xs:documentation>
		</xs:annotation>
	</xs:attribute>
	<xs:attribute name="PETKaucjonowaneLiczbaZwroconychKaucji" type="xs:int" use="optional">
		<xs:annotation>
			<xs:documentation>PET kaucjonowane - liczba zwróconych kaucji.</xs:documentation>
		</xs:annotation>
	</xs:attribute>
	<xs:attribute name="PuszkiKaucjonowaneKwotaZwroconychKaucji" type="xs:decimal" use="optional">
		<xs:annotation>
			<xs:documentation>Puszki kaucjonowane - kwota zwróconej kaucji.</xs:documentation>
		</xs:annotation>
	</xs:attribute>
	<xs:attribute name="PuszkiKaucjonowaneLiczbaZwroconychKaucji" type="xs:int" use="optional">
		<xs:annotation>
			<xs:documentation>Puszki kaucjonowane - liczba zwróconych kaucji.</xs:documentation>
		</xs:annotation>
	</xs:attribute>
  </xs:complexType>
  
  <xs:complexType name="TAsortymentPozycjiDokumentuMagazynowego">
    <xs:annotation>
      <xs:documentation>Dane towaru wstawionego na pozycję dokumentu magazynowego.</xs:documentation>
    </xs:annotation>
    <xs:sequence>
      <xs:element name="Cechy" minOccurs="0" maxOccurs="1">
        <xs:annotation>
          <xs:documentation>Cechy asortymentu.</xs:documentation>
        </xs:annotation>
        <xs:complexType>
          <xs:sequence>
            <xs:element name="Cecha" type="ddk:TPositiveInt" minOccurs="0" maxOccurs="unbounded">
              <xs:annotation>
                <xs:documentation>Identyfikatory cech asortymentu.</xs:documentation>
              </xs:annotation>
            </xs:element>
          </xs:sequence>
        </xs:complexType>
      </xs:element>
    </xs:sequence>
    <xs:attribute name="Symbol" type="xs:string" use="required">
      <xs:annotation>
        <xs:documentation>Symbol towaru.</xs:documentation>
      </xs:annotation>
    </xs:attribute>
    <xs:attribute name="Nazwa" type="xs:string" use="required">
      <xs:annotation>
        <xs:documentation>Nazwa towaru.</xs:documentation>
      </xs:annotation>
    </xs:attribute>    
    <xs:attribute name="Typ" type="xs:int" use="required">
      <xs:annotation>
        <xs:documentation>Typ towaru.</xs:documentation>
      </xs:annotation>
    </xs:attribute>
    <xs:attribute name="Rodzaj" type="xs:int" use="required">
      <xs:annotation>
        <xs:documentation>Rodzaj towaru (1 - usługa, 2 - towar, 3 - opakowanie, 4 - komplet).</xs:documentation>
      </xs:annotation>
    </xs:attribute>
    <xs:attribute name="Grupa" type="ddk:TPositiveInt" use="optional">
      <xs:annotation>
        <xs:documentation>Grupa towaru.</xs:documentation>
      </xs:annotation>
    </xs:attribute>
  </xs:complexType>
  
  <xs:complexType name="TWartoscPozycjiDokumentuMagazynowego">
    <xs:annotation>
      <xs:documentation>Aspekt wartości pozycji dokumentu magazynowego.</xs:documentation>
    </xs:annotation>
    <xs:attribute name="NettoPoRabacie" type="xs:decimal" use="required">
      <xs:annotation>
        <xs:documentation>Wartość netto po rabacie pozycji dokumentu magazynowego.</xs:documentation>
      </xs:annotation>
    </xs:attribute>
    <xs:attribute name="BruttoPoRabacie" type="xs:decimal" use="required">
      <xs:annotation>
        <xs:documentation>Wartość brutto po rabacie pozycji dokumentu magazynowego.</xs:documentation>
      </xs:annotation>
    </xs:attribute>
    <xs:attribute name="VATPoRabacie" type="xs:decimal" use="required">
      <xs:annotation>
        <xs:documentation>Wartość VAT po rabacie pozycji dokumentu magazynowego.</xs:documentation>
      </xs:annotation>
    </xs:attribute>
    <xs:attribute name="NettoPrzedRabatem" type="xs:decimal" use="required">
      <xs:annotation>
        <xs:documentation>Wartość netto przed rabatem pozycji dokumentu magazynowego.</xs:documentation>
      </xs:annotation>
    </xs:attribute>
    <xs:attribute name="BruttoPrzedRabatem" type="xs:decimal" use="required">
      <xs:annotation>
        <xs:documentation>Wartość brutto przed rabatem pozycji dokumentu magazynowego.</xs:documentation>
      </xs:annotation>
    </xs:attribute>
    <xs:attribute name="VATPrzedRabatem" type="xs:decimal" use="required">
      <xs:annotation>
        <xs:documentation>Wartość VAT przed rabatem pozycji dokumentu magazynowego.</xs:documentation>
      </xs:annotation>
    </xs:attribute>
  </xs:complexType>
  
  <xs:complexType name="TPlatnoscNatychmiastowaDokumentuMagazynowego">
    <xs:annotation>
      <xs:documentation>Pozycja płatności na dokumencie magazynowym.</xs:documentation>
    </xs:annotation>
    <xs:attribute name="FormaPlatnosci" type="ddk:TPositiveInt" use="required">
      <xs:annotation>
        <xs:documentation>Identyfikator formy płatności.</xs:documentation>
      </xs:annotation>
    </xs:attribute>
    <xs:attribute name="Kwota" type="xs:decimal" use="required">
      <xs:annotation>
        <xs:documentation>Kwota płatności dokumentu magazynowego.</xs:documentation>
      </xs:annotation>
    </xs:attribute>
    <xs:attribute name="Waluta" type="xs:string" use="required">
      <xs:annotation>
        <xs:documentation>Waluta płatności dokumentu magazynowego.</xs:documentation>
      </xs:annotation>
    </xs:attribute>
  </xs:complexType>
  <!--
  <xs:complexType name="TPlatnoscOdroczonaDokumentuMagazynowego">
    <xs:attribute name="FormaPlatnosci" type="ddk:TPositiveInt" use="optional" />
    <xs:attribute name="Kwota" type="xs:decimal" use="required" />
    <xs:attribute name="Waluta" type="xs:string" use="required" />
    <xs:attribute name="TerminDni" type="xs:int" use="required" />
    <xs:attribute name="Termin" type="xs:dateTime" use="required" />    
  </xs:complexType>
  -->
  <xs:complexType name="TPrzedplataDokumentuMagazynowego">
    <xs:annotation>
      <xs:documentation>Pozycja przedpłaty na dokumencie magazynowym.</xs:documentation>
    </xs:annotation>
    <xs:sequence>
      <xs:element name="Kurs" type="TKursWalutyDokumentuMagazynowego" minOccurs="0" maxOccurs="1">
        <xs:annotation>
          <xs:documentation>Kurs przedpłaty dokumentu magazynowego.</xs:documentation>
        </xs:annotation>
      </xs:element>
    </xs:sequence>
    <xs:attribute name="TypDokumentu" type="xs:unsignedByte" use="required">
      <xs:annotation>
        <xs:documentation>Typ dokumentu przedpłaty dokumentu magazynowego.</xs:documentation>
      </xs:annotation>
    </xs:attribute>
    <xs:attribute name="Data" type="xs:date" use="optional">
      <xs:annotation>
        <xs:documentation>Data dokumentu przedpłaty dokumentu magazynowego.</xs:documentation>
      </xs:annotation>
    </xs:attribute>
    <xs:attribute name="Numer" type="xs:string" use="optional">
      <xs:annotation>
        <xs:documentation>Numer dokumentu przedpłaty dokumentu magazynowego.</xs:documentation>
      </xs:annotation>
    </xs:attribute>
    <xs:attribute name="FormaPlatnosci" type="ddk:TPositiveInt" use="optional">
      <xs:annotation>
        <xs:documentation>Identyfikator formy płatnosci przedpłaty dokumentu magazynowego.</xs:documentation>
      </xs:annotation>
    </xs:attribute>
    <xs:attribute name="Kwota" type="xs:decimal" use="required">
      <xs:annotation>
        <xs:documentation>Kwota przedpłaty dokumentu magazynowego.</xs:documentation>
      </xs:annotation>
    </xs:attribute>
    <xs:attribute name="Waluta" type="xs:string" use="required">
      <xs:annotation>
        <xs:documentation>Waluta przedpłaty dokumentu magazynowego.</xs:documentation>
      </xs:annotation>
    </xs:attribute>
  </xs:complexType>
  
  <xs:complexType name="TPozycjaDokumentuMagazynowego">
    <xs:annotation>
      <xs:documentation>Pozycja dokumentu magazynowego.</xs:documentation>
    </xs:annotation>
    <xs:sequence>
      <xs:element name="Typ" type="xs:int" nillable="true">
        <xs:annotation>
          <xs:documentation>Typ towaru pozycji dokumentu magazynowego.</xs:documentation>
        </xs:annotation>
      </xs:element>
      <xs:element name="Asortyment" type="TAsortymentPozycjiDokumentuMagazynowego" minOccurs="1" maxOccurs="1">
        <xs:annotation>
          <xs:documentation>Asortyment pozycji dokumentu magazynowego.</xs:documentation>
        </xs:annotation>
      </xs:element>
      <xs:element name="Wartosc" type="TWartoscPozycjiDokumentuMagazynowego" minOccurs="1" maxOccurs="1">
        <xs:annotation>
          <xs:documentation>Aspekt wartości pozycji dokumentu magazynowego.</xs:documentation>
        </xs:annotation>
      </xs:element>
    </xs:sequence>
    <xs:attribute name="Index" type="xs:int" use="required">
      <xs:annotation>
        <xs:documentation>Indeks pozycji dokumentu magazynowego na potrzeby opisu księgowego.</xs:documentation>
      </xs:annotation>
    </xs:attribute>
    <xs:attribute name="LP" type="xs:int" use="required">
      <xs:annotation>
        <xs:documentation>Liczba porządkowa pozycji dokumentu magazynowego.</xs:documentation>
      </xs:annotation>
    </xs:attribute>
    <xs:attribute name="StawkaVAT" type="xs:string" use="required">
      <xs:annotation>
        <xs:documentation>Identyfikator stawki VAT pozycji dokumentu magazynowego.</xs:documentation>
      </xs:annotation>
    </xs:attribute>
    <xs:attribute name="Magazyn" type="ddk:TPositiveInt" use="optional">
      <xs:annotation>
        <xs:documentation>Identyfikator magazynu pozycji dokumentu magazynowego.</xs:documentation>
      </xs:annotation>
    </xs:attribute>
    <xs:attribute name="KosztMagazynowy" type="xs:decimal" use="required">
      <xs:annotation>
        <xs:documentation>Koszt magazynowy pozycji dokumentu magazynowego.</xs:documentation>
      </xs:annotation>
    </xs:attribute>
    <xs:attribute name="KosztEwidencyjny" type="xs:decimal" use="required">
      <xs:annotation>
        <xs:documentation>Koszt ewidencyjny pozycji dokumentu magazynowego.</xs:documentation>
      </xs:annotation>
    </xs:attribute>
    <xs:attribute name="WartoscNabycia" type="xs:decimal" use="optional">
      <xs:annotation>
        <xs:documentation>Nieużywane.</xs:documentation>
      </xs:annotation>
    </xs:attribute>
    <xs:attribute name="Pozostalo" type="xs:decimal" use="optional">
      <xs:annotation>
        <xs:documentation>Nieużywane.</xs:documentation>
      </xs:annotation>
    </xs:attribute>
    <xs:attribute name="WalutaKosztow" type="xs:string" use="optional">
      <xs:annotation>
        <xs:documentation>Waluta kosztow pozycji dokumentu magazynowego.</xs:documentation>
      </xs:annotation>
    </xs:attribute>
    <xs:attribute name="PrzyczynaRozbieznosci" type="xs:int" use="optional">
      <xs:annotation>
        <xs:documentation>Przyczyna rozbieżnośći w przychodach/rozchodach wewnętrznych.</xs:documentation>
      </xs:annotation>
    </xs:attribute>
    <xs:attribute name="Opis" type="xs:string" use="optional">
      <xs:annotation>
        <xs:documentation>Opis pozycji.</xs:documentation>
      </xs:annotation>
    </xs:attribute>
  </xs:complexType>
  
  <xs:complexType name="TTabelaVatDokumentuMagazynowego">
    <xs:annotation>
      <xs:documentation>Pozycja tabeli VAT dokumentu magazynowego.</xs:documentation>
    </xs:annotation>
    <xs:attribute name="Index" type="xs:int" use="required">
      <xs:annotation>
        <xs:documentation>Liczba porządkowa pozycji VAT dokumentu magazynowego.</xs:documentation>
      </xs:annotation>
    </xs:attribute>
    <xs:attribute name="StawkaVAT" type="xs:string" use="required">
      <xs:annotation>
        <xs:documentation>Identyfikator stawki VAT pozycji VAT dokumentu magazynowego.</xs:documentation>
      </xs:annotation>
    </xs:attribute>
    <xs:attribute name="WartoscNetto" type="xs:decimal" use="required">
      <xs:annotation>
        <xs:documentation>Wartość netto w danej stawce VAT (kwota w walucie systemowej).</xs:documentation>
      </xs:annotation>
    </xs:attribute>
    <xs:attribute name="WartoscBrutto" type="xs:decimal" use="required">
      <xs:annotation>
        <xs:documentation>Wartość brutto w danej stawce VAT (kwota w walucie systemowej).</xs:documentation>
      </xs:annotation>
    </xs:attribute>
    <xs:attribute name="WartoscVAT" type="xs:decimal" use="required">
      <xs:annotation>
        <xs:documentation>Wartość VAT w danej stawce VAT (kwota w walucie systemowej).</xs:documentation>
      </xs:annotation>
    </xs:attribute>
    <xs:attribute name="Waluta" type="xs:string" use="required">
      <xs:annotation>
        <xs:documentation>Waluta pozycji VAT dokumentu magazynowego.</xs:documentation>
      </xs:annotation>
    </xs:attribute>
    <xs:attribute name="WartoscNettoWWalucie" type="xs:decimal" use="optional">
      <xs:annotation>
        <xs:documentation>Wartość netto w danej stawce VAT (kwota w walucie).</xs:documentation>
      </xs:annotation>
    </xs:attribute>
    <xs:attribute name="WartoscBruttoWWalucie" type="xs:decimal" use="optional">
      <xs:annotation>
        <xs:documentation>Wartość brutto w danej stawce VAT (kwota w walucie).</xs:documentation>
      </xs:annotation>
    </xs:attribute>
    <xs:attribute name="WartoscVATWWalucie" type="xs:decimal" use="optional">
      <xs:annotation>
        <xs:documentation>Wartość VAT w danej stawce VAT (kwota w walucie).</xs:documentation>
      </xs:annotation>
    </xs:attribute>
    <xs:attribute name="WartoscNabycia" type="xs:decimal" use="optional">
      <xs:annotation>
        <xs:documentation>Nieużywane.</xs:documentation>
      </xs:annotation>
    </xs:attribute>
    <xs:attribute name="TransakcjaNettoTabeliVAT" type="xs:decimal" use="optional">
      <xs:annotation>
        <xs:documentation>Nieużywane.</xs:documentation>
      </xs:annotation>
    </xs:attribute>
    <xs:attribute name="TransakcjaVatTabeliVAT" type="xs:decimal" use="optional">
      <xs:annotation>
        <xs:documentation>Nieużywane.</xs:documentation>
      </xs:annotation>
    </xs:attribute>
    <xs:attribute name="TransakcjaBruttoTabeliVAT" type="xs:decimal" use="optional">
      <xs:annotation>
        <xs:documentation>Nieużywane.</xs:documentation>
      </xs:annotation>
    </xs:attribute>
    <xs:attribute name="PoprzednieZaliczkiNettoTabeliVAT" type="xs:decimal" use="optional">
      <xs:annotation>
        <xs:documentation>Nieużywane.</xs:documentation>
      </xs:annotation>
    </xs:attribute>
    <xs:attribute name="PoprzednieZaliczkiVatTabeliVAT" type="xs:decimal" use="optional">
      <xs:annotation>
        <xs:documentation>Nieużywane.</xs:documentation>
      </xs:annotation>
    </xs:attribute>
    <xs:attribute name="PoprzednieZaliczkiBruttoTabeliVAT" type="xs:decimal" use="optional">
      <xs:annotation>
        <xs:documentation>Nieużywane.</xs:documentation>
      </xs:annotation>
    </xs:attribute>
  </xs:complexType>
  
  <xs:complexType name="TKursWalutyDokumentuMagazynowego">
    <xs:annotation>
      <xs:documentation>Aspekt kursu waluty.</xs:documentation>
    </xs:annotation>
    <xs:attribute name="Kurs" type="xs:decimal" use="required">
      <xs:annotation>
        <xs:documentation>Wartość kursu waluty.</xs:documentation>
      </xs:annotation>
    </xs:attribute>
    <xs:attribute name="LiczbaJednostek" type="xs:int" use="required">
      <xs:annotation>
        <xs:documentation>Liczba jednostek waluty przeliczanej.</xs:documentation>
      </xs:annotation>
    </xs:attribute>
  </xs:complexType>
  
  <xs:complexType name="TDokumentMagazynowy">
    <xs:annotation>
      <xs:documentation>Dokument magazynowy wraz z wersją schematu.</xs:documentation>
    </xs:annotation>
    <xs:sequence>
      <xs:element name="Wersja" type="xs:string" nillable="false" fixed="2025">
        <xs:annotation>
          <xs:documentation>Wersja schematu.</xs:documentation>
        </xs:annotation>
      </xs:element>
      <xs:element name="Naglowek" type="TNaglowekDokumentuMagazynowego" nillable="false">
        <xs:annotation>
          <xs:documentation>Naglowek dokumentu magazynowego.</xs:documentation>
        </xs:annotation>
      </xs:element>
      <xs:element name="Pozycje" minOccurs="0" maxOccurs="1">
        <xs:annotation>
          <xs:documentation>Pozycje dokumentu magazynowego.</xs:documentation>
        </xs:annotation>
        <xs:complexType>
          <xs:sequence>
            <xs:element name="Pozycja" type="TPozycjaDokumentuMagazynowego" minOccurs="0" maxOccurs="unbounded">
              <xs:annotation>
                <xs:documentation>Pozycja dokumentu magazynowego.</xs:documentation>
              </xs:annotation>
            </xs:element>
          </xs:sequence>
        </xs:complexType>
      </xs:element>
      <xs:element name="TabeleVAT" minOccurs="0" maxOccurs="1">
        <xs:annotation>
          <xs:documentation>Pozycje VAT dokumentu magazynowego.</xs:documentation>
        </xs:annotation>
        <xs:complexType>
          <xs:sequence>
            <xs:element name="TabelaVAT" type="TTabelaVatDokumentuMagazynowego" minOccurs="0" maxOccurs="unbounded">
              <xs:annotation>
                <xs:documentation>Pozycja VAT dokumentu magazynowego.</xs:documentation>
              </xs:annotation>
            </xs:element>
          </xs:sequence>
        </xs:complexType>
      </xs:element>
      <xs:element name="PlatnosciNatychmiastowe" minOccurs="0" maxOccurs="1">
        <xs:annotation>
          <xs:documentation>Pozycje płatności dokumentu magazynowego.</xs:documentation>
        </xs:annotation>
        <xs:complexType>
          <xs:sequence>
            <xs:element name="PlatnoscNatychmiastowa" type="TPlatnoscNatychmiastowaDokumentuMagazynowego" minOccurs="0" maxOccurs="unbounded">
              <xs:annotation>
                <xs:documentation>Pozycja płatności dokumentu magazynowego.</xs:documentation>
              </xs:annotation>
            </xs:element>
          </xs:sequence>
        </xs:complexType>
      </xs:element>
      <xs:element name="Przedplaty" minOccurs="0" maxOccurs="1">
        <xs:annotation>
          <xs:documentation>Pozycje przedpłat dokumentu magazynowego.</xs:documentation>
        </xs:annotation>
        <xs:complexType>
          <xs:sequence>
            <xs:element name="Przedplata" type="TPrzedplataDokumentuMagazynowego" minOccurs="0" maxOccurs="unbounded">
              <xs:annotation>
                <xs:documentation>Pozycja przedpłaty dokumentu magazynowego.</xs:documentation>
              </xs:annotation>
            </xs:element>
          </xs:sequence>
        </xs:complexType>
      </xs:element>
    </xs:sequence>
  </xs:complexType>
  <xs:element name="Dokument" type="TDokumentMagazynowy">
    <xs:annotation>
      <xs:documentation>Główny węzeł opakowujący dokument magazynowy.</xs:documentation>
    </xs:annotation>
  </xs:element>
</xs:schema>