<?xml version="1.0" encoding="utf-8"?>
<!-- Uzyj xsd.exe do wygenerowania z tego kodu -->
<xs:schema 
  xmlns:xs="http://www.w3.org/2001/XMLSchema" 
  elementFormDefault="qualified" 
  xmlns="http://schemas.insert.com.pl/2012/dokumentyDoKsiegowania/logistyka" 
  targetNamespace="http://schemas.insert.com.pl/2012/dokumentyDoKsiegowania/logistyka" 
  xmlns:ddk="http://schemas.insert.com.pl/2012/dokumentyDoKsiegowania">
  <xs:annotation>
    <xs:documentation>DokumentKKD_2012</xs:documentation>
  </xs:annotation>
  
  <xs:import id="TypyDanychPart" namespace="http://schemas.insert.com.pl/2012/dokumentyDoKsiegowania" schemaLocation="./TypyDanych_2012.xsd" />
  <xs:import id="PolaWlasnePart" namespace="http://schemas.insert.com.pl/2012/dokumentyDoKsiegowania" schemaLocation="./Dane_2012_PolaWlasnePart.xsd" />
  
  <xs:complexType name="TNaglowekDokumentuKKD">
    <xs:annotation>
      <xs:documentation>Dane korekty kosztów dostawy.</xs:documentation>
    </xs:annotation>
    <xs:sequence>
      <xs:element name="KolekcjePolWlasnych" type="ddk:TKolekcjePolWlasnych" minOccurs="0" maxOccurs="1">
        <xs:annotation>
          <xs:documentation>Zbiór pól własnych korekty kosztów dostawy.</xs:documentation>
        </xs:annotation>
      </xs:element>
      <xs:element name="KursWalutyDokumentu" type="TKursWalutyDokumentuKKD" minOccurs="0" maxOccurs="1">
        <xs:annotation>
          <xs:documentation>Kurs waluty dokumentu korekty kosztów dostawy.</xs:documentation>
        </xs:annotation>
      </xs:element>
    </xs:sequence>
    <xs:attribute name="Konfiguracja" type="ddk:TGuid" use="required">
      <xs:annotation>
        <xs:documentation>Identyfikator konfiguracji dokumentu korekty kosztów dostawy (stała).</xs:documentation>
      </xs:annotation>
    </xs:attribute>
    <xs:attribute name="Numer" type="xs:string" use="required">
      <xs:annotation>
        <xs:documentation>Numer dokumentu.</xs:documentation>
      </xs:annotation>
    </xs:attribute>
    <xs:attribute name="DataWprowadzenia" type="xs:date" use="required">
      <xs:annotation>
        <xs:documentation>Data wprowadzenia dokumentu.</xs:documentation>
      </xs:annotation>
    </xs:attribute>
    <xs:attribute name="Waluta" type="xs:string" use="required">
      <xs:annotation>
        <xs:documentation>Waluta dokumentu.</xs:documentation>
      </xs:annotation>
    </xs:attribute>
    <xs:attribute name="NumerPowiazanego" type="xs:string" use="required">
      <xs:annotation>
        <xs:documentation>Numer dokumentu powiązanego.</xs:documentation>
      </xs:annotation>
    </xs:attribute>
    <xs:attribute name="MiejsceWprowadzenia" type="xs:string" use="required">
      <xs:annotation>
        <xs:documentation>Miejsce wprowadzenia dokumentu.</xs:documentation>
      </xs:annotation>
    </xs:attribute>
    <xs:attribute name="Magazyn" type="ddk:TPositiveInt" use="optional">
      <xs:annotation>
        <xs:documentation>Identyfikator magazynu dokumentu.</xs:documentation>
      </xs:annotation>
    </xs:attribute>
    <xs:attribute name="Oddzial" type="xs:string" use="optional">
      <xs:annotation>
        <xs:documentation>Identyfikator oddziału dokumentu.</xs:documentation>
      </xs:annotation>
    </xs:attribute>
    <xs:attribute name="Podmiot" type="ddk:TPositiveInt" use="optional">
      <xs:annotation>
        <xs:documentation>Identyfikator podmiotu na dokumencie (identyfikator wpisu historycznego).</xs:documentation>
      </xs:annotation>
    </xs:attribute>
    <xs:attribute name="Adres" type="ddk:TPositiveInt" use="optional">
      <xs:annotation>
        <xs:documentation>Identyfikator adresu podmiotu na dokumencie.</xs:documentation>
      </xs:annotation>
    </xs:attribute>
    <xs:attribute name="SumaWartoscKosztu" type="xs:decimal" use="required">
      <xs:annotation>
        <xs:documentation>Suma wartości kosztów dokumentu.</xs:documentation>
      </xs:annotation>
    </xs:attribute>
    <xs:attribute name="SumaPozostalo" type="xs:decimal" use="required">
      <xs:annotation>
        <xs:documentation>Pozostało (suma).</xs:documentation>
      </xs:annotation>
    </xs:attribute>
  </xs:complexType>
  
  <xs:complexType name="TAsortymentPozycjiDokumentuKKD">
    <xs:annotation>
      <xs:documentation>Dane towaru wstawionego na pozycję dokumentu.</xs:documentation>
    </xs:annotation>
    <xs:attribute name="Symbol" type="xs:string" use="required">
      <xs:annotation>
        <xs:documentation>Symbol towaru.</xs:documentation>
      </xs:annotation>
    </xs:attribute>
    <xs:attribute name="Nazwa" type="xs:string" use="required">
      <xs:annotation>
        <xs:documentation>Nazwa towaru.</xs:documentation>
      </xs:annotation>
    </xs:attribute>
    <xs:attribute name="Typ" type="xs:int" use="required">
      <xs:annotation>
        <xs:documentation>Typ towaru.</xs:documentation>
      </xs:annotation>
    </xs:attribute>
  </xs:complexType>
  
  <xs:complexType name="TPozycjaDokumentuKKD">
    <xs:annotation>
      <xs:documentation>Pozycja dokumentu korekty kosztów dostawy.</xs:documentation>
    </xs:annotation>
    <xs:sequence>
      <xs:element name="Asortyment" type="TAsortymentPozycjiDokumentuKKD" minOccurs="1" maxOccurs="1">
        <xs:annotation>
          <xs:documentation>Asortyment pozycji dokumentu.</xs:documentation>
        </xs:annotation>
      </xs:element>
    </xs:sequence>
    <xs:attribute name="Index" type="xs:int" use="required">
      <xs:annotation>
        <xs:documentation>Indeks pozycji dokumentu na potrzeby opisu księgowego.</xs:documentation>
      </xs:annotation>
    </xs:attribute>
    <xs:attribute name="LP" type="xs:int" use="required">
      <xs:annotation>
        <xs:documentation>Liczba porządkowa pozycji dokumentu.</xs:documentation>
      </xs:annotation>
    </xs:attribute>
    <xs:attribute name="Koszt" type="xs:decimal" use="required">
      <xs:annotation>
        <xs:documentation>Koszt pozycji dokumentu.</xs:documentation>
      </xs:annotation>
    </xs:attribute>
    <xs:attribute name="WartoscNabycia" type="xs:decimal" use="required">
      <xs:annotation>
        <xs:documentation>Wartość nabycia pozycji dokumentu.</xs:documentation>
      </xs:annotation>
    </xs:attribute>
  </xs:complexType>
  
  <xs:complexType name="TPozycjaKosztuDokumentuKKD">
    <xs:annotation>
      <xs:documentation>Pozycja kosztu dokumentu korekty kosztów dostawy.</xs:documentation>
    </xs:annotation>
    <xs:sequence>
      <xs:element name="Asortyment" type="TAsortymentPozycjiDokumentuKKD" minOccurs="1" maxOccurs="1">
        <xs:annotation>
          <xs:documentation>Asortyment pozycji kosztu dokumentu.</xs:documentation>
        </xs:annotation>
      </xs:element>
    </xs:sequence>
    <xs:attribute name="Dokument" type="xs:string" use="required">
      <xs:annotation>
        <xs:documentation>Numer dokumentu na pozycji kosztu dokumentu.</xs:documentation>
      </xs:annotation>
    </xs:attribute>
    <xs:attribute name="Opis" type="xs:string" use="required">
      <xs:annotation>
        <xs:documentation>Opis pozycji kosztu dokumentu.</xs:documentation>
      </xs:annotation>
    </xs:attribute>
    <xs:attribute name="Koszt" type="xs:decimal" use="required">
      <xs:annotation>
        <xs:documentation>Wartość kosztu na pozycji kosztu dokumentu.</xs:documentation>
      </xs:annotation>
    </xs:attribute>
  </xs:complexType>
  
  <xs:complexType name="TKursWalutyDokumentuKKD">
    <xs:annotation>
      <xs:documentation>Aspekt kursu waluty.</xs:documentation>
    </xs:annotation>
    <xs:attribute name="Kurs" type="xs:decimal" use="required">
      <xs:annotation>
        <xs:documentation>Wartość kursu waluty.</xs:documentation>
      </xs:annotation>
    </xs:attribute>
    <xs:attribute name="LiczbaJednostek" type="xs:int" use="required">
      <xs:annotation>
        <xs:documentation>Liczba jednostek waluty przeliczanej.</xs:documentation>
      </xs:annotation>
    </xs:attribute>
  </xs:complexType>
  
  <xs:complexType name="TDokumentKKD">
    <xs:annotation>
      <xs:documentation>Dokument korekty kosztów dostawy wraz z wersją schematu.</xs:documentation>
    </xs:annotation>
    <xs:sequence>
      <xs:element name="Wersja" type="xs:string" nillable="false" fixed="2012">
        <xs:annotation>
          <xs:documentation>Wersja  schematu.</xs:documentation>
        </xs:annotation>
      </xs:element>
      <xs:element name="Naglowek" type="TNaglowekDokumentuKKD" nillable="false">
        <xs:annotation>
          <xs:documentation>Nagłówek dokumentu.</xs:documentation>
        </xs:annotation>
      </xs:element>
      <xs:element name="Koszty" minOccurs="0" maxOccurs="1">
        <xs:annotation>
          <xs:documentation>Pozycje kosztów dokumentu.</xs:documentation>
        </xs:annotation>
        <xs:complexType>
          <xs:sequence>
            <xs:element name="Koszt" type="TPozycjaKosztuDokumentuKKD" minOccurs="0" maxOccurs="unbounded">
              <xs:annotation>
                <xs:documentation>Pozycja kosztu dokumentu.</xs:documentation>
              </xs:annotation>
            </xs:element>
          </xs:sequence>
        </xs:complexType>
      </xs:element>
      <xs:element name="Pozycje" minOccurs="0" maxOccurs="1">
        <xs:annotation>
          <xs:documentation>Pozycje dokumentu.</xs:documentation>
        </xs:annotation>
        <xs:complexType>
          <xs:sequence>
            <xs:element name="Pozycja" type="TPozycjaDokumentuKKD" minOccurs="0" maxOccurs="unbounded">
              <xs:annotation>
                <xs:documentation>Pozycja dokumentu.</xs:documentation>
              </xs:annotation>
            </xs:element>
          </xs:sequence>
        </xs:complexType>
      </xs:element>
    </xs:sequence>
  </xs:complexType>
  <xs:element name="Dokument" type="TDokumentKKD">
    <xs:annotation>
      <xs:documentation>Główny węzeł opakowujący dokument korekty kosztów dostawy.</xs:documentation>
    </xs:annotation>
  </xs:element>
</xs:schema>