<?xml version="1.0" encoding="utf-8"?>
<!-- Uzyj xsd.exe do wygenerowania z tego kodu -->
<xs:schema 
  xmlns:xs="http://www.w3.org/2001/XMLSchema" 
  elementFormDefault="qualified" 
  xmlns="http://schemas.insert.com.pl/2018/dokumentyDoKsiegowania/bank" 
  targetNamespace="http://schemas.insert.com.pl/2018/dokumentyDoKsiegowania/bank" 
  xmlns:ddk="http://schemas.insert.com.pl/2012/dokumentyDoKsiegowania">
  <xs:annotation>
    <xs:documentation>Dane dyspozycji bankowej.</xs:documentation>
  </xs:annotation>

  <xs:import id="TypyDanychPart" namespace="http://schemas.insert.com.pl/2012/dokumentyDoKsiegowania" schemaLocation="./TypyDanych_2012.xsd" />
  <xs:import id="PolaWlasnePart" namespace="http://schemas.insert.com.pl/2012/dokumentyDoKsiegowania" schemaLocation="./Dane_2012_PolaWlasnePart.xsd" />

  <xs:complexType name="TNaglowekDyspozycjiBankowej">
    <xs:annotation>
      <xs:documentation>Zbiór pól nagłówkowych dyspozycji bankowej.</xs:documentation>
    </xs:annotation>
    <xs:sequence>
      <xs:element name="KolekcjePolWlasnych" type="ddk:TKolekcjePolWlasnych" minOccurs="0" maxOccurs="1">
        <xs:annotation>
          <xs:documentation>Zbiór pól własnych dyspozycji bankowej.</xs:documentation>
        </xs:annotation>
      </xs:element>
    </xs:sequence>
    <xs:attribute name="Typ" type="xs:unsignedByte" use="required">
      <xs:annotation>
        <xs:documentation>Typ dyspozycji bankowej (0 - standardowa, 1 - ZUS, 2 - podatkowa).</xs:documentation>
      </xs:annotation>
    </xs:attribute>
    <xs:attribute name="DataZlozenia" type="xs:date" use="required">
      <xs:annotation>
        <xs:documentation>Data złożenia dyspozycji bankowej.</xs:documentation>
      </xs:annotation>
    </xs:attribute>
    <xs:attribute name="DataAutoryzacji" type="xs:date" use="optional">
      <xs:annotation>
        <xs:documentation>Data autoryzacji dyspozycji bankowej.</xs:documentation>
      </xs:annotation>
    </xs:attribute>
    <xs:attribute name="Kwota" type="xs:decimal" use="required">
      <xs:annotation>
        <xs:documentation>Kwota dyspozycji bankowej.</xs:documentation>
      </xs:annotation>
    </xs:attribute>
    <xs:attribute name="Waluta" type="xs:string" use="required">
      <xs:annotation>
        <xs:documentation>Waluta dyspozycji bankowej.</xs:documentation>
      </xs:annotation>
    </xs:attribute>
    <xs:attribute name="Gotowkowa" type="xs:boolean" use="required">
      <xs:annotation>
        <xs:documentation>Czy rodzajem dyspozycji bankowej jest wpłata gotówkowa.</xs:documentation>
      </xs:annotation>
    </xs:attribute>
    <xs:attribute name="PoleceniePrzelewu" type="xs:boolean" use="required">
      <xs:annotation>
        <xs:documentation>Czy rodzajem  dyspozycji bankowej jest polecenie przelewu.</xs:documentation>
      </xs:annotation>
    </xs:attribute>
    <xs:attribute name="Podmiot" type="ddk:TPositiveInt" use="optional">
      <xs:annotation>
        <xs:documentation>Podmiot dyspozycji bankowej.</xs:documentation>
      </xs:annotation>
    </xs:attribute>
    <xs:attribute name="Adres" type="ddk:TPositiveInt" use="optional">
      <xs:annotation>
        <xs:documentation>Adres podmiotu dyspozycji bankowej.</xs:documentation>
      </xs:annotation>
    </xs:attribute>
    <xs:attribute name="RachunekNadawcy" type="ddk:TPositiveInt" use="optional">
      <xs:annotation>
        <xs:documentation>Rachunek nadawcy dyspozycji bankowej.</xs:documentation>
      </xs:annotation>
    </xs:attribute>
    <xs:attribute name="RachunekOdbiorcy" type="ddk:TPositiveInt" use="optional">
      <xs:annotation>
        <xs:documentation>Rachunek podmiotu dyspozycji bankowej.</xs:documentation>
      </xs:annotation>
    </xs:attribute>
    <xs:attribute name="Tytulem" type="xs:string" use="optional">
      <xs:annotation>
        <xs:documentation>
          W zależności od rodzaju dyspozycji bankowej:
          dla standardowej: zawartość pola tytułem,
          dla ZUS: nr deklaracji + deklaracja,
          dla US: Symbol formularza + okres.
        </xs:documentation>
      </xs:annotation>
    </xs:attribute>
    <xs:attribute name="TypPodatku" type="xs:unsignedByte" use="required">
      <xs:annotation>
        <xs:documentation>Typ podatku dyspozycji bankowej dla US (0 - brak, 1 - PIT, 2 - CIT, 3 - VAT).</xs:documentation>
      </xs:annotation>
    </xs:attribute>
    <xs:attribute name="RodzajSkladki" type="xs:unsignedByte" use="required">
      <xs:annotation>
        <xs:documentation>Rodzaj składki dyspozycji bankowej dla ZUS (0 - brak, 1 - ubezpieczenia społeczne, 2 - ubezpieczenie zdrowotne, 3 - FP i FGŚP, 4 - FEP).</xs:documentation>
      </xs:annotation>
    </xs:attribute>
    <xs:attribute name="Status" type="xs:unsignedByte" use="required">
      <xs:annotation>
        <xs:documentation>Status dyspozycji bankowej (0 - zaplanowana, 1 - w realizacji, 2 - autoryzowana, 3 - wykonana, 4 - odrzucona).</xs:documentation>
      </xs:annotation>
    </xs:attribute>
    <xs:attribute name="TypRozrachunku" type="xs:unsignedByte" use="optional">
      <xs:annotation>
        <xs:documentation>Typ rozrachunku powiązanego z dyspozycją bankową (1 - należność, 2 - zobowiązanie).</xs:documentation>
      </xs:annotation>
    </xs:attribute>
    <xs:attribute name="TypDokumentuRozliczanego" type="ddk:TGuid" use="optional">
      <xs:annotation>
        <xs:documentation>Identyfikator typu dokumentu rozliczanego przez dyspozycję bankową.</xs:documentation>
      </xs:annotation>
    </xs:attribute>
    <xs:attribute name="NumerDokumentuRozliczanego" type="xs:string" use="optional">
      <xs:annotation>
        <xs:documentation>Numer dokumentu rozliczanego przez dyspozycję bankową.</xs:documentation>
      </xs:annotation>
    </xs:attribute>
    <xs:attribute name="TytulemZRozrachunku" type="xs:string" use="optional">
      <xs:annotation>
        <xs:documentation>Tytułem z rozrachunku.</xs:documentation>
      </xs:annotation>
    </xs:attribute>
    <xs:attribute name="KwotaVAT" type="xs:decimal" use="optional">
      <xs:annotation>
        <xs:documentation>Kwota VAT.</xs:documentation>
      </xs:annotation>
    </xs:attribute>
    <xs:attribute name="KwotaZRachunkuVAT" type="xs:decimal" use="optional">
      <xs:annotation>
        <xs:documentation>Kwota z rachunku VAT.</xs:documentation>
      </xs:annotation>
    </xs:attribute>
  </xs:complexType>

  <xs:complexType name="TDyspozycjaBankowa">
    <xs:annotation>
      <xs:documentation>Dyspozycja bankowa wraz z wersją schematu.</xs:documentation>
    </xs:annotation>
    <xs:sequence>
      <xs:element name="Wersja" type="xs:string" nillable="false" fixed="2018">
        <xs:annotation>
          <xs:documentation>Wersja schematu.</xs:documentation>
        </xs:annotation>
      </xs:element>
      <xs:element name="Naglowek" type="TNaglowekDyspozycjiBankowej" nillable="false">
        <xs:annotation>
          <xs:documentation>Nagłówek dyspozycji bankowej.</xs:documentation>
        </xs:annotation>
      </xs:element>
    </xs:sequence>
  </xs:complexType>

  <xs:element name="Dokument" type="TDyspozycjaBankowa">
    <xs:annotation>
      <xs:documentation>Główny węzeł opakowujący dyspozycję bankową.</xs:documentation>
    </xs:annotation>
  </xs:element>
</xs:schema>