<?xml version="1.0" encoding="utf-8"?>
<!-- Uzyj xsd.exe do wygenerowania z tego kodu -->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" 
           elementFormDefault="qualified" 
           xmlns="http://schemas.insert.com.pl/2014/dokumentyDoKsiegowania/rozrachunki" 
           targetNamespace="http://schemas.insert.com.pl/2014/dokumentyDoKsiegowania/rozrachunki" 
           xmlns:ddk="http://schemas.insert.com.pl/2012/dokumentyDoKsiegowania">
  <xs:annotation>
    <xs:documentation>Dane korekty KUP niezapłaconego dokumentu.</xs:documentation>
  </xs:annotation>
  
  <xs:import id="TypyDanychPart" namespace="http://schemas.insert.com.pl/2012/dokumentyDoKsiegowania" schemaLocation="./TypyDanych_2012.xsd" />
  <xs:import id="PolaWlasnePart" namespace="http://schemas.insert.com.pl/2012/dokumentyDoKsiegowania" schemaLocation="./Dane_2012_PolaWlasnePart.xsd" />
  
  <xs:complexType name="TNaglowekKorektyKUPNiezaplaconegoDokumentu">
    <xs:annotation>
      <xs:documentation>Zbiór pól nagłówkowych korekty KUP niezapłaconego dokument.</xs:documentation>
    </xs:annotation>
    <xs:sequence>
      <xs:element name="KolekcjePolWlasnych" type="ddk:TKolekcjePolWlasnych" minOccurs="0" maxOccurs="1">
        <xs:annotation>
          <xs:documentation>Zbiór pól własnych korekty KUP niezapłaconego dokument.</xs:documentation>
        </xs:annotation>
      </xs:element>
    </xs:sequence>
    <xs:attribute name="Waluta" type="ddk:TGuid" use="required">
      <xs:annotation>
        <xs:documentation>Waluta korekty.</xs:documentation>
      </xs:annotation>
    </xs:attribute>
    <xs:attribute name="PodmiotHistoria" type="ddk:TPositiveInt" use="optional">
      <xs:annotation>
        <xs:documentation>Identyfikator podmiotu na korekcie.</xs:documentation>
      </xs:annotation>
    </xs:attribute>
    <xs:attribute name="DataUtworzenia" type="xs:date" use="required">
      <xs:annotation>
        <xs:documentation>Data utworzenia korekty.</xs:documentation>
      </xs:annotation>
    </xs:attribute>
    <xs:attribute name="WartoscPierwotnaDokumentu" type="xs:decimal" use="required">
      <xs:annotation>
        <xs:documentation>Wartość pierwotna dokumentu korygowanego.</xs:documentation>
      </xs:annotation>
    </xs:attribute>
    <xs:attribute name="WartoscNierozliczona" type="xs:decimal" use="required">
      <xs:annotation>
        <xs:documentation>Wartość nierozliczona.</xs:documentation>
      </xs:annotation>
    </xs:attribute>
    <xs:attribute name="DokumentZrodlowy" type="xs:string" use="required">
      <xs:annotation>
        <xs:documentation>Dokument źródłowy</xs:documentation>
      </xs:annotation>
    </xs:attribute>
    <xs:attribute name="DataDokumentuZrodlowego" type="xs:date" use="required">
      <xs:annotation>
        <xs:documentation>Data dokumentu źródłowego.</xs:documentation>
      </xs:annotation>
    </xs:attribute>
    <xs:attribute name="IdDokumentuDoKsiegowaniaDokumentuZrodlowego" type="ddk:TGuid" use="optional">
      <xs:annotation>
        <xs:documentation>Id dokumentu do dekretacji dokumentu źródłowego.</xs:documentation>
      </xs:annotation>
    </xs:attribute>
  </xs:complexType>
  
  <xs:complexType name="TKorektaKUPNiezaplaconegoDokumentu">
    <xs:annotation>
      <xs:documentation>Korekta KUP niezapłaconego dokumentu wraz z wersją schematu.</xs:documentation>
    </xs:annotation>
    <xs:sequence>
      <xs:element name="Wersja" type="xs:string" nillable="false" fixed="2014">
        <xs:annotation>
          <xs:documentation>Wersja schematu.</xs:documentation>
        </xs:annotation>
      </xs:element>
      <xs:element name="Naglowek" type="TNaglowekKorektyKUPNiezaplaconegoDokumentu" nillable="false">
        <xs:annotation>
          <xs:documentation>Nagłówek korekty KUP niezapłaconego dokumentu.</xs:documentation>
        </xs:annotation>
      </xs:element>
    </xs:sequence>
  </xs:complexType>
  <xs:element name="Dokument" type="TKorektaKUPNiezaplaconegoDokumentu">
    <xs:annotation>
      <xs:documentation>Główny węzeł opakowujący korektę KUP niezapłaconego dokumentu.</xs:documentation>
    </xs:annotation>
  </xs:element>
</xs:schema>