<?xml version="1.0" encoding="utf-8"?>
<!-- Uzyj xsd.exe do wygenerowania z tego kodu -->
<xs:schema 
  xmlns:xs="http://www.w3.org/2001/XMLSchema"
  elementFormDefault="qualified" 
  xmlns="http://schemas.insert.com.pl/2022/dokumentyDoKsiegowania/place" 
  targetNamespace="http://schemas.insert.com.pl/2022/dokumentyDoKsiegowania/place" 
  xmlns:ddk="http://schemas.insert.com.pl/2012/dokumentyDoKsiegowania" 
  xmlns:bazowe="http://schemas.insert.com.pl/2022/dokumentyDoKsiegowania/place/bazowe">
  <xs:annotation>
    <xs:documentation>Dane listy składek ZUS.</xs:documentation>
  </xs:annotation>
  
  <xs:import id="TypyDanychPart" namespace="http://schemas.insert.com.pl/2012/dokumentyDoKsiegowania" schemaLocation="./TypyDanych_2012.xsd" />
  <xs:import id="PolaWlasnePart" namespace="http://schemas.insert.com.pl/2012/dokumentyDoKsiegowania" schemaLocation="./Dane_2012_PolaWlasnePart.xsd" />
  <xs:import id="PlaceBazowePart" namespace="http://schemas.insert.com.pl/2022/dokumentyDoKsiegowania/place/bazowe" schemaLocation="BazoweTypy_2022.xsd" />
  
  <xs:complexType name="TNaglowekListySkladek">
    <xs:annotation>
      <xs:documentation>Zbiór pól nagłówkowych listy składek ZUS.</xs:documentation>
    </xs:annotation>
    <xs:complexContent>
      <xs:extension base="bazowe:TNaglowekListyPlacBazowy">
        <xs:sequence>
          <xs:element name="DaneSkladekZUS" type="bazowe:TNaglowekListyPlacDaneSkladekZUS" nillable="false">
            <xs:annotation>
              <xs:documentation>Dane dotyczące składek ZUS.</xs:documentation>
            </xs:annotation>
          </xs:element>
        </xs:sequence>
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>
  
  <xs:complexType name="TWyplataSkladki">
    <xs:annotation>
      <xs:documentation>Dane dotyczące składek ZUS w kontekście wypłaty.</xs:documentation>
    </xs:annotation>
    <xs:complexContent>
      <xs:extension base="bazowe:TWyplataBazowa">
        <xs:sequence>
          <xs:element name="DaneSkladekZUS" type="bazowe:TWyplataDaneSkladekZUS" nillable="false">
            <xs:annotation>
              <xs:documentation>Składki ZUS w kontekście wypłaty.</xs:documentation>
            </xs:annotation>
          </xs:element>
          <xs:element name="WartosciSkladnikowPlacowych" type="bazowe:TWartosciSkladnikowPlacowych" nillable="true">
            <xs:annotation>
              <xs:documentation>Dane dotyczące wartosci składników płacowych</xs:documentation>
            </xs:annotation>
          </xs:element>
        </xs:sequence>
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>
  
  <xs:complexType name="TWyplatySkladki">
    <xs:annotation>
      <xs:documentation>Kolekcja składek ZUS.</xs:documentation>
    </xs:annotation>
    <xs:sequence>
      <xs:element minOccurs="0" maxOccurs="unbounded" name="Wyplata" type="TWyplataSkladki">
        <xs:annotation>
          <xs:documentation>Pozycja składek ZUS listy.</xs:documentation>
        </xs:annotation>
      </xs:element>
    </xs:sequence>
  </xs:complexType>
  
  <xs:complexType name="TListaSkladek">
    <xs:annotation>
      <xs:documentation>Lista składek ZUS.</xs:documentation>
    </xs:annotation>
    <xs:complexContent>
      <xs:extension base="bazowe:TListaPlacBazowa">
        <xs:sequence>
          <xs:element name="Naglowek" type="TNaglowekListySkladek" nillable="false">
            <xs:annotation>
              <xs:documentation>Nagłówek listy składek ZUS.</xs:documentation>
            </xs:annotation>
          </xs:element>
          <xs:element name="Skladki" type="TWyplatySkladki" nillable="true">
            <xs:annotation>
              <xs:documentation>Pozycje listy składek ZUS.</xs:documentation>
            </xs:annotation>
          </xs:element>
        </xs:sequence>
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>
  
  <xs:element name="Dokument" type="TListaSkladek">
    <xs:annotation>
      <xs:documentation>Główny węzeł opakowujący listę składek ZUS.</xs:documentation>
    </xs:annotation>
  </xs:element>
</xs:schema>