<?xml version="1.0" encoding="utf-8"?>
<!-- Uzyj xsd.exe do wygenerowania z tego kodu -->
<xs:schema 
  xmlns:xs="http://www.w3.org/2001/XMLSchema" 
  elementFormDefault="qualified"
  xmlns="http://schemas.insert.com.pl/2022/dokumentyDoKsiegowania/place" 
  targetNamespace="http://schemas.insert.com.pl/2022/dokumentyDoKsiegowania/place"
  xmlns:ddk="http://schemas.insert.com.pl/2012/dokumentyDoKsiegowania" 
  xmlns:bazowe="http://schemas.insert.com.pl/2022/dokumentyDoKsiegowania/place/bazowe">
  <xs:annotation>
    <xs:documentation>Dane listy zaliczek.</xs:documentation>
  </xs:annotation>
  
  <xs:import id="TypyDanychPart" namespace="http://schemas.insert.com.pl/2012/dokumentyDoKsiegowania" schemaLocation="./TypyDanych_2012.xsd" />
  <xs:import id="PolaWlasnePart" namespace="http://schemas.insert.com.pl/2012/dokumentyDoKsiegowania" schemaLocation="./Dane_2012_PolaWlasnePart.xsd" />
  <xs:import id="PlaceBazowePart" namespace="http://schemas.insert.com.pl/2022/dokumentyDoKsiegowania/place/bazowe" schemaLocation="BazoweTypy_2022.xsd" />
  
  <xs:complexType name="TNaglowekListyZaliczek">
    <xs:annotation>
      <xs:documentation>Zbiór pól nagłówkowych listy zaliczek</xs:documentation>
    </xs:annotation>
    <xs:complexContent>
      <xs:extension base="bazowe:TNaglowekListyPlacBazowy">
        <xs:sequence>
          <xs:element name="DaneZaliczek" type="bazowe:TNaglowekListyPlacDaneZaliczek" nillable="false">
            <xs:annotation>
              <xs:documentation>Dane dotyczące zaliczek.</xs:documentation>
            </xs:annotation>
          </xs:element>
        </xs:sequence>
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>
  
  <xs:complexType name="TWyplataZaliczki">
    <xs:annotation>
      <xs:documentation>Dane dotyczące zaliczek w kontekście wypłaty.</xs:documentation>
    </xs:annotation>
    <xs:complexContent>
      <xs:extension base="bazowe:TWyplataBazowa">
        <xs:sequence>
          <xs:element name="DaneZaliczek" type="bazowe:TWyplataDaneZaliczek" nillable="false">
            <xs:annotation>
              <xs:documentation>Zaliczki w kontekście wypłaty.</xs:documentation>
            </xs:annotation>
          </xs:element>
        </xs:sequence>
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>
  
  <xs:complexType name="TWyplatyZaliczki">
    <xs:annotation>
      <xs:documentation>Kolekcja pozycji zaliczek.</xs:documentation>
    </xs:annotation>
    <xs:sequence>
      <xs:element minOccurs="0" maxOccurs="unbounded" name="Wyplata" type="TWyplataZaliczki">
        <xs:annotation>
          <xs:documentation>Pozycja zaliczek listy.</xs:documentation>
        </xs:annotation>
      </xs:element>
    </xs:sequence>
  </xs:complexType>
    
  <xs:complexType name="TListaZaliczek">
    <xs:annotation>
      <xs:documentation>Lista zaliczek.</xs:documentation>
    </xs:annotation>
    <xs:complexContent>
      <xs:extension base="bazowe:TListaPlacBazowa">
        <xs:sequence>
          <xs:element name="Naglowek" type="TNaglowekListyZaliczek" nillable="false">
            <xs:annotation>
              <xs:documentation>Nagłówek listy zaliczek.</xs:documentation>
            </xs:annotation>
          </xs:element>
          <xs:element name="Zaliczki" type="TWyplatyZaliczki" nillable="true">
            <xs:annotation>
              <xs:documentation>Pozycje zaliczek listy.</xs:documentation>
            </xs:annotation>
          </xs:element>
        </xs:sequence>
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>
  
  <xs:element name="Dokument" type="TListaZaliczek">
    <xs:annotation>
      <xs:documentation>Główny węzeł opakowujący listę zaliczek.</xs:documentation>
    </xs:annotation>
  </xs:element>
</xs:schema>