<?xml version="1.0" encoding="utf-8"?>
<!-- Uzyj xsd.exe do wygenerowania z tego kodu -->
<xs:schema 
  xmlns:xs="http://www.w3.org/2001/XMLSchema" 
  elementFormDefault="qualified" 
  xmlns="http://schemas.insert.com.pl/2022/dokumentyDoKsiegowania/place" 
  targetNamespace="http://schemas.insert.com.pl/2022/dokumentyDoKsiegowania/place" 
  xmlns:ddk="http://schemas.insert.com.pl/2012/dokumentyDoKsiegowania" 
  xmlns:bazowe="http://schemas.insert.com.pl/2022/dokumentyDoKsiegowania/place/bazowe">
  <xs:annotation>
    <xs:documentation>Dane listy rachunków.</xs:documentation>
  </xs:annotation>
  
  <xs:import id="TypyDanychPart" namespace="http://schemas.insert.com.pl/2012/dokumentyDoKsiegowania" schemaLocation="./TypyDanych_2012.xsd" />
  <xs:import id="PolaWlasnePart" namespace="http://schemas.insert.com.pl/2012/dokumentyDoKsiegowania" schemaLocation="./Dane_2012_PolaWlasnePart.xsd" />
  <xs:import id="PlaceBazowePart" namespace="http://schemas.insert.com.pl/2022/dokumentyDoKsiegowania/place/bazowe" schemaLocation="BazoweTypy_2022.xsd" />
  
  <xs:complexType name="TNaglowekListyRachunkow">
    <xs:annotation>
      <xs:documentation>Zbiór pól nagłówkowych listy rachunków.</xs:documentation>
    </xs:annotation>
    <xs:complexContent>
      <xs:extension base="bazowe:TNaglowekListyRachunkowBazowy">
        <xs:sequence>
          <xs:element name="DaneZaliczek" type="bazowe:TNaglowekListyRachunkowDaneZaliczek" nillable="false" minOccurs="1" maxOccurs="1">
            <xs:annotation>
              <xs:documentation>Dane dotyczące zaliczek.</xs:documentation>
            </xs:annotation>
          </xs:element>
          <xs:element name="DaneSkladekZUS" type="bazowe:TNaglowekListyRachunkowDaneSkladekZUS" nillable="false" minOccurs="1" maxOccurs="1">
            <xs:annotation>
              <xs:documentation>Dane dotyczące składek ZUS.</xs:documentation>
            </xs:annotation>
          </xs:element>
          <xs:element name="DanePPK" type="bazowe:TNaglowekPPK" nillable="false" minOccurs="0" maxOccurs="1">
            <xs:annotation>
              <xs:documentation>Dane dotyczące PPK.</xs:documentation>
            </xs:annotation>
          </xs:element>
        </xs:sequence>
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>
  
  <xs:complexType name="TRachunekDoUmowyPracowniczejZListyRachunkow">
    <xs:annotation>
      <xs:documentation>Dane dotyczące rachunków do umów pracowniczych, zaliczek i składek ZUS pracownika.</xs:documentation>
    </xs:annotation>
    <xs:complexContent>
      <xs:extension base="bazowe:TRachunekDoUmowyPracowniczejZListyRachunkowBazowy">
        <xs:sequence>
          <xs:element name="DaneWynagrodzenia" type="bazowe:TRachunekDoUmowyPracowniczejDaneWynagrodzenia" nillable="false">
            <xs:annotation>
              <xs:documentation>Dane dotyczące wynagrodzenia pracownika.</xs:documentation>
            </xs:annotation>
          </xs:element>
          <xs:element name="DaneZaliczek" type="bazowe:TRachunekDoUmowyPracowniczejDaneZaliczek" nillable="false">
            <xs:annotation>
              <xs:documentation>Dane dotyczące zaliczek.</xs:documentation>
            </xs:annotation>
          </xs:element>
          <xs:element name="DaneSkladekZUS" type="bazowe:TRachunekDoUmowyPracowniczejDaneSkladekZUS" nillable="false">
            <xs:annotation>
              <xs:documentation>Dane dotyczące składek ZUS.</xs:documentation>
            </xs:annotation>
          </xs:element>
          <xs:element name="DanePPK" type="bazowe:TRachunekDoUmowyPracowniczejPPK" nillable="false" minOccurs="0" maxOccurs="1">
            <xs:annotation>
              <xs:documentation>Dane dotyczące PPK.</xs:documentation>
            </xs:annotation>
          </xs:element>
          <xs:element name="WartosciSkladnikowPlacowych" type="bazowe:TWartosciSkladnikowPlacowych" minOccurs="1">
            <xs:annotation>
              <xs:documentation>Dane dotyczące wartosci składników płacowych</xs:documentation>
            </xs:annotation>
          </xs:element>
        </xs:sequence>
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>
  
  <xs:complexType name="TRachunkiDoUmowPracowniczych">
    <xs:annotation>
      <xs:documentation>Kolekcja rachunków do umów pracowniczych, zaliczek i składek ZUS.</xs:documentation>
    </xs:annotation>
    <xs:sequence>
      <xs:element minOccurs="0" maxOccurs="unbounded" name="RachunekDoUmowyPracowniczej" type="TRachunekDoUmowyPracowniczejZListyRachunkow">
        <xs:annotation>
          <xs:documentation>Rachunki do umów pracowniczych, zaliczki i składki ZUS.</xs:documentation>
        </xs:annotation>
      </xs:element>
    </xs:sequence>
  </xs:complexType>
  
  <xs:complexType name="TListaRachunkow">
    <xs:annotation>
      <xs:documentation>Lista rachunków do umów pracowniczych.</xs:documentation>
    </xs:annotation>
    <xs:complexContent>
      <xs:extension base="bazowe:TListaRachunkowBazowa">
        <xs:sequence>
          <xs:element name="Naglowek" type="TNaglowekListyRachunkow" nillable="false">
            <xs:annotation>
              <xs:documentation>Nagłówek listy rachunków.</xs:documentation>
            </xs:annotation>
          </xs:element>
          <xs:element name="RachunkiDoUmowPracowniczych" type="TRachunkiDoUmowPracowniczych" nillable="true">
            <xs:annotation>
              <xs:documentation>Pozycje rachunków do umów pracowniczych, zaliczek i składek ZUS listy rachunków.</xs:documentation>
            </xs:annotation>
          </xs:element>
        </xs:sequence>
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>
  
  <xs:element name="Dokument" type="TListaRachunkow">
    <xs:annotation>
      <xs:documentation>Główny węzeł opakowujący listę rachunków do umów pracowniczych.</xs:documentation>
    </xs:annotation>
  </xs:element>
</xs:schema>