<?xml version="1.0" encoding="utf-8"?>
<!-- Uzyj xsd.exe do wygenerowania z tego kodu -->
<xs:schema 
  xmlns:xs="http://www.w3.org/2001/XMLSchema" 
  elementFormDefault="qualified" 
  xmlns="http://schemas.insert.com.pl/2017/dokumentyDoKsiegowania/dokumentyWewnetrzne" 
  targetNamespace="http://schemas.insert.com.pl/2017/dokumentyDoKsiegowania/dokumentyWewnetrzne"
  xmlns:ddk="http://schemas.insert.com.pl/2012/dokumentyDoKsiegowania">  
  <xs:annotation>
    <xs:documentation>Dane noty księgowej.</xs:documentation>
  </xs:annotation>
  
  <xs:import id="TypyDanychPart" namespace="http://schemas.insert.com.pl/2012/dokumentyDoKsiegowania" schemaLocation="./TypyDanych_2012.xsd" />
  <xs:import id="PolaWlasnePart" namespace="http://schemas.insert.com.pl/2012/dokumentyDoKsiegowania" schemaLocation="./Dane_2012_PolaWlasnePart.xsd" />
  
  <xs:complexType name="TNaglowekNotyKsiegowej">
    <xs:annotation>
      <xs:documentation>Zbiór pól nagłówkowych operacji bankowej.</xs:documentation>
    </xs:annotation>
    <xs:sequence>
      <xs:element name="KolekcjePolWlasnych" type="ddk:TKolekcjePolWlasnych" minOccurs="0" maxOccurs="1">
        <xs:annotation>
          <xs:documentation>Zbiór pól własnych operacji bankowej.</xs:documentation>
        </xs:annotation>
      </xs:element>
      <xs:element name="Data" type="xs:date" nillable="false">
        <xs:annotation>
          <xs:documentation>Data noty księgowej.</xs:documentation>
        </xs:annotation>
      </xs:element>
      <xs:element name="Podmiot" type="xs:string">
        <xs:annotation>
          <xs:documentation>Podmiot noty księgowej.</xs:documentation>
        </xs:annotation>
      </xs:element>
      <xs:element name="PodmiotAdresHistoria" type="xs:string">
        <xs:annotation>
          <xs:documentation>Adres podmiotu noty księgowej.</xs:documentation>
        </xs:annotation>
      </xs:element>
      <xs:element name="Kwota" type="xs:decimal" nillable="false">
        <xs:annotation>
          <xs:documentation>Kwota noty księgowej.</xs:documentation>
        </xs:annotation>
      </xs:element>
      <xs:element name="KwotaWWalucie" type="xs:decimal" nillable="false">
        <xs:annotation>
          <xs:documentation>Kwota w walucie noty księgowej.</xs:documentation>
        </xs:annotation>
      </xs:element>
      <xs:element name="Kurs" type="xs:decimal" nillable="false">
        <xs:annotation>
          <xs:documentation>Kuts noty księgowej.</xs:documentation>
        </xs:annotation>
      </xs:element>
      <xs:element name="LiczbaJednostek" type="xs:int" nillable="false">
        <xs:annotation>
          <xs:documentation>Liczba jednostek noty księgowej.</xs:documentation>
        </xs:annotation>
      </xs:element>
      <xs:element name="Numer" type="xs:string" nillable="false">
        <xs:annotation>
          <xs:documentation>Numer noty księgowej.</xs:documentation>
        </xs:annotation>
      </xs:element>
      <xs:element name="Typ" type="xs:unsignedByte" nillable="false">
        <xs:annotation>
          <xs:documentation>Czy nota księgowa uznaniowa.</xs:documentation>
        </xs:annotation>
      </xs:element>
    </xs:sequence>
    <xs:attribute name="Waluta" type="xs:string" use="required">
      <xs:annotation>
        <xs:documentation>Waluta noty księgowej.</xs:documentation>
      </xs:annotation>
    </xs:attribute>
  </xs:complexType>

  <xs:complexType name="TPozycjaNotyKsiegowej">
    <xs:annotation>
      <xs:documentation>Dane pozycji noty księgowej.</xs:documentation>
    </xs:annotation>
    <xs:sequence>
      <xs:element name="Tresc" type="xs:string" nillable="false">
        <xs:annotation>
          <xs:documentation>Treść pozycji.</xs:documentation>
        </xs:annotation>
      </xs:element>
      <xs:element name="WartoscPLN" type="xs:decimal" nillable="false">
        <xs:annotation>
          <xs:documentation>Wartość pozycji w PLN.</xs:documentation>
        </xs:annotation>
      </xs:element>
      <xs:element name="WartoscWaluta" type="xs:decimal" nillable="false">
        <xs:annotation>
          <xs:documentation>Wartość pozycji w walucie.</xs:documentation>
        </xs:annotation>
      </xs:element>      
    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="TPozycjeNotyKsiegowej">
    <xs:annotation>
      <xs:documentation>Kolekcja pozycji noty księgowej.</xs:documentation>
    </xs:annotation>
    <xs:sequence>
      <xs:element minOccurs="0" maxOccurs="unbounded" name="Pozycja" type="TPozycjaNotyKsiegowej">
        <xs:annotation>
          <xs:documentation>Pozycje noty księgowej.</xs:documentation>
        </xs:annotation>
      </xs:element>
    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="TPlatnoscNatychmiastowaNotyKsiegowej">
    <xs:annotation>
      <xs:documentation>Pozycja płatności na dokumencie handlowym.</xs:documentation>
    </xs:annotation>
    <xs:attribute name="Kurs" type="xs:decimal" use="required">
      <xs:annotation>
        <xs:documentation>Wartość kursu waluty.</xs:documentation>
      </xs:annotation>
    </xs:attribute>
    <xs:attribute name="LiczbaJednostek" type="xs:int" use="required">
      <xs:annotation>
        <xs:documentation>Liczba jednostek waluty przeliczanej.</xs:documentation>
      </xs:annotation>
    </xs:attribute>
    <xs:attribute name="FormaPlatnosci" type="xs:string" use="required">
      <xs:annotation>
        <xs:documentation>Identyfikator formy płatności.</xs:documentation>
      </xs:annotation>
    </xs:attribute>
    <xs:attribute name="Kwota" type="xs:decimal" use="required">
      <xs:annotation>
        <xs:documentation>Kwota płatności dokumentu handlowego.</xs:documentation>
      </xs:annotation>
    </xs:attribute>
    <xs:attribute name="Waluta" type="xs:string" use="required">
      <xs:annotation>
        <xs:documentation>Waluta płatności dokumentu handlowego.</xs:documentation>
      </xs:annotation>
    </xs:attribute>
    <xs:attribute name="PodmiotCesjiWskazany" type="xs:string" use="optional">
      <xs:annotation>
        <xs:documentation>Podmiot cesyjnej formy płatności wymagającej wskazania podmiotu.</xs:documentation>
      </xs:annotation>
    </xs:attribute>
  </xs:complexType>

  <xs:complexType name="TPlatnosciNatychmiastoweNotyKsiegowej">
    <xs:annotation>
      <xs:documentation>Kolekcja płatności noty księgowej.</xs:documentation>
    </xs:annotation>
    <xs:sequence>
      <xs:element minOccurs="0" maxOccurs="unbounded" name="Pozycja" type="TPlatnoscNatychmiastowaNotyKsiegowej">
        <xs:annotation>
          <xs:documentation>Płatności noty księgowej.</xs:documentation>
        </xs:annotation>
      </xs:element>
    </xs:sequence>
  </xs:complexType>
  
  <xs:complexType name="TNotaKsiegowa">
    <xs:annotation>
      <xs:documentation>Nota księgowa wraz z wersją schematu.</xs:documentation>
    </xs:annotation>
    <xs:sequence>
      <xs:element name="Wersja" type="xs:string" nillable="false" fixed="2017">
        <xs:annotation>
          <xs:documentation>Wersja schematu.</xs:documentation>
        </xs:annotation>
      </xs:element>
      <xs:element name="Naglowek" type="TNaglowekNotyKsiegowej" nillable="false">
        <xs:annotation>
          <xs:documentation>Nagłówek noty księgowej.</xs:documentation>
        </xs:annotation>
      </xs:element>
      <xs:element name="Pozycje" type="TPozycjeNotyKsiegowej" nillable="true">
        <xs:annotation>
          <xs:documentation>Pozycje noty księgowej.</xs:documentation>
        </xs:annotation>
      </xs:element>
      <xs:element name="Platnosci" type="TPlatnosciNatychmiastoweNotyKsiegowej" nillable="true">
        <xs:annotation>
          <xs:documentation>Płatności noty księgowej.</xs:documentation>
        </xs:annotation>
      </xs:element>
    </xs:sequence>
  </xs:complexType>
  
  <xs:element name="Dokument" type="TNotaKsiegowa">
    <xs:annotation>
      <xs:documentation>Główny węzeł opakowujący notę księgową.</xs:documentation>
    </xs:annotation>
  </xs:element>
</xs:schema>