<?xml version="1.0" encoding="utf-8" ?>
<xs:schema xmlns:mstns="http://www.insert.com.pl/GTSchemas/RachunekDoUmowy.xsd" xmlns:gttns="http://www.insert.com.pl/GTSchemas/Typy.xsd" xmlns:b="http://schemas.microsoft.com/BizTalk/2003" attributeFormDefault="qualified" elementFormDefault="qualified" targetNamespace="http://www.insert.com.pl/GTSchemas/RachunekDoUmowy.xsd" id="RachunkiDoUmowy" xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:import schemaLocation=".\Typy_GT.xsd" namespace="http://www.insert.com.pl/GTSchemas/Typy.xsd" />
	<xs:annotation>
		<xs:appinfo>
			<b:references>
				<b:reference targetNamespace="http://www.insert.com.pl/GTSchemas/Typy.xsd" />
			</b:references>
		</xs:appinfo>
	</xs:annotation>
	<xs:element name="RachunkiDoUmow">
		<xs:complexType>
			<xs:sequence>
				<xs:element minOccurs="1" maxOccurs="1" name="wersja" type="gttns:Obowiazkowy" />
				<xs:element minOccurs="0" maxOccurs="unbounded" name="RachunekDoUmowy">
					<xs:complexType>
						<xs:sequence>
							<xs:element minOccurs="1" maxOccurs="1" name="NumerRachunku" type="gttns:Obowiazkowy" />
							<xs:element minOccurs="1" maxOccurs="1" name="DataWystawieniaRachunku" type="gttns:Obowiazkowy" />
							<xs:element minOccurs="0" maxOccurs="1" name="DataPrzekazaniaZaliczkiNaPodatek" />
							<xs:element minOccurs="0" maxOccurs="1" name="DataPrzekazaniaSkladekZUS" />
              <xs:element minOccurs="0" maxOccurs="1" name="DataWplatyPPK" />
							<!--wezel 'Kategoria' jest wezlem opcjonalnym, jezeli go nie ma tzn ze lista bez kategorii-->
							<xs:element minOccurs="0" maxOccurs="1" name="Kategoria" type="gttns:Kategoria" />
							<xs:element minOccurs="1" maxOccurs="1" name="Pracownik" type="gttns:Pracownik" />
							<xs:element minOccurs="1" maxOccurs="1" name="Kwoty">
								<xs:complexType>
									<xs:sequence>
										<xs:element minOccurs="0" maxOccurs="unbounded" name="Kwota">
											<xs:complexType>
												<xs:sequence>
													<xs:choice minOccurs="1" maxOccurs="1">
														<xs:element name="RDUKwotaNaUmowie" />
														<xs:element name="RDUDuzeBrutto" />
														<xs:element name="RDUMaleBrutto" />
														<xs:element name="RDUZaliczkaNaPodatek" />
														<xs:element name="RDUNetto" />
														<xs:element name="RDUWyplataDlaPracownika" />
														<xs:element name="RDUKwotaPrzelewuNaRachunek" />
														<xs:element name="RDUKwotaDoWyplatyGotowka" />														
														<xs:element name="RDUDodatkiOpodatkowane" />
														<xs:element name="RDUPotracenia" />														
														<xs:element name="ZUSSkladkiFEI" />
														<xs:element name="ZUSSkladkiFEII" />
														<xs:element name="ZUSSkladkiFRentowy" />
														<xs:element name="ZUSSkladkiFunduszChorobowy" />
														<xs:element name="ZUSRazemSkladkiPracownika" />
														<xs:element name="ZUSSkladkiPracodawcyFEI" />
														<xs:element name="ZUSSkladkiPracodawcyFRentowy" />
														<xs:element name="ZUSSkladkiPracodawcyFWypadkowy" />
														<xs:element name="ZUSRazemSkladkiPracodawcy" />
														<xs:element name="ZUSZasilkiOpodatkowane" />
														<xs:element name="ZUSZasilkiNieopodatkowane" />														
														<xs:element name="ZasilkiZUS" />
														<xs:element name="ZUSPoOdliczeniuZasilkow" />														
														<xs:element name="FunduszPracy" />
														<xs:element name="FunduszGwarantowanychSwiadczenPrac" />
														<xs:element name="RazemSkladkiZus" />
														<xs:element name="SkladkiZdrowOdliczaneOdPodatku" />
														<xs:element name="SkladkiZdrowNieodliczaneOdPodatku" />
														<xs:element name="SkladkiZdrowotneRazem" />
														<xs:element name="ZUSFunduszEmeryturPomostowych" />	
														<xs:element name="ZUSKosztaPracodawcyRazem" />
                            <xs:element name="PPKWplataPodstawowaPracodawcy" />
                            <xs:element name="PPKWplataDodatkowaPracodawcy" />
                            <xs:element name="PPKWplataPodstawowaPracownika" />
                            <xs:element name="PPKWplataDodatkowaPracownika" />
													</xs:choice>
													<xs:element minOccurs="1" maxOccurs="1" name="Wartosc" type="gttns:Obowiazkowy" />
												</xs:sequence>
											</xs:complexType>
										</xs:element>
									</xs:sequence>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
						<xs:attribute form="unqualified" name="Ident" type="xs:string" />
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
</xs:schema>