<?xml version="1.0" encoding="utf-8"?>
<xs:schema 
  xmlns:xs="http://www.w3.org/2001/XMLSchema" 
  elementFormDefault="qualified" 
  xmlns="http://schemas.insert.com.pl/2022/dokumentyDoKsiegowania/place" 
  targetNamespace="http://schemas.insert.com.pl/2022/dokumentyDoKsiegowania/place"
  xmlns:ddk="http://schemas.insert.com.pl/2012/dokumentyDoKsiegowania" 
  xmlns:bazowe="http://schemas.insert.com.pl/2022/dokumentyDoKsiegowania/place/bazowe">
  <xs:annotation>
    <xs:documentation>Dane rachunku do umowy pracowniczej.</xs:documentation>
  </xs:annotation>
  
  <xs:import id="TypyDanychPart" namespace="http://schemas.insert.com.pl/2012/dokumentyDoKsiegowania" schemaLocation="./TypyDanych_2012.xsd" />
  <xs:import id="PolaWlasnePart" namespace="http://schemas.insert.com.pl/2012/dokumentyDoKsiegowania" schemaLocation="./Dane_2012_PolaWlasnePart.xsd" />
  <xs:import id="PlaceBazowePart" namespace="http://schemas.insert.com.pl/2022/dokumentyDoKsiegowania/place/bazowe" schemaLocation="BazoweTypy_2022.xsd" />
  
  <xs:complexType name="TNaglowekRachunkuDoUmowyPracowniczej">
    <xs:annotation>
      <xs:documentation>Zbiór pól nagłówkowych rachunku do umowy pracowniczej.</xs:documentation>
    </xs:annotation>
    <xs:complexContent>
      <xs:extension base="bazowe:TNaglowekRachunkuDoUmowyPracowniczejBazowy">
        <xs:sequence>
          <xs:element name="DaneWynagrodzenia" type="bazowe:TRachunekDoUmowyPracowniczejDaneWynagrodzenia" nillable="false">
            <xs:annotation>
              <xs:documentation>Dane dotyczące wynagrodzenia pracownika.</xs:documentation>
            </xs:annotation>
          </xs:element>
          <xs:element name="DaneZaliczek" type="bazowe:TRachunekDoUmowyPracowniczejDaneZaliczek" nillable="false">
            <xs:annotation>
              <xs:documentation>Dane dotyczące zaliczek.</xs:documentation>
            </xs:annotation>
          </xs:element>
          <xs:element name="DaneSkladekZUS" type="bazowe:TRachunekDoUmowyPracowniczejDaneSkladekZUS" nillable="false">
            <xs:annotation>
              <xs:documentation>Dane dotyczące składek ZUS.</xs:documentation>
            </xs:annotation>
          </xs:element>
          <xs:element name="DanePPK" type="bazowe:TNaglowekPPK" nillable="false" minOccurs="0" maxOccurs="1">
            <xs:annotation>
              <xs:documentation>Dane dotyczące PPK.</xs:documentation>
            </xs:annotation>
          </xs:element>
        </xs:sequence>
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>
  
  <xs:complexType name="TRachunekDoUmowyPracowniczej">
    <xs:annotation>
      <xs:documentation>Rachunek do umowy pracowniczej.</xs:documentation>
    </xs:annotation>
    <xs:complexContent>
      <xs:extension base="bazowe:TRachunekDoUmowyPracowniczejBazowy">
        <xs:sequence>
          <xs:element name="Naglowek" type="TNaglowekRachunkuDoUmowyPracowniczej" nillable="false">
            <xs:annotation>
              <xs:documentation>Nagłówek rachunku do umowy pracowniczej.</xs:documentation>
            </xs:annotation>
          </xs:element>
          <xs:element name="WartosciSkladnikowPlacowych" type="bazowe:TWartosciSkladnikowPlacowych" minOccurs="1">
            <xs:annotation>
              <xs:documentation>Dane dotyczące wartosci składników płacowych</xs:documentation>
            </xs:annotation>
          </xs:element>
        </xs:sequence>
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>
  
  <xs:element name="Dokument" type="TRachunekDoUmowyPracowniczej">
    <xs:annotation>
      <xs:documentation>Główny węzeł opakowujący rachunek do umowy pracowniczej.</xs:documentation>
    </xs:annotation>
  </xs:element>
</xs:schema>