<?xml version="1.0" encoding="utf-8"?>
<!-- Uzyj xsd.exe do wygenerowania z tego kodu -->
<xs:schema
  xmlns:xs="http://www.w3.org/2001/XMLSchema"
  elementFormDefault="qualified"
  xmlns="http://schemas.insert.com.pl/2024/dokumentyDoKsiegowania/rozrachunki"
  targetNamespace="http://schemas.insert.com.pl/2024/dokumentyDoKsiegowania/rozrachunki"
  xmlns:ddk="http://schemas.insert.com.pl/2012/dokumentyDoKsiegowania">
	<xs:annotation>
		<xs:documentation>Dane rozliczenia sprzedaży.</xs:documentation>
	</xs:annotation>

	<xs:import id="TypyDanychPart" namespace="http://schemas.insert.com.pl/2012/dokumentyDoKsiegowania" schemaLocation="./TypyDanych_2012.xsd" />
	<xs:import id="PolaWlasnePart" namespace="http://schemas.insert.com.pl/2012/dokumentyDoKsiegowania" schemaLocation="./Dane_2012_PolaWlasnePart.xsd" />

	<xs:complexType name="TNaglowekRozliczeniaSprzedazy">
		<xs:annotation>
			<xs:documentation>Zbiór pól nagłówkowych rozliczenia sprzedaży.</xs:documentation>
		</xs:annotation>
		<xs:sequence>
			<xs:element name="KolekcjePolWlasnych" type="ddk:TKolekcjePolWlasnych" minOccurs="0" maxOccurs="1">
				<xs:annotation>
					<xs:documentation>Zbiór pól własnych rozliczenia.</xs:documentation>
				</xs:annotation>
			</xs:element>
			<xs:element name="KursWalutyVAT" type="TKursWalutyRozliczeniaSprzedazy" minOccurs="0" maxOccurs="1">
				<xs:annotation>
					<xs:documentation>Kurs waluty VAT rozliczenia.</xs:documentation>
				</xs:annotation>
			</xs:element>
			<xs:element name="KursDlaPIT" type="TKursWalutyRozliczeniaSprzedazy" minOccurs="0" maxOccurs="1">
				<xs:annotation>
					<xs:documentation>Kurs dla PIT.</xs:documentation>
				</xs:annotation>
			</xs:element>
		</xs:sequence>
		<xs:attribute name="Kwota" type="xs:decimal" use="required">
			<xs:annotation>
				<xs:documentation>Kwota rozliczenia.</xs:documentation>
			</xs:annotation>
		</xs:attribute>
		<xs:attribute name="Waluta" type="ddk:TGuid" use="required">
			<xs:annotation>
				<xs:documentation>Waluta rozliczenia.</xs:documentation>
			</xs:annotation>
		</xs:attribute>
		<xs:attribute name="Podmiot" type="ddk:TPositiveInt" use="optional">
			<xs:annotation>
				<xs:documentation>Identyfikator podmiotu na rozliczeniu.</xs:documentation>
			</xs:annotation>
		</xs:attribute>
		<xs:attribute name="Data" type="xs:date" use="required">
			<xs:annotation>
				<xs:documentation>Data rozliczenia.</xs:documentation>
			</xs:annotation>
		</xs:attribute>
		<xs:attribute name="NumerDokumentu" type="xs:string" use="required">
			<xs:annotation>
				<xs:documentation>Numer dokumentu.</xs:documentation>
			</xs:annotation>
		</xs:attribute>
		<xs:attribute name="DataWystawienia" type="xs:date" use="required">
			<xs:annotation>
				<xs:documentation>Data wystawienia.</xs:documentation>
			</xs:annotation>
		</xs:attribute>
		<xs:attribute name="DataDostawy" type="xs:date" use="required">
			<xs:annotation>
				<xs:documentation>Data dostawy.</xs:documentation>
			</xs:annotation>
		</xs:attribute>
		<xs:attribute name="DataSplaty" type="xs:date" use="required">
			<xs:annotation>
				<xs:documentation>Data spłaty.</xs:documentation>
			</xs:annotation>
		</xs:attribute>
		<xs:attribute name="NumerSplaty" type="xs:string" use="required">
			<xs:annotation>
				<xs:documentation>Numer spłaty.</xs:documentation>
			</xs:annotation>
		</xs:attribute>
		<xs:attribute name="KwotaNetto" type="xs:decimal" use="required">
			<xs:annotation>
				<xs:documentation>Kwota Netto.</xs:documentation>
			</xs:annotation>
		</xs:attribute>
		<xs:attribute name="MetodaKasowaVAT" type="xs:boolean" use="required">
			<xs:annotation>
				<xs:documentation>Metoda Kasowa VAT.</xs:documentation>
			</xs:annotation>
		</xs:attribute>
		<xs:attribute name="MetodaKasowaPIT" type="xs:boolean" use="required">
			<xs:annotation>
				<xs:documentation>Metoda Kasowa PIT.</xs:documentation>
			</xs:annotation>
		</xs:attribute>
	</xs:complexType>

	<xs:complexType name="TRozliczenieSprzedazy">
		<xs:annotation>
			<xs:documentation>Rozliczenie sprzedaży wraz z wersją schematu.</xs:documentation>
		</xs:annotation>
		<xs:sequence>
			<xs:element name="Wersja" type="xs:string" nillable="false" fixed="2024">
				<xs:annotation>
					<xs:documentation>Wersja schematu.</xs:documentation>
				</xs:annotation>
			</xs:element>
			<xs:element name="Naglowek" type="TNaglowekRozliczeniaSprzedazy" nillable="false">
				<xs:annotation>
					<xs:documentation>Nagłówek rozliczenia sprzedaży.</xs:documentation>
				</xs:annotation>
			</xs:element>
			<xs:element name="TabeleVAT" minOccurs="0" maxOccurs="1">
				<xs:annotation>
					<xs:documentation>Tabela VAT rozliczenia.</xs:documentation>
				</xs:annotation>
				<xs:complexType>
					<xs:sequence>
						<xs:element name="TabelaVAT" type="TTabelaVATRozliczeniaSprzedazy" minOccurs="0" maxOccurs="unbounded">
							<xs:annotation>
								<xs:documentation>Pozycja tabeli VAT rozliczenia.</xs:documentation>
							</xs:annotation>
						</xs:element>
					</xs:sequence>
				</xs:complexType>
			</xs:element>
		</xs:sequence>
	</xs:complexType>

	<xs:complexType name="TKursWalutyRozliczeniaSprzedazy">
		<xs:annotation>
			<xs:documentation>Aspekt kursu waluty.</xs:documentation>
		</xs:annotation>
		<xs:attribute name="Kurs" type="xs:decimal" use="required">
			<xs:annotation>
				<xs:documentation>Wartość kursu.</xs:documentation>
			</xs:annotation>
		</xs:attribute>
		<xs:attribute name="LiczbaJednostek" type="xs:int" use="required">
			<xs:annotation>
				<xs:documentation>Liczba jednostek waluty przeliczanej.</xs:documentation>
			</xs:annotation>
		</xs:attribute>
	</xs:complexType>

	<xs:complexType name="TTabelaVATRozliczeniaSprzedazy">
		<xs:annotation>
			<xs:documentation>Wiersz tabeli VAT na rozliczeniu.</xs:documentation>
		</xs:annotation>
		<xs:sequence></xs:sequence>
		<xs:attribute name="Index" type="xs:int" use="required">
			<xs:annotation>
				<xs:documentation>Indeks wiersza w rozliczeniu.</xs:documentation>
			</xs:annotation>
		</xs:attribute>
		<xs:attribute name="StawkaVAT" type="ddk:TGuid" use="required">
			<xs:annotation>
				<xs:documentation>Identyfikator stawki VAT.</xs:documentation>
			</xs:annotation>
		</xs:attribute>
		<xs:attribute name="WartoscNetto" type="xs:decimal" use="required">
			<xs:annotation>
				<xs:documentation>Wartość netto w danej stawce VAT.</xs:documentation>
			</xs:annotation>
		</xs:attribute>
		<xs:attribute name="WartoscBrutto" type="xs:decimal" use="required">
			<xs:annotation>
				<xs:documentation>Wartość brutto w danej stawce VAT.</xs:documentation>
			</xs:annotation>
		</xs:attribute>
		<xs:attribute name="WartoscVAT" type="xs:decimal" use="required">
			<xs:annotation>
				<xs:documentation>Wartość VAT w danej stawce VAT.</xs:documentation>
			</xs:annotation>
		</xs:attribute>
		<xs:attribute name="Waluta" type="ddk:TGuid" use="required">
			<xs:annotation>
				<xs:documentation>Waluta.</xs:documentation>
			</xs:annotation>
		</xs:attribute>
	</xs:complexType>

	<xs:element name="Dokument" type="TRozliczenieSprzedazy">
		<xs:annotation>
			<xs:documentation>Główny węzeł opakowujący rozliczenie sprzedaży.</xs:documentation>
		</xs:annotation>
	</xs:element>
</xs:schema>