<?xml version="1.0" encoding="utf-8"?>
<xs:schema 
  xmlns:xs="http://www.w3.org/2001/XMLSchema"
  elementFormDefault="qualified"
  xmlns="http://schemas.insert.com.pl/2022/dokumentyDoKsiegowania/place" 
  targetNamespace="http://schemas.insert.com.pl/2022/dokumentyDoKsiegowania/place"
  xmlns:ddk="http://schemas.insert.com.pl/2012/dokumentyDoKsiegowania"
  xmlns:bazowe="http://schemas.insert.com.pl/2022/dokumentyDoKsiegowania/place/bazowe">
  <xs:annotation>
    <xs:documentation>Dane zaliczek rachunku do umowy pracowniczej.</xs:documentation>
  </xs:annotation>
  
  <xs:import id="TypyDanychPart" namespace="http://schemas.insert.com.pl/2012/dokumentyDoKsiegowania" schemaLocation="./TypyDanych_2012.xsd" />
  <xs:import id="PolaWlasnePart" namespace="http://schemas.insert.com.pl/2012/dokumentyDoKsiegowania" schemaLocation="./Dane_2012_PolaWlasnePart.xsd" />
  <xs:import id="PlaceBazowePart" namespace="http://schemas.insert.com.pl/2022/dokumentyDoKsiegowania/place/bazowe" schemaLocation="BazoweTypy_2022.xsd" />
  
  <xs:complexType name="TNaglowekZaliczekRachunkuDoUmowyPracowniczej">
    <xs:annotation>
      <xs:documentation>Zbiór pól nagłówkowych zaliczek rachunku do umowy pracowniczej.</xs:documentation>
    </xs:annotation>
    <xs:complexContent>
      <xs:extension base="bazowe:TNaglowekRachunkuDoUmowyPracowniczejBazowy">
        <xs:sequence>
          <xs:element name="DaneZaliczek" type="bazowe:TRachunekDoUmowyPracowniczejDaneZaliczek" nillable="false">
            <xs:annotation>
              <xs:documentation>Dane dotyczące zaliczek.</xs:documentation>
            </xs:annotation>
          </xs:element>
        </xs:sequence>
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>
  
  <xs:complexType name="TZaliczkiRachunkuDoUmowyPracowniczej">
    <xs:annotation>
      <xs:documentation>Zaliczki rachunku do umowy pracowniczej.</xs:documentation>
    </xs:annotation>
    <xs:complexContent>
      <xs:extension base="bazowe:TRachunekDoUmowyPracowniczejBazowy">
        <xs:sequence>
          <xs:element name="Naglowek" type="TNaglowekZaliczekRachunkuDoUmowyPracowniczej" nillable="false">
            <xs:annotation>
              <xs:documentation>Nagłówek zaliczek rachunku do umowy pracowniczej.</xs:documentation>
            </xs:annotation>
          </xs:element>
        </xs:sequence>
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>
  
  <xs:element name="Dokument" type="TZaliczkiRachunkuDoUmowyPracowniczej">
    <xs:annotation>
      <xs:documentation>Główny węzeł opakowujący zaliczki rachunku do umowy pracowniczej.</xs:documentation>
    </xs:annotation>
  </xs:element>
</xs:schema>