<?xml version="1.0" encoding="utf-8"?>
<!-- Uzyj xsd.exe do wygenerowania z tego kodu -->
<xs:schema 
  xmlns:xs="http://www.w3.org/2001/XMLSchema" 
  elementFormDefault="qualified"
  xmlns="http://schemas.insert.com.pl/2012/dokumentyDoKsiegowania" 
  targetNamespace="http://schemas.insert.com.pl/2012/dokumentyDoKsiegowania" 
  id="DaneKBR">
  <xs:annotation>
    <xs:documentation>Dane przesyłanej, zaszyfrowanej paczki.</xs:documentation>
  </xs:annotation>
  
  <xs:complexType name="TZaszyfrowanaPaczka">
    <xs:annotation>
      <xs:documentation>Zaszyfrowana paczka.</xs:documentation>
    </xs:annotation>
    <xs:sequence>
      <xs:element name="Wersja" type="xs:string" fixed="2012_Encrypted">
        <xs:annotation>
          <xs:documentation>Wersja schematu.</xs:documentation>
        </xs:annotation>
      </xs:element>
      <xs:element name="Salt" type="xs:string">
        <xs:annotation>
          <xs:documentation>Sól szyfrowania.</xs:documentation>
        </xs:annotation>
      </xs:element>
      <xs:element name="IV" type="xs:string">
        <xs:annotation>
          <xs:documentation>Wektor inicjujący szyfrowania.</xs:documentation>
        </xs:annotation>
      </xs:element>
      <xs:element name="Dane" type="xs:string">
        <xs:annotation>
          <xs:documentation>Zaszyfrowane dane paczki.</xs:documentation>
        </xs:annotation>
      </xs:element>
    </xs:sequence>
  </xs:complexType>
  <!-- Dokumenty do księgowania obiekt xml -->
  <xs:element name="Dane" type="TZaszyfrowanaPaczka">
    <xs:annotation>
      <xs:documentation>Główny węzeł paczki.</xs:documentation>
    </xs:annotation>
  </xs:element>
</xs:schema>