<?xml version="1.0" encoding="utf-8"?>
<xs:schema attributeFormDefault="unqualified"
           elementFormDefault="qualified"
           targetNamespace="http://schemas.insert.com.pl/2013/hop/ceny"
           xmlns="http://schemas.insert.com.pl/2013/hop/ceny"
           xmlns:xs="http://www.w3.org/2001/XMLSchema">
  
  <xs:annotation>
    <xs:documentation>Ceny asortymentu.</xs:documentation>
  </xs:annotation>

  <xs:complexType name="TPozycjaCennika">
    <xs:annotation>
      <xs:documentation>Dane pojedynczej pozycji cennika.</xs:documentation>
    </xs:annotation>
    <xs:sequence>
      <xs:element name="Asortyment" type="xs:string" >
        <xs:annotation>
          <xs:documentation>Symbol asortymentu.</xs:documentation>
        </xs:annotation>
      </xs:element>
      <xs:element name="Waluta" type="xs:string" >
        <xs:annotation>
          <xs:documentation>Symbol waluty ceny bazowej.</xs:documentation>
        </xs:annotation>
      </xs:element>
      <xs:element minOccurs="0" name="Kalkulacyjna" type="xs:decimal">
        <xs:annotation>
          <xs:documentation>Cena kalkulacyjna w walucie cennika.</xs:documentation>
        </xs:annotation>
      </xs:element>
      <xs:element name="Bazowa" type="xs:decimal">
        <xs:annotation>
          <xs:documentation>Cena bazowa w walucie cennika.</xs:documentation>
        </xs:annotation>
      </xs:element>
      <xs:element name="Ilosc" type="xs:decimal">
        <xs:annotation>
          <xs:documentation>Ilość asortymentu, dla której obowiązuje cena.</xs:documentation>
        </xs:annotation>
      </xs:element>
      <xs:element name="Jm" type="xs:string">
        <xs:annotation>
          <xs:documentation>Jednostka miary, dla której obowiązuje cena.</xs:documentation>
        </xs:annotation>
      </xs:element>
      <xs:element name="Netto" type="xs:decimal">
        <xs:annotation>
          <xs:documentation>Cena netto w walucie cennika.</xs:documentation>
        </xs:annotation>
      </xs:element>
      <xs:element name="Brutto" type="xs:decimal">
        <xs:annotation>
          <xs:documentation>Cena brutto w walucie cennika.</xs:documentation>
        </xs:annotation>
      </xs:element>
      <xs:element name="Marza" type="xs:decimal">
        <xs:annotation>
          <xs:documentation>Marża. Wartość z przedziału [0,1).</xs:documentation>
        </xs:annotation>
      </xs:element>
      <xs:element name="Narzut" type="xs:decimal">
        <xs:annotation>
          <xs:documentation>Narzut (w postaci dziesiętnej, nie procentowej).</xs:documentation>
        </xs:annotation>
      </xs:element>
      <xs:element name="Zysk" type="xs:decimal">
        <xs:annotation>
          <xs:documentation>Zysk w walucie cennika.</xs:documentation>
        </xs:annotation>
      </xs:element>
      <xs:element name="Rabat" minOccurs="0" type="xs:decimal">
        <xs:annotation>
          <xs:documentation>Wartość rabatu domyślnego w postaci dziesiętnej (nie procentowej).</xs:documentation>
        </xs:annotation>
      </xs:element>
    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="TPozycjeCennika">
    <xs:annotation>
      <xs:documentation>Kolekcja pozycji cennika.</xs:documentation>
    </xs:annotation>
    <xs:sequence>
      <xs:element name="Pozycja" maxOccurs="unbounded" minOccurs="0" type="TPozycjaCennika">
        <xs:annotation>
          <xs:documentation>Pozycja cennika.</xs:documentation>
        </xs:annotation>
      </xs:element>
    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="TCennik">
    <xs:annotation>
      <xs:documentation>Cennik</xs:documentation>
    </xs:annotation>
    <xs:sequence>
      <xs:choice>
        <xs:element name="Symbol" type="xs:string">
          <xs:annotation>
            <xs:documentation>Symbol cennika. Występowanie tego elementu oznacza, że ceny dotyczą cennika głównego o podanym symbolu.</xs:documentation>
          </xs:annotation>
        </xs:element>
        <xs:element name="Nazwa" type="xs:string">
          <xs:annotation>
            <xs:documentation>Nazwa cennika. Występowanie tego elementu oznacza, że ceny dotyczą cennika dodatkowego o podanej nazwie.</xs:documentation>
          </xs:annotation>
        </xs:element>
      </xs:choice>
      <xs:element name="Pozycje" type="TPozycjeCennika"></xs:element>
    </xs:sequence>
  </xs:complexType>

  <xs:element name="Ceny">
    <xs:annotation>
      <xs:documentation>Ceny asortymentu w podziale na cenniki.</xs:documentation>
    </xs:annotation>
    <xs:complexType>
      <xs:sequence>
        <xs:element minOccurs="0" maxOccurs="unbounded" name="Cennik" type="TCennik">
          <xs:annotation>
            <xs:documentation>Ceny asortymentu z jednego cennika.</xs:documentation>
          </xs:annotation>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  
</xs:schema>