<?xml version="1.0" encoding="utf-8"?>
<xs:schema attributeFormDefault="unqualified"
           elementFormDefault="qualified"
           targetNamespace="http://schemas.insert.com.pl/2014/hop/historiowanie"
           xmlns="http://schemas.insert.com.pl/2014/hop/historiowanie"
           xmlns:xs="http://www.w3.org/2001/XMLSchema">

  <xs:annotation>
    <xs:documentation>Struktury opisujące historię zmian obiektów.</xs:documentation>
  </xs:annotation>

  <xs:complexType name="THistoria">
    <xs:annotation>
      <xs:documentation>Historia.</xs:documentation>
    </xs:annotation>
    <xs:sequence>
      <xs:element name="SygnaturaUzytkownika" type="xs:string" minOccurs="0">
        <xs:annotation>
          <xs:documentation>Sygnatura użytkownika, który dokonał zmian na obiekcie.</xs:documentation>
        </xs:annotation>
      </xs:element>
      <xs:element name="Data" type="xs:dateTime">
        <xs:annotation>
          <xs:documentation>Data wykonania zmiany na obiekcie.</xs:documentation>
        </xs:annotation>
      </xs:element>
      <!--<xs:choice>
        <xs:sequence>-->
          <xs:element name="Pole" type="xs:string" minOccurs="0">
            <xs:annotation>
              <xs:documentation>Nazwa pola, na którym dokonano zmiany.</xs:documentation>
            </xs:annotation>
          </xs:element>
          <xs:element name="StaraWartosc" type="xs:string" minOccurs="0">
            <xs:annotation>
              <xs:documentation>Wartość przed zmianą.</xs:documentation>
            </xs:annotation>
          </xs:element>
          <xs:element name="NowaWartosc" type="xs:string" minOccurs="0">
            <xs:annotation>
              <xs:documentation>Wartość po zmianie.</xs:documentation>
            </xs:annotation>
          </xs:element>
        <!--</xs:sequence>
        <xs:sequence>-->
          <xs:element name="Komentarz" type="xs:string" minOccurs="0">
            <xs:annotation>
              <xs:documentation>Komentarz opisujący zaistniałe zmiany.</xs:documentation>
            </xs:annotation>
          </xs:element>
        </xs:sequence>
      <!--</xs:choice>
    </xs:sequence>-->
  </xs:complexType>

</xs:schema>