<?xml version="1.0" encoding="utf-8"?>
<xs:schema 
  attributeFormDefault="unqualified" 
  elementFormDefault="qualified" 
  targetNamespace="http://schemas.insert.com.pl/2018/hop/instytucje"
  xmlns="http://schemas.insert.com.pl/2018/hop/instytucje"
  xmlns:wspolne="http://schemas.insert.com.pl/2013/hop"
  xmlns:rachunki="http://schemas.insert.com.pl/2013/hop/rachunkibankowe"
  xmlns:xs="http://www.w3.org/2001/XMLSchema">

  <xs:import id="WspolnePart" namespace="http://schemas.insert.com.pl/2013/hop" schemaLocation="Wspolne.xsd"/>
  <xs:import id="RachunkiBankowe" namespace="http://schemas.insert.com.pl/2013/hop/rachunkibankowe" schemaLocation="RachunkiBankowe.xsd"/>

  <xs:simpleType name="TRodzajRachunkuUS">
    <xs:annotation>
      <xs:documentation>Rodzaje rachunków bankowych Urzędu Skarbowego wg rodzaju przyjmowanych deklaracji.</xs:documentation>
    </xs:annotation>
    <xs:restriction base="xs:string">
      <xs:enumeration value="PIT">
        <xs:annotation>
          <xs:documentation>Rachunek bankowy Urzędu Skarbowego przeznaczony na deklaracje PIT.</xs:documentation>
        </xs:annotation>
      </xs:enumeration>
      <xs:enumeration value="CIT">
        <xs:annotation>
          <xs:documentation>Rachunek bankowy Urzędu Skarbowego przeznaczony na deklaracje CIT.</xs:documentation>
        </xs:annotation>
      </xs:enumeration>
      <xs:enumeration value="VAT">
        <xs:annotation>
          <xs:documentation>Rachunek bankowy Urzędu Skarbowego przeznaczony na deklaracje VAT.</xs:documentation>
        </xs:annotation>
      </xs:enumeration>
    </xs:restriction>
  </xs:simpleType>

  <xs:complexType name="TRachunekBankowyZTypemDeklaracji">
    <xs:annotation>
      <xs:documentation>Rachunek bankowy z opcjonalnym wskazaniem typu przyjmowanych deklaracji skarbowych i określeniem, czy jest rachunkiem ZUS oraz wskazeniem płatnika ZUS.</xs:documentation>
    </xs:annotation>
    <xs:complexContent>
      <xs:extension base="rachunki:TRachunekBankowyKlienta">
        <xs:attribute name="TypDeklaracji" type="TRodzajRachunkuUS" use="optional">
          <xs:annotation>
            <xs:documentation>Rodzaj przyjmowanych deklaracji skarbowych na rachunek bankowy.</xs:documentation>
          </xs:annotation>
        </xs:attribute>
		<xs:attribute name="SkladkiZus" type="xs:boolean" use="optional">
		  <xs:annotation>
			<xs:documentation>Określa, czy rachunek jest przeznaczony dla składek ZUS.</xs:documentation>
		  </xs:annotation>
		</xs:attribute>
		<xs:attribute name="PlatnikZUS" type="xs:string" use="optional">
		  <xs:annotation>
			<xs:documentation>Symbol podmiotu będącego płatnikiem ZUS.</xs:documentation>
		  </xs:annotation>
		</xs:attribute>
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>

   <xs:element name="Instytucje">
    <xs:annotation>
      <xs:documentation>Instytucje.</xs:documentation>
    </xs:annotation>
    <xs:complexType>
      <xs:sequence>
        <xs:element minOccurs="0" maxOccurs="unbounded" name="Instytucja">
          <xs:annotation>
            <xs:documentation>Instytucja.</xs:documentation>
          </xs:annotation>
          <xs:complexType>
            <xs:sequence>
              <xs:element name="Sygnatura" type="xs:string">
                <xs:annotation>
                  <xs:documentation>Unikalny symbol.</xs:documentation>
                </xs:annotation>
              </xs:element>
              <xs:element name="Typ">
                <xs:annotation>
                  <xs:documentation>Typ.</xs:documentation>
                </xs:annotation>
                <xs:simpleType>
                  <xs:restriction base="xs:string">
                    <xs:enumeration value="OrganPodatkowy">
                      <xs:annotation>
                        <xs:documentation>Organ podatkowy.</xs:documentation>
                      </xs:annotation>
                    </xs:enumeration>
                    <xs:enumeration value="OddzialZUS">
                      <xs:annotation>
                        <xs:documentation>Oddział ZUS.</xs:documentation>
                      </xs:annotation>
                    </xs:enumeration>
                    <xs:enumeration value="FunduszPromocji">
                      <xs:annotation>
                        <xs:documentation>Fundusz promocji.</xs:documentation>
                      </xs:annotation>
                    </xs:enumeration>
                    <xs:enumeration value="Komornik">
                      <xs:annotation>
                        <xs:documentation>Komornik.</xs:documentation>
                      </xs:annotation>
                    </xs:enumeration>
                    <xs:enumeration value="InnaInstytucja">
                      <xs:annotation>
                        <xs:documentation>Inna instytucja.</xs:documentation>
                      </xs:annotation>
                    </xs:enumeration>
                    <xs:enumeration value="InstytucjaFinansowa">
                        <xs:annotation>
                          <xs:documentation>Instytucja finansowa.</xs:documentation>
                        </xs:annotation>
                      </xs:enumeration>
                    </xs:restriction>
                </xs:simpleType>
              </xs:element>
              <xs:element name="Nazwa" type="xs:string">
                <xs:annotation>
                  <xs:documentation>Nazwa.</xs:documentation>
                </xs:annotation>
              </xs:element>
              <xs:element name="PelnaNazwa" type="xs:string" minOccurs="0">
                <xs:annotation>
                  <xs:documentation>Pełna nazwa.</xs:documentation>
                </xs:annotation>
              </xs:element>
              <xs:element name="NIP" type="xs:string" minOccurs="0">
                <xs:annotation>
                  <xs:documentation>NIP.</xs:documentation>
                </xs:annotation>
              </xs:element>
              <xs:element name="REGON" type="xs:string" minOccurs="0">
                <xs:annotation>
                  <xs:documentation>REGON.</xs:documentation>
                </xs:annotation>
              </xs:element>
              <xs:element name="KodUrzeduSkarbowego" type="xs:string" minOccurs="0">
                <xs:annotation>
                  <xs:documentation>Tylko dla organu podatkowego (opcjonalny).</xs:documentation>
                </xs:annotation>
              </xs:element>
              <xs:element name="DaneFunduszuPromocji" minOccurs="0">
                <xs:annotation>
                  <xs:documentation>Wymagany dla funduszu promocji.</xs:documentation>
                </xs:annotation>
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="TypNaliczania">
                      <xs:annotation>
                        <xs:documentation>Typ naliczania.</xs:documentation>
                      </xs:annotation>
                      <xs:simpleType>
                        <xs:restriction base="xs:string">
                          <xs:enumeration value="Procentowo">
                            <xs:annotation>
                              <xs:documentation>Procentowo.</xs:documentation>
                            </xs:annotation>
                          </xs:enumeration>
                          <xs:enumeration value="Kwotowo">
                            <xs:annotation>
                              <xs:documentation>Kwotowo.</xs:documentation>
                            </xs:annotation>
                          </xs:enumeration>
                        </xs:restriction>
                      </xs:simpleType>
                    </xs:element>
                    <xs:element name="Procent" minOccurs="0" type="xs:decimal">
                      <xs:annotation>
                        <xs:documentation>Procent wyrażony jako wartość z zakresu [0; 1] (1 oznacza 100%). Wymagany dla procentowego typu naliczania.</xs:documentation>
                      </xs:annotation>
                    </xs:element>
                    <xs:element name="Kwota" minOccurs="0" type="xs:decimal">
                      <xs:annotation>
                        <xs:documentation>Wymagana dla kwotowego typu naliczania.</xs:documentation>
                      </xs:annotation>
                    </xs:element>
                    <xs:element name="JednostkaMiary" minOccurs="0" type="xs:string">
                      <xs:annotation>
                        <xs:documentation>
                          Symbol jednostki miary (np.: szt, usl, cm, ...).
                          Wymagany dla kwotowego typu naliczania, jednak jeśli nie jest podany, to domyślnie przyjmowany jest kilogram.                          
                        </xs:documentation>
                      </xs:annotation>
                    </xs:element>
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
              <xs:element name="Kontakty" type="wspolne:Kontakty" minOccurs="0">
                <xs:annotation>
                  <xs:documentation>Dane kontaktowe.</xs:documentation>
                </xs:annotation>
              </xs:element>
              <xs:element name="Adresy" type="wspolne:Adresy">
                <xs:annotation>
                  <xs:documentation>Adresy.</xs:documentation>
                </xs:annotation>
              </xs:element>
              <xs:element minOccurs="0" name="RachunkiBankowe">
                <xs:annotation>
                  <xs:documentation>Lista rachunków bankowych instytucji.</xs:documentation>
                </xs:annotation>
                <xs:complexType>
                  <xs:sequence>
                    <xs:element minOccurs="0" maxOccurs="unbounded" name="Rachunek" type="TRachunekBankowyZTypemDeklaracji">
                      <xs:annotation>
                        <xs:documentation>Rachunek bankowy instytucji.</xs:documentation>
                      </xs:annotation>
                    </xs:element>
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
              <xs:element name="FlagaWlasna" minOccurs="0">
                <xs:annotation>
                  <xs:documentation>Dane flagi własnej.</xs:documentation>
                </xs:annotation>
                <xs:complexType>
                  <xs:all>
                    <xs:element minOccurs="1" maxOccurs="1" name="Kolor" type="xs:string">
                      <xs:annotation>
                        <xs:documentation>Kolor flagi własnej.</xs:documentation>
                      </xs:annotation>
                    </xs:element>
                    <xs:element minOccurs="0" maxOccurs="1" name="Ksztalt" type="xs:string">
                      <xs:annotation>
                        <xs:documentation>Kształt flagi własnej.</xs:documentation>
                      </xs:annotation>
                    </xs:element>
                    <xs:element minOccurs="0" maxOccurs="1" name="Komentarz" type="xs:string">
                      <xs:annotation>
                        <xs:documentation>Komentarz flagi własnej.</xs:documentation>
                      </xs:annotation>
                    </xs:element>
                  </xs:all>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  
</xs:schema>