<?xml version="1.0" encoding="utf-8"?>
<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified"
           targetNamespace="http://schemas.insert.com.pl/2015/hop/gratyfikant/naliczenia"
           xmlns="http://schemas.insert.com.pl/2015/hop/gratyfikant/naliczenia"
           xmlns:wspolne="http://schemas.insert.com.pl/2013/hop"
           xmlns:wspolneGr="http://schemas.insert.com.pl/2015/hop/gratyfikant"
           xmlns:xs="http://www.w3.org/2001/XMLSchema">

  <xs:import id="WspolnePart" namespace="http://schemas.insert.com.pl/2013/hop" schemaLocation="Wspolne.xsd"/>
  <xs:import id="WspolneGrPart" namespace="http://schemas.insert.com.pl/2015/hop/gratyfikant" schemaLocation="WspolneGr.xsd"/>

  <xs:annotation>
    <xs:documentation>Informacje o naliczeniach i potrąceniach.</xs:documentation>
  </xs:annotation>


  <xs:complexType name="TNaliczeniePotracenie">
    <xs:sequence>
      <xs:element name="Pracownik" type="wspolne:Obowiazkowy">
        <xs:annotation>
          <xs:documentation>Nazwa pracownika.</xs:documentation>
        </xs:annotation>
      </xs:element>
      <xs:element name="Data" type="xs:date">
        <xs:annotation>
          <xs:documentation>Data naliczenia/potrącenia.</xs:documentation>
        </xs:annotation>
      </xs:element>
      <xs:element name="SkladnikPlacowy" type="wspolne:Obowiazkowy">
        <xs:annotation>
          <xs:documentation>Nazwa składnika płacowego.</xs:documentation>
        </xs:annotation>
      </xs:element>
      <xs:element name="Kwota" type="xs:decimal">
        <xs:annotation>
          <xs:documentation>Kwota naliczenia/potrącenia.</xs:documentation>
        </xs:annotation>
      </xs:element>
      <xs:element name="Opis" type="xs:string" minOccurs="0">
        <xs:annotation>
          <xs:documentation>Opcjonalny opis naliczenia/potrącenia.</xs:documentation>
        </xs:annotation>
      </xs:element>
      <xs:element name="SposobRozliczenia" type="wspolneGr:TSposobRozliczenia">
        <xs:annotation>
          <xs:documentation>Sposób rozliczenia naliczenia/potrącenia.</xs:documentation>
        </xs:annotation>
      </xs:element>
      <xs:element name="FlagaWlasna" minOccurs="0">
        <xs:annotation>
          <xs:documentation>Dane flagi własnej.</xs:documentation>
        </xs:annotation>
        <xs:complexType>
          <xs:all>
            <xs:element minOccurs="1" maxOccurs="1" name="Kolor" type="xs:string">
              <xs:annotation>
                <xs:documentation>Kolor flagi własnej.</xs:documentation>
              </xs:annotation>
            </xs:element>
            <xs:element minOccurs="0" maxOccurs="1" name="Ksztalt" type="xs:string">
              <xs:annotation>
                <xs:documentation>Kształt flagi własnej.</xs:documentation>
              </xs:annotation>
            </xs:element>
            <xs:element minOccurs="0" maxOccurs="1" name="Komentarz" type="xs:string">
              <xs:annotation>
                <xs:documentation>Komentarz flagi własnej.</xs:documentation>
              </xs:annotation>
            </xs:element>
          </xs:all>
        </xs:complexType>
      </xs:element>
    </xs:sequence>
  </xs:complexType>
  
  <xs:complexType name="TNaliczeniaPotracenia">
    <xs:sequence>
      <xs:element name="NaliczeniePotracenie" type="TNaliczeniePotracenie" minOccurs="0" maxOccurs="unbounded">
        <xs:annotation>
          <xs:documentation>Dane dotyczące naliczenia/potrącenia.</xs:documentation>
        </xs:annotation>
      </xs:element>
    </xs:sequence>
  </xs:complexType>
  
  <xs:element name="NaliczeniaPotracenia" type="TNaliczeniaPotracenia">
    <xs:annotation>
      <xs:documentation>Dane dotyczące naliczeń i potrąceń.</xs:documentation>
    </xs:annotation>
  </xs:element>
  
</xs:schema>