<?xml version="1.0" encoding="utf-8"?>
<xs:schema attributeFormDefault="unqualified"
           elementFormDefault="qualified"
           targetNamespace="http://schemas.insert.com.pl/2018/hop/oferty"
           xmlns="http://schemas.insert.com.pl/2018/hop/oferty"
           xmlns:p="http://schemas.insert.com.pl/2014/hop/parametryofert"
           xmlns:r="http://schemas.insert.com.pl/2013/hop/rabaty"
           xmlns:xs="http://www.w3.org/2001/XMLSchema">

  <xs:import schemaLocation="Rabaty.xsd" namespace="http://schemas.insert.com.pl/2013/hop/rabaty" />
  <xs:import schemaLocation="ParametryOfert.xsd" namespace="http://schemas.insert.com.pl/2014/hop/parametryofert" />
  
  <xs:annotation>
    <xs:documentation>Oferty.</xs:documentation>
  </xs:annotation>

  <xs:complexType name="TOferta">
    <xs:annotation>
      <xs:documentation>Dane dotyczące oferty.</xs:documentation>
    </xs:annotation>
    <xs:sequence>
      <xs:element name="Numer" type="xs:string" minOccurs="0">
        <xs:annotation>
          <xs:documentation>Numer oferty.</xs:documentation>
        </xs:annotation>
      </xs:element>
      <!--<xs:element name="ProcesOfertowy" minOccurs="0">
        <xs:annotation>
          <xs:documentation>Proces ofertowy z którym powiązana jest oferta.</xs:documentation>
        </xs:annotation>
        <xs:complexType>
          <xs:sequence>
            <xs:element name="Numer" type="xs:string" minOccurs="0">
              <xs:annotation>
                <xs:documentation>Numer procesu ofertowego.</xs:documentation>
              </xs:annotation>
            </xs:element>
            <xs:element name="Nazwa" type="xs:string" minOccurs="0">
              <xs:annotation>
                <xs:documentation>Nazwa procesu ofertowego.</xs:documentation>
              </xs:annotation>
            </xs:element>
          </xs:sequence>
        </xs:complexType>
      </xs:element>-->
      <xs:element name="DataWystawienia" type="xs:date" minOccurs="0">
        <xs:annotation>
          <xs:documentation>Data wystawienia oferty.</xs:documentation>
        </xs:annotation>
      </xs:element>
      <xs:element name="MiejsceWystawienia" type="xs:string" minOccurs="0">
        <xs:annotation>
          <xs:documentation>Miejsce wystawienia oferty.</xs:documentation>
        </xs:annotation>
      </xs:element>
      <xs:element name="TerminRealizacji" type="xs:date" minOccurs="0">
        <xs:annotation>
          <xs:documentation>Termin realizacji oferty.</xs:documentation>
        </xs:annotation>
      </xs:element>
      <!-- Dostawca uzupełnia się z procesu ofertowego. -->
      <!--<xs:element name="Dostawca" type="xs:string" minOccurs="0">
        <xs:annotation>
          <xs:documentation>Sygnatura dostawcy.</xs:documentation>
        </xs:annotation>
      </xs:element>-->
      <xs:element name="Oddzial" type="xs:string" minOccurs="0">
        <xs:annotation>
          <xs:documentation>Symbol oddziału.</xs:documentation>
        </xs:annotation>
      </xs:element>
      <xs:element name="Magazyn" type="xs:string" minOccurs="0">
        <xs:annotation>
          <xs:documentation>Symbol magazyn.</xs:documentation>
        </xs:annotation>
      </xs:element>
      <!--<xs:element name="AdresDostawy" type="xs:string" minOccurs="0">
        <xs:annotation>
          <xs:documentation>Adres dostawy.</xs:documentation>
        </xs:annotation>
      </xs:element>-->
      <!--<xs:element name="SposobDostawy" type="xs:string" minOccurs="0">
        <xs:annotation>
          <xs:documentation>Sposób dostawy.</xs:documentation>
        </xs:annotation>
      </xs:element>-->
      <!--<xs:element name="ObowiazujeOd" type="xs:string" minOccurs="0">
        <xs:annotation>
          <xs:documentation>Określa datę od której obowiązuje oferta.</xs:documentation>
        </xs:annotation>
      </xs:element>-->
      <!--<xs:element name="ObowiazujeDo" type="xs:string" minOccurs="0">
        <xs:annotation>
          <xs:documentation>Określa datę do której obowiązuje oferta.</xs:documentation>
        </xs:annotation>
      </xs:element>-->
      <!-- Klient uzupełnia się z procesu ofertowego. -->
      <!--<xs:element name="Klient" type="xs:string">
        <xs:annotation>
          <xs:documentation>Sygnatura klienta dla którego przygotowano ofertę.</xs:documentation>
        </xs:annotation>
      </xs:element>-->
      <!--<xs:element name="InnyOdbiorca" type="xs:string" minOccurs="0">
        <xs:annotation>
          <xs:documentation>Sygnatura innego odbiorcy oferty.</xs:documentation>
        </xs:annotation>
      </xs:element>-->
      <!--<xs:element name="InnyNabywca" type="xs:string" minOccurs="0">
        <xs:annotation>
          <xs:documentation>Sygnatura innego nabywcy oferty.</xs:documentation>
        </xs:annotation>
      </xs:element>-->
      <!--<xs:element name="TypZamowienia" type="xs:string" minOccurs="0">
        <xs:annotation>
          <xs:documentation>Typ zamównienia</xs:documentation>
        </xs:annotation>
      </xs:element>-->
      <!--<xs:element name="TypWydania" type="xs:string" minOccurs="0">
        <xs:annotation>
          <xs:documentation>Typ wydania.</xs:documentation>
        </xs:annotation>
      </xs:element>-->
      <!--<xs:element name="TypZaliczki" type="xs:string" minOccurs="0">
        <xs:annotation>
          <xs:documentation>Typ zaliczki.</xs:documentation>
        </xs:annotation>
      </xs:element>-->
      <!--<xs:element name="TypDokumentu" type="xs:string" minOccurs="0">
        <xs:annotation>
          <xs:documentation>Typ dokumentu.</xs:documentation>
        </xs:annotation>
      </xs:element>-->
      <xs:element name="SposobWyliczaniaDokumentu">
        <xs:complexType>
          <xs:sequence>
            <xs:element name="PrzeliczaniePozycji" type="p:TPrzeliczaniePozycji">
              <xs:annotation>
                <xs:documentation>Sposoby przeliczania pozycji.</xs:documentation>
              </xs:annotation>
            </xs:element>
            <xs:element name="PrzeliczanieDokumentu" type="TPrzeliczanieDokumentu" minOccurs="0">
              <xs:annotation>
                <xs:documentation>Sposoby przeliczania dokumentu.</xs:documentation>
              </xs:annotation>
            </xs:element>
            <xs:element name="WalutaSymbol" type="xs:string" minOccurs="0">
              <xs:annotation>
                <xs:documentation>Symbol waluty.</xs:documentation>
              </xs:annotation>
            </xs:element>
            <xs:element name="WalutaKurs" type="xs:decimal" minOccurs="0">
              <xs:annotation>
                <xs:documentation>Kurs waluty.</xs:documentation>
              </xs:annotation>
            </xs:element>
            <xs:element name="WalutaLiczbaJednostek" type="xs:int" minOccurs="0">
              <xs:annotation>
                <xs:documentation>Liczba jednostek waluty.</xs:documentation>
              </xs:annotation>
            </xs:element>
            <xs:element name="WalutaRodzajKursu" minOccurs="0">
              <xs:annotation>
                <xs:documentation>Rodzaj kursu waluty.</xs:documentation>
              </xs:annotation>
              <xs:simpleType>
                <xs:restriction base="xs:string">
                  <xs:enumeration value="Sprzedazy" />
                  <xs:enumeration value="Kupna" />
                  <xs:enumeration value="Sredni" />
                </xs:restriction>
              </xs:simpleType>
            </xs:element>
            <xs:element name="WalutaBank" type="xs:string" minOccurs="0">
              <xs:annotation>
                <xs:documentation>Waluta bank.</xs:documentation>
              </xs:annotation>
            </xs:element>
            <xs:element name="TransakcjaHandlowa" type="p:TTransakcjaHandlowa">
              <xs:annotation>
                <xs:documentation>Rodzaj transakcji handlowej.</xs:documentation>
              </xs:annotation>
            </xs:element>
            <xs:element name="PoziomCen">
              <xs:complexType>
                <xs:sequence>
                  <xs:element name="Nazwa" type="xs:string" minOccurs="0">
                    <xs:annotation>
                      <xs:documentation>Nazwa poziomu cen.</xs:documentation>
                    </xs:annotation>
                  </xs:element>
                  <xs:element name="Kalkulowana" type="xs:boolean" minOccurs="0">
                    <xs:annotation>
                      <xs:documentation>.</xs:documentation>
                    </xs:annotation>
                  </xs:element>
                </xs:sequence>
              </xs:complexType>
            </xs:element>
            <xs:element name="KodRodzajuTransakcjiVAT" minOccurs="0">
              <xs:complexType>
                <xs:sequence>
                  <xs:element name="Kod" type="xs:string" minOccurs="0">
                    <xs:annotation>
                      <xs:documentation>Kod rodzaju transakcji VAT.</xs:documentation>
                    </xs:annotation>
                  </xs:element>
                  <xs:element name="Nazwa" type="xs:string" minOccurs="0">
                    <xs:annotation>
                      <xs:documentation>Nazwa rodzaju transakcji.</xs:documentation>
                    </xs:annotation>
                  </xs:element>
                </xs:sequence>
              </xs:complexType>
            </xs:element>
          </xs:sequence>
        </xs:complexType>
      </xs:element>
      <xs:element name="OpisTerminuRealizacji" type="xs:string" minOccurs="0">
        <xs:annotation>
          <xs:documentation>Termin realizacji.</xs:documentation>
        </xs:annotation>
      </xs:element>
      <xs:element name="WarunkiPlatnosci" type="xs:string" minOccurs="0">
        <xs:annotation>
          <xs:documentation>Warunki płatności.</xs:documentation>
        </xs:annotation>
      </xs:element>
      <xs:element name="WarunkiDostawy" type="xs:string" minOccurs="0">
        <xs:annotation>
          <xs:documentation>Warunki dostawy.</xs:documentation>
        </xs:annotation>
      </xs:element>
      <xs:element name="UwagiNaDokument" type="xs:string" minOccurs="0">
        <xs:annotation>
          <xs:documentation>Uwagi na dokument.</xs:documentation>
        </xs:annotation>
      </xs:element>
      <xs:element name="OpisSzczegolowy" type="xs:string" minOccurs="0">
        <xs:annotation>
          <xs:documentation>Opis pełny.</xs:documentation>
        </xs:annotation>
      </xs:element>
      <!--<xs:element name="OkreslajIloscOferowanegoAsortymentu" type="xs:boolean" minOccurs="0">
        <xs:annotation>
          <xs:documentation></xs:documentation>
        </xs:annotation>
      </xs:element>-->
      <xs:element name="Wariant" type="TWariantOferty" minOccurs="0">
        <xs:annotation>
          <xs:documentation>Wariant.</xs:documentation>
        </xs:annotation>
      </xs:element>
      <xs:element name="Opiekun" type="xs:string" minOccurs="0">
        <xs:annotation>
          <xs:documentation>Symbol opiekuna.</xs:documentation>
        </xs:annotation>
      </xs:element>
      <!--<xs:element name="Kontakt" type="xs:string" minOccurs="0">
        <xs:annotation>
          <xs:documentation>Kontakt z opiekunem.</xs:documentation>
        </xs:annotation>
      </xs:element>-->
      <xs:element name="Kategoria" type="xs:string" minOccurs="0">
        <xs:annotation>
          <xs:documentation>Nazwa kategorii oferty.</xs:documentation>
        </xs:annotation>
      </xs:element>
      <!--<xs:element name="Tytul" type="xs:string" minOccurs="0">
        <xs:annotation>
          <xs:documentation>tytuł oferty.</xs:documentation>
        </xs:annotation>
      </xs:element>-->
      <!--<xs:element name="Podtytul" type="xs:string" minOccurs="0">
        <xs:annotation>
          <xs:documentation>Podtytuł oferty.</xs:documentation>
        </xs:annotation>
      </xs:element>-->
      <!--<xs:element name="Uwagi" type="xs:string" minOccurs="0">
        <xs:annotation>
          <xs:documentation>Uwagi.</xs:documentation>
        </xs:annotation>
      </xs:element>-->
      <!--<xs:element name="PrzenosUwagi" type="xs:boolean" minOccurs="0">
        <xs:annotation>
          <xs:documentation>Określa, czy uwagi zostaną przeniesione na dokumentu realizujące.</xs:documentation>
        </xs:annotation>
      </xs:element>-->
      <!--<xs:element name="OfertaHandlowa" type="xs:string" minOccurs="0">
        <xs:annotation>
          <xs:documentation></xs:documentation>
        </xs:annotation>
      </xs:element>-->
      <!--<xs:element name="InformacjeKoncowe" type="xs:string" minOccurs="0">
        <xs:annotation>
          <xs:documentation></xs:documentation>
        </xs:annotation>
      </xs:element>-->
      <!--<xs:element name="PlatnosciSugerowane" type="xs:string" minOccurs="0">
        <xs:annotation>
          <xs:documentation></xs:documentation>
        </xs:annotation>
      </xs:element>-->
    </xs:sequence>
  </xs:complexType>
  
  <xs:element name="Oferty">
    <xs:annotation>
      <xs:documentation>Oferty.</xs:documentation>
    </xs:annotation>
    <xs:complexType>
      <xs:sequence>
        <xs:element name="Oferta" type="TOferta" minOccurs="0" maxOccurs="unbounded">
          <xs:annotation>
            <xs:documentation>Oferta.</xs:documentation>
          </xs:annotation>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>

  <xs:complexType name="TWariantOferty">
    <xs:annotation>
      <xs:documentation>Dane opisujące wariant oferty.</xs:documentation>
    </xs:annotation>
    <xs:sequence>
      <xs:element name="Towary" minOccurs="0">
        <xs:annotation>
          <xs:documentation>Lista towarów.</xs:documentation>
        </xs:annotation>
        <xs:complexType>
          <xs:sequence minOccurs="1" maxOccurs="unbounded">
            <xs:element name="Towar" type="TWariantOfertyTowar">
              <xs:annotation>
                <xs:documentation>Towar.</xs:documentation>
              </xs:annotation>
            </xs:element>
          </xs:sequence>
        </xs:complexType>
      </xs:element>
    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="TWariantOfertyTowar">
    <xs:annotation>
      <xs:documentation>Dane opisujące towar.</xs:documentation>
    </xs:annotation>
    <xs:sequence>
      <xs:element name="LP" type="xs:int" minOccurs="0">
        <xs:annotation>
          <xs:documentation>Liczba porządkowa.</xs:documentation>
        </xs:annotation>
      </xs:element>
      <xs:element name="Rodzaj" type="TRodzajTowaru">
        <xs:annotation>
          <xs:documentation>Rodzaj towaru (jesli pole symbolu jest puste, a rodzajem jest usługa, to jest to usługa jednorazowa).</xs:documentation>
        </xs:annotation>
      </xs:element>
      <xs:element name="Symbol" type="xs:string" minOccurs="0">
        <xs:annotation>
          <xs:documentation>Symbol towaru.</xs:documentation>
        </xs:annotation>
      </xs:element>
      <xs:element name="Nazwa" type="xs:string" minOccurs="0">
        <xs:annotation>
          <xs:documentation>Nazwa towaru.</xs:documentation>
        </xs:annotation>
      </xs:element>
      <xs:element name="OpisPozycji" type="xs:string" minOccurs="0">
        <xs:annotation>
          <xs:documentation>Opis pozycji.</xs:documentation>
        </xs:annotation>
      </xs:element>
      <xs:element name="PKWiU" type="xs:string" minOccurs="0">
        <xs:annotation>
          <xs:documentation>PKWiU dla pozycji usług jednorazowych.</xs:documentation>
        </xs:annotation>
      </xs:element>
      <xs:element name="Magazyn" type="xs:string" minOccurs="0">
        <xs:annotation>
          <xs:documentation>Sygnatura magazynu.</xs:documentation>
        </xs:annotation>
      </xs:element>
      <xs:element name="Ilosc" type="xs:decimal">
        <xs:annotation>
          <xs:documentation>Liczba towarów.</xs:documentation>
        </xs:annotation>
      </xs:element>
      <xs:element name="JednostkaMiary" type="xs:string">
        <xs:annotation>
          <xs:documentation>Jednostka miary.</xs:documentation>
        </xs:annotation>
      </xs:element>
      <!-- Cena netto/brutto w zależności od sposobu przeliczania pozycji. -->
      <xs:element name="CenaWWalucie" type="xs:decimal">
        <xs:annotation>
          <xs:documentation>Cena w walucie.</xs:documentation>
        </xs:annotation>
      </xs:element>
      <xs:element name="TerminRealizacji" type="xs:date" minOccurs="0">
        <xs:annotation>
          <xs:documentation>Termin realizacji.</xs:documentation>
        </xs:annotation>
      </xs:element>
      <xs:element name="CenaNetto" type="xs:decimal" minOccurs="0">
        <xs:annotation>
          <xs:documentation>Cena netto.</xs:documentation>
        </xs:annotation>
      </xs:element>
      <xs:element name="CenaBrutto" type="xs:decimal" minOccurs="0">
        <xs:annotation>
          <xs:documentation>Cena brutto.</xs:documentation>
        </xs:annotation>
      </xs:element>
      <xs:element name="CenaNettoRabat" type="xs:decimal" minOccurs="0">
        <xs:annotation>
          <xs:documentation>Cena netto po rabacie.</xs:documentation>
        </xs:annotation>
      </xs:element>
      <xs:element name="CenaBruttoRabat" type="xs:decimal" minOccurs="0">
        <xs:annotation>
          <xs:documentation>Cena brutto po rabacie.</xs:documentation>
        </xs:annotation>
      </xs:element>
      <xs:element name="WartoscNetto" type="xs:decimal" minOccurs="0">
        <xs:annotation>
          <xs:documentation>Wartość netto.</xs:documentation>
        </xs:annotation>
      </xs:element>
      <xs:element name="WartoscBrutto" type="xs:decimal" minOccurs="0">
        <xs:annotation>
          <xs:documentation>Wartość brutto.</xs:documentation>
        </xs:annotation>
      </xs:element>
      <xs:element name="WartoscVAT" type="xs:decimal" minOccurs="0">
        <xs:annotation>
          <xs:documentation>Wartość VAT.</xs:documentation>
        </xs:annotation>
      </xs:element>
      <xs:element name="WartoscNettoRabat" type="xs:decimal" minOccurs="0">
        <xs:annotation>
          <xs:documentation>Wartość netto po rabacie.</xs:documentation>
        </xs:annotation>
      </xs:element>
      <xs:element name="WartoscBruttoRabat" type="xs:decimal" minOccurs="0">
        <xs:annotation>
          <xs:documentation>Wartość brutto po rabacie.</xs:documentation>
        </xs:annotation>
      </xs:element>
      <xs:element name="WartoscVATRabat" type="xs:decimal" minOccurs="0">
        <xs:annotation>
          <xs:documentation>Wartość VAT po rabacie.</xs:documentation>
        </xs:annotation>
      </xs:element>
      <xs:element name="JestRabat" type="xs:boolean" minOccurs="0">
        <xs:annotation>
          <xs:documentation>Czy występuje rabat na pozycji.</xs:documentation>
        </xs:annotation>
      </xs:element>
      <xs:element name="Rabat" minOccurs="0">
        <xs:annotation>
          <xs:documentation>Rabat.</xs:documentation>
        </xs:annotation>
        <xs:complexType>
          <xs:sequence>
            <xs:element name="Rodzaj" type="r:RodzajRabatu">
              <xs:annotation>
                <xs:documentation>Rodzaj rabatu.</xs:documentation>
              </xs:annotation>
            </xs:element>
            <xs:element name="Wartosc" type="xs:decimal">
              <xs:annotation>
                <xs:documentation>Wartość w walucie lub procent.</xs:documentation>
              </xs:annotation>
            </xs:element>
          </xs:sequence>
        </xs:complexType>
      </xs:element>
      <xs:element name="StawkaVat" minOccurs="0">
        <xs:annotation>
          <xs:documentation>Symbol stawki VAT, np. 8, 23, zw.</xs:documentation>
        </xs:annotation>
        <xs:complexType>
          <xs:sequence>
            <xs:element name="Symbol" type="xs:string">
              <xs:annotation>
                <xs:documentation>Symbol stawki VAT.</xs:documentation>
              </xs:annotation>
            </xs:element>
            <xs:element name="Wartosc" type="xs:decimal">
              <xs:annotation>
                <xs:documentation>Wartość stawki VAT.</xs:documentation>
              </xs:annotation>
            </xs:element>
          </xs:sequence>
        </xs:complexType>
      </xs:element>
      <xs:element name="TerminWaznosci" type="xs:string" minOccurs="0">
        <xs:annotation>
          <xs:documentation>Termin ważności towaru.</xs:documentation>
        </xs:annotation>
      </xs:element>
    </xs:sequence>
  </xs:complexType>

  <xs:simpleType name="TRodzajTowaru">
    <xs:annotation>
      <xs:documentation>Rodzaje towarów.</xs:documentation>
    </xs:annotation>
    <xs:restriction base="xs:string">
      <xs:enumeration value="Towar" />
      <xs:enumeration value="Usluga" />
      <xs:enumeration value="Opakowanie" />
      <xs:enumeration value="Komplet" />
      <xs:enumeration value="OplataDodatkowa" />
    </xs:restriction>
  </xs:simpleType>

  <xs:simpleType name="TPrzeliczanieDokumentu">
    <xs:annotation>
      <xs:documentation>Sposoby przeliczania dokumentu.</xs:documentation>
    </xs:annotation>
    <xs:restriction base="xs:string">
      <xs:enumeration value="NaPozycjach">
        <xs:annotation>
          <xs:documentation>Jako suma wartości VAT na pozycjach.</xs:documentation>
        </xs:annotation>
      </xs:enumeration>
      <xs:enumeration value="WStawkach">
        <xs:annotation>
          <xs:documentation>Od sum obrotów w poszczególnych stawkach.</xs:documentation>
        </xs:annotation>
      </xs:enumeration>
    </xs:restriction>
  </xs:simpleType>
  
</xs:schema>