<?xml version="1.0" encoding="utf-8"?>
<xs:schema
  attributeFormDefault="unqualified"
  elementFormDefault="qualified"
  xmlns="http://schemas.insert.com.pl/2018/hop/klienci"
  targetNamespace="http://schemas.insert.com.pl/2018/hop/klienci"
  xmlns:xs="http://www.w3.org/2001/XMLSchema"
  xmlns:sd="http://schemas.xsddoc.codeplex.com/schemaDoc/2009/3"
  xmlns:maml="http://ddue.schemas.microsoft.com/authoring/2003/5"
  xmlns:wspolne="http://schemas.insert.com.pl/2013/hop"
>

  <xs:import id="WspolnePart" namespace="http://schemas.insert.com.pl/2013/hop" schemaLocation="Wspolne.xsd"/>

  <xs:annotation>
    <xs:documentation>Parametry kartoteki klientów.</xs:documentation>
  </xs:annotation>

  <xs:complexType name="TLimitKredytu">
    <xs:annotation>
      <xs:documentation>Określa limity kredytowania kupieckiego pojedyńczego dokumentu.</xs:documentation>
    </xs:annotation>
    <xs:all>
      <xs:element name="Wartosc" type="xs:decimal">
        <xs:annotation>
          <xs:documentation>Wartość graniczna.</xs:documentation>
        </xs:annotation>
      </xs:element>
      <xs:element name="LimitPowyzejWartosci" type="xs:decimal">
        <xs:annotation>
          <xs:documentation>Maksymalny procent wartości dokumentu, który może być pokryty kredytem kupieckim jeśli wartość dokumentu przekracza wartość graniczną.</xs:documentation>
        </xs:annotation>
      </xs:element>
      <xs:element name="LimitPonizejWartosci" type="xs:decimal">
        <xs:annotation>
          <xs:documentation>Maksymalny procent wartości dokumentu, który może być pokryty kredytem kupieckim jeśli wartość dokumentu nie przekracza wartości granicznej.</xs:documentation>
        </xs:annotation>
      </xs:element>
    </xs:all>
  </xs:complexType>
  
  <xs:complexType name="TKredytKupiecki">
    <xs:annotation>
      <xs:documentation>Określa parametry kredytowania kupieckiego dla kontrahenta.</xs:documentation>
    </xs:annotation>
    <xs:all>
      <xs:element name="Forma" minOccurs="0" type="xs:string">
        <xs:annotation>
          <xs:appinfo>
            <sd:schemaDoc>
              <maml:summary>
                <maml:para>
                  Nazwa domyślnej formy kredytu kupieckiego dla kontrahenta. Ze słownika form płatności. Element wymagany, gdy kredyt jest dozwolony (atrybut <sd:xmlEntityReference>http://schemas.insert.com.pl/2018/hop/klienci#T/TKredytKupiecki/@Zezwalaj</sd:xmlEntityReference>).
                </maml:para>
              </maml:summary>
            </sd:schemaDoc>
          </xs:appinfo>
          <xs:documentation>
            Nazwa domyślnej formy kredytu kupieckiego dla kontrahenta. Ze słownika form płatności. Element wymagany, gdy kredyt jest dozwolony (atrybut Zezwalaj).</xs:documentation>
        </xs:annotation>
      </xs:element>
      <xs:element name="Domyslny" minOccurs="0" type="xs:decimal">
        <xs:annotation>
          <xs:documentation>Wartość procentowa domyślnego kredytu kupiecki dla kontrahenta.</xs:documentation>
        </xs:annotation>
      </xs:element>
      <xs:element name="Max" minOccurs="0" type="xs:decimal">
        <xs:annotation>
          <xs:documentation>Maksymalna wartość kredytu kupieckiego dla kontrahenta.</xs:documentation>
        </xs:annotation>
      </xs:element>
      <xs:element name="MaxLiczbaDok" minOccurs="0" type="xs:int">
        <xs:annotation>
          <xs:documentation>Maksymalna liczba kredytowanych dokumentów dla kontrahenta.</xs:documentation>
        </xs:annotation>
      </xs:element>
      <xs:element name="MaxLiczbaDniSp" minOccurs="0" type="xs:int">
        <xs:annotation>
          <xs:documentation>Maksymalna liczba dni spóźnienia dla kontrahenta.</xs:documentation>
        </xs:annotation>
      </xs:element>
      <xs:element name="LimitKredytowySprzedazy" minOccurs="0" type="TLimitKredytu">
        <xs:annotation>
          <xs:documentation>Limit kredytowy na dokumentach sprzedaży.</xs:documentation>
        </xs:annotation>
      </xs:element>
      <xs:element name="LimitKredytowyWydania" minOccurs="0" type="TLimitKredytu">
        <xs:annotation>
          <xs:documentation>Limit kredytowy na wydaniach.</xs:documentation>
        </xs:annotation>
      </xs:element>
      <xs:element name="LimitKredytowyZamowienia" minOccurs="0" type="TLimitKredytu">
        <xs:annotation>
          <xs:documentation>Limit kredytowy na zamówieniach.</xs:documentation>
        </xs:annotation>
      </xs:element>
    </xs:all>
    <xs:attribute name="Zezwalaj" type="xs:boolean" use="required">
      <xs:annotation>
        <xs:documentation>Określa, czy dozwolone jest kredytowanie danego podmiotu.</xs:documentation>
      </xs:annotation>
    </xs:attribute>
  </xs:complexType>

  <xs:complexType name="TParametryPodmiotow">
    <xs:annotation>
      <xs:documentation>Parametry kartoteki klientów, m.in. szablony.</xs:documentation>
    </xs:annotation>
    <xs:all>
      <xs:element minOccurs="0" name="Parametry">
        <xs:annotation>
          <xs:documentation>Parametry kartoteki.</xs:documentation>
        </xs:annotation>

        <xs:complexType>
          <xs:sequence>
            <xs:element minOccurs="0" name="AutoNadawanieSymbolu" type="xs:boolean">
              <xs:annotation>
                <xs:documentation>Parametr decydujący o automatycznym nadawaniu symbolu w kartotece.</xs:documentation>
              </xs:annotation>
            </xs:element>
          </xs:sequence>
        </xs:complexType>

      </xs:element>
      
      <xs:element minOccurs="0" name="Szablony">
        <xs:annotation>
          <xs:documentation>Szablony klientów: firm i osób.</xs:documentation>
        </xs:annotation>
        <xs:complexType>
          <xs:sequence>
            <xs:element minOccurs="0" maxOccurs="unbounded" name="Szablon">
              <xs:annotation>
                <xs:documentation>Parametry szablonu klienta.</xs:documentation>
              </xs:annotation>
              <xs:complexType>
                <xs:all>
                  <xs:element name="Klient">
                    <xs:annotation>
                      <xs:documentation>Rodzaj klienta (standardowy, potencjalny)</xs:documentation>
                    </xs:annotation>
                    <xs:simpleType>
                      <xs:restriction base="xs:string">
                        <xs:enumeration value="S">
                          <xs:annotation>
                            <xs:documentation>Standardowy.</xs:documentation>
                          </xs:annotation>
                        </xs:enumeration>
                        <xs:enumeration value="P">
                          <xs:annotation>
                            <xs:documentation>Potencjalny klient.</xs:documentation>
                          </xs:annotation>
                        </xs:enumeration>
                      </xs:restriction>
                    </xs:simpleType>
                  </xs:element>
                  <xs:element minOccurs="0" name="Opiekun" type="xs:string">
                    <xs:annotation>
                      <xs:documentation>Symbol użytkownika będącego opiekunem klienta.</xs:documentation>
                    </xs:annotation>
                  </xs:element>

                  <xs:element minOccurs="0" name="KodPocztowy" type="xs:string">
                    <xs:annotation>
                      <xs:documentation>Kod pocztowy.</xs:documentation>
                    </xs:annotation>
                  </xs:element>
                  <xs:element minOccurs="0" name="Miejscowosc" type="xs:string">
                    <xs:annotation>
                      <xs:documentation>Nazwa miejscowości.</xs:documentation>
                    </xs:annotation>
                  </xs:element>
                  <xs:element minOccurs="0" name="Wojewodztwo" type="xs:string">
                    <xs:annotation>
                      <xs:documentation>Nazwa województwa.</xs:documentation>
                    </xs:annotation>
                  </xs:element>
                  <xs:element minOccurs="0" name="Panstwo" type="xs:string">
                    <xs:annotation>
                      <xs:documentation>Nazwa państwa.</xs:documentation>
                    </xs:annotation>
                  </xs:element>
                  <xs:element minOccurs="0" name="Region" type="xs:string">
                    <xs:annotation>
                      <xs:documentation>Nazwa regionu, do którego będzie należeć podmiot utworzony z szablonu.</xs:documentation>
                    </xs:annotation>
                  </xs:element>                  

                  <xs:element minOccurs="0" name="Grupa" type="xs:string">
                    <xs:annotation>
                      <xs:documentation>Nazwa grupy, do której będzie należeć podmiot utworzony z szablonu. Pusty element oznacza brak przypisania do grupy.</xs:documentation>
                    </xs:annotation>
                  </xs:element>
                  <xs:element minOccurs="0" name="Cechy">
                    <xs:annotation>
                      <xs:documentation>Kolekcja przypisanych cech.</xs:documentation>
                    </xs:annotation>
                    <xs:complexType>
                      <xs:sequence>
                        <xs:element minOccurs="0" maxOccurs="unbounded" name="Cecha" type="xs:string">
                          <xs:annotation>
                            <xs:documentation>Nazwa cechy.</xs:documentation>
                          </xs:annotation>
                        </xs:element>
                      </xs:sequence>
                    </xs:complexType>
                  </xs:element>

                  <xs:element minOccurs="0" name="Cennik" type="xs:string">
                    <xs:annotation>
                      <xs:documentation>Symbol przypisanego cennika głównego.</xs:documentation>
                    </xs:annotation>
                  </xs:element>
                  <xs:element minOccurs="0" name="Rabat" type="xs:string">
                    <xs:annotation>
                      <xs:documentation>Nazwa przypisanego rabatu.</xs:documentation>
                    </xs:annotation>
                  </xs:element>
                  <xs:element minOccurs="0" name="Kredyt" type="TKredytKupiecki">
                    <xs:annotation>
                      <xs:documentation>Określa parametry kredytowania kupieckiego dla kontrahenta.</xs:documentation>
                    </xs:annotation>
                  </xs:element>
                </xs:all>
                <xs:attribute name="Typ" use="required">
                  <xs:annotation>
                    <xs:documentation>Typ podmiotu (osoba, firma).</xs:documentation>
                  </xs:annotation>
                  <xs:simpleType>
                    <xs:restriction base="xs:string">
                      <xs:enumeration value="Osoba">
                        <xs:annotation>
                          <xs:documentation>Podmiot jest osobą.</xs:documentation>
                        </xs:annotation>
                      </xs:enumeration>
                      <xs:enumeration value="Firma">
                        <xs:annotation>
                          <xs:documentation>Podmiot jest firmą.</xs:documentation>
                        </xs:annotation>
                      </xs:enumeration>
                    </xs:restriction>
                  </xs:simpleType>
                </xs:attribute>
              </xs:complexType>
            </xs:element>
          </xs:sequence>
        </xs:complexType>
      </xs:element>
            
      <xs:element minOccurs="0" name="Wlasne">
        <xs:annotation>
          <xs:documentation>Definicje standardowych pól własnych dla podmiotów.</xs:documentation>
        </xs:annotation>
        <xs:complexType>
          <xs:sequence>
            <xs:element minOccurs="0" maxOccurs="unbounded" name="Pole" type="xs:string">
              <xs:annotation>
                <xs:documentation>Nazwa standardowego pola własnego.</xs:documentation>
              </xs:annotation>
            </xs:element>
          </xs:sequence>
        </xs:complexType>
      </xs:element>

      <xs:element minOccurs="0" name="WlasneRozszerzone">
        <xs:annotation>
          <xs:documentation>Definicje rozszerzonych pól własnych dla podmiotów.</xs:documentation>
        </xs:annotation>
        <xs:complexType>
          <xs:sequence>
            <xs:element minOccurs="0" maxOccurs="unbounded" name="PoleRozszerzone" type="wspolne:TPoleWlasneRozszerzone">
              <xs:annotation>
                <xs:documentation>Definicja pola własnego rozszerzonego.</xs:documentation>
              </xs:annotation>
            </xs:element>
          </xs:sequence>
        </xs:complexType>
      </xs:element>
    </xs:all>
  </xs:complexType>

  <xs:element name="ParametryPodmiotow" type="TParametryPodmiotow">
    <xs:annotation>
      <xs:documentation>Parametry kartoteki klientów.</xs:documentation>
    </xs:annotation>
  </xs:element>
</xs:schema>
