<?xml version="1.0" encoding="utf-8"?>
<xs:schema attributeFormDefault="unqualified"
           elementFormDefault="qualified"
           targetNamespace="http://schemas.insert.com.pl/2014/hop/parametryprocesowofertowych"
           xmlns="http://schemas.insert.com.pl/2014/hop/parametryprocesowofertowych"
           xmlns:w="http://schemas.insert.com.pl/2013/hop"
           xmlns:xs="http://www.w3.org/2001/XMLSchema">

  <xs:annotation>
    <xs:documentation>Parametry procesów ofertowych.</xs:documentation>
  </xs:annotation>

  <xs:import id="WspolnePart" namespace="http://schemas.insert.com.pl/2013/hop" schemaLocation="Wspolne.xsd"/>

  <xs:complexType name="TParametryProcesowOfertowych">
    <xs:annotation>
      <xs:documentation>Parametry procesów ofertowych.</xs:documentation>
    </xs:annotation>
    <xs:sequence>
      <xs:element name="Scenariusz" type="xs:string" minOccurs="0">
        <xs:annotation>
          <xs:documentation>Nazwa domyslnego scenariusza procesu ofertowego.</xs:documentation>
        </xs:annotation>
      </xs:element>
      <xs:element name="Kategoria" type="xs:string" minOccurs="0">
        <xs:annotation>
          <xs:documentation>Nazwa domyślnej kategorii procesu ofertowego.</xs:documentation>
        </xs:annotation>
      </xs:element>
      <xs:element name="PlanowanyCzasTrwania" minOccurs="0">
        <xs:annotation>
          <xs:documentation>Planowany czas trwania procesu ofertowego.</xs:documentation>
        </xs:annotation>
        <xs:complexType>
          <xs:sequence>
            <xs:element name="Wartosc" type="xs:int">
              <xs:annotation>
                <xs:documentation>Wartość.</xs:documentation>
              </xs:annotation>
            </xs:element>
            <xs:element name="OkresCzasu" type="TOkresCzasuDlaProcesu">
              <xs:annotation>
                <xs:documentation>Jednostka czasu.</xs:documentation>
              </xs:annotation>
            </xs:element>
          </xs:sequence>
        </xs:complexType>
      </xs:element>
      <xs:element name="PokazWKalendarzu" type="xs:boolean" minOccurs="0">
        <xs:annotation>
          <xs:documentation>Określa, czy proces ofertowy będzie wyświetlany w kalendarzu.</xs:documentation>
        </xs:annotation>
      </xs:element>
      <xs:element name="KolorWKalendarzu" type="xs:string" minOccurs="0">
        <xs:annotation>
          <xs:documentation>Określa kolor w jakim proces ofertowy będzie wyświetlany w kalendarzu.</xs:documentation>
        </xs:annotation>
      </xs:element>
      <xs:element name="TerminRealizacji" type="xs:string" minOccurs="0">
        <xs:annotation>
          <xs:documentation>Termin realizacji.</xs:documentation>
        </xs:annotation>
      </xs:element>
      <xs:element name="WarunkiPlatnosci" type="xs:string" minOccurs="0">
        <xs:annotation>
          <xs:documentation>Warunki płatności.</xs:documentation>
        </xs:annotation>
      </xs:element>
      <xs:element name="WarunkiDostawy" type="xs:string" minOccurs="0">
        <xs:annotation>
          <xs:documentation>Warunki dostawy.</xs:documentation>
        </xs:annotation>
      </xs:element>
      <xs:element name="UwagiNaDokument" type="xs:string" minOccurs="0">
        <xs:annotation>
          <xs:documentation>Uwagi na dokument.</xs:documentation>
        </xs:annotation>
      </xs:element>
      <xs:element name="OkreslajGodzine" type="xs:boolean" minOccurs="0">
        <xs:annotation>
          <xs:documentation>Uwagi na dokument.</xs:documentation>
        </xs:annotation>
      </xs:element>
      <xs:element minOccurs="0" name="WlasneRozszerzone">
        <xs:annotation>
          <xs:documentation>Definicje rozszerzonych pól własnych dla proceu ofertowego.</xs:documentation>
        </xs:annotation>
        <xs:complexType>
          <xs:sequence>
            <xs:element minOccurs="0" maxOccurs="unbounded" name="PoleRozszerzone" type="w:TPoleWlasneRozszerzone">
              <xs:annotation>
                <xs:documentation>Definicja pola własnego rozszerzonego.</xs:documentation>
              </xs:annotation>
            </xs:element>
          </xs:sequence>
        </xs:complexType>
      </xs:element>
    </xs:sequence>
  </xs:complexType>

  <xs:element name="ParametryProcesowOfertowych" type="TParametryProcesowOfertowych">
    <xs:annotation>
      <xs:documentation>Parametry procesów ofertowych.</xs:documentation>
    </xs:annotation>
  </xs:element>

  <xs:simpleType name="TOkresCzasuDlaProcesu">
    <xs:restriction base="xs:string">
      <xs:enumeration value="Dzien" />
      <xs:enumeration value="Tydzien" />
      <xs:enumeration value="Miesiac" />
    </xs:restriction>
  </xs:simpleType>
  
</xs:schema>
