<?xml version="1.0" encoding="utf-8"?>
<xs:schema elementFormDefault="qualified"
           targetNamespace="http://schemas.insert.com.pl/2013/hop/rachunkibankowe"
           xmlns="http://schemas.insert.com.pl/2013/hop/rachunkibankowe"
           xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:annotation>
    <xs:documentation>Rachunki bankowe podmiotu.</xs:documentation>
  </xs:annotation>
  <xs:complexType name="TRachunekBankowy">
    <xs:annotation>
      <xs:documentation>Dane rachunku bankowego.</xs:documentation>
    </xs:annotation>
    <xs:sequence>
      <xs:annotation>
        <xs:documentation>Dane rachunku bankowego.</xs:documentation>
      </xs:annotation>
      <xs:element name="Nazwa" type="xs:string">
        <xs:annotation>
          <xs:documentation>Nazwa.</xs:documentation>
        </xs:annotation>
      </xs:element>
      <xs:element name="Numer" type="xs:string">
        <xs:annotation>
          <xs:documentation>Numer.</xs:documentation>
        </xs:annotation>
      </xs:element>
      <xs:element name="Bank" type="xs:string">
        <xs:annotation>
          <xs:documentation>Nazwa banku.</xs:documentation>
        </xs:annotation>
      </xs:element>
      <xs:element name="Waluta" type="xs:string">
        <xs:annotation>
          <xs:documentation>Symbol waluty.</xs:documentation>
        </xs:annotation>
      </xs:element>
      <xs:element name="Saldo" type="xs:decimal" minOccurs="0">
        <xs:annotation>
          <xs:documentation>Saldo.</xs:documentation>
        </xs:annotation>
      </xs:element>
      <xs:element name="NumerRachunkuVAT" type="xs:string" minOccurs="0">
        <xs:annotation>
          <xs:documentation>Numer rachunku VAT.</xs:documentation>
        </xs:annotation>
      </xs:element>
    </xs:sequence>
    <xs:attribute name="Podstawowy" type="xs:boolean" use="optional">
      <xs:annotation>
        <xs:documentation>Określa, czy jest to podstawowy rachunek bankowy.</xs:documentation>
      </xs:annotation>
    </xs:attribute>
    <xs:attribute name="JestRachunkiemVAT" type="xs:boolean" use="optional">
      <xs:annotation>
        <xs:documentation>Określa, czy rachunek bankowy jest rachunkiem VAT.</xs:documentation>
      </xs:annotation>
    </xs:attribute>
  </xs:complexType>

  <xs:complexType name="TRachunekBankowyKlienta">
    <xs:annotation>
      <xs:documentation>Dane rachunku bankowego klienta.</xs:documentation>
    </xs:annotation>
    <xs:sequence>
      <xs:annotation>
        <xs:documentation>Dane rachunku bankowego klienta.</xs:documentation>
      </xs:annotation>
      <xs:element name="Nazwa" type="xs:string">
        <xs:annotation>
          <xs:documentation>Nazwa.</xs:documentation>
        </xs:annotation>
      </xs:element>
      <xs:element name="Numer" type="xs:string">
        <xs:annotation>
          <xs:documentation>Numer.</xs:documentation>
        </xs:annotation>
      </xs:element>
      <xs:element name="Waluta" type="xs:string" minOccurs="0">
        <xs:annotation>
          <xs:documentation>Symbol waluty.</xs:documentation>
        </xs:annotation>
      </xs:element>
    </xs:sequence>
    <xs:attribute name="Podstawowy" type="xs:boolean" use="optional">
      <xs:annotation>
        <xs:documentation>Określa, czy jest to podstawowy rachunek bankowy.</xs:documentation>
      </xs:annotation>
    </xs:attribute>
    <xs:attribute name="Usuniety" type="xs:boolean" use="optional">
      <xs:annotation>
        <xs:documentation>Określa, czy rachunek został usunięty.</xs:documentation>
      </xs:annotation>
    </xs:attribute>
  </xs:complexType>

  <xs:complexType name="TRachunkiBankowe">
    <xs:annotation>
      <xs:documentation>Rachunki bankowe podmiotu.</xs:documentation>
    </xs:annotation>
    <xs:sequence>
      <xs:annotation>
        <xs:documentation>Kolekcja rachunków bankowych podmiotu.</xs:documentation>
      </xs:annotation>
      <xs:element name="RachunekBankowy" maxOccurs="unbounded" minOccurs="0" type="TRachunekBankowy">
        <xs:annotation>
          <xs:documentation>Rachunek bankowy.</xs:documentation>
        </xs:annotation>
      </xs:element>
    </xs:sequence>
  </xs:complexType>

  <xs:element name="RachunkiBankowe" type="TRachunkiBankowe">
    <xs:annotation>
      <xs:documentation>Rachunki bankowe podmiotu.</xs:documentation>
    </xs:annotation>
  </xs:element>
</xs:schema>