<?xml version="1.0" encoding="utf-8"?>
<xs:schema elementFormDefault="qualified"
           targetNamespace="http://schemas.insert.com.pl/2014/hop/rozrachunki"
           xmlns="http://schemas.insert.com.pl/2014/hop/rozrachunki"
           xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:annotation>
    <xs:documentation>Informacje o nierozliczonych rozrachunkach.</xs:documentation>
  </xs:annotation>
  <xs:simpleType name="TRodzajRozrachunku">
    <xs:annotation>
      <xs:documentation>Określa rodzaj rozrachunku.</xs:documentation>
    </xs:annotation>
    <xs:restriction base="xs:string">
      <xs:enumeration value="NAL">
        <xs:annotation>
          <xs:documentation>Należność.</xs:documentation>
        </xs:annotation>
      </xs:enumeration>
      <xs:enumeration value="ZOB">
        <xs:annotation>
          <xs:documentation>Zobowiązanie</xs:documentation>
        </xs:annotation>
      </xs:enumeration>
      <xs:enumeration value="SNAL">
        <xs:annotation>
          <xs:documentation>Spłata należności</xs:documentation>
        </xs:annotation>
      </xs:enumeration>
      <xs:enumeration value="SZOB">
        <xs:annotation>
          <xs:documentation>Spłata zobowiązania</xs:documentation>
        </xs:annotation>
      </xs:enumeration>
      <xs:enumeration value="NAL(O)">
        <xs:annotation>
          <xs:documentation>Należność z tytułu odsetek, kar itp.</xs:documentation>
        </xs:annotation>
      </xs:enumeration>
      <xs:enumeration value="ZOB(O)">
        <xs:annotation>
          <xs:documentation>Zobowiązanie z tytułu odsetek, kar itp.</xs:documentation>
        </xs:annotation>
      </xs:enumeration>
      <xs:enumeration value="NAL(K)">
        <xs:annotation>
          <xs:documentation>Korekta zmniejszająca zobowiązanie.</xs:documentation>
        </xs:annotation>
      </xs:enumeration>
      <xs:enumeration value="ZOB(K)">
        <xs:annotation>
          <xs:documentation>Korekta zmniejszająca należność.</xs:documentation>
        </xs:annotation>
      </xs:enumeration>
      <xs:enumeration value="RD">
        <xs:annotation>
          <xs:documentation>Dodatnia różnica kursowa.</xs:documentation>
        </xs:annotation>
      </xs:enumeration>
      <xs:enumeration value="RU">
        <xs:annotation>
          <xs:documentation>Ujemna różnica kursowa.</xs:documentation>
        </xs:annotation>
      </xs:enumeration>
    </xs:restriction>
  </xs:simpleType>

  <xs:simpleType name="TTypOdsetek">
    <xs:annotation>
      <xs:documentation>Określa typ odsetek.</xs:documentation>
    </xs:annotation>
    <xs:restriction base="xs:string">
      <xs:enumeration value="brak">
        <xs:annotation>
          <xs:documentation>Brak odsetek.</xs:documentation>
        </xs:annotation>
      </xs:enumeration>
      <xs:enumeration value="ustawowe">
        <xs:annotation>
          <xs:documentation>Odsetki ustawowe.</xs:documentation>
        </xs:annotation>
      </xs:enumeration>
      <xs:enumeration value="krotność ustawowych">
        <xs:annotation>
          <xs:documentation>Krotność odsetek ustawowych.</xs:documentation>
        </xs:annotation>
      </xs:enumeration>
      <xs:enumeration value="wg stopy własnej">
        <xs:annotation>
          <xs:documentation>Odsetki wg ustalonej stopy.</xs:documentation>
        </xs:annotation>
      </xs:enumeration>
    </xs:restriction>
  </xs:simpleType>

  <xs:simpleType name="TStronaKwotyPozycjiDokumentuKsiegowego">
    <xs:annotation>
      <xs:documentation>Strona (Winien lub Ma) pozycji dokumentu księgowego.</xs:documentation>
    </xs:annotation>
    <xs:restriction base="xs:string">
      <xs:enumeration value="Wn">
        <xs:annotation>
          <xs:documentation>Winien.</xs:documentation>
        </xs:annotation>
      </xs:enumeration>
      <xs:enumeration value="Ma">
        <xs:annotation>
          <xs:documentation>Ma.</xs:documentation>
        </xs:annotation>
      </xs:enumeration>
    </xs:restriction>
  </xs:simpleType>

  <xs:complexType name="TRozrachunek">
    <xs:annotation>
      <xs:documentation>Dane nierozliczonego rozrachunku.</xs:documentation>
    </xs:annotation>
    <xs:all>
      <xs:element type="xs:date" name="DataPowstania">
        <xs:annotation>
          <xs:documentation>Data powstania rozrachunku.</xs:documentation>
        </xs:annotation>
      </xs:element>
      <xs:element type="xs:date" name="DataDokumentu">
        <xs:annotation>
          <xs:documentation>Data dokumentu źródłowego.</xs:documentation>
        </xs:annotation>
      </xs:element>
      <xs:element type="xs:string" name="Dokument">
        <xs:annotation>
          <xs:documentation>Numer dokumentu źródłowego.</xs:documentation>
        </xs:annotation>
      </xs:element>
      <xs:element type="xs:string" name="Tytulem" minOccurs="0">
        <xs:annotation>
          <xs:documentation>Tytuł rozrachunku.</xs:documentation>
        </xs:annotation>
      </xs:element>
      <xs:element type="xs:string" name="Podmiot">
        <xs:annotation>
          <xs:documentation>Symbol podmiotu.</xs:documentation>
        </xs:annotation>
      </xs:element>
      <xs:element type="xs:decimal" name="Kwota">
        <xs:annotation>
          <xs:documentation>Kwota rozrachunku.</xs:documentation>
        </xs:annotation>
      </xs:element>
      <xs:element type="xs:decimal" name="KwotaPozostala">
        <xs:annotation>
          <xs:documentation>Kwota pozostała do rozliczenia. Wartość musi być równa różnicy kwoty rozrachunku i sumy rozliczeń.</xs:documentation>
        </xs:annotation>
      </xs:element>
      <xs:element type="xs:decimal" name="KwotaVAT" minOccurs="0" maxOccurs="1">
        <xs:annotation>
          <xs:documentation>Kwota VAT rozrachunku.</xs:documentation>
        </xs:annotation>
      </xs:element>
      <xs:element type="xs:decimal" name="KwotaVATPozostala" minOccurs="0" maxOccurs="1">
        <xs:annotation>
          <xs:documentation>Kwota VAT pozostała do rozliczenia. Wartość musi być równa różnicy kwoty VAT rozrachunku i sumy rozliczeń.</xs:documentation>
        </xs:annotation>
      </xs:element>
      <xs:element type="xs:string" name="Waluta">
        <xs:annotation>
          <xs:documentation>Symbol waluty rozrachunku.</xs:documentation>
        </xs:annotation>
      </xs:element>
      <xs:element type="xs:decimal" name="Kurs" minOccurs="0" maxOccurs="1">
        <xs:annotation>
          <xs:documentation>Kurs do waluty systemowej (nie trzeba podawać dla waluty systemowej).</xs:documentation>
        </xs:annotation>
      </xs:element>
      <xs:element type="xs:date" name="TerminPlatnosci" minOccurs="0">
        <xs:annotation>
          <xs:documentation>Termin płatności rozrachunku. Można go podać tylko wtedy, gdy rodzaj rozrachunku pozwala na windykację.</xs:documentation>
        </xs:annotation>
      </xs:element>
      <xs:element name="Odsetki">
        <xs:annotation>
          <xs:documentation>Informacje o sposobie naliczania odsetek.</xs:documentation>
        </xs:annotation>
        <xs:complexType>
          <xs:attribute name="RodzajOdsetek" type="TTypOdsetek">
            <xs:annotation>
              <xs:documentation>Rodzaj odsetek.</xs:documentation>
            </xs:annotation>
          </xs:attribute>
          <xs:attribute name="StopaOdsetek" type="xs:string" use="optional">
            <xs:annotation>
              <xs:documentation>Stopa odsetek (jeśli rodzaj jej wymaga).</xs:documentation>
            </xs:annotation>
          </xs:attribute>
        </xs:complexType>
      </xs:element>
      <xs:element name="HistoriaRozliczen" minOccurs="0">
        <xs:annotation>
          <xs:documentation>Historia rozliczeń rozrachunku.</xs:documentation>
        </xs:annotation>
        <xs:complexType>
          <xs:sequence>
            <xs:element name="Rozliczenie" minOccurs="0" maxOccurs="unbounded">
              <xs:annotation>
                <xs:documentation>Historia rozliczeń rozrachunku.</xs:documentation>
              </xs:annotation>
              <xs:complexType>
                <xs:annotation>
                  <xs:documentation>Dane rozliczenia.</xs:documentation>
                </xs:annotation>
                <xs:all>
                  <xs:element type="TRodzajRozrachunku" name="Rodzaj">
                    <xs:annotation>
                      <xs:documentation>Rodzaj rozrachunku.</xs:documentation>
                    </xs:annotation>
                  </xs:element>
                  <xs:element type="xs:date" name="DataPowstania">
                    <xs:annotation>
                      <xs:documentation>Data powstania rozrachunku.</xs:documentation>
                    </xs:annotation>
                  </xs:element>
                  <xs:element type="xs:date" name="DataDokumentu">
                    <xs:annotation>
                      <xs:documentation>Data dokumentu źródłowego.</xs:documentation>
                    </xs:annotation>
                  </xs:element>
                  <xs:element type="xs:string" name="Dokument">
                    <xs:annotation>
                      <xs:documentation>Numer dokumentu źródłowego.</xs:documentation>
                    </xs:annotation>
                  </xs:element>
                  <xs:element type="xs:decimal" name="Kwota">
                    <xs:annotation>
                      <xs:documentation>Kwota rozliczenia.</xs:documentation>
                    </xs:annotation>
                  </xs:element>
                  <xs:element type="xs:decimal" name="KwotaVAT" minOccurs="0" maxOccurs="1">
                    <xs:annotation>
                      <xs:documentation>Kwota VAT rozliczenia.</xs:documentation>
                    </xs:annotation>
                  </xs:element>
                </xs:all>
              </xs:complexType>
            </xs:element>
          </xs:sequence>
        </xs:complexType>
      </xs:element>
      <xs:element name="BilansOtwarcia" minOccurs="0" maxOccurs="1">
        <xs:annotation>
          <xs:documentation>Dane powiązania z bilansem otwarcia.</xs:documentation>
        </xs:annotation>
        <xs:complexType>
          <xs:all>
            <xs:element name="Konto" type="xs:string" minOccurs="1" maxOccurs="1" nillable="false">
              <xs:annotation>
                <xs:documentation>Numer konta księgowego powiązanego zapisu w bilansie otwarcia okresu obrachunkowego.</xs:documentation>
              </xs:annotation>
            </xs:element>
            <xs:element name="Strona" type="TStronaKwotyPozycjiDokumentuKsiegowego" minOccurs="1" maxOccurs="1" nillable="false">
              <xs:annotation>
                <xs:documentation>Numer konta księgowego powiązanego zapisu w bilansie otwarcia okresu obrachunkowego.</xs:documentation>
              </xs:annotation>
            </xs:element>
            <xs:element name="Kwota" type="xs:decimal" minOccurs="1" maxOccurs="1" nillable="false">
              <xs:annotation>
                <xs:documentation>Kwota pozycji bilansu otwarcia okresu obrachunkowego.</xs:documentation>
              </xs:annotation>
            </xs:element>
          </xs:all>
        </xs:complexType>
      </xs:element>
      <xs:element name="FlagaWlasna" minOccurs="0">
        <xs:annotation>
          <xs:documentation>Dane flagi własnej.</xs:documentation>
        </xs:annotation>
        <xs:complexType>
          <xs:all>
            <xs:element minOccurs="1" maxOccurs="1" name="Kolor" type="xs:string">
              <xs:annotation>
                <xs:documentation>Kolor flagi własnej.</xs:documentation>
              </xs:annotation>
            </xs:element>
            <xs:element minOccurs="0" maxOccurs="1" name="Ksztalt" type="xs:string">
              <xs:annotation>
                <xs:documentation>Kształt flagi własnej.</xs:documentation>
              </xs:annotation>
            </xs:element>
            <xs:element minOccurs="0" maxOccurs="1" name="Komentarz" type="xs:string">
              <xs:annotation>
                <xs:documentation>Komentarz flagi własnej.</xs:documentation>
              </xs:annotation>
            </xs:element>
          </xs:all>
        </xs:complexType>
      </xs:element>
    </xs:all>
    <xs:attribute type="TRodzajRozrachunku" name="Rodzaj">
      <xs:annotation>
        <xs:documentation>Rodzaj rozrachunku.</xs:documentation>
      </xs:annotation>
    </xs:attribute>
    <xs:attribute name="TypPodmiotu" type="xs:string">
      <xs:annotation>
        <xs:documentation>Typ podmiotu.</xs:documentation>
      </xs:annotation>
    </xs:attribute>
    <xs:attribute name="Program" type="xs:string">
      <xs:annotation>
        <xs:documentation>Program, w którym został stworzony rozrachunek.</xs:documentation>
      </xs:annotation>
    </xs:attribute>
    <xs:attribute name="Ksiegowy" type="xs:boolean">
      <xs:annotation>
        <xs:documentation>Informacja, czy rozrachunek jest powiązany z zapisem księgowym.</xs:documentation>
      </xs:annotation>
    </xs:attribute>
  </xs:complexType>

  <xs:complexType name="TRozrachunki">
    <xs:annotation>
      <xs:documentation>Kolekcja nierozliczonych rozrachunków.</xs:documentation>
    </xs:annotation>
    <xs:sequence>
      <xs:element name="Rozrachunek" maxOccurs="unbounded" minOccurs="0" type="TRozrachunek">
        <xs:annotation>
          <xs:documentation>Nierozliczony rozrachunek.</xs:documentation>
        </xs:annotation>
      </xs:element>
    </xs:sequence>
  </xs:complexType>

  <xs:element name="Rozrachunki" type="TRozrachunki">
    <xs:annotation>
      <xs:documentation>Nierozliczone rozrachunki.</xs:documentation>
    </xs:annotation>
  </xs:element>
</xs:schema>
