<?xml version="1.0" encoding="utf-8"?>
<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified"
    targetNamespace="http://schemas.insert.com.pl/2015/hop/SprawozdaniaFinansowe"
    xmlns="http://schemas.insert.com.pl/2015/hop/SprawozdaniaFinansowe"
    xmlns:xs="http://www.w3.org/2001/XMLSchema"
>
  <xs:annotation>
    <xs:documentation>Informacje o sprawozdaniach finansowych.</xs:documentation>
  </xs:annotation>

  <xs:complexType name="TDefinicjaSkladnika">
    <xs:annotation>
      <xs:documentation>Definicja pojedynczego składnika.</xs:documentation>
    </xs:annotation>
    <xs:sequence>
      <xs:element name="NazwaPola" type="xs:string">
        <xs:annotation>
          <xs:documentation>Nazwa pola do którego jest przypisana funkcja w danym sprawozdaniu.</xs:documentation>
        </xs:annotation>
      </xs:element>
      <xs:element name="Funkcja" type="xs:string" minOccurs="0" maxOccurs="1">
        <xs:annotation>
          <xs:documentation>funkcja wykonywana na podanym koncie.</xs:documentation>
          <xs:appinfo>SalodWn(020-1)</xs:appinfo>
        </xs:annotation>
      </xs:element>

      <xs:element name="Dodac" type="xs:boolean" minOccurs="0" maxOccurs="1">
        <xs:annotation>
          <xs:documentation>True - Dodać wynik funkcji, False - Odjąć wynik funkcji.</xs:documentation>
        </xs:annotation>
      </xs:element>

      <!-- Hierarchia składników -->

      <xs:element name="Level" type="xs:int" minOccurs="1" maxOccurs="1">
        <xs:annotation>
          <xs:documentation>Głębokość zagnieżdżenia w strukturze liczona od 1</xs:documentation>
        </xs:annotation>
      </xs:element>

      <xs:element name="Id" type="xs:string" minOccurs="1" maxOccurs="1">
        <xs:annotation>
          <xs:documentation>Unikalne Id w strukturze pojedynczego sprawozdania</xs:documentation>
        </xs:annotation>
      </xs:element>

      <xs:element name="Rodzic" type="xs:string" minOccurs="0" maxOccurs="1">
        <xs:annotation>
          <xs:documentation>Id elementu nadrzędnego.</xs:documentation>
        </xs:annotation>
      </xs:element>

      <xs:element name="Lisc" type="xs:boolean" minOccurs="1" maxOccurs="1">
        <xs:annotation>
          <xs:documentation>Liść w strukturze</xs:documentation>
        </xs:annotation>
      </xs:element>
      
    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="TSkladnikiDefSF">
    <xs:sequence>
      <xs:element name="Skladnik" minOccurs="0" maxOccurs="unbounded" type="TDefinicjaSkladnika">
        <xs:annotation>
          <xs:documentation>Dane składnika pola sprawozdania finansowego.</xs:documentation>
        </xs:annotation>
      </xs:element>
    </xs:sequence>
  </xs:complexType>
  
  <xs:complexType name="TDefinicjaSprawozdaniaFinansowego">
    <xs:annotation>
      <xs:documentation>Dane sprawozdania finansowego.</xs:documentation>
    </xs:annotation>
    <xs:sequence>
      <xs:element name="Nazwa" type="xs:string">
        <xs:annotation>
          <xs:documentation>Nazwa sprawozdania</xs:documentation>
        </xs:annotation>
      </xs:element>
      <xs:element name="Skladniki" type="TSkladnikiDefSF">
        <xs:annotation>
          <xs:documentation>Składniki Pola sprawozdania finansowego.</xs:documentation>
        </xs:annotation>
      </xs:element>
    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="TDefinicjeSprawozdanFinansowych">
    <xs:annotation>
      <xs:documentation>Dane sprawozdań finansowych.</xs:documentation>
    </xs:annotation>
    <xs:sequence>
      <xs:element name="Sprawozdanie" minOccurs="0" maxOccurs="unbounded" type="TDefinicjaSprawozdaniaFinansowego">
        <xs:annotation>
          <xs:documentation>Dane sprawozdania finansowego.</xs:documentation>
        </xs:annotation>
      </xs:element>
    </xs:sequence>
  </xs:complexType>
  
  <xs:element name="Sprawozdania" type="TDefinicjeSprawozdanFinansowych">
    <xs:annotation>
      <xs:documentation>Kolekcja sprawozdań finansowych.</xs:documentation>
    </xs:annotation>
  </xs:element>
</xs:schema>
