<?xml version="1.0" encoding="utf-8"?>
<xs:schema attributeFormDefault="unqualified"
           elementFormDefault="qualified"
           targetNamespace="http://schemas.insert.com.pl/2014/hop/szablonydzialan"
           xmlns="http://schemas.insert.com.pl/2014/hop/szablonydzialan"
           xmlns:xs="http://www.w3.org/2001/XMLSchema"
           xmlns:td="http://schemas.insert.com.pl/2014/hop/typydzialan"
           xmlns:d="http://schemas.insert.com.pl/2014/hop/dzialania">

  <xs:import schemaLocation="TypyDzialan.xsd" namespace="http://schemas.insert.com.pl/2014/hop/typydzialan" />
  <xs:import schemaLocation="Dzialania.xsd" namespace="http://schemas.insert.com.pl/2014/hop/dzialania" />

  <xs:annotation>
    <xs:documentation>Szablony działań.</xs:documentation>
  </xs:annotation>

  <xs:complexType name="TSzablonDzialania">
    <xs:sequence>
      <xs:element name="Typ" type="xs:string">
        <xs:annotation>
          <xs:documentation>Typ działania.</xs:documentation>
        </xs:annotation>
      </xs:element>
      <xs:element name="Domyslny" type="xs:boolean" minOccurs="0">
        <xs:annotation>
          <xs:documentation>Ustawia szablon jako szablon domyslny dla typu.</xs:documentation>
        </xs:annotation>
      </xs:element>
      <xs:element name="Nazwa" type="xs:string">
        <xs:annotation>
          <xs:documentation>Nazwa szablonu.</xs:documentation>
        </xs:annotation>
      </xs:element>
      <xs:element name="Temat" type="xs:string" minOccurs="0">
        <xs:annotation>
          <xs:documentation>Temat działania.</xs:documentation>
        </xs:annotation>
      </xs:element>
      <xs:element name="Rodzaj" type="xs:string" minOccurs="0">
        <xs:annotation>
          <xs:documentation>Rodzaj działania opisujący na wyższym poziomie szczegółowości typ działania.</xs:documentation>
        </xs:annotation>
      </xs:element>
      <xs:element name="Klasa" type="d:TKlasaDzialania" minOccurs="0">
        <xs:annotation>
          <xs:documentation>Klasa działania z Gestora GT.</xs:documentation>
        </xs:annotation>
      </xs:element>
      <xs:element name="Kierunek" type="td:TKierunekDzialania" minOccurs="0">
        <xs:annotation>
          <xs:documentation>Kierunek działania.</xs:documentation>
        </xs:annotation>
      </xs:element>
      <xs:element name="Lokalizacja" type="xs:string" minOccurs="0">
        <xs:annotation>
          <xs:documentation>Lokalizacja działania.</xs:documentation>
        </xs:annotation>
      </xs:element>
      <xs:element name="NieOkreslajCzasu" type="xs:boolean" minOccurs="0">
        <xs:annotation>
          <xs:documentation>Określa, czy działanie będzie miało datę początku i końca.</xs:documentation>
        </xs:annotation>
      </xs:element>
      <xs:element name="Calodzienne" type="xs:boolean" minOccurs="0">
        <xs:annotation>
          <xs:documentation>Określa, czy działanie jest całodzienne.</xs:documentation>
        </xs:annotation>
      </xs:element>
      <xs:element name="PlanowanyPoczatek" type="TPlanowanyPoczatekDzialania" minOccurs="0">
        <xs:annotation>
          <xs:documentation>Planowany początek działania.</xs:documentation>
        </xs:annotation>
      </xs:element>
      <xs:element name="CzasTrwania" type="xs:int" minOccurs="0">
        <xs:annotation>
          <xs:documentation>Czas trwania w minutach.</xs:documentation>
        </xs:annotation>
      </xs:element>
      <xs:element name="Wykonawca" type="TWykonawcaWSzablonie" minOccurs="0">
        <xs:annotation>
          <xs:documentation>Osoba zajmująca się działaniem.</xs:documentation>
        </xs:annotation>
      </xs:element>
      <xs:element name="Priorytet" type="d:TPriorytetDzialania">
        <xs:annotation>
          <xs:documentation>Priorytet działania.</xs:documentation>
        </xs:annotation>
      </xs:element>
      <xs:element name="PokazujWKalendarzu" type="xs:boolean" minOccurs="0">
        <xs:annotation>
          <xs:documentation>Określa, czy działanie będzie widoczne w kalendarzu.</xs:documentation>
        </xs:annotation>
      </xs:element>
      <xs:element name="KolorWKalendarzu" type="xs:string" minOccurs="0">
        <xs:annotation>
          <xs:documentation>Określa kolor jaki będzie charakteryzował działanie.</xs:documentation>
        </xs:annotation>
      </xs:element>
      <xs:element name="Przypomnienie" type="xs:int" minOccurs="0">
        <xs:annotation>
          <xs:documentation>Określa ile minut przed działaniem pojawi sie przypomnienie informujące o jego początku.</xs:documentation>
        </xs:annotation>
      </xs:element>
      <xs:element name="Prywatne" type="xs:boolean" minOccurs="0">
        <xs:annotation>
          <xs:documentation>Określa, czy działanie jest widoczne tylko dla twórcy oraz kierownika.</xs:documentation>
        </xs:annotation>
      </xs:element>
      <xs:element name="StopienRealizacji" type="xs:string" minOccurs="0">
        <xs:annotation>
          <xs:documentation>Stopień realizacji działania.</xs:documentation>
        </xs:annotation>
      </xs:element>
      <xs:element name="Opis" type="xs:string" minOccurs="0">
        <xs:annotation>
          <xs:documentation>Opis działania.</xs:documentation>
        </xs:annotation>
      </xs:element>
      <xs:element name="OpisSzczegolowy" type="xs:string" minOccurs="0">
        <xs:annotation>
          <xs:documentation>Opis szczegółowy działania.</xs:documentation>
        </xs:annotation>
      </xs:element>
    </xs:sequence>
  </xs:complexType>

  <xs:element name="SzablonyDzialan">
    <xs:annotation>
      <xs:documentation>Szablony działań.</xs:documentation>
    </xs:annotation>
    <xs:complexType>
      <xs:sequence>
        <xs:element name="Szablon" type="TSzablonDzialania" minOccurs="0" maxOccurs="unbounded">
          <xs:annotation>
            <xs:documentation>Szablon działania.</xs:documentation>
          </xs:annotation>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>

  <xs:simpleType name="TPlanowanyPoczatekDzialania">
    <xs:annotation>
      <xs:documentation>Określa planowany początek działania.</xs:documentation>
    </xs:annotation>
    <xs:restriction base="xs:string">
      <xs:enumeration value="Dzis" />
      <xs:enumeration value="Jutro" />
      <xs:enumeration value="Pojutrze" />
      <xs:enumeration value="Tydzien pozniej" />
      <xs:enumeration value="Dwa tygodnie pozniej" />
      <xs:enumeration value="Cztery tygodnie pozniej" />
      <xs:enumeration value="Niedziela" />
      <xs:enumeration value="Poniedzialek" />
      <xs:enumeration value="Wtorek" />
      <xs:enumeration value="Sroda" />
      <xs:enumeration value="Czwartek" />
      <xs:enumeration value="Piatek" />
      <xs:enumeration value="Sobota" />
    </xs:restriction>
  </xs:simpleType>

  <xs:simpleType name="TTypWykonawcyWSzablonie">
    <xs:annotation>
      <xs:documentation>Typ wykonawcy działania.</xs:documentation>
    </xs:annotation>
    <xs:restriction base="xs:string">
      <xs:enumeration value="Brak">
        <xs:annotation>
          <xs:documentation>Brak domyślnego wykonawcy działania.</xs:documentation>
        </xs:annotation>
      </xs:enumeration>
      <xs:enumeration value="ZKontekstu">
        <xs:annotation>
          <xs:documentation>Osoba zalogowana jest domyślnym wykonawcą.</xs:documentation>
        </xs:annotation>
      </xs:enumeration>
      <xs:enumeration value="Okreslony">
        <xs:annotation>
          <xs:documentation>Wykonawca określany na podstawie podanej sygnatury.</xs:documentation>
        </xs:annotation>
      </xs:enumeration>
    </xs:restriction>
  </xs:simpleType>

  <xs:complexType name="TWykonawcaWSzablonie">
    <xs:annotation>
      <xs:documentation>Wykonawca działania.</xs:documentation>
    </xs:annotation>
    <xs:sequence>
      <xs:element name="Typ" type="TTypWykonawcyWSzablonie">
        <xs:annotation>
          <xs:documentation>Typ wykonawcy działania.</xs:documentation>
        </xs:annotation>
      </xs:element>
      <xs:element name="Sygnatura" type="xs:string" minOccurs="0" />
    </xs:sequence>
  </xs:complexType>

</xs:schema>