<?xml version="1.0" encoding="utf-8"?>
<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified"
           xmlns="http://schemas.insert.com.pl/2018/hop/towary"
           targetNamespace="http://schemas.insert.com.pl/2018/hop/towary"
           xmlns:wspolne="http://schemas.insert.com.pl/2013/hop"
           xmlns:xs="http://www.w3.org/2001/XMLSchema">

  <xs:import id="WspolnePart" namespace="http://schemas.insert.com.pl/2013/hop" schemaLocation="Wspolne.xsd"/>

  <xs:annotation>
    <xs:documentation>Dane kartoteki towarów, usług, opakowań i kompletów.</xs:documentation>
  </xs:annotation>
  <xs:complexType name="TTowarKontrahenta">
    <xs:annotation>
      <xs:documentation>Dane asortymentu dla kontrahenta.</xs:documentation>
    </xs:annotation>
    <xs:sequence>
      <xs:element name="Sygnatura" type="xs:string">
        <xs:annotation>
          <xs:documentation>Symbol kontrahenta.</xs:documentation>
        </xs:annotation>
      </xs:element>
      <xs:element minOccurs="0" name="SymbolAsortymentu" type="xs:string">
        <xs:annotation>
          <xs:documentation>Symbol asortymentu u kontrahenta.</xs:documentation>
        </xs:annotation>
      </xs:element>
      <xs:element minOccurs="0" name="SredniCzasDostawy" type="xs:int">
        <xs:annotation>
          <xs:documentation>Średni czas dostawy.</xs:documentation>
        </xs:annotation>
      </xs:element>
    </xs:sequence>
    <xs:attribute name="Podstawowy" type="xs:boolean" use="optional">
      <xs:annotation>
        <xs:documentation>Określa czy jest podstawowym dostawcą.</xs:documentation>
      </xs:annotation>
    </xs:attribute>
  </xs:complexType>

  <xs:complexType name="TDaneOplatyCukrowej">
    <xs:annotation>
      <xs:documentation>Dane do wyliczenia opłaty cukrowej.</xs:documentation>
    </xs:annotation>
    <xs:sequence>
      <xs:element name="PodlegaOplacieCukrowej" type="xs:boolean" minOccurs="1" maxOccurs="1">
        <xs:annotation>
          <xs:documentation>Parametr określający czy towar podlega opłacie cukrowej.</xs:documentation>
        </xs:annotation>
      </xs:element>
      <xs:element name="ZawartoscCukru" type="xs:decimal" minOccurs="1" maxOccurs="1">
        <xs:annotation>
          <xs:documentation>Zawartość cukru w gramach na litr napoju.</xs:documentation>
        </xs:annotation>
      </xs:element>
      <xs:element name="InneSubstancjeSlodzace" type="xs:boolean" minOccurs="1" maxOccurs="1">
        <xs:annotation>
          <xs:documentation>Parametr określający czy napój zawiera inne substancje słodzące.</xs:documentation>
        </xs:annotation>
      </xs:element>
      <xs:element name="Minimum20ProcentSoku" type="xs:boolean" minOccurs="1" maxOccurs="1">
        <xs:annotation>
          <xs:documentation>Parametr określający czy napój zawiera minumum 20% soku.</xs:documentation>
        </xs:annotation>
      </xs:element>
      <xs:element name="NapojWeglowodanowoElektrolityczny" type="xs:boolean" minOccurs="1" maxOccurs="1">
        <xs:annotation>
          <xs:documentation>Parametr określający czy napój jest węglowodanowo-elektrolityczny (izotonik).</xs:documentation>
        </xs:annotation>
      </xs:element>
      <xs:element name="PodlegaOplacieKofeinowej" type="xs:boolean" minOccurs="1" maxOccurs="1">
        <xs:annotation>
          <xs:documentation>Parametr określający czy towar podlega opłacie kofeinowej.</xs:documentation>
        </xs:annotation>
      </xs:element>
      <xs:element name="ObjetoscNapoju" type="xs:decimal" minOccurs="1" maxOccurs="1">
        <xs:annotation>
          <xs:documentation>Objętość napoju w litrach dla podstawowej jednostki miary.</xs:documentation>
        </xs:annotation>
      </xs:element>
    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="TMasa">
    <xs:annotation>
      <xs:documentation>Dane masy jednostki miary asortymentu.</xs:documentation>
    </xs:annotation>
    <xs:sequence>
      <xs:element name="Jednostka" type="xs:string">
        <xs:annotation>
          <xs:documentation>Symbol jednostki masy, np. kg.</xs:documentation>
        </xs:annotation>
      </xs:element>
      <xs:element name="Wartosc" type="xs:decimal">
        <xs:annotation>
          <xs:documentation>Masa w danej jednostce masy.</xs:documentation>
        </xs:annotation>
      </xs:element>      
    </xs:sequence>
  </xs:complexType>
  
  <xs:complexType name="TJednostkaMiary">
    <xs:annotation>
      <xs:documentation>Dane jednostki miary asortymentu.</xs:documentation>
    </xs:annotation>
    <xs:sequence>
      <xs:element name="Symbol" type="xs:string">
        <xs:annotation>
          <xs:documentation>Symbol jednostki miary asortymentu.</xs:documentation>
        </xs:annotation>
      </xs:element>
      <xs:element minOccurs="0" name="PodstKodKreskowy" type="xs:string">
        <xs:annotation>
          <xs:documentation>Podstawowy kod kreskowy dla jednostki miary danego asortymentu.</xs:documentation>
        </xs:annotation>
      </xs:element>
      <xs:element minOccurs="0" name="KodyKreskowe">
        <xs:annotation>
          <xs:documentation>Dodatkowe kody kreskowe dla jednostki miary danego asortymentu.</xs:documentation>
        </xs:annotation>
        <xs:complexType>
          <xs:sequence>
            <xs:element minOccurs="0" maxOccurs="unbounded" name="Kod" type="xs:string">
              <xs:annotation>
                <xs:documentation>Dodatkowy kod kreskowy dla jednostki miary danego asortymentu.</xs:documentation>
              </xs:annotation>
            </xs:element>
          </xs:sequence>
        </xs:complexType>
      </xs:element>
      <xs:element minOccurs="0" name="Precyzja" type="xs:int">
        <xs:annotation>
          <xs:documentation>Precyzja jednostki miary.</xs:documentation>
        </xs:annotation>
      </xs:element>
      <xs:element minOccurs="0" name="Opakowanie" type="xs:string">
        <xs:annotation>
          <xs:documentation>Symbol opakowania powiązanego z jednostką miary asortymentu.</xs:documentation>
        </xs:annotation>
      </xs:element>
      <xs:element minOccurs="0" name="NazwaDlaUf" type="xs:string">
        <xs:annotation>
          <xs:documentation>Nazwa towaru w danej jednostce dla urządzeń fiskalnych.</xs:documentation>
        </xs:annotation>
      </xs:element>
      <xs:element minOccurs="0" name="PLU" type="xs:string">
        <xs:annotation>
          <xs:documentation>PLU dla jednostki miary asortymentu.</xs:documentation>
        </xs:annotation>
      </xs:element>
      <xs:element minOccurs="0" name="WysylajNaUrz" type="xs:boolean">
        <xs:annotation>
          <xs:documentation>Czy informacje o danej jednostce miary asortymentu wysyłać do urządzenia fiskalnego.</xs:documentation>
        </xs:annotation>
      </xs:element>
      <xs:element minOccurs="0" name="Objetosc">
        <xs:annotation>
          <xs:documentation>Objętość 1 j.m. towaru w danej jednostce.</xs:documentation>
        </xs:annotation>
        <xs:complexType>
          <xs:sequence>
            <xs:element name="Jednostka" type="xs:string">
              <xs:annotation>
                <xs:documentation>Symbol jednostki objętości, np. m3.</xs:documentation>
              </xs:annotation>
            </xs:element>
            <xs:element name="Wartosc" type="xs:decimal">
              <xs:annotation>
                <xs:documentation>Objętość w danej jednostce objętości.</xs:documentation>
              </xs:annotation>
            </xs:element>
          </xs:sequence>
        </xs:complexType>
      </xs:element>
      <xs:element minOccurs="0" name="Masa" type="TMasa">
        <xs:annotation>
          <xs:documentation>Masa brutto 1 j.m. towaru w danej jednostce.</xs:documentation>
        </xs:annotation>
      </xs:element>
      <xs:element minOccurs="0" name="MasaNetto" type="TMasa">
        <xs:annotation>
          <xs:documentation>Masa netto 1 j.m. towaru w danej jednostce.</xs:documentation>
        </xs:annotation>
      </xs:element>
    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="TJednostkaMiaryDodatkowa">
    <xs:annotation>
      <xs:documentation>Dane dodatkowej jednostki miary.</xs:documentation>
    </xs:annotation>
    <xs:complexContent>
      <xs:extension base="TJednostkaMiary">
        <xs:sequence>
          <xs:element name="Ilosc" type="xs:decimal">
            <xs:annotation>
              <xs:documentation>Ilość towaru w jednostce dodatkowej. Do celów przeliczania z j.m. nadrzędnej na dodatkową - licznik.</xs:documentation>
            </xs:annotation>
          </xs:element>
          <xs:element name="IloscNadrzJm" type="xs:decimal">
            <xs:annotation>
              <xs:documentation>Ilość towaru w jednostce dodatkowej. Do celów przeliczania z j.m. nadrzędnej na dodatkową - mianownik.</xs:documentation>
            </xs:annotation>
          </xs:element>
          <xs:element name="NadrzednaJm" type="xs:string">
            <xs:annotation>
              <xs:documentation>Symbol nadrzędnej jednostki miary. Musi być także jednostką miary tego asortymentu</xs:documentation>
            </xs:annotation>
          </xs:element>
        </xs:sequence>
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>

  <xs:simpleType name="TKlasyfikacjaPKWIU">
    <xs:annotation>
      <xs:documentation>Rodzaj klasyfikacji PKWiU.</xs:documentation>
    </xs:annotation>
    <xs:restriction base="xs:string">
      <xs:enumeration value="PKWIU2008">
        <xs:annotation>
          <xs:documentation>Klasyfikacja PKWiU 2008.</xs:documentation>
        </xs:annotation>
      </xs:enumeration>
      <xs:enumeration value="PKWIU2015">
        <xs:annotation>
          <xs:documentation>Klasyfikacja PKWiU 2015.</xs:documentation>
        </xs:annotation>
      </xs:enumeration>
    </xs:restriction>
  </xs:simpleType>
  
  <xs:element name="Asortyment">
    <xs:annotation>
      <xs:documentation>Dane kartoteki towarów, usług, opakowań i kompletów.</xs:documentation>
    </xs:annotation>
    <xs:complexType>
      <xs:sequence>
        <xs:element minOccurs="0" maxOccurs="unbounded" name="Pozycja">
          <xs:annotation>
            <xs:documentation>Dane pozycji kartoteki towarów, usług, opakowań i kompletów.</xs:documentation>
          </xs:annotation>
          <xs:complexType>
            <xs:all>
              <xs:element name="Sygnatura" type="xs:string">
                <xs:annotation>
                  <xs:documentation>Symbol</xs:documentation>
                </xs:annotation>
              </xs:element>
              <xs:element name="Nazwa" type="xs:string">
                <xs:annotation>
                  <xs:documentation>Nazwa</xs:documentation>
                </xs:annotation>
              </xs:element>
              <xs:element minOccurs="0" name="PKWIU">
                <xs:annotation>
                  <xs:documentation>Kod PKWiU</xs:documentation>
                </xs:annotation>
                <xs:complexType>
                  <xs:simpleContent>
                    <xs:extension base="xs:string">
                      <xs:attribute use="required" name="Klasyfikacja" type="TKlasyfikacjaPKWIU" />
                    </xs:extension>
                  </xs:simpleContent>
                </xs:complexType>
              </xs:element>
              <xs:element minOccurs="0" name="KodCN" type="xs:string">
                <xs:annotation>
                  <xs:documentation>Kod CN</xs:documentation>
                </xs:annotation>
              </xs:element>
              <xs:element minOccurs="0" name="Opis" type="xs:string">
                <xs:annotation>
                  <xs:documentation>Opis</xs:documentation>
                </xs:annotation>
              </xs:element>
              <xs:element minOccurs="0" name="Uwagi" type="xs:string">
                <xs:annotation>
                  <xs:documentation>Uwagi</xs:documentation>
                </xs:annotation>
              </xs:element>
              <xs:element minOccurs="0" name="StronaWww" type="xs:string">
                <xs:annotation>
                  <xs:documentation>Strona WWW.</xs:documentation>
                </xs:annotation>
              </xs:element>

              <xs:element minOccurs="0" name="Zdjecia">
                <xs:annotation>
                  <xs:documentation>Kolekcja zdjęć.</xs:documentation>
                </xs:annotation>
                <xs:complexType>
                  <xs:sequence>
                    <xs:element minOccurs="0" maxOccurs="unbounded" name="Zdjecie" type="xs:string">
                      <xs:annotation>
                        <xs:documentation>Ścieżka względna do pliku ze zdjęciem. Względem lokalizacji pliku XML.</xs:documentation>
                      </xs:annotation>
                    </xs:element>
                  </xs:sequence>
                </xs:complexType>
              </xs:element>

              <xs:element minOccurs="0" name="Charakterystyka" type="xs:string">
                <xs:annotation>
                  <xs:documentation>Pełna charakterystyka produktu, przeznaczona do publikowania w internecie na stronach WWW. Format: tekstowy, preferowany HTML.</xs:documentation>
                </xs:annotation>
              </xs:element>
              <xs:element minOccurs="0" name="Grupa" type="xs:string">
                <xs:annotation>
                  <xs:documentation>Nazwa grupy, do której należy pozycja kartoteki.</xs:documentation>
                </xs:annotation>
              </xs:element>
              <xs:element minOccurs="0" name="Cechy">
                <xs:annotation>
                  <xs:documentation>Kolekcja przypisanych cech.</xs:documentation>
                </xs:annotation>
                <xs:complexType>
                  <xs:sequence>
                    <xs:element minOccurs="0" maxOccurs="unbounded" name="Cecha" type="xs:string">
                      <xs:annotation>
                        <xs:documentation>Nazwa przypisanej cechy.</xs:documentation>
                      </xs:annotation>
                    </xs:element>
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
              <xs:element name="JednostkiMiar">
                <xs:annotation>
                  <xs:documentation>Informacje o jednostkach miar pozycji kartoteki.</xs:documentation>
                </xs:annotation>
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="PodstJm" type="TJednostkaMiary">
                      <xs:annotation>
                        <xs:documentation>Dane podstawowej jednostki miary.</xs:documentation>
                      </xs:annotation>
                    </xs:element>
                    <xs:element minOccurs="0" maxOccurs="unbounded" name="Jm" type="TJednostkaMiaryDodatkowa">
                      <xs:annotation>
                        <xs:documentation>Dane dodatkowej jednostki miary.</xs:documentation>
                      </xs:annotation>
                    </xs:element>
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
              <xs:element minOccurs="0" name="PorownawczaJm" type="xs:string">
                <xs:annotation>
                  <xs:documentation>Symbol jednostki porównawczej. Musi być także jednostką miary tej pozycji kartoteki.</xs:documentation>
                </xs:annotation>
              </xs:element>
              <xs:element name="JmSprzedazy" type="xs:string">
                <xs:annotation>
                  <xs:documentation>Symbol j.m. używanej przy sprzedaży.</xs:documentation>
                </xs:annotation>
              </xs:element>
              <xs:element name="JmZakupu" type="xs:string">
                <xs:annotation>
                  <xs:documentation>Symbol j.m. wykorzystywanej przy zakupie.</xs:documentation>
                </xs:annotation>
              </xs:element>
              <xs:element name="StawkaVatSprzedaz">
                <xs:annotation>
                  <xs:documentation>Stawka VAT przy sprzedaży.</xs:documentation>
                </xs:annotation>
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="Symbol" type="xs:string">
                      <xs:annotation>
                        <xs:documentation>Symbol.</xs:documentation>
                      </xs:annotation>
                    </xs:element>
                    <xs:element name="Nazwa" type="xs:string">
                      <xs:annotation>
                        <xs:documentation>Nazwa.</xs:documentation>
                      </xs:annotation>
                    </xs:element>
                    <xs:element name="Wartosc" type="xs:decimal">
                      <xs:annotation>
                        <xs:documentation>Wartość w procentach.</xs:documentation>
                      </xs:annotation>
                    </xs:element>
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
              <xs:element name="StawkaVatZakup">
                <xs:annotation>
                  <xs:documentation>Stawka VAT przy zakupie.</xs:documentation>
                </xs:annotation>
                <xs:complexType>
                  <xs:sequence minOccurs="0">
                    <xs:element name="Symbol" type="xs:string">
                      <xs:annotation>
                        <xs:documentation>Symbol.</xs:documentation>
                      </xs:annotation>
                    </xs:element>
                    <xs:element name="Nazwa" type="xs:string">
                      <xs:annotation>
                        <xs:documentation>Nazwa.</xs:documentation>
                      </xs:annotation>
                    </xs:element>
                    <xs:element name="Wartosc" type="xs:decimal">
                      <xs:annotation>
                        <xs:documentation>Wartość procentowa.</xs:documentation>
                      </xs:annotation>
                    </xs:element>
                  </xs:sequence>
                  <xs:attribute name="JakPrzySprzedazy" type="xs:boolean" use="optional">
                    <xs:annotation>
                      <xs:documentation>Określa, czy stawka VAT przy zakupie jest taka jak przy sprzedaży. Jeśli tak, dane stawki nie są wymagane.</xs:documentation>
                    </xs:annotation>
                  </xs:attribute>
                </xs:complexType>
              </xs:element>


              <xs:element minOccurs="0" name="Stany">
                <xs:annotation>
                  <xs:documentation>Parametry kontroli stanów magazynowych w podziale na magazyny. Nie dotyczy usług.</xs:documentation>
                </xs:annotation>
                <xs:complexType>
                  <xs:sequence>
                    <xs:element minOccurs="0" maxOccurs="unbounded" name="Magazyn">
                      <xs:annotation>
                        <xs:documentation>Magazyn, którego dotyczą parametry.</xs:documentation>
                      </xs:annotation>
                      <xs:complexType>
                        <xs:all>
                          <xs:element name="Symbol" type="xs:string">
                            <xs:annotation>
                              <xs:documentation>Symbol magazynu.</xs:documentation>
                            </xs:annotation>
                          </xs:element>
                          <xs:element name="Stan">
                            <xs:annotation>
                              <xs:documentation>Parametry kontroli stanów magazynowych.</xs:documentation>
                            </xs:annotation>
                            <xs:complexType>
                              <xs:all>
                                <xs:element name="Ilosc" type="xs:decimal">
                                  <xs:annotation>
                                    <xs:documentation>Ilość, która ma być kontrolowana.</xs:documentation>
                                  </xs:annotation>                                  
                                </xs:element>
                              </xs:all>
                              <xs:attribute name="Rodzaj" type="xs:string">
                                <xs:annotation>
                                  <xs:documentation>Rodzaj kontroli (min - stan minimalny).</xs:documentation>
                                </xs:annotation>
                              </xs:attribute>
                            </xs:complexType>
                          </xs:element>
                        </xs:all>
                      </xs:complexType>
                    </xs:element>
                  </xs:sequence>
                </xs:complexType>
              </xs:element>

              <xs:element minOccurs="0" name="KontrolaTW" type="xs:int">
                <xs:annotation>
                  <xs:documentation>Określa, czy termin ważności ma być kontrolowany, poprzez podanie liczby dni do końca terminu ważności.</xs:documentation>
                </xs:annotation>
              </xs:element>

              <!--<xs:element minOccurs="0" name="KontrolaTW">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element minOccurs="0" maxOccurs="unbounded" name="LiczbaDni" type="xs:int" />
                  </xs:sequence>
                </xs:complexType>
              </xs:element>-->

              <xs:element name="OtwartaCena" type="xs:boolean">
                <xs:annotation>
                  <xs:documentation>Określa, czy cena jest otwarta.</xs:documentation>
                </xs:annotation>
              </xs:element>
              <xs:element name="Wazony" type="xs:boolean">
                <xs:annotation>
                  <xs:documentation>Określa, czy towar ważony.</xs:documentation>
                </xs:annotation>
              </xs:element>
              <xs:element name="ObrotMarza" type="xs:boolean">
                <xs:annotation>
                  <xs:documentation>Określa, czy pozycja podlega obrotowi VAT marża.</xs:documentation>
                </xs:annotation>
              </xs:element>
              <xs:element minOccurs="0" name="CenaEwidencyjna" type="xs:decimal">
                <xs:annotation>
                  <xs:documentation>Cena ewidencyjna.</xs:documentation>
                </xs:annotation>
              </xs:element>
              <xs:element minOccurs="0" name="Powiazany" type="xs:string">
                <xs:annotation>
                  <xs:documentation>Symbol powiązanego towaru, usługi, kompletu lub opakowania.</xs:documentation>
                </xs:annotation>
              </xs:element>
              <xs:element minOccurs="0" name="OplataDodatkowa" type="xs:string">
                <xs:annotation>
                  <xs:documentation>Symbol powiązanej opłaty dodatkowej.</xs:documentation>
                </xs:annotation>
              </xs:element>
              <xs:element name="SklepInternet" type="xs:boolean">
                <xs:annotation>
                  <xs:documentation>Określa, czy pozycja przeznaczona do sklepu internetowego.</xs:documentation>
                </xs:annotation>
              </xs:element>
              <xs:element name="SerwisAukcyjny" type="xs:boolean">
                <xs:annotation>
                  <xs:documentation>Określa, czy pozycja przeznaczona do sprzedaży w serwisie aukcyjnym.</xs:documentation>
                </xs:annotation>
              </xs:element>
              <xs:element name="SprzedazMobilna" type="xs:boolean">
                <xs:annotation>
                  <xs:documentation>Określa, czy pozycja przeznaczona do sprzedaży mobilnej.</xs:documentation>
                </xs:annotation>
              </xs:element>
              <xs:element minOccurs="0" name="Skladniki">
                <xs:annotation>
                  <xs:documentation>Określa składniki kompletu. Tylko dla pozycji typu komplet.</xs:documentation>
                </xs:annotation>
                <xs:complexType>
                  <xs:sequence>
                    <xs:element minOccurs="0" maxOccurs="unbounded" name="Skladnik">
                      <xs:annotation>
                        <xs:documentation>Określa składnik.</xs:documentation>
                      </xs:annotation>
                      <xs:complexType>
                        <xs:sequence>
                          <xs:element name="Symbol" type="xs:string">
                            <xs:annotation>
                              <xs:documentation>Symbol składnika.</xs:documentation>
                            </xs:annotation>
                          </xs:element>
                          <xs:element name="Liczba" type="xs:decimal">
                            <xs:annotation>
                              <xs:documentation>Ilość składnika w j.m. na 1 j.m. kompletu.</xs:documentation>
                            </xs:annotation>
                          </xs:element>
                          <xs:element name="Jm" type="xs:string">
                            <xs:annotation>
                              <xs:documentation>Jednostka miary składnika, w której podano ilość.</xs:documentation>
                            </xs:annotation>
                          </xs:element>
                        </xs:sequence>
                      </xs:complexType>
                    </xs:element>
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
              <xs:element minOccurs="0" name="SprzedazPrzezWartosc" type="xs:string">
                <xs:annotation>
                  <xs:documentation>Określa, czy pozycja przeznaczona do sprzedaży przez wartość i sposób przeliczenia pozycji dokumentu. WyliczIlosc oznacza, że na podstawie podanej wartości będzie wyliczana ilość.</xs:documentation>
                </xs:annotation>
              </xs:element>
              <xs:element minOccurs="0" name="Dostawcy">
                <xs:annotation>
                  <xs:documentation>Lista dostawców towaru.</xs:documentation>
                </xs:annotation>
                <xs:complexType>
                  <xs:sequence>
                    <xs:element minOccurs="0" maxOccurs="unbounded" name="Dostawca" type="TTowarKontrahenta">
                      <xs:annotation>
                        <xs:documentation>Określa powiązanie z dostawcą.</xs:documentation>
                      </xs:annotation>
                    </xs:element>
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
              <xs:element minOccurs="0" name="Producent" type="TTowarKontrahenta">
                <xs:annotation>
                  <xs:documentation>Określa powiązanie z producentem.</xs:documentation>
                </xs:annotation>
              </xs:element>
              <xs:element minOccurs="0" name="FunduszPromocji" type="xs:string">
                <xs:annotation>
                  <xs:documentation>Symbol funduszu promocji, z pozycja może być refundowana.</xs:documentation>
                </xs:annotation>
              </xs:element>

              <xs:element minOccurs="0" name="Wlasne">
                <xs:annotation>
                  <xs:documentation>Wartości pól własnych.</xs:documentation>
                </xs:annotation>
                <xs:complexType>
                  <xs:sequence>
                    <xs:element minOccurs="0" maxOccurs="unbounded" name="Pole">
                      <xs:annotation>
                        <xs:documentation>Pole własne. Zawartość tego elementu jest wartością pola.</xs:documentation>
                      </xs:annotation>
                      <xs:complexType>
                        <xs:simpleContent>
                          <xs:extension base="xs:string">
                            <xs:attribute name="Nazwa" type="xs:string" use="required">
                              <xs:annotation>
                                <xs:documentation>Nazwa pola własnego.</xs:documentation>
                              </xs:annotation>
                            </xs:attribute>
                          </xs:extension>
                        </xs:simpleContent>
                      </xs:complexType>
                    </xs:element>
                  </xs:sequence>
                </xs:complexType>
              </xs:element>

              <xs:element minOccurs="0" name="WlasneRozszerzone">
                <xs:annotation>
                  <xs:documentation>Wartości pól własnych podmiotu.</xs:documentation>
                </xs:annotation>
                <xs:complexType>
                  <xs:sequence>
                    <xs:element minOccurs="0" maxOccurs="unbounded" name="PoleRozszerzone">
                      <xs:annotation>
                        <xs:documentation>Pole własne rozszerzone towaru. Zawartość tego elementu jest wartością pola.</xs:documentation>
                      </xs:annotation>
                      <xs:complexType>
                        <xs:simpleContent>
                          <xs:extension base="xs:string">
                            <xs:attribute name="Nazwa" type="xs:string" use="required">
                              <xs:annotation>
                                <xs:documentation>Nazwa pola własnego.</xs:documentation>
                              </xs:annotation>
                            </xs:attribute>
                          </xs:extension>
                        </xs:simpleContent>
                      </xs:complexType>
                    </xs:element>
                  </xs:sequence>
                </xs:complexType>
              </xs:element>

              <xs:element name="BibliotekaDokumentow" type="wspolne:TBibliotekaDokumentow" minOccurs="0">
                <xs:annotation>
                  <xs:documentation>Dane obiektów z biblioteki dokumentów.</xs:documentation>
                </xs:annotation>
              </xs:element>
              
              <xs:element name="FlagaWlasna" minOccurs="0">
                <xs:annotation>
                  <xs:documentation>Dane flagi własnej.</xs:documentation>
                </xs:annotation>
                <xs:complexType>
                  <xs:all>
                    <xs:element minOccurs="1" maxOccurs="1" name="Kolor" type="xs:string">
                      <xs:annotation>
                        <xs:documentation>Kolor flagi własnej.</xs:documentation>
                      </xs:annotation>
                    </xs:element>
                    <xs:element minOccurs="0" maxOccurs="1" name="Ksztalt" type="xs:string">
                      <xs:annotation>
                        <xs:documentation>Kształt flagi własnej.</xs:documentation>
                      </xs:annotation>
                    </xs:element>
                    <xs:element minOccurs="0" maxOccurs="1" name="Komentarz" type="xs:string">
                      <xs:annotation>
                        <xs:documentation>Komentarz flagi własnej.</xs:documentation>
                      </xs:annotation>
                    </xs:element>
                  </xs:all>
                </xs:complexType>
              </xs:element>
              
              <xs:element minOccurs="0" name="MechanizmPodzielonejPlatnosci" type="xs:byte">
                <xs:annotation>
                  <xs:documentation>Określa, czy towar jest objęty mechanizmem podzielonej płatności.</xs:documentation>
                </xs:annotation>
              </xs:element>
              
            <xs:element minOccurs="0" name="GrupyJpkVat">
              <xs:annotation>
                <xs:documentation>Grupy asortymentu JPK_VAT przypisane do kartoteki asortymentu.</xs:documentation>
              </xs:annotation>
              <xs:complexType>
                <xs:all>
                  <xs:element minOccurs="1" name="GTU_01" type="xs:boolean">
                    <xs:annotation>
                      <xs:documentation>Dostawa napojów alkoholowych - alkoholu etylowego, piwa, wina, napojów fermentowanych i wyrobów pośrednich, w rozumieniu przepisów o podatku akcyzowym</xs:documentation>
                    </xs:annotation>
                  </xs:element>
                  <xs:element minOccurs="1" name="GTU_02" type="xs:boolean">
                    <xs:annotation>
                      <xs:documentation>Dostawa towarów, o których mowa w art. 103 ust. 5aa ustawy</xs:documentation>
                    </xs:annotation>
                  </xs:element>
                  <xs:element minOccurs="1" name="GTU_03" type="xs:boolean">
                    <xs:annotation>
                      <xs:documentation>Dostawa oleju opałowego w rozumieniu przepisów o podatku akcyzowym oraz olejów smarowych, pozostałych olejów o kodach CN od 2710 19 71 do 2710 19 99, z wyłączeniem wyrobów o kodzie CN 2710 19 85 (oleje białe, parafina ciekła) oraz smarów plastycznych zaliczanych do kodu CN 2710 19 99, olejów smarowych o kodzie CN 2710 20 90, preparatów smarowych objętych pozycją CN 3403, z wyłączeniem smarów plastycznych objętych tą pozycją</xs:documentation>
                    </xs:annotation>
                  </xs:element>
                  <xs:element minOccurs="1" name="GTU_04" type="xs:boolean">
                    <xs:annotation>
                      <xs:documentation>Dostawa wyrobów tytoniowych, suszu tytoniowego, płynu do papierosów elektronicznych i wyrobów nowatorskich, w rozumieniu przepisów o podatku akcyzowym</xs:documentation>
                    </xs:annotation>
                  </xs:element>
                  <xs:element minOccurs="1" name="GTU_05" type="xs:boolean">
                    <xs:annotation>
                      <xs:documentation>Dostawa odpadów - wyłącznie określonych w poz. 79-91 załącznika nr 15 do ustawy</xs:documentation>
                    </xs:annotation>
                  </xs:element>
                  <xs:element minOccurs="1" name="GTU_06" type="xs:boolean">
                    <xs:annotation>
                      <xs:documentation>Dostawa urządzeń elektronicznych oraz części i materiałów do nich, wyłącznie określonych w poz. 7-9, 59-63, 65, 66, 69 i 94-96 załącznika nr 15 do ustawy</xs:documentation>
                    </xs:annotation>
                  </xs:element>
                  <xs:element minOccurs="1" name="GTU_07" type="xs:boolean">
                    <xs:annotation>
                      <xs:documentation>Dostawa pojazdów oraz części samochodowych o kodach wyłącznie CN 8701 - 8708 oraz CN 8708 10</xs:documentation>
                    </xs:annotation>
                  </xs:element>
                  <xs:element minOccurs="1" name="GTU_08" type="xs:boolean">
                    <xs:annotation>
                      <xs:documentation>Dostawa metali szlachetnych oraz nieszlachetnych - wyłącznie określonych w poz. 1-3 załącznika nr 12 do ustawy oraz w poz. 12-25, 33-40, 45, 46, 56 i 78 załącznika nr 15 do ustawy</xs:documentation>
                    </xs:annotation>
                  </xs:element>
                  <xs:element minOccurs="1" name="GTU_09" type="xs:boolean">
                    <xs:annotation>
                      <xs:documentation>Dostawa leków oraz wyrobów medycznych - produktów leczniczych, środków spożywczych specjalnego przeznaczenia żywieniowego oraz wyrobów medycznych, objętych obowiązkiem zgłoszenia, o którym mowa w art. 37av ust. 1 ustawy z dnia 6 września 2001 r. - Prawo farmaceutyczne (Dz. U. z 2019 r. poz. 499, z późn. zm.)</xs:documentation>
                    </xs:annotation>
                  </xs:element>
                  <xs:element minOccurs="1" name="GTU_10" type="xs:boolean">
                    <xs:annotation>
                      <xs:documentation>Dostawa budynków, budowli i gruntów</xs:documentation>
                    </xs:annotation>
                  </xs:element>
                  <xs:element minOccurs="1" name="GTU_11" type="xs:boolean">
                    <xs:annotation>
                      <xs:documentation>Świadczenie usług w zakresie przenoszenia uprawnień do emisji gazów cieplarnianych, o których mowa w ustawie z dnia 12 czerwca 2015 r. o systemie handlu uprawnieniami do emisji gazów cieplarnianych (Dz. U. z 2018 r. poz. 1201 i 2538 oraz z 2019 r. poz. 730, 1501 i 1532)</xs:documentation>
                    </xs:annotation>
                  </xs:element>
                  <xs:element minOccurs="1" name="GTU_12" type="xs:boolean">
                    <xs:annotation>
                      <xs:documentation>Świadczenie usług o charakterze niematerialnym - wyłącznie: doradczych, księgowych, prawnych, zarządczych, szkoleniowych, marketingowych, firm centralnych (head offices), reklamowych, badania rynku i opinii publicznej, w zakresie badań naukowych i prac rozwojowych</xs:documentation>
                    </xs:annotation>
                  </xs:element>
                  <xs:element minOccurs="1" name="GTU_13" type="xs:boolean">
                    <xs:annotation>
                      <xs:documentation>Świadczenie usług transportowych i gospodarki magazynowej - Sekcja H PKWiU 2015 symbol ex 49.4, ex 52.1</xs:documentation>
                    </xs:annotation>
                  </xs:element>                  
                </xs:all>
              </xs:complexType>
            </xs:element>

              <xs:element name="DaneOplatyCukrowej" type="TDaneOplatyCukrowej" minOccurs="0" maxOccurs="1">
                <xs:annotation>
                  <xs:documentation>Dane do wyliczenia opłaty cukrowej dla asortymentu.</xs:documentation>
                </xs:annotation>
              </xs:element>

              <xs:element name="KrajPochodzenia" minOccurs="0" maxOccurs="1">
                <xs:annotation>
                  <xs:documentation>Domyślny kraj pochodzenia asortymentu.</xs:documentation>
                </xs:annotation>
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="KodKraju" type="xs:string" minOccurs="1" maxOccurs="1">
                      <xs:annotation>
                        <xs:documentation>Kod kraju.</xs:documentation>
                      </xs:annotation>
                    </xs:element>
                    <xs:element name="Nazwa" type="xs:string" minOccurs="0" maxOccurs="1">
                      <xs:annotation>
                        <xs:documentation>Nazwa kraju.</xs:documentation>
                      </xs:annotation>
                    </xs:element>
                  </xs:sequence>
                </xs:complexType>
              </xs:element>

              <xs:element name="JmUzupelniajaca" type="xs:string" minOccurs="0" maxOccurs="1">
                <xs:annotation>
                  <xs:documentation>Symbol j.m. uzupełniającej wykorzystywanej w deklaracji INTRASTAT.</xs:documentation>
                </xs:annotation>
              </xs:element>
              
            </xs:all>
            <xs:attribute name="Rodzaj" type="xs:string" use="required">
              <xs:annotation>
                <xs:documentation>Rodzaj elementu kartoteki: TW, US, OP, KT, OD (towar, usługa, opakowanie, komplet, opłata dodatkowa).</xs:documentation>
              </xs:annotation>
            </xs:attribute>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>

