<?xml version="1.0" encoding="utf-8"?>
<xs:schema attributeFormDefault="unqualified"
           elementFormDefault="qualified"
           targetNamespace="http://schemas.insert.com.pl/2014/hop/typydzialan"
           xmlns="http://schemas.insert.com.pl/2014/hop/typydzialan"
           xmlns:xs="http://www.w3.org/2001/XMLSchema"
           xmlns:dzialania="http://schemas.insert.com.pl/2014/hop/dzialania">

  <xs:import id="Dzialania" schemaLocation="Dzialania.xsd" namespace="http://schemas.insert.com.pl/2014/hop/dzialania" />

  <xs:annotation>
    <xs:documentation>Typy działań.</xs:documentation>
  </xs:annotation>

  <xs:element name="TypyDzialan">
    <xs:annotation>
      <xs:documentation>Typy działań.</xs:documentation>
    </xs:annotation>
    <xs:complexType>
      <xs:sequence minOccurs="0" maxOccurs="unbounded">
        <xs:element name="Typ" type="TTypDzialania">
          <xs:annotation>
            <xs:documentation>Typ działania.</xs:documentation>
          </xs:annotation>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>

  <xs:complexType name="TTypDzialania">
    <xs:annotation>
      <xs:documentation>Dane typu działania.</xs:documentation>
    </xs:annotation>
    <xs:sequence>
      <xs:element name="Nazwa" type="xs:string">
        <xs:annotation>
          <xs:documentation>Nazwa typu działania.</xs:documentation>
        </xs:annotation>
      </xs:element>
      <xs:element name="Kierunek" type="xs:boolean" minOccurs="0">
        <xs:annotation>
          <xs:documentation>Określa, czy dla działania tego typu będzie można zdefiniować kierunek wychodzący lub przychodzący.</xs:documentation>
        </xs:annotation>
      </xs:element>
      <xs:element name="PokazujKomentarz" type="xs:boolean" minOccurs="0">
        <xs:annotation>
          <xs:documentation>Określa, czy pokazywać komentarz po zakończeniu.</xs:documentation>
        </xs:annotation>
      </xs:element>
      <xs:element name="PokazujKomentarzPoRejestracji" type="xs:boolean" minOccurs="0">
        <xs:annotation>
          <xs:documentation>Określa, czy pokazywac komentarz po rejestracji.</xs:documentation>
        </xs:annotation>
      </xs:element>
      <xs:element name="RodzajeDzialan" minOccurs="0">
        <xs:annotation>
          <xs:documentation>Rodzaje działań opisujące typ działania.</xs:documentation>
        </xs:annotation>
        <xs:complexType>
          <xs:sequence minOccurs="0" maxOccurs="unbounded" >
            <xs:element name="Rodzaj" type="TRodzajDzialania">
              <xs:annotation>
                <xs:documentation>Rodzaj działania opisujący na wyższym poziomie szczegółowości typ działania.</xs:documentation>
              </xs:annotation>
            </xs:element>
          </xs:sequence>
        </xs:complexType>
      </xs:element>
      <xs:element name="StopnieRealizacjiDzialania" minOccurs="0">
        <xs:annotation>
          <xs:documentation>Stopnie realizacji działania..</xs:documentation>
        </xs:annotation>
        <xs:complexType>
          <xs:sequence minOccurs="0" maxOccurs="unbounded" >
            <xs:element name="StopienRealizacji" type="TStopienRealizacjiDzialania">
              <xs:annotation>
                <xs:documentation>Stopień realizacji działania.</xs:documentation>
              </xs:annotation>
            </xs:element>
          </xs:sequence>
        </xs:complexType>
      </xs:element>
    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="TRodzajDzialania">
    <xs:annotation>
      <xs:documentation>Dane rodzaju działania.</xs:documentation>
    </xs:annotation>
    <xs:sequence>
      <xs:element name="Nazwa" type="xs:string">
        <xs:annotation>
          <xs:documentation>Nazwa rodzaju działania.</xs:documentation>
        </xs:annotation>
      </xs:element>
      <xs:element name="Aktywny" type="xs:boolean" minOccurs="0">
        <xs:annotation>
          <xs:documentation>Określa, czy rodzaj ma się pojawiać w systemie, np. w filtrach.</xs:documentation>
        </xs:annotation>
      </xs:element>
    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="TStopienRealizacjiDzialania">
    <xs:annotation>
      <xs:documentation>Dane stopnia realizacji działania działania.</xs:documentation>
    </xs:annotation>
    <xs:sequence>
      <xs:element name="Nazwa" type="xs:string">
        <xs:annotation>
          <xs:documentation>Nazwa stopnia realizacji działania.</xs:documentation>
        </xs:annotation>
      </xs:element>
      <xs:element name="Postep" type="xs:int" minOccurs="0">
        <xs:annotation>
          <xs:documentation>Postęp realizacji działania w procentach.</xs:documentation>
        </xs:annotation>
      </xs:element>
      <xs:element name="Sukces" type="TSukcesDzialania" minOccurs="0">
        <xs:annotation>
          <xs:documentation>Określa, czy stopień realizacji działania oznacza jego sukces.</xs:documentation>
        </xs:annotation>
      </xs:element>
      <xs:element name="DomyslnyDla" type="TDomyslnyStopienRealizacji" minOccurs="0">
        <xs:annotation>
          <xs:documentation>Określa, czy stopień realizacji działania jest domyślny dla działania zakończonego sukcesem/porażką.</xs:documentation>
        </xs:annotation>
      </xs:element>
    </xs:sequence>
  </xs:complexType>

  <xs:simpleType name="TSukcesDzialania">
    <xs:annotation>
      <xs:documentation>Wartości pozwalające określić, czy dany stopień realizacji działania oznacza sukces, czy porażkę.</xs:documentation>
    </xs:annotation>
    <xs:restriction base="xs:string">
      <xs:enumeration value="Tak">
        <xs:annotation>
          <xs:documentation>Sukces działania. Pole postępu w stopniu realizacji działania musi być ustawione na 100%.</xs:documentation>
        </xs:annotation>
      </xs:enumeration>
      <xs:enumeration value="Nie">
        <xs:annotation>
          <xs:documentation>Porażka działania. Pole postępu w stopniu realizacji działania musi być ustawione na 100%.</xs:documentation>
        </xs:annotation>
      </xs:enumeration>
      <xs:enumeration value="Nie określono">
        <xs:annotation>
          <xs:documentation>Nie określono, czy dla podanego postępu działania jest zakończone sukcesem lub porażką.</xs:documentation>
        </xs:annotation>
      </xs:enumeration>
    </xs:restriction>
  </xs:simpleType>

  <xs:simpleType name="TDomyslnyStopienRealizacji">
    <xs:annotation>
      <xs:documentation>Wartości pozwalające określić, czy dany stopień realizacji działania będzie domyślny dla sukcesu/porażki danego typu działania.</xs:documentation>
    </xs:annotation>
    <xs:restriction base="xs:string">
      <xs:enumeration value="Sukces">
        <xs:annotation>
          <xs:documentation>Określa, czy stopień realizacji działania będzie domyślny dla działania zakończonego sukcesem.</xs:documentation>
        </xs:annotation>
      </xs:enumeration>
      <xs:enumeration value="Porazka">
        <xs:annotation>
          <xs:documentation>Określa, czy stopień realizacji działania będzie domyślny dla działania zakończonego porażką.</xs:documentation>
        </xs:annotation>
      </xs:enumeration>
    </xs:restriction>
  </xs:simpleType>

  <xs:simpleType name="TKierunekDzialania">
    <xs:annotation>
      <xs:documentation>Określa kto wychodzi z inicjatywą.</xs:documentation>
    </xs:annotation>
    <xs:restriction base="xs:string">
      <xs:enumeration value="Wychodzace">
        <xs:annotation>
          <xs:documentation>Oznacza, że to my wychodzimy z inicjatywą, np. dzwonimy do klienta w celu przedstawienia oferty.</xs:documentation>
        </xs:annotation>
      </xs:enumeration>
      <xs:enumeration value="Przychodzace">
        <xs:annotation>
          <xs:documentation>Oznacza, że to ktoś inny wychodzi z inicjatywą, np. klient dzwoni do nas w sprawie reklamacji.</xs:documentation>
        </xs:annotation>
      </xs:enumeration>
    </xs:restriction>
  </xs:simpleType>

  <xs:complexType name="TypyDzialanDummy">
    <xs:annotation>
      <xs:documentation>Zarezerwowane.</xs:documentation>
    </xs:annotation>
    <xs:attribute name="Dummy1" type="TKierunekDzialania">
      <xs:annotation>
        <xs:documentation>Zarezerwowane.</xs:documentation>
      </xs:annotation>
    </xs:attribute>
  </xs:complexType>

</xs:schema>