<?xml version="1.0" encoding="utf-8"?>
<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified"
           targetNamespace="http://schemas.insert.com.pl/2013/hop/umowyPracownicze"
           xmlns="http://schemas.insert.com.pl/2013/hop/umowyPracownicze"
           xmlns:xs="http://www.w3.org/2001/XMLSchema"
           xmlns:wspolne="http://schemas.insert.com.pl/2013/hop">
  <xs:annotation>
    <xs:documentation>Informacje o umowach o pracę oraz umowach cywilnoprawnych.</xs:documentation>
  </xs:annotation>

  <xs:import id="WspolnePart" namespace="http://schemas.insert.com.pl/2013/hop" schemaLocation="Wspolne.xsd"/>

  <xs:simpleType name="TTypSkladnikaPlacowego">
    <xs:annotation>
      <xs:documentation>Określa typ składnika płacowego.</xs:documentation>
    </xs:annotation>
    <xs:restriction base="xs:string">
      <xs:enumeration value="Naliczenie">
        <xs:annotation>
          <xs:documentation>Składnik płacowy jako naliczenie.</xs:documentation>
        </xs:annotation>
      </xs:enumeration>
      <xs:enumeration value="Potracenie">
        <xs:annotation>
          <xs:documentation>Składnik płacowy jako potrącenie.</xs:documentation>
        </xs:annotation>
      </xs:enumeration>
    </xs:restriction>
  </xs:simpleType>

  <xs:simpleType name="TTypPlatnika">
    <xs:annotation>
      <xs:documentation>Określa typ płatnika.</xs:documentation>
    </xs:annotation>
    <xs:restriction base="xs:string">
      <xs:enumeration value="Pracodawca">
        <xs:annotation>
          <xs:documentation>Pracodawca jako płatnik.</xs:documentation>
        </xs:annotation>
      </xs:enumeration>
      <xs:enumeration value="ZUS">
        <xs:annotation>
          <xs:documentation>ZUS jako płatnik.</xs:documentation>
        </xs:annotation>
      </xs:enumeration>
    </xs:restriction>
  </xs:simpleType>

  <xs:complexType name="TSkladnikPlacowy">
    <xs:annotation>
      <xs:documentation>Definicja składnika płacowego.</xs:documentation>
    </xs:annotation>
    <xs:sequence>
      <xs:element name="Nazwa" type="xs:string">
        <xs:annotation>
          <xs:documentation>Nazwa składnika płacowego.</xs:documentation>
        </xs:annotation>
      </xs:element>
      <xs:element name="Typ" type="TTypSkladnikaPlacowego">
        <xs:annotation>
          <xs:documentation>Typ składnika płacowego.</xs:documentation>
        </xs:annotation>
      </xs:element>
      <xs:element name="Platnik" type="TTypPlatnika">
        <xs:annotation>
          <xs:documentation>Typ płatnika składnika płacowego.</xs:documentation>
        </xs:annotation>
      </xs:element>
      <xs:element name="FlagaWlasna" minOccurs="0">
        <xs:annotation>
          <xs:documentation>Dane flagi własnej.</xs:documentation>
        </xs:annotation>
        <xs:complexType>
          <xs:all>
            <xs:element minOccurs="1" maxOccurs="1" name="Kolor" type="xs:string">
              <xs:annotation>
                <xs:documentation>Kolor flagi własnej.</xs:documentation>
              </xs:annotation>
            </xs:element>
            <xs:element minOccurs="0" maxOccurs="1" name="Ksztalt" type="xs:string">
              <xs:annotation>
                <xs:documentation>Kształt flagi własnej.</xs:documentation>
              </xs:annotation>
            </xs:element>
            <xs:element minOccurs="0" maxOccurs="1" name="Komentarz" type="xs:string">
              <xs:annotation>
                <xs:documentation>Komentarz flagi własnej.</xs:documentation>
              </xs:annotation>
            </xs:element>
          </xs:all>
        </xs:complexType>
      </xs:element>
    </xs:sequence>
    <xs:attribute name="Opodatkowany" type="xs:boolean" use="optional">
      <xs:annotation>
        <xs:documentation>Składnik płacowy wchodzący w skład podstawy opodatkowania.</xs:documentation>
      </xs:annotation>
    </xs:attribute>
    <xs:attribute name="UbezpieczenieEmerytalne" type="xs:boolean" use="optional">
      <xs:annotation>
        <xs:documentation>Składnik płacowy wchodzący w skład podstawy na ubezpieczenie emerytalne i rentowe.</xs:documentation>
      </xs:annotation>
    </xs:attribute>
    <xs:attribute name="UbezpieczenieChorobowe" type="xs:boolean" use="optional">
      <xs:annotation>
        <xs:documentation>Składnik płacowy wchodzący w skład podstawy na ubezpieczenie chorobowe i wypadkowe.</xs:documentation>
      </xs:annotation>
    </xs:attribute>
    <xs:attribute name="UbezpieczenieZdrowotne" type="xs:boolean" use="optional">
      <xs:annotation>
        <xs:documentation>Składnik płacowy wchodzący w skład podstawy na ubezpieczenie zdrowotne.</xs:documentation>
      </xs:annotation>
    </xs:attribute>
    <xs:attribute name="ZwolnienieZPodatkuDlaMlodych" type="xs:boolean" use="optional">
      <xs:annotation>
        <xs:documentation>Czy stosować zwolnienie z podatku dla młodych (do 26 lat).</xs:documentation>
      </xs:annotation>
    </xs:attribute>
  </xs:complexType>

  <xs:complexType name="TSkladnikiPlacowe">
    <xs:annotation>
      <xs:documentation>Lista dostępnych składników płacowych.</xs:documentation>
    </xs:annotation>
    <xs:sequence>
      <xs:element name="SkladnikPlacowy" minOccurs="0" maxOccurs="unbounded" type="TSkladnikPlacowy">
        <xs:annotation>
          <xs:documentation>Dane składnika płacowego.</xs:documentation>
        </xs:annotation>
      </xs:element>
    </xs:sequence>
  </xs:complexType>

  <xs:simpleType name="TTypOkresuUmowy">
    <xs:annotation>
      <xs:documentation>Typ okresu obowiązywania umowy.</xs:documentation>
    </xs:annotation>
    <xs:restriction base="xs:string">
      <xs:enumeration value="Nieokreslony">
        <xs:annotation>
          <xs:documentation>Umowa na czas nieokreślony.</xs:documentation>
        </xs:annotation>
      </xs:enumeration>
      <xs:enumeration value="Okreslony">
        <xs:annotation>
          <xs:documentation>Umowa na czas określony.</xs:documentation>
        </xs:annotation>
      </xs:enumeration>
      <xs:enumeration value="Probny">
        <xs:annotation>
          <xs:documentation>Umowa na okres próbny.</xs:documentation>
        </xs:annotation>
      </xs:enumeration>
    </xs:restriction>
  </xs:simpleType>

  <xs:simpleType name="TTypRaportuZUS">
    <xs:annotation>
      <xs:documentation>Typ generowanego raportu dla ZUS.</xs:documentation>
    </xs:annotation>
    <xs:restriction base="xs:string">
      <xs:enumeration value="RCA">
        <xs:annotation>
          <xs:documentation>Raport RCA.</xs:documentation>
        </xs:annotation>
      </xs:enumeration>
      <xs:enumeration value="RZA">
        <xs:annotation>
          <xs:documentation>Raport RZA.</xs:documentation>
        </xs:annotation>
      </xs:enumeration>
    </xs:restriction>
  </xs:simpleType>

  <xs:complexType name="TSkladkiZUS">
    <xs:annotation>
      <xs:documentation>Definicja naliczanych składek ZUS.</xs:documentation>
    </xs:annotation>
    <xs:attribute name="Emerytalne" type="xs:boolean">
      <xs:annotation>
        <xs:documentation>Naliczanie składek emerytalnych.</xs:documentation>
      </xs:annotation>
    </xs:attribute>
    <xs:attribute name="Rentowe" type="xs:boolean">
      <xs:annotation>
        <xs:documentation>Naliczanie składek rentowych.</xs:documentation>
      </xs:annotation>
    </xs:attribute>
    <xs:attribute name="Zdrowotne" type="xs:boolean">
      <xs:annotation>
        <xs:documentation>Naliczanie składek zdrowotnych.</xs:documentation>
      </xs:annotation>
    </xs:attribute>
    <xs:attribute name="Chorobowe" type="xs:boolean">
      <xs:annotation>
        <xs:documentation>Naliczanie składek chorobowych.</xs:documentation>
      </xs:annotation>
    </xs:attribute>
    <xs:attribute name="Wypadkowe" type="xs:boolean">
      <xs:annotation>
        <xs:documentation>Naliczanie składek wypadkowych.</xs:documentation>
      </xs:annotation>
    </xs:attribute>
    <xs:attribute name="FP" type="xs:boolean">
      <xs:annotation>
        <xs:documentation>Naliczanie składek Funduszu Pracy i Fundusz Solidarnościowy.</xs:documentation>
      </xs:annotation>
    </xs:attribute>
    <xs:attribute name="FGSP" type="xs:boolean">
      <xs:annotation>
        <xs:documentation>Naliczanie składek Funduszu Gwarantowanych Świadczeń Pracowniczych.</xs:documentation>
      </xs:annotation>
    </xs:attribute>
  </xs:complexType>

  <xs:simpleType name="TOdliczanieKUP">
    <xs:annotation>
      <xs:documentation>Typ odliczania kosztów uzyskania przychodu.</xs:documentation>
    </xs:annotation>
    <xs:restriction base="xs:string">
      <xs:enumeration value="Odliczac">
        <xs:annotation>
          <xs:documentation>Odliczanie kosztów uzyskania przychodu.</xs:documentation>
        </xs:annotation>
      </xs:enumeration>
      <xs:enumeration value="NieOdliczac">
        <xs:annotation>
          <xs:documentation>Brak odliczania kosztów uzyskania przychodu.</xs:documentation>
        </xs:annotation>
      </xs:enumeration>
      <xs:enumeration value="OdliczacPowiekszone">
        <xs:annotation>
          <xs:documentation>Odliczanie powiększonych kosztów uzyskania przychodu.</xs:documentation>
        </xs:annotation>
      </xs:enumeration>
    </xs:restriction>
  </xs:simpleType>
                  
  <xs:complexType name="TPodatek">
    <xs:annotation>
      <xs:documentation>Dane naliczanego podatku w ramach umowy o pracę.</xs:documentation>
    </xs:annotation>
    <xs:sequence>
      <xs:element name="OdliczanieKUP" type="TOdliczanieKUP">
        <xs:annotation>
          <xs:documentation>Rodzaj naliczania kosztów uzyskania przychodu.</xs:documentation>
        </xs:annotation>
      </xs:element>
      <xs:element name="OdliczanieUlgi" type="wspolne:TOdliczanieUlgi" minOccurs="0">
        <xs:annotation>
          <xs:documentation>Rodzaj odliczania ulgi podatkowej.</xs:documentation>
        </xs:annotation>
      </xs:element>
    </xs:sequence>
    <xs:attribute name="NaliczaniePodatku" type="xs:boolean">
      <xs:annotation>
        <xs:documentation>Włączenie naliczania podatku w ramach umowy.</xs:documentation>
      </xs:annotation>
    </xs:attribute>
    <xs:attribute name="OdliczanieUlgi" type="xs:boolean" use="optional">
      <xs:annotation>
        <xs:documentation>Atrybut już nieużywany.
                          Włączenie odliczania ulgi podatkowej.
        </xs:documentation>
      </xs:annotation>
    </xs:attribute>
  </xs:complexType>

  <xs:complexType name="TPodatekUC">
    <xs:annotation>
      <xs:documentation>Dane naliczanego podatku w ramach umowy cywilnoprawnej.</xs:documentation>
    </xs:annotation>
    <xs:sequence>    
      <xs:element name="OdliczanieUlgi" type="wspolne:TOdliczanieUlgi" minOccurs="0">
        <xs:annotation>
          <xs:documentation>Rodzaj odliczania ulgi podatkowej.</xs:documentation>
        </xs:annotation>
      </xs:element>
    </xs:sequence>
  </xs:complexType>  
  
  <xs:simpleType name="TTypWyplaty">
    <xs:restriction base="xs:string">
      <xs:enumeration value="NaKonto">
        <xs:annotation>
          <xs:documentation>Przelew całego wynagrodzenia na konto.</xs:documentation>
        </xs:annotation>
      </xs:enumeration>
      <xs:enumeration value="CzesciowoNaKonto">
        <xs:annotation>
          <xs:documentation>Przelew części wynagrodzenia na konto.</xs:documentation>
        </xs:annotation>
      </xs:enumeration>
      <xs:enumeration value="Gotowka">
        <xs:annotation>
          <xs:documentation>Wypłata całego wynagrodzenia w gotówce.</xs:documentation>
        </xs:annotation>
      </xs:enumeration>
    </xs:restriction>
  </xs:simpleType>
  
  <xs:complexType name="TWyplata">
    <xs:annotation>
      <xs:documentation>Rodzaj wypłaty wynagrodzenia.</xs:documentation>
    </xs:annotation>
    <xs:sequence>
      <xs:element name="Typ" type="TTypWyplaty">
        <xs:annotation>
          <xs:documentation>Typ wypłaty.</xs:documentation>
        </xs:annotation>
      </xs:element>
      <xs:element name="KwotaPrzelewu" type="xs:decimal" minOccurs="0">
        <xs:annotation>
          <xs:documentation>Opcjonalna kwota do wypłaty przelewem.</xs:documentation>
        </xs:annotation>
      </xs:element>
    </xs:sequence>
  </xs:complexType>

  <xs:simpleType name="TTypUmowy">
    <xs:restriction base="xs:string">
      <xs:enumeration value="Pracownicza">
        <xs:annotation>
          <xs:documentation>Umowa pracownicza.</xs:documentation>
        </xs:annotation>
      </xs:enumeration>
      <xs:enumeration value="CywilnoPrawna">
        <xs:annotation>
          <xs:documentation>Umowa cywilno-prawna.</xs:documentation>
        </xs:annotation>
      </xs:enumeration>
    </xs:restriction>
  </xs:simpleType>

  <xs:complexType name="TRozwiazanaUmowa">
    <xs:sequence>
      <xs:element name="Data" type="xs:date">
        <xs:annotation>
          <xs:documentation>Data rozwiązania umowy.</xs:documentation>
        </xs:annotation>
      </xs:element>
      <xs:element name="Przyczyna" type="xs:string" minOccurs="0">
        <xs:annotation>
          <xs:documentation>Opcjonalna przyczyna rozwiązania umowy.</xs:documentation>
        </xs:annotation>
      </xs:element>
    </xs:sequence>
  </xs:complexType>
  
  <xs:complexType name="TUmowa">
    <xs:annotation>
      <xs:documentation>Dane umowy.</xs:documentation>
    </xs:annotation>
    <xs:sequence>
      <xs:element name="Pracownik" type="xs:string">
        <xs:annotation>
          <xs:documentation>Symbol pracownika, którego dotyczy umowa.</xs:documentation>
        </xs:annotation>
      </xs:element>
      <xs:element name="Numer" type="xs:string">
        <xs:annotation>
          <xs:documentation>Alfanumeryczny symbol (numer) umowy.</xs:documentation>
        </xs:annotation>
      </xs:element>
      <xs:element name="Kwota" type="xs:decimal" minOccurs="0">
        <xs:annotation>
          <xs:documentation>Kwota umowy.</xs:documentation>
        </xs:annotation>
      </xs:element>
      <xs:element name="TypOkresu" type="TTypOkresuUmowy">
        <xs:annotation>
          <xs:documentation>Typ okresu obowiązywania umowy.</xs:documentation>
        </xs:annotation>
      </xs:element>
      <xs:element name="Od" type="xs:date">
        <xs:annotation>
          <xs:documentation>Początek obowiązywania umowy.</xs:documentation>
        </xs:annotation>
      </xs:element>
      <xs:element name="Do" type="xs:date" minOccurs="0">
        <xs:annotation>
          <xs:documentation>Koniec obowiązywania umowy, jeśli dotyczy.</xs:documentation>
        </xs:annotation>
      </xs:element>
      <xs:element name="Wymiar" minOccurs="0">
        <xs:annotation>
          <xs:documentation>Wymiar zatrudnienia.</xs:documentation>
        </xs:annotation>
        <xs:complexType>
          <xs:attribute name="Licznik" type="xs:int">
            <xs:annotation>
              <xs:documentation>Licznik ułamka wyznaczającego wymiar zatrudnienia.</xs:documentation>
            </xs:annotation>
          </xs:attribute>
          <xs:attribute name="Mianownik" type="xs:int">
            <xs:annotation>
              <xs:documentation>Mianownik ułamka wyznaczającego wymiar zatrudnienia.</xs:documentation>
            </xs:annotation>
          </xs:attribute>
        </xs:complexType>
      </xs:element>
      <xs:element name="Opis" type="xs:string" minOccurs="0">
        <xs:annotation>
          <xs:documentation>Opis umowy.</xs:documentation>
        </xs:annotation>
      </xs:element>
      <xs:element name="SkladnikiPlacowe" minOccurs="0">
        <xs:complexType>
          <xs:sequence>
            <xs:element name="Skladnik" type="TSkladnikPlacowyZWartosciami" minOccurs="0" maxOccurs="unbounded">
              <xs:annotation>
                <xs:documentation>Wartości składnika płacowego.</xs:documentation>
              </xs:annotation>
            </xs:element>
          </xs:sequence>
        </xs:complexType>
      </xs:element>
      <xs:element name="KodUbezpieczenia" type="xs:string">
        <xs:annotation>
          <xs:documentation>Kod tytułu ubezpieczenia.</xs:documentation>
        </xs:annotation>
      </xs:element>
      <xs:element name="GenerowanyRaport" type="TTypRaportuZUS" minOccurs="0">
        <xs:annotation>
          <xs:documentation>Opcjonalny typ raportu generowanego dla ZUS.</xs:documentation>
        </xs:annotation>
      </xs:element>
      <xs:element name="SkladkiZUS" type="TSkladkiZUS">
        <xs:annotation>
          <xs:documentation>Typy naliczanych składek ZUS.</xs:documentation>
        </xs:annotation>
      </xs:element>
      <xs:element name="Podatek" type="TPodatek" minOccurs="0">
        <xs:annotation>
          <xs:documentation>Dane naliczanego podatku w ramach umowy o pracę.</xs:documentation>
        </xs:annotation>
      </xs:element>
      <xs:element name="PodatekUC" type="TPodatekUC" minOccurs="0">
        <xs:annotation>
          <xs:documentation>Dane naliczanego podatku w ramach umowy cywilnoprawnej.</xs:documentation>
        </xs:annotation>
      </xs:element>
      <xs:element name="Wyplata" type="TWyplata">
        <xs:annotation>
          <xs:documentation>Rodzaj wypłaty wynagrodzenia.</xs:documentation>
        </xs:annotation>
      </xs:element>
      <xs:element name="Rozwiazanie" type="TRozwiazanaUmowa" minOccurs="0">
        <xs:annotation>
          <xs:documentation>Opcjonalne dane rozwiązanej umowy (data, przyczyna).</xs:documentation>
        </xs:annotation>
      </xs:element>
      <xs:element name="Tresc" type="xs:string">
        <xs:annotation>
          <xs:documentation>Treść umowy w formacie tekstu RTF zakodowanego jako hex.</xs:documentation>
        </xs:annotation>
      </xs:element>
      <xs:element minOccurs="0" name="WlasneRozszerzone">
        <xs:annotation>
          <xs:documentation>Wartości pól własnych wspólnika.</xs:documentation>
        </xs:annotation>
        <xs:complexType>
          <xs:sequence>
            <xs:element minOccurs="0" maxOccurs="unbounded" name="PoleRozszerzone">
              <xs:annotation>
                <xs:documentation>Pole własne rozszerzone podmiotu. Zawartość tego elementu jest wartością pola.</xs:documentation>
              </xs:annotation>
              <xs:complexType>
                <xs:simpleContent>
                  <xs:extension base="xs:string">
                    <xs:attribute name="Nazwa" type="xs:string" use="required">
                      <xs:annotation>
                        <xs:documentation>Nazwa pola własnego.</xs:documentation>
                      </xs:annotation>
                    </xs:attribute>
                  </xs:extension>
                </xs:simpleContent>
              </xs:complexType>
            </xs:element>
          </xs:sequence>
        </xs:complexType>
      </xs:element>
      <xs:element name="FlagaWlasna" minOccurs="0">
        <xs:annotation>
          <xs:documentation>Dane flagi własnej.</xs:documentation>
        </xs:annotation>
        <xs:complexType>
          <xs:all>
            <xs:element minOccurs="1" maxOccurs="1" name="Kolor" type="xs:string">
              <xs:annotation>
                <xs:documentation>Kolor flagi własnej.</xs:documentation>
              </xs:annotation>
            </xs:element>
            <xs:element minOccurs="0" maxOccurs="1" name="Ksztalt" type="xs:string">
              <xs:annotation>
                <xs:documentation>Kształt flagi własnej.</xs:documentation>
              </xs:annotation>
            </xs:element>
            <xs:element minOccurs="0" maxOccurs="1" name="Komentarz" type="xs:string">
              <xs:annotation>
                <xs:documentation>Komentarz flagi własnej.</xs:documentation>
              </xs:annotation>
            </xs:element>
          </xs:all>
        </xs:complexType>
      </xs:element>
    </xs:sequence>
    <xs:attribute name="Typ" type="TTypUmowy">
      <xs:annotation>
        <xs:documentation>Rodzaj umowy.</xs:documentation>
      </xs:annotation>
    </xs:attribute>
  </xs:complexType>

  <xs:complexType name="TSkladnikPlacowyZWartosciami">
    <xs:annotation>
      <xs:documentation>Nazwa składnika płacowego wraz z wartościami w okresach.</xs:documentation>
    </xs:annotation>
    <xs:sequence>
      <xs:element name="Nazwa" type="xs:string">
        <xs:annotation>
          <xs:documentation>Nazwa składnika płacowego.</xs:documentation>
        </xs:annotation>
      </xs:element>
      <xs:element name="WartosciSkladnikow">
        <xs:annotation>
          <xs:documentation>Wartości składnika płacowego w okresach.</xs:documentation>
        </xs:annotation>
        <xs:complexType>
          <xs:sequence>
            <xs:element name="WartoscSkladnika" type="TWartoscSkladnikaPlacowego" minOccurs="0" maxOccurs="unbounded">
              <xs:annotation>
                <xs:documentation>Pojedyncza wartość składnika płacowego.</xs:documentation>
              </xs:annotation>
            </xs:element>
          </xs:sequence>
        </xs:complexType>
      </xs:element>
    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="TWartoscSkladnikaPlacowego">
    <xs:annotation>
      <xs:documentation>Wartość składnika płacowego w określonym czasie trwania umowy.</xs:documentation>
    </xs:annotation>
    <xs:sequence>

      <xs:element name="Wartosc" type="xs:decimal">
        <xs:annotation>
          <xs:documentation>Wartość składnika.</xs:documentation>
        </xs:annotation>
      </xs:element>
      <xs:element name="Mnoznik" type="xs:decimal">
        <xs:annotation>
          <xs:documentation>Mnożnik składnika.</xs:documentation>
        </xs:annotation>
      </xs:element>
      <xs:element name="Od" type="xs:date" minOccurs="0">
        <xs:annotation>
          <xs:documentation>Opcjonalny początek okresu obowiązywania składnika. Gdy nie podano - okres od początku obowiązywania umowy.</xs:documentation>
        </xs:annotation>
      </xs:element>
      <xs:element name="Do" type="xs:date" minOccurs="0">
        <xs:annotation>
          <xs:documentation>Opcjonalny koniec okresu obowiązywania składnika. Gdy nie podano - okres do końca obowiązywania umowy.</xs:documentation>
        </xs:annotation>
      </xs:element>
    </xs:sequence>
  </xs:complexType>
  
  <xs:complexType name="TUmowy">
    <xs:annotation>
      <xs:documentation>Dane umów.</xs:documentation>
    </xs:annotation>
    <xs:sequence>
      <xs:element name="Umowa" minOccurs="0" maxOccurs="unbounded" type="TUmowa">
        <xs:annotation>
          <xs:documentation>Dane umowy.</xs:documentation>
        </xs:annotation>
      </xs:element>
    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="TSzablonUmowy">
    <xs:annotation>
      <xs:documentation>Treść (szablon) pojedynczego typu umowy.</xs:documentation>
    </xs:annotation>
    <xs:sequence>
      <xs:element name="Nazwa" type="xs:string">
        <xs:annotation>
          <xs:documentation>Nazwa szablonu.</xs:documentation>
        </xs:annotation>
      </xs:element>
      <xs:element name="Tresc" type="xs:string">
        <xs:annotation>
          <xs:documentation>Treść szablonu w formacie tekstu RTF zakodowanego jako hex.</xs:documentation>
        </xs:annotation>
      </xs:element>
    </xs:sequence>
    <xs:attribute name="Typ" type="TTypUmowy">
      <xs:annotation>
        <xs:documentation>Rodzaj umowy.</xs:documentation>
      </xs:annotation>
    </xs:attribute>
  </xs:complexType>
  
  <xs:complexType name="TSzablonyUmow">
    <xs:annotation>
      <xs:documentation>Domyślne treści (szablony) umów pracowniczych.</xs:documentation>
    </xs:annotation>
    <xs:sequence>
      <xs:element name="SzablonUmowy" type="TSzablonUmowy" minOccurs="0" maxOccurs="unbounded">
        <xs:annotation>
          <xs:documentation>Treść (szablon) pojedynczego typu umowy.</xs:documentation>
        </xs:annotation>
      </xs:element>
    </xs:sequence>
  </xs:complexType>
  
  <xs:complexType name="TUmowyPracownicze">
    <xs:annotation>
      <xs:documentation>Dane umów pracowniczych wraz z definicją składników płacowych.</xs:documentation>
    </xs:annotation>
    <xs:sequence>
      <xs:element name="SkladnikiPlacowe" type="TSkladnikiPlacowe">
        <xs:annotation>
          <xs:documentation>Dane składników płacowych</xs:documentation>
        </xs:annotation>
      </xs:element>
      <xs:element name="SzablonyUmow" type="TSzablonyUmow">
        <xs:annotation>
          <xs:documentation>Domyślne treści (szablony) umów pracowniczych.</xs:documentation>
        </xs:annotation>
      </xs:element>
      <xs:element name="Umowy" type="TUmowy">
        <xs:annotation>
          <xs:documentation>Dane umów pracowniczych.</xs:documentation>
        </xs:annotation>
      </xs:element>
    </xs:sequence>
  </xs:complexType>

  <xs:element name="UmowyPracownicze" type="TUmowyPracownicze">
    <xs:annotation>
      <xs:documentation>Umowy pracownicze.</xs:documentation>
    </xs:annotation>
  </xs:element>
</xs:schema>