<?xml version="1.0" encoding="utf-8"?>
<xs:schema
  attributeFormDefault="unqualified" 
  elementFormDefault="qualified" 
  targetNamespace="http://schemas.insert.com.pl/2015/hop/gratyfikant" 
  xmlns="http://schemas.insert.com.pl/2015/hop/gratyfikant"
  xmlns:xs="http://www.w3.org/2001/XMLSchema">

  <xs:simpleType name="TSposobRozliczenia">
    <xs:restriction base="xs:string">
      <xs:enumeration value="Automatyczne">
        <xs:annotation>
          <xs:documentation>Rozliczenie automatyczne.</xs:documentation>
        </xs:annotation>
      </xs:enumeration>
      <xs:enumeration value="Reczne">
        <xs:annotation>
          <xs:documentation>Rozliczenie ręczne.</xs:documentation>
        </xs:annotation>
      </xs:enumeration>
    </xs:restriction>
  </xs:simpleType>

  <xs:complexType name="TPolaWlasne">
    <xs:sequence>
      <xs:element minOccurs="0" maxOccurs="unbounded" name="PoleRozszerzone">
        <xs:annotation>
          <xs:documentation>Pole własne rozszerzone. Zawartość tego elementu jest wartością pola.</xs:documentation>
        </xs:annotation>
        <xs:complexType>
          <xs:simpleContent>
            <xs:extension base="xs:string">
              <xs:attribute name="Nazwa" type="xs:string" use="required">
                <xs:annotation>
                  <xs:documentation>Nazwa pola własnego.</xs:documentation>
                </xs:annotation>
              </xs:attribute>
            </xs:extension>
          </xs:simpleContent>
        </xs:complexType>
      </xs:element>
    </xs:sequence>
  </xs:complexType>

  <!-- Xsd2Code nie chce generować enumów jeśli nie są użyte w tym pliku -->
  <xs:complexType name="Dummy">
    <xs:annotation>
      <xs:documentation>Zarezerwowane.</xs:documentation>
    </xs:annotation>
    <xs:attribute name="Dummy1" type="TSposobRozliczenia">
      <xs:annotation>
        <xs:documentation>Zarezerwowane.</xs:documentation>
      </xs:annotation>
    </xs:attribute>
  </xs:complexType>
  
</xs:schema>
