<?xml version="1.0" encoding="utf-8"?>
<xs:schema attributeFormDefault="unqualified" 
           elementFormDefault="qualified"
           targetNamespace="http://schemas.insert.com.pl/2014/hop/zestawyklientow"
           xmlns="http://schemas.insert.com.pl/2014/hop/zestawyklientow"
           xmlns:xs="http://www.w3.org/2001/XMLSchema">

  <xs:annotation>
    <xs:documentation>Zestawy klientów.</xs:documentation>
  </xs:annotation>

  <xs:complexType name="TZestawKlientow">
    <xs:annotation>
      <xs:documentation>Dane dotyczące jednego zestawu klientów.</xs:documentation>
    </xs:annotation>
    <xs:sequence>
      <xs:element name="Nazwa" type="xs:string">
        <xs:annotation>
          <xs:documentation>Nazwa zestawu klientów.</xs:documentation>
        </xs:annotation>
      </xs:element>
      <xs:element name="Opis" type="xs:string" minOccurs="0">
        <xs:annotation>
          <xs:documentation>Opis zestawu klientów.</xs:documentation>
        </xs:annotation>
      </xs:element>
      <xs:element name="Publiczny" type="xs:boolean" minOccurs="0">
        <xs:annotation>
          <xs:documentation>Określa, czy zestaw jest publiczny czy prywanty.</xs:documentation>
        </xs:annotation>
      </xs:element>
      <xs:element name="Opiekun" type="TOpiekunZestawuKlientow">
        <xs:annotation>
          <xs:documentation>Opiekun zestawu.</xs:documentation>
        </xs:annotation>
      </xs:element>
      <xs:element name="Klienci">
        <xs:annotation>
          <xs:documentation>Klienci.</xs:documentation>
        </xs:annotation>
        <xs:complexType>
          <xs:sequence minOccurs="0" maxOccurs="unbounded">
            <xs:element name ="Klient" type="TKlientWZestawieKlientow">
              <xs:annotation>
                <xs:documentation>Klient.</xs:documentation>
              </xs:annotation>
            </xs:element>
          </xs:sequence>
        </xs:complexType>
      </xs:element>
    </xs:sequence>
  </xs:complexType>

  <xs:element name="ZestawyKlientow">
    <xs:annotation>
      <xs:documentation>Zestawy klientów.</xs:documentation>
    </xs:annotation>
    <xs:complexType>
      <xs:sequence minOccurs="0" maxOccurs="unbounded" >
        <xs:element name="Zestaw" type="TZestawKlientow">
          <xs:annotation>
            <xs:documentation>Zestaw klientów.</xs:documentation>
          </xs:annotation>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>

  <xs:complexType name="TKlientWZestawieKlientow">
    <xs:annotation>
      <xs:documentation>Klienci w zestawie klientów.</xs:documentation>
    </xs:annotation>
    <xs:sequence>
      <xs:element name="Rodzaj" minOccurs="0">
        <xs:annotation>
          <xs:documentation>Rodzaj klienta. Domyślnie jest kontrahent.</xs:documentation>
        </xs:annotation>
        <xs:simpleType>
          <xs:annotation>
            <xs:documentation>Rodzaj klienta.</xs:documentation>
          </xs:annotation>
          <xs:restriction base="xs:string">
            <xs:enumeration value="Kontrahent" />
            <xs:enumeration value="PracownikKontrahenta" />
            <xs:enumeration value="Personel" />
          </xs:restriction>
        </xs:simpleType>
      </xs:element>
      <xs:element name="Sygnatura" type="xs:string">
        <xs:annotation>
          <xs:documentation>Sygnatura klienta.</xs:documentation>
        </xs:annotation>
      </xs:element>
      <xs:element name="Imie" type="xs:string" minOccurs="0">
        <xs:annotation>
          <xs:documentation>Imię klienta.</xs:documentation>
        </xs:annotation>
      </xs:element>
      <xs:element name="Nazwisko" type="xs:string" minOccurs="0">
        <xs:annotation>
          <xs:documentation>Nazwisko klienta.</xs:documentation>
        </xs:annotation>
      </xs:element>
    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="TOpiekunZestawuKlientow">
    <xs:annotation>
      <xs:documentation>Opiekun zestawu klientów.</xs:documentation>
    </xs:annotation>
    <xs:sequence>
      <xs:element name="Sygnatura" type="xs:string">
        <xs:annotation>
          <xs:documentation>Sygnatura opiekuna.</xs:documentation>
        </xs:annotation>
      </xs:element>
    </xs:sequence>
  </xs:complexType>
  
</xs:schema>
