//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PrzykladyFunkcjiWyliczaniaKZD {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PrzykladyFunkcjiWyliczaniaKZD.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nie znaleziono metody wyliczania zapotrzebowania o nazwie: {0}..
        /// </summary>
        internal static string BrakMetodyWyliczania {
            get {
                return ResourceManager.GetString("BrakMetodyWyliczania", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Asortyment nie obsługuje pól własnych..
        /// </summary>
        internal static string BrakObslugiPolWlasnych {
            get {
                return ResourceManager.GetString("BrakObslugiPolWlasnych", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nie zdefiniowano pola własnego o nazwie {0}..
        /// </summary>
        internal static string BrakPolaWlasnego {
            get {
                return ResourceManager.GetString("BrakPolaWlasnego", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wygenerowane.
        /// </summary>
        internal static string NazwaFlagiPrzesuniecia {
            get {
                return ResourceManager.GetString("NazwaFlagiPrzesuniecia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimalna ilość zamówiona.
        /// </summary>
        internal static string NazwaPolaWlasnego {
            get {
                return ResourceManager.GetString("NazwaPolaWlasnego", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MPR.
        /// </summary>
        internal static string SymbolMagazynuPrzyjec {
            get {
                return ResourceManager.GetString("SymbolMagazynuPrzyjec", resourceCulture);
            }
        }
    }
}
