//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ObslugaLogistyki.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ObslugaLogistyki.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nie można usunąć dokumentu ponieważ został zarezerwowany na nim transport samochodem dostawczym..
        /// </summary>
        internal static string BlokadaUsuwaniaDokumentuRezerwujacegoSamochodDostawczyKomunikat {
            get {
                return ResourceManager.GetString("BlokadaUsuwaniaDokumentuRezerwujacegoSamochodDostawczyKomunikat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nie można zmienić samochodu dostawczego gdyż został on zarezerwowany..
        /// </summary>
        internal static string BlokadaZmianySamochoduDostawczegoKomunikat {
            get {
                return ResourceManager.GetString("BlokadaZmianySamochoduDostawczegoKomunikat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to W słowniku samochodów dostawczych nie ma żadnych elementów..
        /// </summary>
        internal static string BrakElementowSlownikaSamochodowDostawczychKomunikat {
            get {
                return ResourceManager.GetString("BrakElementowSlownikaSamochodowDostawczychKomunikat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nie zdefiniowano pola własnego o nazwie {0}..
        /// </summary>
        internal static string BrakPolaWlasnegoKomunikat {
            get {
                return ResourceManager.GetString("BrakPolaWlasnegoKomunikat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nie zdefiniowano słownika własnego SQL o nazwie &apos;{0}&apos;..
        /// </summary>
        internal static string BrakSlownikaSamochodowDostawczychKomunikat {
            get {
                return ResourceManager.GetString("BrakSlownikaSamochodowDostawczychKomunikat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nie odnaleziono wybranego na dokumencie samochodu dostawczego w słowniku zasobów..
        /// </summary>
        internal static string BrakZasobuWBazieDanychKomunikat {
            get {
                return ResourceManager.GetString("BrakZasobuWBazieDanychKomunikat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ^(?&lt;key&gt;\w+)\s*=\s*(?&lt;value&gt;\d+)(\s*\/{2}.*)*$.
        /// </summary>
        internal static string ConfigLineRegex {
            get {
                return ResourceManager.GetString("ConfigLineRegex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Samochód dostawczy.
        /// </summary>
        internal static string NazwaPolaWlasnego {
            get {
                return ResourceManager.GetString("NazwaPolaWlasnego", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Samochody dostawcze.
        /// </summary>
        internal static string NazwaSlownikaWlasnego {
            get {
                return ResourceManager.GetString("NazwaSlownikaWlasnego", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dokument typu {0} nie obsługuje pól własnych..
        /// </summary>
        internal static string NieobslugiwanePolaWlasneKomunikat {
            get {
                return ResourceManager.GetString("NieobslugiwanePolaWlasneKomunikat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transport firmowy jest opłacalny w przypadku gdy całkowita masa towarów przekracza {0:0} kg zaś kwota do zapłaty przekracza {1:0.00} {2}. Kontrahent powinien dostawę zorganizować we własnym zakresie..
        /// </summary>
        internal static string NieoplacalnyTransportFirmowyKomunikat {
            get {
                return ResourceManager.GetString("NieoplacalnyTransportFirmowyKomunikat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Słownik &apos;{0}&apos; został niepoprawnie zdefiniowany..
        /// </summary>
        internal static string NiepoprawnieZdefiniowanySlownikSamochodowDostawczychKomunikat {
            get {
                return ResourceManager.GetString("NiepoprawnieZdefiniowanySlownikSamochodowDostawczychKomunikat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ^I\d{1,2}$.
        /// </summary>
        internal static string PoleWlasneIntegerRegex {
            get {
                return ResourceManager.GetString("PoleWlasneIntegerRegex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Podanie samochodu dostawczego nie jest wymagane..
        /// </summary>
        internal static string SamochodDostawczyNiewymaganyKomunikat {
            get {
                return ResourceManager.GetString("SamochodDostawczyNiewymaganyKomunikat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Podanie sposobu dostawy jest wymagane..
        /// </summary>
        internal static string SposobDostawyWymaganyKomunikat {
            get {
                return ResourceManager.GetString("SposobDostawyWymaganyKomunikat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Na dokumentach realizowanych wybrano różne samochody dostawcze..
        /// </summary>
        internal static string WieleSamochodowDostawczychNaDokumentachRealizowanychKomunikat {
            get {
                return ResourceManager.GetString("WieleSamochodowDostawczychNaDokumentachRealizowanychKomunikat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dla sposobu dostawy &apos;{0}&apos; wymagane jest ustawienie samochodu dostawczego..
        /// </summary>
        internal static string WymaganySamochodDostawczyKomunikat {
            get {
                return ResourceManager.GetString("WymaganySamochodDostawczyKomunikat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zarezerwowano samochód dostawczy {0} i dodano zadanie o numerze {1}..
        /// </summary>
        internal static string ZarezerwowanoSamochodDostawczyKomunikat {
            get {
                return ResourceManager.GetString("ZarezerwowanoSamochodDostawczyKomunikat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zmieniono datę {0} dokumentu ze względu na brak wolnych terminów dla samochodu dostawczego..
        /// </summary>
        internal static string ZmienionoDateDokumentuDostawyKomunikat {
            get {
                return ResourceManager.GetString("ZmienionoDateDokumentuDostawyKomunikat", resourceCulture);
            }
        }
    }
}
