<?xml version="1.0" encoding="utf-8"?>
<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified"
           xmlns="http://schemas.insert.com.pl/2015/hop/flagiwlasne"
           targetNamespace="http://schemas.insert.com.pl/2015/hop/flagiwlasne"
           xmlns:xs="http://www.w3.org/2001/XMLSchema">

  <xs:annotation>
    <xs:documentation>Flagi własne.</xs:documentation>
  </xs:annotation>
  
  <xs:complexType name="TFlagaWlasna">
    <xs:annotation>
      <xs:documentation>Dane flagi własnej.</xs:documentation>
    </xs:annotation>
    <xs:all>
      <xs:element name="Nazwa" type="xs:string">
        <xs:annotation>
          <xs:documentation>Nazwa flagi własnej.</xs:documentation>
        </xs:annotation>
      </xs:element>
      <xs:element minOccurs="0" name="Opis" type="xs:string">
        <xs:annotation>
          <xs:documentation>Opis flagi własnej.</xs:documentation>
        </xs:annotation>
      </xs:element>
      <xs:element name="Kolor" type="xs:string">
        <xs:annotation>
          <xs:documentation>
            Kolor flagi własnej w formacie #XXXXXXXX. Dopuszczalne wartości:
            #FFFFFFFF - White,
            #FFFECC02 - Yellow,
            #FFFFFF00 - Yellow,
            #FFFE99C8 - Pink,
            #FFFFC0CB - Pink,
            #FF008000 - Green,
            #FF39B54A - Green,
            #FF0000CD - MediumBlue,
            #FF0160EF - MediumBlue,
            #FF000000 - Black,
            #FF414141 - Black,
            #FF808080 - Gray,
            #FFA3A3A3 - Gray,
            #FFFF0000 - Red,
            #FFFE3B3B - Red,
            #FF87CEFA - LightSkyBlue,
            #FF00BFF3 - LightSkyBlue,
            #FFC69C6D - Olive,
            #FF808000 - Olive,
            #FFFFA500 - Orange,
            #FFDC143C - Crimson,
            #FFDDA0DD - Plum,
            #FF9400D3 - DarkViolet,
            #FF4169E1 - RoyalBlue,
            #FF9ACD32 - YellowGreen,
            #FFA52A2A - Brown.
            Jeśli podany kolor nie znajduje się na liście dopuszczalnych, domyślnie zostanie nadany kolor biały.
          </xs:documentation>
        </xs:annotation>
      </xs:element>
      <xs:element minOccurs="0" name="Ksztalt" type="xs:string">
        <xs:annotation>
          <xs:documentation>Kształt flagi własnej. Wartość z typu wyliczeniowego InsERT.Moria.Flagi.KsztaltFlagiWlasnej. Jeśli nie zostanie podana, domyślnie zostanie nadany kształt Flaga.</xs:documentation>
        </xs:annotation>
      </xs:element>
      <xs:element name="Domena" type="xs:string">
        <xs:annotation>
          <xs:documentation>
            Domena flagi własnej. Dopuszczalne wartości (bez cudzysłowu):
            "Definicje list płac",
            "Deklaracje skarbowe",
            "Deklaracje ZUS",
            "Dekretacja i księgowanie",
            "Dokumenty kasowe",
            "Działania",
            "Ewidencja akordów",
            "Ewidencja czasu pracy",
            "Ewidencja naliczeń i potrąceń",
            "Ewidencja osobowa",
            "Ewidencja potrąceń komorniczych",
            "Ewidencja prowizji",
            "Ewidencja VAT sprzedaży",
            "Ewidencja VAT zakupu",
            "Faktury sprzedaży",
            "Faktury wewnętrzne",
            "Faktury zakupu",
            "Inwentaryzacja",
            "Kompensaty",
            "Kontrahenci",
            "Korekty faktur wewnętrznych",
            "Korekty kosztów",
            "Korekty kosztów dostawy",
            "Korekty sprzedaży",
            "Korekty zakupu",
            "KPiR",
            "Noty korygujące",
            "Operacje bankowe",
            "Operacje na środkach trwałych",
            "Plan kont",
            "Promocje",
            "Przyjęcia magazynowe",
            "Rachunki do umów CP",
            "Raport kasowy",
            "Rozrachunki",
            "Schematy importu i dekretacji",
            "Składniki płacowe",
            "Sprzedaż detaliczna",
            "Szanse sprzedaży",
            "Środki trwałe",
            "Towary i uslugi",
            "Umowy cywilnoprawne",
            "Umowy o pracę",
            "Wiadomości",
            "Wyciągi bankowe",
            "Wydania magazynowe",
            "Wypłaty",
            "Zamówienia do dostawców",
            "Zamówienia od klientów",
            "Zestawy płacowe",
            "Zlecenia",
            "Zwroty detaliczne",
            </xs:documentation>
        </xs:annotation>
      </xs:element>
      <xs:element minOccurs="0" name="AutomatyczneNadawanie" type="xs:boolean">
        <xs:annotation>
          <xs:documentation>Czy automatycznie nadawać flagę własną.</xs:documentation>
        </xs:annotation>
      </xs:element>
    </xs:all>
  </xs:complexType>

  <xs:element name="FlagiWlasne">
    <xs:annotation>
      <xs:documentation>Dane słownika flag własnych.</xs:documentation>
    </xs:annotation>
    <xs:complexType>
      <xs:sequence minOccurs="0" maxOccurs="unbounded">
        <xs:element name="FlagaWlasna" type="TFlagaWlasna">
          <xs:annotation>
            <xs:documentation>Flaga własna.</xs:documentation>
          </xs:annotation>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>
