<?xml version="1.0" encoding="utf-8"?>
<xs:schema elementFormDefault="qualified"
           targetNamespace="http://schemas.insert.com.pl/2014/hop/formyplatnosci"
           xmlns="http://schemas.insert.com.pl/2014/hop/formyplatnosci"
           xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:annotation>
    <xs:documentation>Informacje o formach płatności.</xs:documentation>
  </xs:annotation>
  <xs:simpleType name="TTypPlatnosci">
    <xs:annotation>
      <xs:documentation>Dane typu płatności.</xs:documentation>
    </xs:annotation>
    <xs:restriction base="xs:string">
      <xs:enumeration value="Gotowka">
        <xs:annotation>
          <xs:documentation>Gotówka.</xs:documentation>
        </xs:annotation>
      </xs:enumeration>
      <xs:enumeration value="Odroczona">
        <xs:annotation>
          <xs:documentation>Płatność odroczona.</xs:documentation>
        </xs:annotation>
      </xs:enumeration>
      <xs:enumeration value="KartaPrzySprzedazy">
        <xs:annotation>
          <xs:documentation>Karta płatnicza przy sprzedaży.</xs:documentation>
        </xs:annotation>
      </xs:enumeration>
      <xs:enumeration value="KartaPrzyZakupie">
        <xs:annotation>
          <xs:documentation>Karta płatnicza przy zakupie.</xs:documentation>
        </xs:annotation>
      </xs:enumeration>
      <xs:enumeration value="Kredyt">
        <xs:annotation>
          <xs:documentation>Kredyt.</xs:documentation>
        </xs:annotation>
      </xs:enumeration>
    </xs:restriction>
  </xs:simpleType>

  <xs:complexType name="TRata">
    <xs:annotation>
      <xs:documentation>Dane raty rozrachunku.</xs:documentation>
    </xs:annotation>
    <xs:attribute name="Termin" type="xs:int" use="required">
      <xs:annotation>
        <xs:documentation>Termin płatności.</xs:documentation>
      </xs:annotation>
    </xs:attribute>
    <xs:attribute name="Procent" type="xs:decimal" use="required">
      <xs:annotation>
        <xs:documentation>Procent kwoty.</xs:documentation>
      </xs:annotation>
    </xs:attribute>
  </xs:complexType>
  
  <xs:complexType name="TRaty">
    <xs:annotation>
      <xs:documentation>Kolekcja rat.</xs:documentation>
    </xs:annotation>
    <xs:sequence>
      <xs:element name="Rata" minOccurs="0" maxOccurs="unbounded" type="TRata">
        <xs:annotation>
          <xs:documentation>Rata rozrachunku.</xs:documentation>
        </xs:annotation>
      </xs:element>
    </xs:sequence>
    <xs:attribute name="MinimalnaKwotaRaty" type="xs:decimal" use="required">
      <xs:annotation>
        <xs:documentation>Minimalna kwota raty.</xs:documentation>
      </xs:annotation>
    </xs:attribute>
  </xs:complexType>
  
  <xs:complexType name="TFormaPlatnosci">
    <xs:annotation>
      <xs:documentation>Dane formy płatności.</xs:documentation>
    </xs:annotation>
    <xs:sequence>
      <xs:element name="Nazwa" type="xs:string">
        <xs:annotation>
          <xs:documentation>Nazwa.</xs:documentation>
        </xs:annotation>
      </xs:element>
      <xs:element name="Typ" type="TTypPlatnosci">
        <xs:annotation>
          <xs:documentation>Typ.</xs:documentation>
        </xs:annotation>
      </xs:element>
      <xs:element name="Waluta" type="xs:string" minOccurs="0">
        <xs:annotation>
          <xs:documentation>Symbol waluty.</xs:documentation>
        </xs:annotation>
      </xs:element>
      <xs:element name="Podmiot" type="xs:string" minOccurs="0">
        <xs:annotation>
          <xs:documentation>Symbol podmiotu.</xs:documentation>
        </xs:annotation>
      </xs:element>
      <xs:element name="RachunekBankowy" type="xs:string" minOccurs="0">
        <xs:annotation>
          <xs:documentation>Numer rachunku bankowego bez spacji ani innych sparatorów.</xs:documentation>
        </xs:annotation>
      </xs:element>
      <xs:element name="Termin" type="xs:int" minOccurs="0">
        <xs:annotation>
          <xs:documentation>Termin płatności w dniach.</xs:documentation>
        </xs:annotation>
      </xs:element>
      <xs:element name="Raty" type="TRaty" minOccurs="0">
        <xs:annotation>
          <xs:documentation>Kolekcja rat.</xs:documentation>
        </xs:annotation>
      </xs:element>
    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="TFormyPlatnosci">
    <xs:annotation>
      <xs:documentation>Kolekcja form płatności.</xs:documentation>
    </xs:annotation>
    <xs:sequence>
      <xs:element name="FormaPlatnosci" maxOccurs="unbounded" minOccurs="0" type="TFormaPlatnosci">
        <xs:annotation>
          <xs:documentation>Forma płatności.</xs:documentation>
        </xs:annotation>
      </xs:element>
    </xs:sequence>
  </xs:complexType>

  <xs:element name="FormyPlatnosci" type="TFormyPlatnosci">
    <xs:annotation>
      <xs:documentation>Kolekcja form płatności.</xs:documentation>
    </xs:annotation>
  </xs:element>
</xs:schema>