<?xml version="1.0" encoding="utf-8"?>
<xs:schema attributeFormDefault="unqualified" 
           elementFormDefault="qualified"
           targetNamespace="http://schemas.insert.com.pl/2014/hop/kalendarze"
           xmlns="http://schemas.insert.com.pl/2014/hop/kalendarze"
           xmlns:xs="http://www.w3.org/2001/XMLSchema">

  <xs:annotation>
    <xs:documentation>Struktury kalendarzowe, np. cykle.</xs:documentation>
  </xs:annotation>
  
  <xs:complexType name="TCykl">
    <xs:sequence>
      <xs:element name="Typ" type="TTypCyklu">
        <xs:annotation>
          <xs:documentation>Typ cyklu określający częstotliwość pojawiania się wystąpień, np. codziennie, cotygodniowo, itp.</xs:documentation>
        </xs:annotation>
      </xs:element>
      <xs:element name="TypDnia" type="TTypDnia" minOccurs="0">
        <xs:annotation>
          <xs:documentation>Określa typ dnia, np. dzień roboczy, poniedziałek, itp.</xs:documentation>
        </xs:annotation>
      </xs:element>
      <xs:element name="DzienWMiesiacu" type="TDzienWMiesiacu" minOccurs="0">
        <xs:annotation>
          <xs:documentation>Określa, w którym dniu miesiąca pojawi się wystąpienie cykliczne, np. czwarty piątek miesiąca.</xs:documentation>
        </xs:annotation>
      </xs:element>
      <xs:element name="NrDnia" type="xs:unsignedByte" minOccurs="0">
        <xs:annotation>
          <xs:documentation>Numer dnia w miesiącu.</xs:documentation>
        </xs:annotation>
      </xs:element>
      <xs:element name="NrMiesiaca" type="xs:unsignedByte" minOccurs="0">
        <xs:annotation>
          <xs:documentation>Numer miesiąca.</xs:documentation>
        </xs:annotation>
      </xs:element>
      <xs:element name="Interwal" type="xs:int" minOccurs="0">
        <xs:annotation>
          <xs:documentation>Interwał, czyli częstotliwość pojawiania się wystąpień cyklu, np. w cyklu miesięcznym można określić, że wystąpienia mają pojawiać się co dwa miesiące.</xs:documentation>
        </xs:annotation>
      </xs:element>
      <xs:element name="ZakresPowtorzen" type="TZakresPowtorzen" minOccurs="0">
        <xs:annotation>
          <xs:documentation>Określa, jak długo wystąpienia cyklu mają się pojawiać.</xs:documentation>
        </xs:annotation>
      </xs:element>
      <xs:element name="Od" type="xs:date" minOccurs="0">
        <xs:annotation>
          <xs:documentation>Data od której mają pojawiać się wystąpienia cyklu.</xs:documentation>
        </xs:annotation>
      </xs:element>
      <xs:element name="Do" type="xs:date" minOccurs="0">
        <xs:annotation>
          <xs:documentation>Data do której mają pojawiać się wystąpienia cykliczne.</xs:documentation>
        </xs:annotation>
      </xs:element>
      <xs:element name="GodzinaPoczatku" type="xs:time" minOccurs="0">
        <xs:annotation>
          <xs:documentation>Godzina początku wystąpienia cyklicznego.</xs:documentation>
        </xs:annotation>
      </xs:element>
      <xs:element name="CzasTrwania" type="xs:int" minOccurs="0">
        <xs:annotation>
          <xs:documentation>Czas trwania wystąpienia cyklicznego.</xs:documentation>
        </xs:annotation>
      </xs:element>
      <xs:element name="IloscPowtorzen" type="xs:int" minOccurs="0">
        <xs:annotation>
          <xs:documentation>Ilość wystapień cyklicznych.</xs:documentation>
        </xs:annotation>
      </xs:element>
      <xs:element name="Dni" minOccurs="0">
        <xs:annotation>
          <xs:documentation>Dni, w ktorych ma pojawiać się wystąpienie cykliczne cotygodniowe.</xs:documentation>
        </xs:annotation>
        <xs:complexType>
          <xs:sequence minOccurs="1" maxOccurs="unbounded">
            <xs:element name="Dzien" type="TDzien">
              <xs:annotation>
                <xs:documentation>Dzień tygodnia.</xs:documentation>
              </xs:annotation>
            </xs:element>
          </xs:sequence>
        </xs:complexType>
      </xs:element>
    </xs:sequence>
  </xs:complexType>

  <xs:simpleType name="TTypCyklu">
    <xs:annotation>
      <xs:documentation>Typ cyklu.</xs:documentation>
    </xs:annotation>
    <xs:restriction base="xs:string">
      <xs:enumeration value="Codzienny">
        <xs:annotation>
          <xs:documentation>Codzienne wystąpienia cyklu.</xs:documentation>
        </xs:annotation>
      </xs:enumeration>
      <xs:enumeration value="CodziennyPowszedni">
        <xs:annotation>
          <xs:documentation>Wystapienia cyklu w dni powszednie.</xs:documentation>
        </xs:annotation>
      </xs:enumeration>
      <xs:enumeration value="Cotygodniowy">
        <xs:annotation>
          <xs:documentation>Cykl występujący w określone dni tygodnia.</xs:documentation>
        </xs:annotation>
      </xs:enumeration>
      <xs:enumeration value="ComiesiecznyDzienWMiesiacu">
        <xs:annotation>
          <xs:documentation>Cykl występujący raz w miesiącu we wskazanym dniu (np.: przedostatni dzień miesiąca).</xs:documentation>
        </xs:annotation>
      </xs:enumeration>
      <xs:enumeration value="ComiesiecznyKonkretnyDzienMiesiaca">
        <xs:annotation>
          <xs:documentation>Cykl występujący raz w miesiąciu we wskazanym wprost dniu miesiąca (np.: 2. dzień miesiąca).</xs:documentation>
        </xs:annotation>
      </xs:enumeration>
      <xs:enumeration value="CorocznyKonkretnyDzienRoku">
        <xs:annotation>
          <xs:documentation>Cykl wystepujący raz w roku we wskazanym wprost dniu (np.: 2. lutego).</xs:documentation>
        </xs:annotation>
      </xs:enumeration>
      <xs:enumeration value="CorocznyDzienWMiesiacu">
        <xs:annotation>
          <xs:documentation>Cykl wystepujący raz w roku we wskazanym dniu jednego z miesięcy (np.: 3. dzień wolny w grudniu).</xs:documentation>
        </xs:annotation>
      </xs:enumeration>
    </xs:restriction>
  </xs:simpleType>

  <xs:simpleType name="TTypDnia">
    <xs:annotation>
      <xs:documentation>Określa typ dnia.</xs:documentation>
    </xs:annotation>
    <xs:restriction base="xs:string">
      <xs:enumeration value="Dowolny">
        <xs:annotation>
          <xs:documentation>Dowolny dzień tygodnia.</xs:documentation>
        </xs:annotation>
      </xs:enumeration>
      <xs:enumeration value="Poniedzialek">
        <xs:annotation>
          <xs:documentation>Poniedziałek.</xs:documentation>
        </xs:annotation>
      </xs:enumeration>
      <xs:enumeration value="Wtorek">
        <xs:annotation>
          <xs:documentation>Wtorek.</xs:documentation>
        </xs:annotation>
      </xs:enumeration>
      <xs:enumeration value="Sroda">
        <xs:annotation>
          <xs:documentation>Środa.</xs:documentation>
        </xs:annotation>
      </xs:enumeration>
      <xs:enumeration value="Czwartek">
        <xs:annotation>
          <xs:documentation>Czwartek.</xs:documentation>
        </xs:annotation>
      </xs:enumeration>
      <xs:enumeration value="Piatek">
        <xs:annotation>
          <xs:documentation>Piątek.</xs:documentation>
        </xs:annotation>
      </xs:enumeration>
      <xs:enumeration value="Sobota">
        <xs:annotation>
          <xs:documentation>Sobota.</xs:documentation>
        </xs:annotation>
      </xs:enumeration>
      <xs:enumeration value="Niedziela">
        <xs:annotation>
          <xs:documentation>Niedziela.</xs:documentation>
        </xs:annotation>
      </xs:enumeration>
      <xs:enumeration value="DzienRoboczy">
        <xs:annotation>
          <xs:documentation>Dzień roboczy.</xs:documentation>
        </xs:annotation>
      </xs:enumeration>
      <xs:enumeration value="DzienWolny">
        <xs:annotation>
          <xs:documentation>Dzień wolny.</xs:documentation>
        </xs:annotation>
      </xs:enumeration>
    </xs:restriction>
  </xs:simpleType>

  <xs:simpleType name="TDzienWMiesiacu">
    <xs:annotation>
      <xs:documentation>Określa numer wystąpienia jakiegoś typu dnia w miesiącu, np. drugi wtorek miesiąca.</xs:documentation>
    </xs:annotation>
    <xs:restriction base="xs:string">
      <xs:enumeration value="Ostatni">
        <xs:annotation>
          <xs:documentation>Ostatni dzień danego typu w miesiącu.</xs:documentation>
        </xs:annotation>
      </xs:enumeration>
      <xs:enumeration value="Pierwszy">
        <xs:annotation>
          <xs:documentation>Pierwszy dzień danego typu w miesiącu.</xs:documentation>
        </xs:annotation>
      </xs:enumeration>
      <xs:enumeration value="Drugi">
        <xs:annotation>
          <xs:documentation>Drugi dzień danego typu w miesiącu.</xs:documentation>
        </xs:annotation>
      </xs:enumeration>
      <xs:enumeration value="Trzeci">
        <xs:annotation>
          <xs:documentation>Trzeci dzień danego typu w miesiącu.</xs:documentation>
        </xs:annotation>
      </xs:enumeration>
      <xs:enumeration value="Czwarty">
        <xs:annotation>
          <xs:documentation>Czwarty dzień danego typu w miesiącu.</xs:documentation>
        </xs:annotation>
      </xs:enumeration>
    </xs:restriction>
  </xs:simpleType>

  <xs:simpleType name="TZakresPowtorzen">
    <xs:annotation>
      <xs:documentation>Zakres powtórzeń cyklu.</xs:documentation>
    </xs:annotation>
    <xs:restriction base="xs:string">
      <xs:enumeration value="BrakZakonczenia">
        <xs:annotation>
          <xs:documentation>Nieskończona ilość powtórzeń cyklu.</xs:documentation>
        </xs:annotation>
      </xs:enumeration>
      <xs:enumeration value="IloscPowtorzen">
        <xs:annotation>
          <xs:documentation>Wskazana ilość powtórzeń cyklu, np. dwa powtórzenia.</xs:documentation>
        </xs:annotation>
      </xs:enumeration>
      <xs:enumeration value="DoDnia">
        <xs:annotation>
          <xs:documentation>Powtórzenia cyklu będą pojawiać sie do wskazanego dnia.</xs:documentation>
        </xs:annotation>
      </xs:enumeration>
    </xs:restriction>
  </xs:simpleType>

  <xs:simpleType name="TDzien">
    <xs:annotation>
      <xs:documentation>Dni tygodnia.</xs:documentation>
    </xs:annotation>
    <xs:restriction base="xs:string">
      <xs:enumeration value="PN">
        <xs:annotation>
          <xs:documentation>Poniedziałek.</xs:documentation>
        </xs:annotation>
      </xs:enumeration>
      <xs:enumeration value="WT">
        <xs:annotation>
          <xs:documentation>Wtorek.</xs:documentation>
        </xs:annotation>
      </xs:enumeration>
      <xs:enumeration value="SR">
        <xs:annotation>
          <xs:documentation>Środa.</xs:documentation>
        </xs:annotation>
      </xs:enumeration>
      <xs:enumeration value="CZ">
        <xs:annotation>
          <xs:documentation>Czwartek.</xs:documentation>
        </xs:annotation>
      </xs:enumeration>
      <xs:enumeration value="PT">
        <xs:annotation>
          <xs:documentation>Piątek.</xs:documentation>
        </xs:annotation>
      </xs:enumeration>
      <xs:enumeration value="SO">
        <xs:annotation>
          <xs:documentation>Sobota.</xs:documentation>
        </xs:annotation>
      </xs:enumeration>
      <xs:enumeration value="N">
        <xs:annotation>
          <xs:documentation>Niedziela.</xs:documentation>
        </xs:annotation>
      </xs:enumeration>
    </xs:restriction>
  </xs:simpleType>

</xs:schema>
