<?xml version="1.0" encoding="utf-8"?>
<xs:schema attributeFormDefault="unqualified"
           elementFormDefault="qualified"
           targetNamespace="http://schemas.insert.com.pl/2014/hop/kontapocztowe"
           xmlns="http://schemas.insert.com.pl/2014/hop/kontapocztowe"
           xmlns:xs="http://www.w3.org/2001/XMLSchema">

  <xs:complexType name="TSerwer">
    <xs:annotation>
      <xs:documentation>Dane serwera.</xs:documentation>
    </xs:annotation>
    <xs:sequence>
      <xs:element name="Adres" type="xs:string" minOccurs="0">
        <xs:annotation>
          <xs:documentation>Adres serwera.</xs:documentation>
        </xs:annotation>
      </xs:element>
      <xs:element name="Port" type="xs:int" minOccurs="0">
        <xs:annotation>
          <xs:documentation>Port, na którym nasłuchuje serwer.</xs:documentation>
        </xs:annotation>
      </xs:element>
      <xs:element name="Uzytkownik" type="xs:string" minOccurs="0">
        <xs:annotation>
          <xs:documentation>Nazwa użytkownika.</xs:documentation>
        </xs:annotation>
      </xs:element>
      <xs:element name="Szyfrowanie" type="TSzyfrowanie" minOccurs="0">
        <xs:annotation>
          <xs:documentation>Szyfrowanie.</xs:documentation>
        </xs:annotation>
      </xs:element>
      <xs:element name="Uwierzytelnianie" type="TUwierzytelnianie" minOccurs="0">
        <xs:annotation>
          <xs:documentation>Metody uwierzytelniania.</xs:documentation>
        </xs:annotation>
      </xs:element>
    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="TSerwerPocztyPrzychodzacej">
    <xs:complexContent>
      <xs:extension base="TSerwer">
        <xs:sequence>
          <xs:element name="Protokol">
            <xs:annotation>
              <xs:documentation>Protkół.</xs:documentation>
            </xs:annotation>
            <xs:simpleType>
              <xs:restriction base="xs:string">
                <xs:enumeration value="POP3" />
                <xs:enumeration value="IMAP" />
                <xs:enumeration value="Outlook" />
              </xs:restriction>
            </xs:simpleType>
          </xs:element>
          <xs:element name="PobieranieZalacznikow" minOccurs="0">
            <xs:annotation>
              <xs:documentation>Określa, co robić z załącznikami dla poczty przychodzącej.</xs:documentation>
            </xs:annotation>
            <xs:simpleType>
              <xs:restriction base="xs:string">
                <xs:enumeration value="NiePobieraj" />
                <xs:enumeration value="PobierajWszystkie" />
                <xs:enumeration value="PobierajMniejszeNiz" />
              </xs:restriction>
            </xs:simpleType>
          </xs:element>
          <xs:element name="Rozmiar" type="xs:int" minOccurs="0">
            <xs:annotation>
              <xs:documentation>Maksymalny rozmiar załącznika w KB.</xs:documentation>
            </xs:annotation>
          </xs:element>
          <xs:element name="PozostawKopie" minOccurs="0">
            <xs:annotation>
              <xs:documentation>Określa, czy pozostawiać kopię wiadomości na serwerze.</xs:documentation>
            </xs:annotation>
            <xs:simpleType>
              <xs:restriction base="xs:string">
                <xs:enumeration value="Tak">
                  <xs:annotation>
                    <xs:documentation>Na serwerze nie będzie pozostawiana kopia pobranych wiadomości.</xs:documentation>
                  </xs:annotation>
                </xs:enumeration>
                <xs:enumeration value="Nie">
                  <xs:annotation>
                    <xs:documentation>Na serwerze pozostawiana będzie kopia pobranych wiadomości.</xs:documentation>
                  </xs:annotation>
                </xs:enumeration>
                <xs:enumeration value="DoCzasu">
                  <xs:annotation>
                    <xs:documentation>Pozostawiona na serwerze kopia będzie usuwana po upływie liczby dni określonej w polu CzasZyciaKopii.</xs:documentation>
                  </xs:annotation>
                </xs:enumeration>
                <xs:enumeration value="DoUsuniecia">
                  <xs:annotation>
                    <xs:documentation>Pozostawiona na serwerze kopia będzie usuwana, gdy wiadomość zostanie usunięta lokalnie.</xs:documentation>
                  </xs:annotation>
                </xs:enumeration>
                <xs:enumeration value="DoCzasuDoUsuniecia">
                  <xs:annotation>
                    <xs:documentation>Połączenie dwóch powyższych.</xs:documentation>
                  </xs:annotation>
                </xs:enumeration>
              </xs:restriction>
            </xs:simpleType>
          </xs:element>
          <xs:element name="CzasZyciaKopii" type="xs:int" minOccurs="0">
            <xs:annotation>
              <xs:documentation>Czas życia kopii na serwerze (w dniach).</xs:documentation>
            </xs:annotation>
          </xs:element>
        </xs:sequence>
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>

  <xs:complexType name="TSerwerPocztyWychodzacej">
    <xs:complexContent>
      <xs:extension base="TSerwer">
        <xs:sequence>
          <xs:element name="LimityWysylania">
            <xs:annotation>
              <xs:documentation>Limity wysyłania wiadomości.</xs:documentation>
            </xs:annotation>
            <xs:complexType>
              <xs:sequence>
                <xs:element name="WTrakciePolaczenia" type="xs:int" minOccurs="0">
                  <xs:annotation>
                    <xs:documentation>Limit wysyłanych wiadomości przy jednym połączeniu.</xs:documentation>
                  </xs:annotation>
                </xs:element>
                <xs:element name="WCiaguDoby" type="xs:int" minOccurs="0">
                  <xs:annotation>
                    <xs:documentation>Limit wysyłanych wiadmości w ciągu doby.</xs:documentation>
                  </xs:annotation>
                </xs:element>
                <xs:element name="GodzinaZmianyDaty" type="xs:unsignedByte" minOccurs="0">
                  <xs:annotation>
                    <xs:documentation>Godzina zmiany daty serwera dla limitu dobowego.</xs:documentation>
                  </xs:annotation>
                </xs:element>
                <xs:element name="Niestandardowy" type="xs:int" minOccurs="0">
                  <xs:annotation>
                    <xs:documentation>Limit wysyłanych wiadomości w określonym czasie.</xs:documentation>
                  </xs:annotation>
                </xs:element>
                <xs:element name="Czas" type="xs:int" minOccurs="0">
                  <xs:annotation>
                    <xs:documentation>Liczba sekund w ciągu których można wysłać określoną liczbe wiadomości dla limitu niestandardowego.</xs:documentation>
                  </xs:annotation>
                </xs:element>
              </xs:sequence>
            </xs:complexType>
          </xs:element>
          <xs:element name="PotwierdzenieOtrzymania" type="xs:boolean" minOccurs="0">
            <xs:annotation>
              <xs:documentation>Żądaj potwierdzenie otrzymania.</xs:documentation>
            </xs:annotation>
          </xs:element>
          <xs:element name="PotwierdzeniePrzeczytania" type="xs:boolean" minOccurs="0">
            <xs:annotation>
              <xs:documentation>Żądaj potwierdzenie otrzymania.</xs:documentation>
            </xs:annotation>
          </xs:element>
          <xs:element name="KasujZalacznikiPoWyslaniu" type="xs:boolean" minOccurs="0">
            <xs:annotation>
              <xs:documentation>Czy kasować załączniki po wysłaniu wiadomości.</xs:documentation>
            </xs:annotation>
          </xs:element>
        </xs:sequence>
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>

  <xs:simpleType name="TSzyfrowanie">
    <xs:annotation>
      <xs:documentation>Szyfrowanie.</xs:documentation>
    </xs:annotation>
    <xs:restriction base="xs:string">
      <xs:enumeration value="BezSzyfrowania" />
      <xs:enumeration value="StartTLS" />
      <xs:enumeration value="SSL" />
    </xs:restriction>
  </xs:simpleType>

  <xs:simpleType name="TUwierzytelnianie">
    <xs:annotation>
      <xs:documentation>Metody uwierzytelniania.</xs:documentation>
    </xs:annotation>
    <xs:restriction base="xs:string">
      <xs:enumeration value="BezUwierzytelniania" />
      <xs:enumeration value="NormalneHaslo" />
      <xs:enumeration value="SzyfrowaneHaslo" />
    </xs:restriction>
  </xs:simpleType>

  <xs:complexType name="TKontoPocztowe">
    <xs:annotation>
      <xs:documentation>Dane konta pocztowego.</xs:documentation>
    </xs:annotation>
    <xs:sequence>
      <xs:element name="NazwaKonta" type="xs:string">
        <xs:annotation>
          <xs:documentation>Nazwa konta pocztowego.</xs:documentation>
        </xs:annotation>
      </xs:element>
      <xs:element name="NazwaWyswietlana" type="xs:string">
        <xs:annotation>
          <xs:documentation>Nazwa wyświetlana w polu Od.</xs:documentation>
        </xs:annotation>
      </xs:element>
      <xs:element name="Adres" type="xs:string">
        <xs:annotation>
          <xs:documentation>Adres e-mail konta pocztowego.</xs:documentation>
        </xs:annotation>
      </xs:element>
      <xs:element name="AdresZwrotny" type="xs:string" minOccurs="0">
        <xs:annotation>
          <xs:documentation>Adres zwrotny.</xs:documentation>
        </xs:annotation>
      </xs:element>
      <xs:element name="Aktywne" type="xs:boolean">
        <xs:annotation>
          <xs:documentation>Określa, czy konto jest aktywne.</xs:documentation>
        </xs:annotation>
      </xs:element>
      <xs:element name="SerwerPocztyPrzychodzacej" type="TSerwerPocztyPrzychodzacej">
        <xs:annotation>
          <xs:documentation>Serwer poczty przychodzącej IMAP/POP3.</xs:documentation>
        </xs:annotation>
      </xs:element>
      <xs:element name="SerwerPocztyWychodzacej" type="TSerwerPocztyWychodzacej">
        <xs:annotation>
          <xs:documentation>Serwer poczty wychodzącej SMTP.</xs:documentation>
        </xs:annotation>
      </xs:element>
      <!--<xs:element name="Format" type="TFormatWiadomosci" minOccurs="0">
        <xs:annotation>
          <xs:documentation>Domyślny format nowej wiadomości.</xs:documentation>
        </xs:annotation>
      </xs:element>-->
      <xs:element name="PriorytetDlaNowejWiadomosci">
        <xs:annotation>
          <xs:documentation>Określa, priorytet dla nowej wiadomości.</xs:documentation>
        </xs:annotation>
        <xs:simpleType>
          <xs:restriction base="xs:string">
            <xs:enumeration value="Najnizszy" />
            <xs:enumeration value="Niski" />
            <xs:enumeration value="Normalny" />
            <xs:enumeration value="Wysoki" />
            <xs:enumeration value="Najwyzszy" />
          </xs:restriction>
        </xs:simpleType>
      </xs:element>
      <!--<xs:element name="PrzeczytanaPo" type="xs:int" minOccurs="0">
        <xs:annotation>
          <xs:documentation>Oznacza wiadomość jako przeczytaną po wyświetleniu jej przez liczbę sekund określoną w tym polu.</xs:documentation>
        </xs:annotation>
      </xs:element>-->
      <xs:element name="SprawdzajPocztePrzyStarcie" type="xs:boolean" minOccurs="0">
        <xs:annotation>
          <xs:documentation>Określa, czy program ma sprawdzać pocztę przy starcie.</xs:documentation>
        </xs:annotation>
      </xs:element>
      <xs:element name="SprawdzajPoczteCo" type="xs:int" minOccurs="0">
        <xs:annotation>
          <xs:documentation>Określa co jaki czas w minutach ma następować sprawdzanie poczty.</xs:documentation>
        </xs:annotation>
      </xs:element>
      <xs:element name="PrzenosDoSkrzynkiNadawczej" type="xs:boolean" minOccurs="0">
        <xs:annotation>
          <xs:documentation>Określa, czy wysyłać wiadomości zamiast przenosić je do skrzynki nadawczej.</xs:documentation>
        </xs:annotation>
      </xs:element>
      <xs:element name="Foldery" minOccurs="0">
        <xs:annotation>
          <xs:documentation>Foldery.</xs:documentation>
        </xs:annotation>
        <xs:complexType>
          <xs:sequence minOccurs="1" maxOccurs="unbounded">
            <xs:element name="Folder" type="xs:string">
              <xs:annotation>
                <xs:documentation>Nazwa.</xs:documentation>
              </xs:annotation>
            </xs:element>
          </xs:sequence>
        </xs:complexType>
      </xs:element>
      <xs:element name="Uprawnienia" type="TUprawnieniaDoKontaPocztowego">
        <xs:annotation>
          <xs:documentation>Uprawnienia do konta.</xs:documentation>
        </xs:annotation>
      </xs:element>
    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="TUprawnieniaDoKontaPocztowego">
    <xs:annotation>
      <xs:documentation>Uprawnienia do konta.</xs:documentation>
    </xs:annotation>
    <xs:sequence>
      <xs:element name="Opiekun" type="xs:string" minOccurs="0">
        <xs:annotation>
          <xs:documentation>Sygnatura opiekuna.</xs:documentation>
        </xs:annotation>
      </xs:element>
      <xs:element name="Uzytkownicy">
        <xs:annotation>
          <xs:documentation>Użytkownicy uprawnieni do użytkownia z konta.</xs:documentation>
        </xs:annotation>
        <xs:complexType>
          <xs:sequence minOccurs="0" maxOccurs="unbounded">
            <xs:element name="Uzytkownik" type="xs:string">
              <xs:annotation>
                <xs:documentation>Sygnatura użytkownika.</xs:documentation>
              </xs:annotation>
            </xs:element>
          </xs:sequence>
        </xs:complexType>
      </xs:element>
    </xs:sequence>
  </xs:complexType>

  <xs:element name="KontaPocztowe">
    <xs:annotation>
      <xs:documentation>Konta pocztowe.</xs:documentation>
    </xs:annotation>
    <xs:complexType>
      <xs:sequence minOccurs="0" maxOccurs="unbounded">
        <xs:element name="KontoPocztowe" type="TKontoPocztowe">
          <xs:annotation>
            <xs:documentation>Konto pocztowe.</xs:documentation>
          </xs:annotation>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  
</xs:schema>