<?xml version="1.0" encoding="utf-8"?>
<xs:schema elementFormDefault="qualified"
           targetNamespace="http://schemas.insert.com.pl/2013/hop/liniekursowwalut"
           xmlns="http://schemas.insert.com.pl/2013/hop/liniekursowwalut"
           xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:annotation>
    <xs:documentation>Informacje o liniach kursów walut.</xs:documentation>
  </xs:annotation>
  <xs:complexType name="TLinieKursowWalut">
    <xs:annotation>
      <xs:documentation>Kolekcja linii kursów walut.</xs:documentation>
    </xs:annotation>
    <xs:sequence>
      <xs:element name="LiniaKursowWalut" maxOccurs="unbounded" minOccurs="0" type="xs:string">
        <xs:annotation>
          <xs:documentation>Nazwa linii kursów walut.</xs:documentation>
        </xs:annotation>
      </xs:element>
    </xs:sequence>
  </xs:complexType>

  <xs:element name="LinieKursowWalut" type="TLinieKursowWalut">
    <xs:annotation>
      <xs:documentation>Kolekcja linii kursów walut.</xs:documentation>
    </xs:annotation>
  </xs:element>
</xs:schema>