<?xml version="1.0" encoding="utf-8"?>
<xs:schema elementFormDefault="qualified"
           targetNamespace="http://schemas.insert.com.pl/2013/hop/miejscauzytkowania"
           xmlns="http://schemas.insert.com.pl/2013/hop/miejscauzytkowania"
           xmlns:xs="http://www.w3.org/2001/XMLSchema">

  <xs:simpleType name="TSymbol">
    <xs:annotation>
      <xs:documentation>Typ znakowy ograniczony do 5 znaków</xs:documentation>
    </xs:annotation>
    <xs:restriction base="xs:string">
      <xs:minLength value="1"/>
      <xs:maxLength value="5"/>
    </xs:restriction>
  </xs:simpleType>

  <xs:simpleType name="TNazwa">
    <xs:annotation>
      <xs:documentation>Typ znakowy ograniczony do 255 znaków</xs:documentation>
    </xs:annotation>
    <xs:restriction base="xs:string">
      <xs:minLength value="1"/>
      <xs:maxLength value="255"/>
    </xs:restriction>
  </xs:simpleType>

  <xs:complexType name="TMiejsceUzytkowaniaInfo">
    <xs:sequence>
      <xs:element type="TSymbol" name="Symbol" minOccurs="1" maxOccurs="1"/>
      <xs:element type="TNazwa" name="Nazwa" minOccurs="1" maxOccurs="1"/>
    </xs:sequence>    
  </xs:complexType>

  <xs:complexType name="TMiejsceUzytkowania">
    <xs:sequence>
      <xs:element type="TSymbol" name="Symbol" minOccurs="1" maxOccurs="1"/>
      <xs:element type="TNazwa" name="Nazwa" minOccurs="1" maxOccurs="1"/>      
    </xs:sequence>
    <xs:attribute name="Aktywne" type="xs:byte" use="required" />
  </xs:complexType>

  <xs:complexType name="TMiejscaUzytkowania">
    <xs:sequence>
      <xs:element name="MiejsceUzytkowania" maxOccurs="unbounded" minOccurs="0" type="TMiejsceUzytkowania"/>
    </xs:sequence>
  </xs:complexType>

  <xs:element name="MiejscaUzytkowania" type="TMiejscaUzytkowania"/>
</xs:schema>