<?xml version="1.0" encoding="utf-8"?>
<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified"
           xmlns="http://schemas.insert.com.pl/2013/hop/danepodmiotu"
           targetNamespace="http://schemas.insert.com.pl/2013/hop/danepodmiotu"
           xmlns:xs="http://www.w3.org/2001/XMLSchema"
           xmlns:sd="http://schemas.xsddoc.codeplex.com/schemaDoc/2009/3"
           xmlns:maml="http://ddue.schemas.microsoft.com/authoring/2003/5"
           xmlns:wspolne="http://schemas.insert.com.pl/2013/hop">
  <xs:annotation>
    <xs:documentation>Dane firmy jako podmiotu gospodarczego.</xs:documentation>
  </xs:annotation>

  <xs:import id="WspolnePart" namespace="http://schemas.insert.com.pl/2013/hop" schemaLocation="Wspolne.xsd"/>

  <xs:simpleType name="TFormaPrawnaFirmy">
    <xs:restriction base="xs:string">
      <xs:enumeration value="InnaNizWlasnoscPrywatna">
        <xs:annotation>
          <xs:documentation>Forma prawna firmy inna niż własność prywatna.</xs:documentation>
        </xs:annotation>
      </xs:enumeration>
      <xs:enumeration value="PrywatnaFirmaOsobyFizycznej">
        <xs:annotation>
          <xs:documentation>Przedsiębiorstwo prywatne osoby fizycznej, wymagające wskazania właściciela.</xs:documentation>
        </xs:annotation>
      </xs:enumeration>
    </xs:restriction>
  </xs:simpleType>
  
  <xs:element name="MojaFirma">
    <xs:annotation>
      <xs:documentation>Dane podmiotu gospodarczego.</xs:documentation>
    </xs:annotation>
    <xs:complexType>
      <xs:all>
        <xs:element minOccurs="0" name="Sygnatura" type="xs:string">
          <xs:annotation>
            <xs:documentation>Symbol.</xs:documentation>
          </xs:annotation>
        </xs:element>
        <xs:element name="DaneFirmy">
          <xs:annotation>
            <xs:documentation>Dane firmy.</xs:documentation>
          </xs:annotation>
          <xs:complexType>
            <xs:all>
              <xs:element name="REGON" type="xs:string" minOccurs="0">
                <xs:annotation>
                  <xs:documentation>Numer REGON.</xs:documentation>
                </xs:annotation>
              </xs:element>
              <xs:element name="Nazwa" type="xs:string">
                <xs:annotation>
                  <xs:documentation>Pełna nazwa firmy.</xs:documentation>
                </xs:annotation>
              </xs:element>
              <xs:element name="NazwaSkrocona" type="xs:string">
                <xs:annotation>
                  <xs:documentation>Skrócona nazwa firmy.</xs:documentation>
                </xs:annotation>
              </xs:element>
            </xs:all>
          </xs:complexType>
        </xs:element>
        <xs:element name="NazwaPlatnik" type="xs:string" minOccurs="0">
          <xs:annotation>
            <xs:documentation>Nazwa firmy dla programu Płatnik.</xs:documentation>
          </xs:annotation>
        </xs:element>
        <xs:element name="TerminSkladaniaDeklaracjiZUS" type="wspolne:TerminSkladaniaDeklaracjiZUS" minOccurs="0">
          <xs:annotation>
            <xs:documentation>Termin składania deklaracji ZUS.</xs:documentation>
          </xs:annotation>
        </xs:element>
        <xs:element name="NIP" type="xs:string">
          <xs:annotation>
            <xs:documentation>Numer NIP.</xs:documentation>
          </xs:annotation>
        </xs:element>
        <xs:element name="UE" minOccurs="0" type="wspolne:FirmaUE">
          <xs:annotation>
            <xs:documentation>Cechy rejestracji podmiotu w zakresie handlu w UE.</xs:documentation>
          </xs:annotation>
        </xs:element>

        <xs:element name="Kontakty" type="wspolne:Kontakty" minOccurs="0">
          <xs:annotation>
            <xs:documentation>Dane kontaktowe.</xs:documentation>
          </xs:annotation>
        </xs:element>
        <xs:element name="Adresy" type="wspolne:Adresy">
          <xs:annotation>
            <xs:documentation>Adresy podmiotu. Jeden, główny adres jest wymagany.</xs:documentation>
          </xs:annotation>
        </xs:element>
        <xs:element name="US" type="xs:string" minOccurs="0">
          <xs:annotation>
            <xs:documentation>Symbol urzędu skarbowego właściwego dla podmiotu.</xs:documentation>
          </xs:annotation>
        </xs:element>
        <xs:element name="FormaPrawna" type="TFormaPrawnaFirmy" minOccurs="0">
          <xs:annotation>
            <xs:documentation>Forma prawna firmy</xs:documentation>
          </xs:annotation>
        </xs:element>
        <xs:element name="Wlasciciel" type="xs:string" minOccurs="0">
          <xs:annotation>
            <xs:documentation>Symbol wspólnika - właściciela firmy. Wymagane dla przedsiębiorstw prywatnych osób fizycznych.</xs:documentation>
          </xs:annotation>
        </xs:element>

        <xs:element name="ModelOrganizacyjny">
          <xs:annotation>
            <xs:documentation>Podział firmy na jednostki organizacyjne.</xs:documentation>
          </xs:annotation>
          <xs:complexType>
            <xs:all>
              <xs:element name="Centrala">
                <xs:annotation>
                  <xs:documentation>Dane centrali firmy.</xs:documentation>
                </xs:annotation>
                <xs:complexType>
                  <xs:all>
                    <xs:element name="Symbol" type="xs:string">
                      <xs:annotation>
                        <xs:documentation>Symbol centrali.</xs:documentation>
                      </xs:annotation>
                    </xs:element>
                    <xs:element name="Opis" minOccurs="0" type="xs:string">
                      <xs:annotation>
                        <xs:documentation>Opis centrali.</xs:documentation>
                      </xs:annotation>
                    </xs:element>
                    <xs:element name="CennikGlowny" minOccurs="0" type="xs:string">
                      <xs:annotation>
                        <xs:documentation>Domyślny cennik główny dla centrali.</xs:documentation>
                      </xs:annotation>
                    </xs:element>
                  </xs:all>
                </xs:complexType>
              </xs:element>
              <xs:element minOccurs="0" name="Oddzial">
                <xs:annotation>
                  <xs:documentation>Dane oddziału firmy.</xs:documentation>
                </xs:annotation>
                <xs:complexType>
                  <xs:all>
                    <xs:element name="Nazwa" type="xs:string">
                      <xs:annotation>
                        <xs:documentation>Nazwa oddziału.</xs:documentation>
                      </xs:annotation>
                    </xs:element>
                    <xs:element name="Symbol" type="xs:string">
                      <xs:annotation>
                        <xs:documentation>Unikalny symbol oddziału.</xs:documentation>
                      </xs:annotation>
                    </xs:element>
                    <xs:element name="Opis" minOccurs="0" type="xs:string">
                      <xs:annotation>
                        <xs:documentation>Opis oddziału.</xs:documentation>
                      </xs:annotation>
                    </xs:element>
                    <xs:element name="CennikGlowny" minOccurs="0" type="xs:string">
                      <xs:annotation>
                        <xs:documentation>Domyślny cennik główny dla oddziału.</xs:documentation>
                      </xs:annotation>
                    </xs:element>
                  </xs:all>
                </xs:complexType>
              </xs:element>
            </xs:all>
          </xs:complexType>
        </xs:element>

        <xs:element name="Magazyny">
          <xs:annotation>
            <xs:documentation>Magazyny firmy.</xs:documentation>
          </xs:annotation>
          <xs:complexType>
            <xs:sequence>
              <xs:element name="Magazyn" minOccurs="0" maxOccurs="unbounded">
                <xs:annotation>
                  <xs:documentation>Dane magazynu.</xs:documentation>
                </xs:annotation>
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="Symbol" type="xs:string">
                      <xs:annotation>
                        <xs:documentation>Symbol magazynu.</xs:documentation>
                      </xs:annotation>
                    </xs:element>
                    <xs:element name="Nazwa" type="xs:string">
                      <xs:annotation>
                        <xs:documentation>Nazwa magazynu.</xs:documentation>
                      </xs:annotation>
                    </xs:element>
                    <xs:element name="Opis" type="xs:string">
                      <xs:annotation>
                        <xs:documentation>Opis magazynu.</xs:documentation>
                      </xs:annotation>
                    </xs:element>
                    <xs:element name="SposobWydawaniaTowaru" minOccurs="0" type="xs:string">
                      <xs:annotation>
                        <xs:appinfo>
                          <sd:schemaDoc>
                            <maml:summary>
                              <maml:para>
                                Sposób wydawania towaru. Identyfikator funkcji określającej kolejność wydawania towaru z magazynu (<maml:externalLink>
                                  <maml:linkText>więcej...</maml:linkText>
                                  <maml:linkUri>mk:@MSITStore:InsERT.nexo.Sfera.chm::/html/ACAFE329.htm</maml:linkUri>
                                  <maml:linkTarget>_self</maml:linkTarget>
                                </maml:externalLink>).
                              </maml:para>
                            </maml:summary>
                          </sd:schemaDoc>
                        </xs:appinfo>
                        <xs:documentation>Sposób wydawania towaru. Identyfikator funkcji określającej kolejność wydawania towaru z magazynu.</xs:documentation>
                      </xs:annotation>
                    </xs:element>

                    <xs:element name="Adresy" type="wspolne:Adresy">
                      <xs:annotation>
                        <xs:documentation>Adres magazynu. Jeśli będzie więcej niż jeden, zaimportowany zostanie jedynie pierwszy adres.</xs:documentation>
                      </xs:annotation>
                    </xs:element>

                    <xs:element minOccurs="0" name="Sektory">
                      <xs:annotation>
                        <xs:documentation>Podział magazynu na sektory.</xs:documentation>
                      </xs:annotation>
                      <xs:complexType>
                        <xs:sequence>
                          <xs:element maxOccurs="unbounded" name="Sektor" type="xs:string">
                            <xs:annotation>
                              <xs:documentation>Unikalna nazwa sektora.</xs:documentation>
                            </xs:annotation>
                          </xs:element>
                        </xs:sequence>
                      </xs:complexType>
                    </xs:element>

                    <xs:element minOccurs="0" name="JednostkiOrganizacyjne">
                      <xs:annotation>
                        <xs:documentation>Jednostki organizacyjne firmy (centrala, oddział), do których jest przypisany magazyn.</xs:documentation>
                      </xs:annotation>
                      <xs:complexType>
                        <xs:sequence>
                          <xs:element maxOccurs="unbounded" name="Jednostka">
                            <xs:annotation>
                              <xs:documentation>Symbol jednostki organizacyjnej, do której jest przypisany magazyn.</xs:documentation>
                            </xs:annotation>
                            <xs:complexType>
                              <xs:simpleContent>
                                <xs:extension base="xs:string">
                                  <xs:attribute name="Glowny" type="xs:boolean" use="optional">
                                    <xs:annotation>
                                      <xs:documentation>Określa, czy w danej jednostce ten magazyn jest magazynem głównym.</xs:documentation>
                                    </xs:annotation>
                                  </xs:attribute>
                                </xs:extension>
                              </xs:simpleContent>
                            </xs:complexType>
                          </xs:element>
                        </xs:sequence>
                      </xs:complexType>
                    </xs:element>
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
        
        <xs:element name="Cenniki">
          <xs:complexType>
            <xs:sequence>
              <xs:element minOccurs="0" maxOccurs="unbounded" name="Cennik">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="Typ">
                      <xs:annotation>
                        <xs:documentation>Typ cennika.</xs:documentation>
                      </xs:annotation>
                      <xs:simpleType>
                        <xs:restriction base="xs:string">
                          <xs:enumeration value="S">
                            <xs:annotation>
                              <xs:documentation>Statyczny.</xs:documentation>
                            </xs:annotation>
                          </xs:enumeration>
                          <xs:enumeration value="D">
                            <xs:annotation>
                              <xs:documentation>Dynamiczny.</xs:documentation>
                            </xs:annotation>
                          </xs:enumeration>
                        </xs:restriction>
                      </xs:simpleType>
                    </xs:element>
                    <xs:element name="Status">
                      <xs:annotation>
                        <xs:documentation>Status cennika.</xs:documentation>
                      </xs:annotation>
                      <xs:simpleType>
                        <xs:restriction base="xs:string">
                          <xs:enumeration value="P">
                            <xs:annotation>
                              <xs:documentation>W przygotowaniu.</xs:documentation>
                            </xs:annotation>
                          </xs:enumeration>
                          <xs:enumeration value="O">
                            <xs:annotation>
                              <xs:documentation>Opublikowany.</xs:documentation>
                            </xs:annotation>
                          </xs:enumeration>
                          <xs:enumeration value="Z">
                            <xs:annotation>
                              <xs:documentation>Zakończony.</xs:documentation>
                            </xs:annotation>
                          </xs:enumeration>
                        </xs:restriction>
                      </xs:simpleType>
                    </xs:element>
                    <xs:choice>
                      <xs:element name="Symbol" type="xs:string">
                        <xs:annotation>
                          <xs:documentation>Symbol cennika, gdy jest to cennik główny. Musi być unikalny.</xs:documentation>
                        </xs:annotation>
                      </xs:element>
                      <xs:element name="CennikGlowny" type="xs:string">
                        <xs:annotation>
                          <xs:documentation>Symbol cennika głównego dla cennika dodatkowego.</xs:documentation>
                        </xs:annotation>
                      </xs:element>
                    </xs:choice>
                    <xs:element name="Nazwa" type="xs:string">
                      <xs:annotation>
                        <xs:documentation>Nazwa cennika. Musi być unikalna, gdy jest to cennik dodatkowy.</xs:documentation>
                      </xs:annotation>
                    </xs:element>
                    <xs:element name="Opis" type="xs:string" />
                    <xs:element name="Waluta" type="xs:string">
                      <xs:annotation>
                        <xs:documentation>Symbol waluty cennika.</xs:documentation>
                      </xs:annotation>
                    </xs:element>
                    <xs:element minOccurs="0" name="LiniaKursow" type="xs:string" />
                    <xs:element minOccurs="0" name="OkresObowiazywania">
                      <xs:annotation>
                        <xs:documentation>Okres obowiązywania cennika. Brak tego elementu oznacza cennik bezterminowy.</xs:documentation>
                      </xs:annotation>
                      <xs:complexType>
                        <xs:sequence>
                          <xs:element name="Od" type="xs:date" />
                          <xs:element name="Do" type="xs:date" />
                        </xs:sequence>
                      </xs:complexType>
                    </xs:element>
                    <xs:element name="Kalkulacja">
                      <xs:annotation>
                          <xs:documentation>Sposób kalkulacji cen. Od netto lub brutto.</xs:documentation>
                      </xs:annotation>
                      <xs:simpleType>
                        <xs:restriction base="xs:string">
                          <xs:enumeration value="netto" />
                          <xs:enumeration value="brutto" />
                        </xs:restriction>
                      </xs:simpleType>
                    </xs:element>
                    <xs:element name="SposobWyliczania">
                      <xs:annotation>
                        <xs:documentation>Sposób wyliczania cen. Od zadanego narzutu, marży lub zysku.</xs:documentation>
                      </xs:annotation>
                      <xs:complexType>
                        <xs:sequence>
                          <xs:element name="Podstawa">
                            <xs:annotation>
                              <xs:documentation>Sposób wyliczania cen w cenniku.</xs:documentation>
                            </xs:annotation>
                            <xs:simpleType>
                              <xs:restriction base="xs:string">
                                <xs:enumeration value="narzut">
                                  <xs:annotation>
                                    <xs:documentation>Wyliczanie cen od narzutu. Wartość narzutu (element Wartosc) powinna być podana w postaci liczby (nie w procentach).</xs:documentation>
                                  </xs:annotation>
                                </xs:enumeration>
                                <xs:enumeration value="marza">
                                  <xs:annotation>
                                    <xs:documentation>Wyliczanie cen od marży. Wartość marży (element Wartosc) powinna być podana w postaci liczby (nie w procentach).</xs:documentation>
                                  </xs:annotation>
                                </xs:enumeration>
                                <xs:enumeration value="zysk">
                                  <xs:annotation>
                                    <xs:documentation>Wyliczanie cen od podanego zysku. Wartość zysku (element Wartosc) powinna być podana kwotowo w walucie cennika.</xs:documentation>
                                  </xs:annotation>
                                </xs:enumeration>
                              </xs:restriction>
                            </xs:simpleType>
                          </xs:element>
                          <xs:element name="Wartosc" type="xs:decimal">
                            <xs:annotation>
                              <xs:documentation>Wartość parametru dla sposobu wyliczania cen.</xs:documentation>
                            </xs:annotation>
                          </xs:element>
                        </xs:sequence>
                      </xs:complexType>
                    </xs:element>
                    <xs:element name="Rabat" type="xs:decimal">
                      <xs:annotation>
                        <xs:documentation>Domyślny rabat. Wartość powinna być podana w postaci liczby (nie procent).</xs:documentation>
                      </xs:annotation>
                    </xs:element>
                    <xs:element name="RabatMaksymalny" type="xs:decimal">
                      <xs:annotation>
                        <xs:documentation>Maksymalny rabat. Wartość powinna być podana w postaci liczby (nie procent).</xs:documentation>
                      </xs:annotation>
                    </xs:element>
                    <xs:element minOccurs="0" name="FunkcjaWyboruPozycjiCennika" type="xs:string">
                      <xs:annotation>
                        <xs:appinfo>
                          <sd:schemaDoc>
                            <maml:summary>
                              <maml:para>
                                Sposób wyboru pozycji do cennika. Identyfikator funkcji (<maml:externalLink>
                                  <maml:linkText>więcej...</maml:linkText>
                                  <maml:linkUri>mk:@MSITStore:InsERT.nexo.Sfera.chm::/html/439F6970.htm</maml:linkUri>
                                  <maml:linkTarget>_self</maml:linkTarget>
                                </maml:externalLink>).
                              </maml:para>
                            </maml:summary>
                          </sd:schemaDoc>
                        </xs:appinfo>
                        <xs:documentation>Sposób wyboru pozycji do cennika. Identyfikator funkcji.</xs:documentation>
                      </xs:annotation>
                    </xs:element>
                    <xs:element name="FunkcjaWyliczaniaCenyDlaTowarow" type="xs:string">
                      <xs:annotation>
                         <xs:appinfo>
                          <sd:schemaDoc>
                            <maml:summary>
                              <maml:para>
                                Sposób wyliczania cen dla towarów. Identyfikator funkcji z podzbioru dla towarów (<maml:externalLink>
                                  <maml:linkText>więcej...</maml:linkText>
                                  <maml:linkUri>mk:@MSITStore:InsERT.nexo.Sfera.chm::/html/31B39617.htm</maml:linkUri>
                                  <maml:linkTarget>_self</maml:linkTarget>
                                </maml:externalLink>).
                              </maml:para>
                            </maml:summary>
                          </sd:schemaDoc>
                        </xs:appinfo>
                        <xs:documentation>Sposób wyliczania cen dla towarów. Identyfikator funkcji.</xs:documentation>
                      </xs:annotation>
                    </xs:element>
                    <xs:element name="FunkcjaWyliczaniaCenyDlaUslug" type="xs:string">
                      <xs:annotation>
                        <xs:appinfo>
                          <sd:schemaDoc>
                            <maml:summary>
                              <maml:para>
                                Sposób wyliczania cen dla usług. Identyfikator funkcji z podzbioru dla usług (<maml:externalLink>
                                  <maml:linkText>więcej...</maml:linkText>
                                  <maml:linkUri>mk:@MSITStore:InsERT.nexo.Sfera.chm::/html/31B39617htm</maml:linkUri>
                                  <maml:linkTarget>_self</maml:linkTarget>
                                </maml:externalLink>).
                              </maml:para>
                            </maml:summary>
                          </sd:schemaDoc>
                        </xs:appinfo>
                        <xs:documentation>Sposób wyliczania cen dla usług. Identyfikator funkcji.</xs:documentation>
                      </xs:annotation>
                    </xs:element>
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
          </xs:complexType>
        </xs:element>

        <xs:element minOccurs="0" name="Uzytkownicy">
          <xs:annotation>
            <xs:documentation>Użytkownicy systemu.</xs:documentation>
          </xs:annotation>
          <xs:complexType>
            <xs:sequence>
              <xs:element maxOccurs="unbounded" name="Uzytkownik">
                <xs:annotation>
                  <xs:documentation>Dane użytkownika systemu.</xs:documentation>
                </xs:annotation>
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="Sygnatura" type="xs:string">
                      <xs:annotation>
                        <xs:documentation>Symbol użytkownika. Jeśli istnieje pracownik o tym symbolu, dane te zostaną powiązane.</xs:documentation>
                      </xs:annotation>
                    </xs:element>
                    <xs:element name="Imie" type="xs:string" minOccurs="0">
                      <xs:annotation>
                        <xs:documentation>Imię użytkownika.</xs:documentation>
                      </xs:annotation>
                    </xs:element>
                    <xs:element name="Nazwisko" type="xs:string">
                      <xs:annotation>
                        <xs:documentation>Nazwisko użytkownika.</xs:documentation>
                      </xs:annotation>
                    </xs:element>
                    <xs:element name="SygnaturaKsiegowa" type="xs:string" minOccurs="0">
                      <xs:annotation>
                        <xs:documentation>Sygnatura księgowa użytkownika.</xs:documentation>
                      </xs:annotation>
                    </xs:element>
                    <xs:element name="Szef" type="xs:boolean" minOccurs="0">
                      <xs:annotation>
                        <xs:documentation>Flaga mówiąca o tym, czy użytkownik jest Szefem.</xs:documentation>
                      </xs:annotation>
                    </xs:element>
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
        <xs:element name="BibliotekaDokumentow" type="wspolne:TBibliotekaDokumentow" minOccurs="0">
          <xs:annotation>
            <xs:documentation>Dane obiektów z biblioteki dokumentów.</xs:documentation>
          </xs:annotation>
        </xs:element>
      </xs:all>
    </xs:complexType>
  </xs:element>
</xs:schema>
