<?xml version="1.0" encoding="utf-8"?>
<xs:schema elementFormDefault="qualified"
           targetNamespace="http://schemas.insert.com.pl/2014/hop/numeracja"
           xmlns="http://schemas.insert.com.pl/2014/hop/numeracja"
           xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:annotation>
    <xs:documentation>Parametry numeracji dokumentów.</xs:documentation>
  </xs:annotation>

  <xs:complexType name="TElementFormatu" abstract="true">
    <xs:annotation>
      <xs:documentation>Dane elementu formatu.</xs:documentation>
    </xs:annotation>
    <xs:sequence>
    </xs:sequence>
    <xs:attribute name="CiagFormatujacy" type="xs:string">
      <xs:annotation>
        <xs:documentation>Ciąg formatujący.</xs:documentation>
      </xs:annotation>
    </xs:attribute>
    <xs:attribute name="NumerPorzadkowy" type="xs:int">
      <xs:annotation>
        <xs:documentation>Numer porządkowy.</xs:documentation>
      </xs:annotation>
    </xs:attribute>
  </xs:complexType>

  <xs:complexType name="TElementFormatuStala">
    <xs:annotation>
      <xs:documentation>Dane elementu formatu typu stała.</xs:documentation>
    </xs:annotation>
    <xs:complexContent>
      <xs:annotation>
        <xs:documentation>Dane elementu formatu typu stała.</xs:documentation>
      </xs:annotation>
      <xs:extension base="TElementFormatu">
        <xs:attribute name="Stala" type="xs:string">
          <xs:annotation>
            <xs:documentation>Stała.</xs:documentation>
          </xs:annotation>
        </xs:attribute>
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>

  <xs:complexType name="TElementFormatuSymbol">
    <xs:annotation>
      <xs:documentation>Dane elementu formatu typu symbol.</xs:documentation>
    </xs:annotation>
    <xs:complexContent>
      <xs:extension base="TElementFormatu">
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>

  <xs:complexType name="TElementFormatuKontekst">
    <xs:annotation>
      <xs:documentation>Dane elementu formatu typu kontekst.</xs:documentation>
    </xs:annotation>
    <xs:complexContent>
      <xs:extension base="TElementFormatu">
        <xs:attribute name="KluczObiektu" type="xs:string">
          <xs:annotation>
            <xs:documentation>Klucz obiektu.</xs:documentation>
          </xs:annotation>
        </xs:attribute>
        <xs:attribute name="AdresWObiekcie" type="xs:string">
          <xs:annotation>
            <xs:documentation>Adres w obiekcie.</xs:documentation>
          </xs:annotation>
        </xs:attribute>
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>

  <xs:complexType name="TElementFormatuNumer">
    <xs:annotation>
      <xs:documentation>Dane elementu formatu typu numer.</xs:documentation>
    </xs:annotation>
    <xs:complexContent>
      <xs:extension base="TElementFormatu">
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>

  <xs:complexType name="TFormat">
    <xs:annotation>
      <xs:documentation>Dane formatu numeracji dokumentu.</xs:documentation>
    </xs:annotation>
    <xs:sequence>
      <xs:annotation>
        <xs:documentation>Kolekcja elementów formatu.</xs:documentation>
      </xs:annotation>
      <xs:element name="ElementFormatu" type="TElementFormatu" maxOccurs="unbounded">
        <xs:annotation>
          <xs:documentation>Element formatu.</xs:documentation>
        </xs:annotation>
      </xs:element>
    </xs:sequence>
  </xs:complexType>

  <xs:simpleType name="TMetodaWypelnianiaLuk">
    <xs:annotation>
      <xs:documentation>Metoda wypełniania luk.</xs:documentation>
    </xs:annotation>
    <xs:restriction base="xs:string">
      <xs:enumeration value="NieWypelniaj">
        <xs:annotation>
          <xs:documentation>Nie wypełniaj.</xs:documentation>
        </xs:annotation>
      </xs:enumeration>
      <xs:enumeration value="MaksPlusJeden">
        <xs:annotation>
          <xs:documentation>Maks plus jeden.</xs:documentation>
        </xs:annotation>
      </xs:enumeration>
      <xs:enumeration value="PierwszyWolny">
        <xs:annotation>
          <xs:documentation>Pierwszy wolny.</xs:documentation>
        </xs:annotation>
      </xs:enumeration>
    </xs:restriction>
  </xs:simpleType>

  <xs:complexType name="TRegulyWartosciPoczatkowych">
    <xs:annotation>
      <xs:documentation>Reguły wartości początkowych rejestrów numeracyjnych.</xs:documentation>
    </xs:annotation>
    <xs:sequence>
      <xs:annotation>
        <xs:documentation>Kolekcja reguł wartości początkowych.</xs:documentation>
      </xs:annotation>
      <xs:element name="RegulaWartosciPoczatkowych" minOccurs="0" maxOccurs="unbounded">
        <xs:annotation>
          <xs:documentation>Reguła wartości początkowych.</xs:documentation>
        </xs:annotation>
        <xs:complexType>
          <xs:annotation>
            <xs:documentation>Reguła wartości początkowych.</xs:documentation>
          </xs:annotation>
          <xs:all>
            <xs:annotation>
              <xs:documentation>Elementy reguły wartości początkowych.</xs:documentation>
            </xs:annotation>
            <xs:element name="WartosciowanieAtrybutowRegul">
              <xs:annotation>
                <xs:documentation>Wartościowanie atrybutów reguł.</xs:documentation>
              </xs:annotation>
              <xs:complexType>
                <xs:annotation>
                  <xs:documentation>Wartościowanie atrybutów reguł.</xs:documentation>
                </xs:annotation>
                <xs:sequence>
                  <xs:annotation>
                    <xs:documentation>Kolekcja wartościowań atrybutów reguły.</xs:documentation>
                  </xs:annotation>
                  <xs:element name="WartosciowanieAtrybutuReguly" minOccurs="0" maxOccurs="unbounded">
                    <xs:annotation>
                      <xs:documentation>Wartościowanie atrybutów reguły.</xs:documentation>
                    </xs:annotation>
                    <xs:complexType>
                      <xs:annotation>
                        <xs:documentation>Wartościowanie atrybutów reguły.</xs:documentation>
                      </xs:annotation>
                      <xs:attribute name="NumerPorzadkowyAtrybutu" type="xs:int">
                        <xs:annotation>
                          <xs:documentation>Numer porządkowy atrybutu.</xs:documentation>
                        </xs:annotation>
                      </xs:attribute>
                      <xs:attribute name="Wartosc" type="xs:string">
                        <xs:annotation>
                          <xs:documentation>Wartość atrybutu.</xs:documentation>
                        </xs:annotation>
                      </xs:attribute>
                    </xs:complexType>
                  </xs:element>
                </xs:sequence>
              </xs:complexType>
            </xs:element>
            <xs:element name="NumerPoczatkowy" type="xs:int">
              <xs:annotation>
                <xs:documentation>Numer początkowy.</xs:documentation>
              </xs:annotation>
            </xs:element>
          </xs:all>
        </xs:complexType>
      </xs:element>
    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="TRejestrNumeracyjny">
    <xs:annotation>
      <xs:documentation>Rejestr numeracyjny.</xs:documentation>
    </xs:annotation>
    <xs:all>
      <xs:annotation>
        <xs:documentation>Dane rejestru numeracyjnego.</xs:documentation>
      </xs:annotation>
      <xs:element name="Format" type="TFormat">
        <xs:annotation>
          <xs:documentation>Format rejestru.</xs:documentation>
        </xs:annotation>
      </xs:element>
      <xs:element name="ZbiorAtrybutow" minOccurs="0">
        <xs:annotation>
          <xs:documentation>Zbiór atrybutów.</xs:documentation>
        </xs:annotation>
        <xs:complexType>
          <xs:annotation>
            <xs:documentation>Zbiór atrybutów.</xs:documentation>
          </xs:annotation>
          <xs:sequence>
            <xs:annotation>
              <xs:documentation>Kolekcja atrybutów licznika.</xs:documentation>
            </xs:annotation>
            <xs:element name="AtrybutLicznika" minOccurs="0" maxOccurs="unbounded">
              <xs:annotation>
                <xs:documentation>Atrybut licznika.</xs:documentation>
              </xs:annotation>
              <xs:complexType>
                <xs:annotation>
                  <xs:documentation>Atrybut licznika.</xs:documentation>
                </xs:annotation>
                <xs:attribute name="AdresWObiekcie" type="xs:string">
                  <xs:annotation>
                    <xs:documentation>Adres w obiekcie.</xs:documentation>
                  </xs:annotation>
                </xs:attribute>
                <xs:attribute name="KluczObiektu" type="xs:string">
                  <xs:annotation>
                    <xs:documentation>Klucz obiektu.</xs:documentation>
                  </xs:annotation>
                </xs:attribute>
                <xs:attribute name="NumerPorzadkowy" type="xs:int">
                  <xs:annotation>
                    <xs:documentation>Numer porządkowy.</xs:documentation>
                  </xs:annotation>
                </xs:attribute>
                <xs:attribute name="DataNadaniaNumeru" type="xs:boolean" use="optional" default="false">
                  <xs:annotation>
                    <xs:documentation>Data nadania numeru.</xs:documentation>
                  </xs:annotation>
                </xs:attribute>
              </xs:complexType>
            </xs:element>
            <xs:element name="RegulyWartosciPoczatkowych" maxOccurs="unbounded" type="TRegulyWartosciPoczatkowych">
              <xs:annotation>
                <xs:documentation>Reguły wartości początkowych.</xs:documentation>
              </xs:annotation>
            </xs:element>
          </xs:sequence>
        </xs:complexType>
      </xs:element>
    </xs:all>
    <xs:attribute name="Dziedzina" type="xs:long" use="required">
      <xs:annotation>
        <xs:documentation>Dziedzina.</xs:documentation>
      </xs:annotation>
    </xs:attribute>
    <xs:attribute name="MetodaWypelnianiaLuk" type="TMetodaWypelnianiaLuk" use="required">
      <xs:annotation>
        <xs:documentation>Metoda wypełniania luk.</xs:documentation>
      </xs:annotation>
    </xs:attribute>
    <xs:attribute name="Chronologiczny" type="xs:boolean" use="required">
      <xs:annotation>
        <xs:documentation>Informacja, czy chronologiczny.</xs:documentation>
      </xs:annotation>
    </xs:attribute>
    <xs:attribute name="UzywaNumeru" type="xs:boolean" use="required">
      <xs:annotation>
        <xs:documentation>Informacja, czy używa numeru.</xs:documentation>
      </xs:annotation>
    </xs:attribute>
    <xs:attribute name="Symbol" type="xs:string" use="required">
      <xs:annotation>
        <xs:documentation>Symbol.</xs:documentation>
      </xs:annotation>
    </xs:attribute>
    <xs:attribute name="Nazwa" type="xs:string" use="required">
      <xs:annotation>
        <xs:documentation>Nazwa.</xs:documentation>
      </xs:annotation>
    </xs:attribute>
    <xs:attribute name="Opis" type="xs:string" use="required">
      <xs:annotation>
        <xs:documentation>Opis.</xs:documentation>
      </xs:annotation>
    </xs:attribute>
    <xs:attribute name="Konfiguracja" type="xs:string" use="optional">
      <xs:annotation>
        <xs:documentation>Symbol konfiguracji dokumentu logistycznego w nexo, do której dany rejestr ma być podłączony (tylko dla dokumentów Subiekta).</xs:documentation>
      </xs:annotation>
    </xs:attribute>
  </xs:complexType>

  <xs:complexType name="TNumeracja">
    <xs:annotation>
      <xs:documentation>Konfiguracja numeracji dokumentów.</xs:documentation>
    </xs:annotation>
    <xs:sequence>
      <xs:annotation>
        <xs:documentation>Kolekcja rejestrów numeracyjnych.</xs:documentation>
      </xs:annotation>
      <xs:element name="Rejestr" maxOccurs="unbounded" minOccurs="0" type="TRejestrNumeracyjny">
        <xs:annotation>
          <xs:documentation>Rejestr numeracyjny.</xs:documentation>
        </xs:annotation>
      </xs:element>
    </xs:sequence>
  </xs:complexType>

  <xs:element name="Numeracja" type="TNumeracja">
    <xs:annotation>
      <xs:documentation>Konfiguracja numeracji dokumentów.</xs:documentation>
    </xs:annotation>
  </xs:element>
</xs:schema>