<?xml version="1.0" encoding="utf-8"?>
<xs:schema elementFormDefault="qualified"
           targetNamespace="http://schemas.insert.com.pl/2013/hop/operacjest"
           xmlns="http://schemas.insert.com.pl/2013/hop/operacjest"
           xmlns:wspolne="http://schemas.insert.com.pl/2013/hop"
           xmlns:ST="http://schemas.insert.com.pl/2018/hop/srodkitrwale"
           xmlns:MU="http://schemas.insert.com.pl/2013/hop/miejscauzytkowania"
           xmlns:xs="http://www.w3.org/2001/XMLSchema">

  <xs:import id="WspolnePart" namespace="http://schemas.insert.com.pl/2013/hop" schemaLocation="Wspolne.xsd"/>
  <xs:import id="SrodekTrPart" namespace="http://schemas.insert.com.pl/2018/hop/srodkitrwale" schemaLocation="SrodkiTrwale.xsd"/>
  <xs:import id="MiejsceUzytPart" namespace="http://schemas.insert.com.pl/2013/hop/miejscauzytkowania" schemaLocation="MiejscaUzytkowania.xsd"/>

  <xs:simpleType name="TMetodaUmarzania">
    <xs:restriction base="xs:string">
      <xs:enumeration value="Liniowa" />
      <xs:enumeration value="Degresywna" />
      <xs:enumeration value="Natychmiastowa" />
    </xs:restriction>
  </xs:simpleType>

  <xs:simpleType name="TRozpoczecieUmarzania">
    <xs:restriction base="xs:string">
      <xs:enumeration value="MiesiacPrzyjecia" />
      <xs:enumeration value="MiesiacNastepny" />      
    </xs:restriction>
  </xs:simpleType>

  <xs:simpleType name="TTypTypuAmortyzacji">
    <xs:restriction base="xs:string">
      <xs:enumeration value="Podatkowy" />
      <xs:enumeration value="Bilansowy" />
      <xs:enumeration value="Inny" />
    </xs:restriction>    
  </xs:simpleType>
  
  <xs:complexType name="TTypAmortyzacji">
    <xs:sequence>
      <xs:element minOccurs="1" name="Symbol" type="xs:string"/>
      <xs:element minOccurs="1" name="Nazwa" type="xs:string"/>
      <xs:element minOccurs="1" name="Typ" type="TTypTypuAmortyzacji" />
      <xs:element minOccurs="0" maxOccurs="1" name="Umorzenie">
        <xs:complexType>
          <xs:sequence>
            <xs:element minOccurs="1" name="Metoda" type="TMetodaUmarzania"/>
            <xs:element minOccurs="1" name="UmorzenieRoczne" type="xs:decimal" />
            <xs:element minOccurs="0" name="WspolczDegr" type="xs:decimal" />
          </xs:sequence>
        </xs:complexType>
      </xs:element>
    </xs:sequence>
  </xs:complexType>

  <xs:simpleType name="TTypWzorcaAmortyzacji">
    <xs:restriction base="xs:string">
      <xs:enumeration value="Miesieczny" />
      <xs:enumeration value="Kwartalny" />
      <xs:enumeration value="Roczny" />
      <xs:enumeration value="Uzytkownika" />
    </xs:restriction>
  </xs:simpleType>

  <xs:complexType name="TOperacjaOT">
		<xs:sequence>				        
			      <xs:element minOccurs="1" maxOccurs="1" name="SrodekTrwaly" type="ST:TSrodekTrwalyInfo"/>
						<xs:element minOccurs="1" name="Numer" type="wspolne:Obowiazkowy" />
						<xs:element minOccurs="1" name="Data" type="xs:date" />
            <xs:element minOccurs="1" name="TypAmortyzacji" type="TTypAmortyzacji" />
              
						<xs:element minOccurs="1" maxOccurs="1" name="Uzytkowanie">
							<xs:complexType>
								<xs:sequence>
									<xs:element minOccurs="1" maxOccurs="1" name="Miejsce" type="MU:TMiejsceUzytkowaniaInfo" />
									<xs:element minOccurs="1" maxOccurs="1" name="Uzytkownik" type="wspolne:Obowiazkowy" />
								</xs:sequence>
							</xs:complexType>
						</xs:element>
              
						<xs:element minOccurs="0" maxOccurs="1" name="Umarzanie">
							<xs:complexType>
								<xs:sequence>                                                                                                       
                    
                  <xs:element minOccurs="1" name="WartoscPoczatkowa" type="xs:decimal"/>
                  <xs:element minOccurs="1" name="WartoscPoczatkowaStanowiacaKoszty" type="xs:decimal"/>

                  <xs:element minOccurs="1" maxOccurs="1" name="MetodaUmarzania" type="TMetodaUmarzania"/>
                  <xs:element minOccurs="0" maxOccurs="1" name="UmorzenieRoczne" type="xs:decimal" />
                  <xs:element minOccurs="0" maxOccurs="1" name="WspolczynnikDegresywnosci" type="xs:decimal" />
                  <xs:element minOccurs="0" maxOccurs="1" name="Podwyzszone" type="xs:decimal" />
																				
									<xs:element minOccurs="1" maxOccurs="1" name="RozpoczecieUmarzania" type="TRozpoczecieUmarzania"/>

                  <xs:element minOccurs="1" maxOccurs="1" name="WzorzecPlanuAmortyzacji">
                    <xs:complexType>
                      <xs:sequence>
                        <xs:element name="TypPodzialu" type="TTypWzorcaAmortyzacji" minOccurs="1" maxOccurs="1"/>
                        <xs:element minOccurs="0" maxOccurs="unbounded" name="Wzorzec">
                          <xs:complexType>
                            <xs:attribute form="unqualified" name="Miesiac" type="xs:int" />
                            <xs:attribute form="unqualified" name="Licznik" type="xs:int" />
                            <xs:attribute form="unqualified" name="Mianownik" type="xs:int" />
                          </xs:complexType>
                        </xs:element>
                      </xs:sequence>
                      <!--<xs:attribute form="unqualified" name="Typ" type="TTypWzorcaAmortyzacji"  />-->
                    </xs:complexType>
                  </xs:element>


                  <xs:element minOccurs="0" maxOccurs="1" name="HistoriaAmortyzacji">
										<xs:complexType>
											<xs:sequence>
												<xs:element minOccurs="1" maxOccurs="1" name="DataPierwszejAmortyzacjiWProgramie" type="xs:date" />
                        <xs:element minOccurs="0" maxOccurs="unbounded" name="AmortyzacjaHistoryczna">
                          <xs:complexType>
                            <xs:attribute form="unqualified" name="Miesiac" type="xs:int" />
                            <xs:attribute form="unqualified" name="Wartosc" type="xs:decimal" />
                          </xs:complexType>
                        </xs:element>													
											</xs:sequence>
                      <xs:attribute form="unqualified" name="PrzyjetyWczesniej" type="xs:boolean" />
                    </xs:complexType>                    
								  </xs:element>
								</xs:sequence>
                
							</xs:complexType>                
						</xs:element>

            <xs:element minOccurs="0" name="WlasneRozszerzone">
              <xs:annotation>
                <xs:documentation>Wartości pól własnych podmiotu.</xs:documentation>
              </xs:annotation>
              <xs:complexType>
                <xs:sequence>
                  <xs:element minOccurs="0" maxOccurs="unbounded" name="PoleRozszerzone">
                    <xs:annotation>
                      <xs:documentation>Pole własne rozszerzone podmiotu. Zawartość tego elementu jest wartością pola.</xs:documentation>
                    </xs:annotation>
                    <xs:complexType>
                      <xs:simpleContent>
                        <xs:extension base="xs:string">
                          <xs:attribute name="Nazwa" type="xs:string" use="required">
                            <xs:annotation>
                              <xs:documentation>Nazwa pola własnego.</xs:documentation>
                            </xs:annotation>
                          </xs:attribute>
                        </xs:extension>
                      </xs:simpleContent>
                    </xs:complexType>
                  </xs:element>
                </xs:sequence>
              </xs:complexType>
            </xs:element>
            <xs:element name="FlagaWlasna" minOccurs="0">
              <xs:annotation>
                <xs:documentation>Dane flagi własnej.</xs:documentation>
              </xs:annotation>
              <xs:complexType>
                <xs:all>
                  <xs:element minOccurs="1" maxOccurs="1" name="Kolor" type="xs:string">
                    <xs:annotation>
                      <xs:documentation>Kolor flagi własnej.</xs:documentation>
                    </xs:annotation>
                  </xs:element>
                  <xs:element minOccurs="0" maxOccurs="1" name="Ksztalt" type="xs:string">
                    <xs:annotation>
                      <xs:documentation>Kształt flagi własnej.</xs:documentation>
                    </xs:annotation>
                  </xs:element>
                  <xs:element minOccurs="0" maxOccurs="1" name="Komentarz" type="xs:string">
                    <xs:annotation>
                      <xs:documentation>Komentarz flagi własnej.</xs:documentation>
                    </xs:annotation>
                  </xs:element>
                </xs:all>
              </xs:complexType>
            </xs:element>
					</xs:sequence>
          <xs:attribute form="unqualified" name="Umarzany" type="xs:boolean" />
          
				</xs:complexType>

  <xs:complexType name="TOperacjaMO">
    <xs:attribute name="test" />
  </xs:complexType>
  
  <xs:complexType name="TOperacjeST">
    <xs:sequence>
      <xs:element name="Przyjecie" minOccurs="0" maxOccurs="unbounded" type="TOperacjaOT"/>      
    </xs:sequence>
  </xs:complexType>

  <xs:element name="OperacjeST" type="TOperacjeST"/>
  
</xs:schema>
