<?xml version="1.0" encoding="utf-8"?>
<xs:schema elementFormDefault="qualified"
           targetNamespace="http://schemas.insert.com.pl/2013/hop/parametryfinansow"
           xmlns="http://schemas.insert.com.pl/2013/hop/parametryfinansow"
           xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:annotation>
    <xs:documentation>Parametry finansów.</xs:documentation>
  </xs:annotation>

  <xs:simpleType name ="TTrybRozpoznawaniaOperacji">
    <xs:annotation>
      <xs:documentation>Tryb rozpoznawania operacji bankowych.</xs:documentation>
    </xs:annotation>
    <xs:restriction base="xs:string">
      <xs:enumeration value="Zawsze">
        <xs:annotation>
          <xs:documentation>Zawsze rozpoznawaj.</xs:documentation>
        </xs:annotation>
      </xs:enumeration>
      <xs:enumeration value="Nigdy">
        <xs:annotation>
          <xs:documentation>Nigdy nie rozpoznawaj.</xs:documentation>
        </xs:annotation>
      </xs:enumeration>
      <xs:enumeration value="Pytaj">
        <xs:annotation>
          <xs:documentation>Pytaj, czy rozpoznać.</xs:documentation>
        </xs:annotation>
      </xs:enumeration>
    </xs:restriction>
  </xs:simpleType>

  <xs:simpleType name ="TTrybImportuRozrachunkow">
    <xs:annotation>
      <xs:documentation>Tryb importu rozrachunków do księgowości.</xs:documentation>
    </xs:annotation>
    <xs:restriction base="xs:string">
      <xs:enumeration value="UtworzNowy">
        <xs:annotation>
          <xs:documentation>Zawsze twórz nowy rozrachunek powiązany z zapisem księgowym.</xs:documentation>
        </xs:annotation>
      </xs:enumeration>
      <xs:enumeration value="PodlaczLubUtworzNowy">
        <xs:annotation>
          <xs:documentation>Podłącz istniejący rozrachunek, a w razie niepowodzenia utwórz nowy.</xs:documentation>
        </xs:annotation>
      </xs:enumeration>
      <xs:enumeration value="PodlaczLubRozliczIstniejacyIUtworzNowy">
        <xs:annotation>
          <xs:documentation>Podłącz istniejący rozrachunek, a w razie niepowodzenia rozlicz istniejący i utwórz nowy.</xs:documentation>
        </xs:annotation>
      </xs:enumeration>
      <xs:enumeration value="PodlaczLubPrzerwij">
        <xs:annotation>
          <xs:documentation>Podłącz instniejący rozrachunek, a w razie niepowodzenia przerwij import.</xs:documentation>
        </xs:annotation>
      </xs:enumeration>
    </xs:restriction>
  </xs:simpleType>

  <xs:simpleType name ="TTrybTworzeniaRozrachunku">
    <xs:annotation>
      <xs:documentation>Tryb tworzenia rozrachunku do zapisu księgowego.</xs:documentation>
    </xs:annotation>
    <xs:restriction base="xs:string">
      <xs:enumeration value="UtworzIPokaz">
        <xs:annotation>
          <xs:documentation>Pokaż formatkę utworzonego rozrachunku.</xs:documentation>
        </xs:annotation>
      </xs:enumeration>
      <xs:enumeration value="UtworzWTle">
        <xs:annotation>
          <xs:documentation>Nie pokazuj utworzonego rozrachunku.</xs:documentation>
        </xs:annotation>
      </xs:enumeration>
    </xs:restriction>
  </xs:simpleType>

  <xs:complexType name="TParametryFinansow">
    <xs:annotation>
      <xs:documentation>Parametry finansów.</xs:documentation>
    </xs:annotation>
    <xs:all>
      <xs:annotation>
        <xs:documentation>Zbiór parametrów.</xs:documentation>
      </xs:annotation>
      <xs:element name="Kasa">
        <xs:annotation>
          <xs:documentation>Parametry kasy.</xs:documentation>
        </xs:annotation>
        <xs:complexType>
          <xs:annotation>
            <xs:documentation>Parametry kasy.</xs:documentation>
          </xs:annotation>
          <xs:all>
            <xs:annotation>
              <xs:documentation>Zbiór parametrów dla różnego typu dokumentów kasowych.</xs:documentation>
            </xs:annotation>
            <xs:element name="Wplata">
              <xs:annotation>
                <xs:documentation>Parametry dla wpłaty.</xs:documentation>
              </xs:annotation>
              <xs:complexType>
                <xs:annotation>
                  <xs:documentation>Parametry dla wpłaty.</xs:documentation>
                </xs:annotation>
                <xs:all>
                  <xs:annotation>
                    <xs:documentation>Zbiór parametrów dla wpłaty.</xs:documentation>
                  </xs:annotation>
                  <xs:element name="LiniaKursowWalut" type="xs:string">
                    <xs:annotation>
                      <xs:documentation>Nazwa domyślnej linii kursów walut.</xs:documentation>
                    </xs:annotation>
                  </xs:element>
                  <xs:element name="RodzajOperacji" type="xs:string">
                    <xs:annotation>
                      <xs:documentation>Symbol domyślnego rodzaju operacji kasowej.</xs:documentation>
                    </xs:annotation>
                  </xs:element>
                  <xs:element name="DrukujPoZapisie" type="xs:boolean">
                    <xs:annotation>
                      <xs:documentation>Informacja, czy dokument wpłaty ma być automatycznie drukowany po utworzeniu.</xs:documentation>
                    </xs:annotation>
                  </xs:element>
                  <xs:element name="ParametryWydruku" type="xs:boolean">
                    <xs:annotation>
                      <xs:documentation>Informacja, czy pokazywać parametry wydruku przed wydrukowaniem dokumentu.</xs:documentation>
                    </xs:annotation>
                  </xs:element>
                </xs:all>
              </xs:complexType>
            </xs:element>
            <xs:element name="Wyplata">
              <xs:annotation>
                <xs:documentation>Parametry dla wypłaty.</xs:documentation>
              </xs:annotation>
              <xs:complexType>
                <xs:annotation>
                  <xs:documentation>Parametry dla wypłaty.</xs:documentation>
                </xs:annotation>
                <xs:all>
                  <xs:annotation>
                    <xs:documentation>Zbiór parametrów dla wypłaty.</xs:documentation>
                  </xs:annotation>
                  <xs:element name="LiniaKursowWalut" type="xs:string">
                    <xs:annotation>
                      <xs:documentation>Nazwa domyślnej linii kursów walut.</xs:documentation>
                    </xs:annotation>
                  </xs:element>
                  <xs:element name="RodzajOperacji" type="xs:string">
                    <xs:annotation>
                      <xs:documentation>Symbol domyślnego rodzaju operacji kasowej.</xs:documentation>
                    </xs:annotation>
                  </xs:element>
                  <xs:element name="DrukujPoZapisie" type="xs:boolean">
                    <xs:annotation>
                      <xs:documentation>Informacja, czy dokument wypłaty ma być automatycznie drukowany po utworzeniu.</xs:documentation>
                    </xs:annotation>
                  </xs:element>
                  <xs:element name="ParametryWydruku" type="xs:boolean">
                    <xs:annotation>
                      <xs:documentation>Informacja, czy pokazywać parametry wydruku przed wydrukowaniem dokumentu.</xs:documentation>
                    </xs:annotation>
                  </xs:element>
                </xs:all>
              </xs:complexType>
            </xs:element>
          </xs:all>
        </xs:complexType>
      </xs:element>
      <xs:element name="Bank">
        <xs:annotation>
          <xs:documentation>Parametry bankowości.</xs:documentation>
        </xs:annotation>
        <xs:complexType>
          <xs:annotation>
            <xs:documentation>Parametry bankowości.</xs:documentation>
          </xs:annotation>
          <xs:all>
            <xs:annotation>
              <xs:documentation>Zbiór parametrów bankowości.</xs:documentation>
            </xs:annotation>
            <xs:element name="OperacjeBankowe">
              <xs:annotation>
                <xs:documentation>Parametry operacji bankowych.</xs:documentation>
              </xs:annotation>
              <xs:complexType>
                <xs:annotation>
                  <xs:documentation>Parametry operacji bankowych.</xs:documentation>
                </xs:annotation>
                <xs:all>
                  <xs:annotation>
                    <xs:documentation>Zbiór parametrów.</xs:documentation>
                  </xs:annotation>
                  <xs:element name="RodzajDlaWplaty" type="xs:string">
                    <xs:annotation>
                      <xs:documentation>Symbol domyślnego rodzaju operacji bankowej dla wpłaty.</xs:documentation>
                    </xs:annotation>
                  </xs:element>
                  <xs:element name="RodzajDlaWyplaty" type="xs:string">
                    <xs:annotation>
                      <xs:documentation>Symbol domyślnego rodzaju operacji bankowej dla wypłaty.</xs:documentation>
                    </xs:annotation>
                  </xs:element>
                  <xs:element name="TworzOperacjeDoDyspozycji" type="xs:boolean">
                    <xs:annotation>
                      <xs:documentation>Informacja, czy automatycznie tworzyć operację bankową do dyspozycji.</xs:documentation>
                    </xs:annotation>
                  </xs:element>
                </xs:all>
              </xs:complexType>
            </xs:element>
            <xs:element name="BankowoscElektroniczna">
              <xs:annotation>
                <xs:documentation>Parametry bankowości elektronicznej.</xs:documentation>
              </xs:annotation>
              <xs:complexType>
                <xs:annotation>
                  <xs:documentation>Parametry bankowości elektronicznej.</xs:documentation>
                </xs:annotation>
                <xs:all>
                  <xs:annotation>
                    <xs:documentation>Zbiór parametrów.</xs:documentation>
                  </xs:annotation>
                  <xs:element name="RozpoznawanieOperacjiPoImporcie" type="TTrybRozpoznawaniaOperacji">
                    <xs:annotation>
                      <xs:documentation>Tryb rozpoznawania operacji bankowych po zaimportowaniu.</xs:documentation>
                    </xs:annotation>
                  </xs:element>
                  <xs:element name="RozpoznawanieKontrahenta" type="xs:boolean">
                    <xs:annotation>
                      <xs:documentation>Informacja, czy podczas rozpoznawania operacji próbować rozpoznać kontrahenta.</xs:documentation>
                    </xs:annotation>
                  </xs:element>
                  <xs:element name="DolnyProgDopasowania" type="xs:double">
                    <xs:annotation>
                      <xs:documentation>Dolny próg dopasowania kontrahenta.</xs:documentation>
                    </xs:annotation>
                  </xs:element>
                  <xs:element name="GornyProgDopasowania" type="xs:double">
                    <xs:annotation>
                      <xs:documentation>Górny próg dopasowania kontrahenta.</xs:documentation>
                    </xs:annotation>
                  </xs:element>
                </xs:all>
              </xs:complexType>
            </xs:element>
            <xs:element name="DyspozycjeBankowe">
              <xs:annotation>
                <xs:documentation>Parametry dyspozycji bankowych.</xs:documentation>
              </xs:annotation>
              <xs:complexType>
                <xs:annotation>
                  <xs:documentation>Parametry dyspozycji bankowych.</xs:documentation>
                </xs:annotation>
                <xs:all>
                  <xs:annotation>
                    <xs:documentation>Zbiór parametrów.</xs:documentation>
                  </xs:annotation>
                  <xs:element name="DrukujPoZapisie" type="xs:boolean">
                    <xs:annotation>
                      <xs:documentation>Informacja, czy automatycznie drukować dyspozycję po zapisie.</xs:documentation>
                    </xs:annotation>
                  </xs:element>
                  <xs:element name="ParametryWydruku" type="xs:boolean">
                    <xs:annotation>
                      <xs:documentation>Informacja, czy pokazywać parametry wydruku przed wydrukowaniem dokumentu.</xs:documentation>
                    </xs:annotation>
                  </xs:element>
                </xs:all>
              </xs:complexType>
            </xs:element>
          </xs:all>
        </xs:complexType>
      </xs:element>
      <xs:element name="Rozrachunki">
        <xs:annotation>
          <xs:documentation>Parametry rozrachunków.</xs:documentation>
        </xs:annotation>
        <xs:complexType>
          <xs:annotation>
            <xs:documentation>Parametry rozrachunków.</xs:documentation>
          </xs:annotation>
          <xs:all>
            <xs:annotation>
              <xs:documentation>Zbiór parametrów.</xs:documentation>
            </xs:annotation>
            <xs:element name="TrybImportuRozrachunkow" type="TTrybImportuRozrachunkow">
              <xs:annotation>
                <xs:documentation>Tryb importowania rozrachunków do księgowości.</xs:documentation>
              </xs:annotation>
            </xs:element>
            <xs:element name="TrybTworzeniaRozrachunku" type="TTrybTworzeniaRozrachunku">
              <xs:annotation>
                <xs:documentation>Tryb tworzenia rozrachunków do zapisów księgowych.</xs:documentation>
              </xs:annotation>
            </xs:element>
            <xs:element name="UkrywanieRozrachunkowKsiegowych" type="xs:boolean">
              <xs:annotation>
                <xs:documentation>Informacja, czy w Subiekcie nexo pokazywać rozrachunki utworzone do zapisów księgowych.</xs:documentation>
              </xs:annotation>
            </xs:element>
            <xs:element name="WyswietlListeRozrachunkowDoPodlaczenia" type="xs:boolean">
              <xs:annotation>
                <xs:documentation>Informacja, czy podczas tworzenia zapisu księgowego generującego rozrachunek pokazywać listę rozrachunków, które można podłączyć do zapisu.</xs:documentation>
              </xs:annotation>
            </xs:element>
            <xs:element name="RozliczanieRozrachunkowKsiegowychINieksiegowych" type="xs:boolean">
              <xs:annotation>
                <xs:documentation>Informacja, czy można rozliczać rozrachunki powiązane z zapisami księgowymi z rozrachunkami niepowiązanymi z zapisami księgowymi.</xs:documentation>
              </xs:annotation>
            </xs:element>
            <xs:element name="PokazujWszystkieRozrachunki" type="xs:boolean">
              <xs:annotation>
                <xs:documentation>Informacja, czy w serwisie rozrachunków pokazywać widok wszystkich rozrachunków.</xs:documentation>
              </xs:annotation>
            </xs:element>
          </xs:all>
        </xs:complexType>
      </xs:element>
    </xs:all>
  </xs:complexType>

  <xs:element name="ParametryFinansow" type="TParametryFinansow">
    <xs:annotation>
      <xs:documentation>Parametry finansów.</xs:documentation>
    </xs:annotation>
  </xs:element>
</xs:schema>