<?xml version="1.0" encoding="utf-8"?>
<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified"
           targetNamespace="http://schemas.insert.com.pl/2018/hop/rejestrCzynnosciPrzetwarzania"
           xmlns="http://schemas.insert.com.pl/2018/hop/rejestrCzynnosciPrzetwarzania"
           xmlns:wspolne="http://schemas.insert.com.pl/2013/hop"
           xmlns:xs="http://www.w3.org/2001/XMLSchema">

  <xs:import id="WspolnePart" namespace="http://schemas.insert.com.pl/2013/hop" schemaLocation="Wspolne.xsd"/>

  <xs:annotation>
    <xs:documentation>Informacje o rejestrze czynności przetwarzania.</xs:documentation>
  </xs:annotation>
  
  <xs:complexType name="TElementRejestruCzynnosciPrzetwarzania">
    <xs:sequence>
      <xs:element name="ProwadzonyPrzez" type="TRejestrProwadzonyPrzez">
        <xs:annotation>
          <xs:documentation>Określa przez kogo prowadzony jest rejestr (ADO lub podmiot przetwarzający).</xs:documentation>
        </xs:annotation>
      </xs:element>
      <xs:element name="NazwaSkrocona" type="wspolne:Obowiazkowy">
        <xs:annotation>
          <xs:documentation>Nazwa skrócona elementu rejestru czynności przetwarzania.</xs:documentation>
        </xs:annotation>
      </xs:element>
      <xs:element name="NazwaZbioru" type="wspolne:Obowiazkowy">
        <xs:annotation>
          <xs:documentation>Nazwa zbioru.</xs:documentation>
        </xs:annotation>
      </xs:element>
      <xs:element name="KategorieOsob" type="wspolne:Obowiazkowy" minOccurs="0">
        <xs:annotation>
          <xs:documentation>Kategorie osób (dla ADO).</xs:documentation>
        </xs:annotation>
      </xs:element>
      <xs:element name="KategorieDanychLubPrzetwarzan" type="wspolne:Obowiazkowy" minOccurs="0">
        <xs:annotation>
          <xs:documentation>Kategorie danych (dla ADO) lub kategorie przetwarzań (dla podmiotu przetwarzającego).</xs:documentation>
        </xs:annotation>
      </xs:element>
      <xs:element name="OdbiorcyDanychLubDaneAdministratora" type="wspolne:Obowiazkowy" minOccurs="0">
        <xs:annotation>
          <xs:documentation>Odbiorcy danych (dla ADO) lub dane administratora (dla podmiotu przetwarzającego).</xs:documentation>
        </xs:annotation>
      </xs:element>
      <xs:element name="CelePrzetwarzania" minOccurs="0">
        <xs:annotation>
          <xs:documentation>Cele przetwarzania (dla ADO).</xs:documentation>
        </xs:annotation>
        <xs:complexType>
          <xs:sequence>
            <xs:element name="CelPrzetwarzania" type="wspolne:Obowiazkowy" minOccurs="1" maxOccurs="unbounded">
              <xs:annotation>
                <xs:documentation>Nazwa skrócona celu przetwarzania.</xs:documentation>
              </xs:annotation>
            </xs:element>
          </xs:sequence>
        </xs:complexType>
      </xs:element>
      <xs:element name="PanstwaTrzecie" type="wspolne:Obowiazkowy" minOccurs="0">
        <xs:annotation>
          <xs:documentation>Państwa trzecie, do których dane są przekazane.</xs:documentation>
        </xs:annotation>
      </xs:element>
      <xs:element name="PlanowaneTerminyUsunieciaDanych" type="wspolne:Obowiazkowy" minOccurs="0">
        <xs:annotation>
          <xs:documentation>Planowane terminy usunięcia danych (dla ADO).</xs:documentation>
        </xs:annotation>
      </xs:element>
      <xs:element name="OpisSrodkowBezpieczenstwa" type="wspolne:Obowiazkowy" minOccurs="0">
        <xs:annotation>
          <xs:documentation>Opis technicznych i organizacyjnych środków bezpieczeństwa.</xs:documentation>
        </xs:annotation>
      </xs:element>
    </xs:sequence>
  </xs:complexType>
  
  <xs:simpleType name="TRejestrProwadzonyPrzez">
    <xs:restriction base="xs:string">
      <xs:enumeration value="ADO">
        <xs:annotation>
          <xs:documentation>Administrator danych osobowych.</xs:documentation>
        </xs:annotation>
      </xs:enumeration>
      <xs:enumeration value="PodmiotPrzetwarzajacy">
        <xs:annotation>
          <xs:documentation>Podmiot przetwarzający.</xs:documentation>
        </xs:annotation>
      </xs:enumeration>
    </xs:restriction>
  </xs:simpleType>
  
  <xs:complexType name="TRejestrCzynnosciPrzetwarzania">
    <xs:sequence>
      <xs:element name="ElementRejestruCzynnosciPrzetwarzania" type="TElementRejestruCzynnosciPrzetwarzania" minOccurs="0" maxOccurs="unbounded">
        <xs:annotation>
          <xs:documentation>Dane dotyczące elementu rejestru czynności przetwarzania.</xs:documentation>
        </xs:annotation>
      </xs:element>
    </xs:sequence>
  </xs:complexType>
  
  <xs:element name="RejestrCzynnosciPrzetwarzania" type="TRejestrCzynnosciPrzetwarzania">
    <xs:annotation>
      <xs:documentation>Dane dotyczące rejestru czynności przetwarzania.</xs:documentation>
    </xs:annotation>
  </xs:element>
  
</xs:schema>