<?xml version="1.0" encoding="utf-8"?>
<xs:schema id="Sledz"
    elementFormDefault="qualified"
    xmlns=""
    xmlns:xs="http://www.w3.org/2001/XMLSchema"
>
  <xs:element name="Sledz">
    <xs:complexType>
      <xs:all>
        <xs:element name="ECP"
                    minOccurs="0"
                    maxOccurs="1">
          <xs:complexType>
            <xs:attribute name="DniPlanowanych" type="xs:string" use="required"/>
            <xs:attribute name="GodzinPlanowanych" type="xs:string" use="required"/>
            <xs:attribute name="GodzinNocnychPlanowanych" type="xs:string" use="required"/>
            <xs:attribute name="DniWykonanych" type="xs:string" use="required"/>
            <xs:attribute name="GodzinWykonanych" type="xs:string" use="required"/>
            <xs:attribute name="GodzinWykonanychNocnych" type="xs:string" use="required"/>
            <xs:attribute name="DniPozaUmowa" type="xs:string" use="required"/>
            <xs:attribute name="GodzinPozaUmowa" type="xs:string" use="required"/>
            <xs:attribute name="DniAbsZasilk" type="xs:string" use="required"/>
            <xs:attribute name="DniRoboczychAbsZasilk" type="xs:string" use="required"/>
            <xs:attribute name="GodzinAbsZasilk" type="xs:string" use="required"/>
            <xs:attribute name="DniUrlopu" type="xs:string" use="required"/>
            <xs:attribute name="DniNPNieNaliczajacejWynagrodzenia" type="xs:string" use="optional"/>
            <xs:attribute name="GodzinUrlopu" type="xs:string" use="required"/>
            <xs:attribute name="GodzinNPNieNaliczajacychWynagrodzenia" type="xs:string" use="optional"/>
            <xs:attribute name="DniInnejNieob" type="xs:string" use="required"/>
            <xs:attribute name="GodzinInnejNieob" type="xs:string" use="required"/>
            <xs:attribute name="GodzinAbsencji" type="xs:string" use="required"/>
            <xs:attribute name="GodzinNadl0" type="xs:string" use="required"/>
            <xs:attribute name="GodzinNadl50" type="xs:string" use="required"/>
            <xs:attribute name="GodzinNadl100" type="xs:string" use="required"/>
            <xs:attribute name="Etat" type="xs:string" use="optional"/>
            <xs:attribute name="Kalendarz" type="xs:string" use="optional"/>
            <xs:attribute name="SystemCP" type="xs:string" use="optional"/>
            <xs:attribute name="OkresRozl" type="xs:string" use="optional"/>
            <xs:attribute name="DniPracyZdalnej" type="xs:string" use="optional" />
            <xs:attribute name="DniPracyZdalnejOkazjonalnej" type="xs:string" use="optional" />
            <xs:attribute name="GodzinPracyZdalnej" type="xs:string" use="optional" />
            <xs:attribute name="GodzinPracyZdalnejOkazjonalnej" type="xs:string" use="optional" />
            <xs:attribute name="GodzinPrzepracowanychWDniuAbsencji" type="xs:string" use="optional" />
          </xs:complexType>
        </xs:element>
        <xs:element name="Brutto"
                    minOccurs="1"
                    maxOccurs="1">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="Skladnik"
                        type="TSkladnik"
                        minOccurs ="0"
                        maxOccurs="unbounded"/>
            </xs:sequence>
            <xs:attribute name="Wartosc" type="xs:string" use="optional"/>
            <xs:attribute name="ZasilkiPlaciZUS" type="TBool" use="optional"/>
          </xs:complexType>
        </xs:element>
        <xs:element name="ZwolnienieZPITDo26Lat" 
                    minOccurs="0" 
                    maxOccurs="1" 
                    type="TObliczeniaZWartoscia" />
        <xs:element name="ZwolnienieZPodatkuDlaSeniora"
                    minOccurs="0"
                    maxOccurs="1"
                    type="TObliczeniaZWartoscia" />
        <xs:element name="ZwolnienieZPodatkuDlaPowracajacego"
                    minOccurs="0"
                    maxOccurs="1"
                    type="TObliczeniaZWartoscia" />
        <xs:element name="ZwolnienieZPodatkuDlaRodziny4Plus"
                    minOccurs="0"
                    maxOccurs="1"
                    type="TObliczeniaZWartoscia" />
        <xs:element name="ZwolnienieZPodatkuInne"
                    minOccurs="0"
                    maxOccurs="1"
                    type="TObliczeniaZWartoscia" />
        <xs:element name="UlgaDlaKlasySredniej"
                    minOccurs="0"
                    maxOccurs="1"
                    type="TObliczeniaZWartoscia" />
        <xs:element name="KwotaWylaczonaZPodstawySkladekZUS"
                    minOccurs="0"
                    maxOccurs="1"
                    type="TObliczeniaZWartoscia" />
        <xs:element name="SkladkiZUS"
                    minOccurs="1"
                    maxOccurs="1">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="Podstawa"
                        type="TPodstawa"
                        minOccurs ="0"
                        maxOccurs="unbounded"/>
              <xs:element name="Skladka"
                        type="TSkladkaZUS"
                        minOccurs ="0"
                        maxOccurs="unbounded"/>
            </xs:sequence>
            <xs:attribute name="WartoscPracownik" type="xs:string" use="optional"/>
            <xs:attribute name="WartoscPracodawca" type="xs:string" use="optional"/>
          </xs:complexType>
        </xs:element>
        <xs:element name="WplatyNaPPK"
                    minOccurs="0"
                    maxOccurs="1">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="Podstawa"
                          type="TPodstawa"
                          minOccurs="1"
                          maxOccurs="1" />
              <xs:element name="Wplata"
                          type="TWplataNaPPK"
                          minOccurs="0"
                          maxOccurs="unbounded" />
              <xs:element name="RozliczeniePodatku"
                          type="TObliczeniaZKomentarzem"
                          minOccurs="0"
                          maxOccurs="1" />
            </xs:sequence>
            <xs:attribute name="WartoscPracownik" type="xs:string" use="optional" />
            <xs:attribute name="WartoscPracodawca" type="xs:string" use="optional" />
          </xs:complexType>
        </xs:element>
        <xs:element name="SkladkiBudzetowe"
                    minOccurs="0"
                    maxOccurs="1">
          <xs:complexType>
            <xs:all>
              <xs:element name="Macierzynskie"
                        minOccurs ="0"
                        maxOccurs="1">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="EmerytalnoRentowe"
                            minOccurs ="0"
                            maxOccurs="1">
                      <xs:complexType>
                        <xs:all>
                          <xs:element name="Podstawa"
                                  minOccurs="0"
                                  maxOccurs="1">
                            <xs:complexType>
                              <xs:attribute name="Zasilek" type="xs:string" use="required"/>
                              <xs:attribute name="PodwyzszenieZasilku" type="xs:string" use="required"/>
                              <xs:attribute name="Podstawa" type="xs:string" use="required"/>
                              <xs:attribute name="Limit" type="xs:string" use="optional"/>
                              <xs:attribute name="Poprzednie" type="xs:string" use="optional"/>
                              <xs:attribute name="PodstawaZwykla" type="xs:string" use="optional"/>
                              <xs:attribute name="PodstawaDlaUrlopuWychowawczego" type="xs:string" use="optional"/>
                              <xs:attribute name="Ograniczono" type="TBool" use="optional"/>
                              <xs:attribute name="Wartosc" type="xs:string" use="required"/>
                            </xs:complexType>
                          </xs:element>
                          <xs:element name="SkladkaEmerytalna"
                                  type="TSkladkaBudzetowa"
                                  minOccurs="0"
                                  maxOccurs="1"/>
                          <xs:element name="SkladkaRentowa"
                                  type="TSkladkaBudzetowaRentowa"
                                  minOccurs="0"
                                  maxOccurs="1"/>
                        </xs:all>
                        <xs:attribute name="Nalicza" type="TBool" use="optional"/>
                      </xs:complexType>
                    </xs:element>
                  </xs:sequence>
                  <xs:attribute name="Powod" type="xs:string" use="optional"/>
                </xs:complexType>
              </xs:element>
              <xs:element name="Wychowawcze"
                        minOccurs ="0"
                        maxOccurs="1">
                <xs:complexType>
                  <xs:all>
                    <xs:element name="EmerytalnoRentowe"
                            minOccurs ="0"
                            maxOccurs="1">
                        <xs:complexType>
                          <xs:all>
                            <xs:element name="Podstawa"
                                      minOccurs="0"
                                      maxOccurs="1">
                              <xs:complexType>
                                <xs:attribute name="PodstawaZAbsencji" type="xs:string" use="required"/>
                                <xs:attribute name="DniKalendarz" type="xs:string" use="required"/>
                                <xs:attribute name="PodstawaZaCzasUrlopu" type="xs:string" use="required"/>
                                <xs:attribute name="Limit" type="xs:string" use="optional"/>
                                <xs:attribute name="Poprzednie" type="xs:string" use="optional"/>
                                <xs:attribute name="PodstawaZwykla" type="xs:string" use="optional"/>
                                <xs:attribute name="Ograniczono" type="TBool" use="optional"/>
                                <xs:attribute name="Korekta" type="xs:string" use="optional"/>
                                <xs:attribute name="PodstawaSkorygowana" type="xs:string" use="optional"/>
                                <xs:attribute name="Wartosc" type="xs:string" use="required"/>
                              </xs:complexType>
                            </xs:element>
                            <xs:element name="SkladkaEmerytalna"
                                    type="TSkladkaBudzetowa"
                                    minOccurs="0"
                                    maxOccurs="1"/>
                            <xs:element name="SkladkaRentowa"
                                      type="TSkladkaBudzetowaRentowa"
                                      minOccurs="0"
                                      maxOccurs="1"/>
                          </xs:all>
                          <xs:attribute name="Nalicza" type="TBool" use="optional"/>
                        </xs:complexType>
                    </xs:element>
                    <xs:element name="Zdrowotne"
                            minOccurs ="0"
                            maxOccurs="1">
                      <xs:complexType>
                        <xs:attribute name="Nalicza" type="TBool" use="required"/>
                        <xs:attribute name="JuzNaliczona" type="TBool" use="required"/>
                        <xs:attribute name="Podstawa" type="xs:string" use="optional"/>
                        <xs:attribute name="ProcentOdl" type="xs:string" use="optional"/>
                        <xs:attribute name="ProcentNieodl" type="xs:string" use="optional"/>
                        <xs:attribute name="Procent" type="xs:string" use="optional"/>
                        <xs:attribute name="Korekta" type="xs:string" use="optional"/>
                        <xs:attribute name="Wartosc" type="xs:string" use="optional"/>
                      </xs:complexType>
                    </xs:element>
                  </xs:all>
                  <xs:attribute name="Powod" type="xs:string" use="optional"/>
                  <xs:attribute name="Dni" type="xs:string" use="optional"/>
                </xs:complexType>
              </xs:element>
            </xs:all>
            <!--<xs:attribute name="WartoscPracownik" type="xs:string" use="optional"/>-->
          </xs:complexType>
        </xs:element>
        <xs:element name="SkladkaZdrowotna"
                    minOccurs="1"
                    maxOccurs="1">
          <xs:complexType>
            <xs:all>
              <xs:element name="PodstawaZdrowotna"
                          type="TPodstawaZdrowotna"
                          minOccurs="1"
                          maxOccurs="1"/>
              <xs:element name="PodstawaZdrowotnaOdliczana"
                          type="TPodstawaZdrowotna"
                          minOccurs="0"
                          maxOccurs="1"/>
              <xs:element name="SkladkaZdrowotnaNaliczona"
                          type="TSkladkaZdrowotna"
                          minOccurs="1"
                          maxOccurs="1"/>
              <xs:element name="SkladkaZdrowotnaOdliczana"
                          type="TSkladkaZdrowotna"
                          minOccurs="0"
                          maxOccurs="1"/>
              <xs:element name="SkladkaZdrowotnaNieodliczana"
                          type="TSkladkaZdrowotna"
                          minOccurs="1"
                          maxOccurs="1"/>
              <xs:element name="SkladkaZdrowotnaNieograniczana"
                          type="TSkladkaZdrowotnaNieograniczana"
                          minOccurs="0"
                          maxOccurs="1"/>
              <xs:element name="PodatekMinusUlga"
                          type="TObliczenia"
                          minOccurs="0"
                          maxOccurs="1" />
            </xs:all>
            <xs:attribute name="Nalicza" type="TBool" use="optional"/>
            <xs:attribute name="PodatekMinusUlga" type="xs:string" use="optional"/>
            <xs:attribute name="DlaRachunku" type="TBool" use="optional"/>
            <xs:attribute name="Wartosc" type="xs:string" use="optional"/>            
          </xs:complexType>
        </xs:element>
        <xs:element name="Podatek"
                    type="TPodatek"
                    minOccurs="1"
                    maxOccurs="1" />
        <xs:element name="Netto"
                          minOccurs="1"
                          maxOccurs="1">
          <xs:complexType>
            <xs:attribute name="Brutto" type="xs:string" use="optional"/>
            <xs:attribute name="SkladkiZUS" type="xs:string" use="optional"/>
            <xs:attribute name="Podatek" type="xs:string" use="optional"/>
            <xs:attribute name="SkladkaZdrowotna" type="xs:string" use="optional"/>
            <xs:attribute name="KwotaZwolniona" type="xs:string" use="optional"/>
            <xs:attribute name="WplataNaPPK" type="xs:string" use="optional"/>
            <xs:attribute name="Wartosc" type="xs:string" use="optional"/>
          </xs:complexType>
        </xs:element>
        <xs:element name="DoWyplaty"
                          minOccurs="1"
                          maxOccurs="1">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="Skladnik"
                        type="TSkladnik"
                        minOccurs ="0"
                        maxOccurs="unbounded"/>
            </xs:sequence>
            <xs:attribute name="Netto" type="xs:string" use="optional"/>
            <xs:attribute name="Potracenia" type="xs:string" use="optional"/>
            <xs:attribute name="Dodatki" type="xs:string" use="optional"/>
            <xs:attribute name="WNaturze" type="xs:string" use="optional"/>
            <xs:attribute name="Wartosc" type="xs:string" use="optional"/>
          </xs:complexType>
        </xs:element>
        <xs:element name="Obciazenie"
                          minOccurs="1"
                          maxOccurs="1">
          <xs:complexType>
            <xs:attribute name="Brutto" type="xs:string" use="optional"/>
            <xs:attribute name="SkladkiZUS" type="xs:string" use="optional"/>
            <xs:attribute name="Dodatki" type="xs:string" use="optional"/>
            <xs:attribute name="ZasilkiZUS" type="xs:string" use="optional"/>
            <xs:attribute name="KwotaZwolniona" type="xs:string" use="optional"/>
            <xs:attribute name="WplataNaPPK" type="xs:string" use="optional"/>
            <xs:attribute name="Wartosc" type="xs:string" use="optional"/>
          </xs:complexType>
        </xs:element>
      </xs:all>
      <xs:attribute name="wersja" type="xs:string" use="optional"/>
    </xs:complexType>
  </xs:element>
  
  <xs:complexType name="TPomniejszenie">
    <xs:attribute name="Nazwa" type="xs:string" use="optional"/>
    <xs:attribute name="Wartosc" type="xs:string" use="optional"/>
    <xs:attribute name="Sposob" type="xs:string" use=" optional"/>
    <xs:attribute name="DniGodzin" type="xs:string" use="optional"/>
    <xs:attribute name="Opis" type="xs:string" use="optional"/>
  </xs:complexType>

  <xs:complexType name="TPomniejszenia">
    <xs:choice>
      <xs:sequence>
        <xs:element name="Pomniejszenie"
                  type="TPomniejszenie"
                  minOccurs="0"
                  maxOccurs="unbounded"/>
      </xs:sequence>
      <xs:sequence>
        <xs:element name="PomniejszeniaWOkresie"
                    type="TPomniejszeniaWOkresie"
                    minOccurs="0"
                    maxOccurs="unbounded">
        </xs:element>
      </xs:sequence>
    </xs:choice>
    <xs:attribute name="Wartosc" type="xs:string" use="required"/>
    <xs:attribute name="Opis" type="xs:string" use="optional"/>
  </xs:complexType>

  <xs:complexType name="TPomniejszeniaWOkresie">
    <xs:sequence>
      <xs:element name="Pomniejszenie"
                  type="TPomniejszenie"
                  minOccurs="0"
                  maxOccurs="unbounded">
      </xs:element>
    </xs:sequence>
    <xs:attribute name="Wartosc" type="xs:string" use="required"/>
    <xs:attribute name="Okres" type="xs:string" use="required"/>
  </xs:complexType>

  <xs:complexType name="TPowiekszenia">
    <xs:choice>
      <xs:sequence>
        <xs:element name="Powiekszenie"
                  type="TPowiekszenie"
                  minOccurs="0"
                  maxOccurs="unbounded"/>
      </xs:sequence>
      <xs:sequence>
        <xs:element name="PowiekszeniaWOkresie"
                    type="TPowiekszeniaWOkresie"
                    minOccurs="0"
                    maxOccurs="unbounded">
        </xs:element>
      </xs:sequence>
    </xs:choice>
    <xs:attribute name="Wartosc" type="xs:string" use="required"/>
    <xs:attribute name="Opis" type="xs:string" use="optional"/>
  </xs:complexType>

  <xs:complexType name="TPowiekszeniaWOkresie">
    <xs:sequence>
      <xs:element name="Powiekszenie"
                  type="TPowiekszenie"
                  minOccurs="0"
                  maxOccurs="unbounded">
      </xs:element>
    </xs:sequence>
    <xs:attribute name="Wartosc" type="xs:string" use="required"/>
    <xs:attribute name="Okres" type="xs:string" use="required"/>
  </xs:complexType>

  <xs:complexType name="TPowiekszenie">
    <xs:attribute name="Nazwa" type="xs:string" use="optional"/>
    <xs:attribute name="Wartosc" type="xs:string" use="optional"/>
    <xs:attribute name="Sposob" type="xs:string" use=" optional"/>
    <xs:attribute name="DniGodzin" type="xs:string" use="optional"/>
    <xs:attribute name="Opis" type="xs:string" use="optional"/>
  </xs:complexType>

  <xs:complexType name="TObliczenie">
    <xs:sequence>
      <xs:element name="Obliczenia"
                  minOccurs="0"
                  maxOccurs="1"
                  type="TObliczenia" />
    </xs:sequence>
    <xs:attribute name="Nr" type="xs:string" use="optional"/>
    <xs:attribute name="Nazwa" type="xs:string" use="required"/>
    <xs:attribute name="Wartosc" type="xs:string" use="optional"/>
    <xs:attribute name="Opis" type="xs:string" use="optional"/>
    <xs:attribute name="Separator" type="TBool" use="optional"/>
    <xs:attribute name="Wyroznione" type="TBool" use="optional"/>
    <xs:attribute name="Id" type="xs:string" use="optional"/>
  </xs:complexType>

  <xs:complexType name="TObliczenia">
    <xs:sequence>
      <xs:element name="Obliczenie"
                type="TObliczenie"
                minOccurs ="0"
                maxOccurs="unbounded"/>
    </xs:sequence>
    <xs:attribute name="IsExpanded" type="TBool" use="optional"/>
  </xs:complexType>

  <xs:complexType name="TKorekta">
    <xs:attribute name="Nazwa" type="xs:string" use="required"/>
    <xs:attribute name="Wartosc" type="xs:string" use="required"/>
  </xs:complexType>

  <xs:complexType name="TKorekty">
    <xs:sequence>
      <xs:element name="Korekta"
                type="TKorekta"
                minOccurs ="0"
                maxOccurs="unbounded"/>
    </xs:sequence>
    <xs:attribute name="Wartosc" type="xs:string" use="required"/>
    <xs:attribute name="Nadpisano" type="TBool" use="optional"/>
    <xs:attribute name="Pozostalo" type="xs:string" use="optional"/>
  </xs:complexType>
  
  <xs:complexType name="TSkladnik">
    <xs:all>
      <xs:element name="Pomniejszenia"
                type="TPomniejszenia"
                minOccurs="0"
                maxOccurs="1"/>
      <xs:element name="Obliczenia"
                type="TObliczenia"
                minOccurs="0"
                maxOccurs="1"/>
      <xs:element name="Korekty"
                type="TKorekty"
                minOccurs="0"
                maxOccurs="1"/>
      <xs:element name="Powiekszenia"
                type="TPowiekszenia"
                minOccurs="0"
                maxOccurs="1"/>
      <xs:element name="Opodatkowanie"
                type="TObliczenia"
                minOccurs="0"
                maxOccurs="1"/>
    </xs:all>
    <xs:attribute name="Nazwa" type="xs:string" use="optional"/>
    <xs:attribute name="NazwaWidoczna" type="xs:string" use="optional"/>
    <xs:attribute name="Wartosc" type="xs:string" use="optional"/>
    <xs:attribute name="WartoscNominalna" type="xs:string" use="optional"/>
    <xs:attribute name="WartoscFinalna" type="xs:string" use="optional"/>
    <xs:attribute name="NadpisanoWartNom" type="TBool" use="optional"/>
    <xs:attribute name="NadpisanoWartNomOpis" type="xs:string" use="optional"/>
    <xs:attribute name="NadpisanoWartFin" type="TBool" use="optional"/>
  </xs:complexType>

  <xs:complexType name="TPodstawa">
    <xs:sequence>
      <xs:element name="Skladnik"
                type="TSkladnik"
                minOccurs ="0"
                maxOccurs="unbounded"/>
    </xs:sequence>
    <xs:attribute name="Nazwa" type="xs:string" use="optional"/>
    <xs:attribute name="NazwaWyswietlana" type="xs:string" use="optional"/>
    <xs:attribute name="Wartosc" type="xs:string" use="optional"/>
    <xs:attribute name="Nalicza" type="TNalicza" use="optional"/>
    <xs:attribute name="Ograniczono" type="TBool" use="optional"/>
    <xs:attribute name="Ograniczanie" type="TBool" use="optional"/>
    <xs:attribute name="Limit" type="xs:string" use="optional"/>
    <xs:attribute name="Poprzednie" type="xs:string" use="optional"/>
    <xs:attribute name="WylaczonoWKorekcie" type="xs:string" use="optional" />
    <xs:attribute name="KwotaWylaczonaZPodstawy" type="xs:string" use="optional" />
    
  </xs:complexType>

  <xs:complexType name="TSkladka">
    <xs:attribute name="Nalicza" type="TNalicza" use="optional"/>
    <xs:attribute name="Nazwa" type="xs:string" use="optional"/>
    <xs:attribute name="NazwaWyswietlana" type="xs:string" use="optional"/>
    <xs:attribute name="Procent" type="xs:string" use="optional"/>
    <xs:attribute name="ProcentKomentarz" type="xs:string" use="optional"/>
    <xs:attribute name="Nadpisano" type="TBool" use="optional"/>
    <xs:attribute name="Wartosc" type="xs:string" use="optional"/>
    <xs:attribute name="PodstawaBiezaca" type="xs:string" use="optional"/>
    <xs:attribute name="PodstawaSumaryczna" type="xs:string" use="optional"/>
    <xs:attribute name="KwotaWyliczona" type="xs:string" use="optional"/>
    <xs:attribute name="KwotaJuzZaplacona" type="xs:string" use="optional"/>
  </xs:complexType>

  <xs:complexType name="TSkladkaZUS">
    <xs:complexContent>
      <xs:extension base="TSkladka">
        <xs:sequence>
          <xs:element minOccurs="0" name="PrzekroczenieMinimalnej" type="TPrzekroczenieMinimalnej" />
        </xs:sequence>
        <xs:attribute name="PonizejLimituWieku" type="TBool" use="optional"/>
        <xs:attribute name="OkresZwolnienia" type="TBool" use="optional"/>
        <xs:attribute name="Komentarz" type="xs:string" use="optional"/>
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>

  <xs:complexType name="TSkladkaZdrowotna">
    <xs:complexContent>
      <xs:extension base="TSkladka">
        <xs:attribute name="WartoscNieograniczona" type="xs:string" use="optional"/>
        <xs:attribute name="Ryczalt" type="TBool" use="optional"/>
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>

  <xs:complexType name="TSkladkaZdrowotnaNieograniczana">
    <xs:attribute name="SumaSkladnikow" type="xs:string" use="optional"/>
    <xs:attribute name="KwotaWylaczonaZeSkladek" type="xs:string" use="optional"/>
    <xs:attribute name="SkladkiSpoleczne" type="xs:string" use="optional"/>
    <xs:attribute name="Podstawa" type="xs:string" use="optional"/>
    <xs:attribute name="Procent" type="xs:string" use="optional"/>
    <xs:attribute name="Wartosc" type="xs:string" use="optional"/>
  </xs:complexType>

  <xs:complexType name="TSkladkaBudzetowa">
    <xs:attribute name="Nalicza" type="TBool" use="optional"/>
    <xs:attribute name="Procent" type="xs:string" use="optional"/>
    <xs:attribute name="Wartosc" type="xs:string" use="required"/>
  </xs:complexType>

  <xs:complexType name="TSkladkaBudzetowaRentowa">
    <xs:complexContent>
      <xs:extension base="TSkladkaBudzetowa">
        <xs:attribute name="ProcentPracownik" type="xs:string" use="optional"/>
        <xs:attribute name="ProcentPracodawca" type="xs:string" use="optional"/>
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>

  <xs:complexType name="TPodstawaZdrowotna">
    <xs:sequence>
      <xs:element name="Skladnik"
                type="TSkladnik"
                minOccurs ="0"
                maxOccurs="unbounded"/>
    </xs:sequence>
    <xs:attribute name="SumaSkladnikow" type="xs:string" use="optional"/>
    <xs:attribute name="SkladkiSpoleczne" type="xs:string" use="optional"/>
    <xs:attribute name="Wartosc" type="xs:string" use="optional"/>
    <xs:attribute name="Ryczalt" type="TBool" use="optional"/>
    <xs:attribute name="KwotaWylaczonaZPodstawy" type="xs:string" use="optional" />
  </xs:complexType>

  <xs:simpleType name="TBool">
    <xs:restriction base="xs:string">
      <xs:enumeration value="tak" />
      <xs:enumeration value="nie" />
    </xs:restriction>
  </xs:simpleType>
  
  <xs:simpleType name="TNalicza">
    <xs:restriction base="xs:string">
      <xs:enumeration value="tak" />
      <xs:enumeration value="nie" />
      <xs:enumeration value="wlaczono" />
      <xs:enumeration value="wylaczono" />
    </xs:restriction>
  </xs:simpleType>

  <xs:complexType name="TPrzekroczenieMinimalnej">
    <xs:sequence>
      <xs:element name="Obliczenie"
                type="TObliczenie"
                minOccurs ="0"
                maxOccurs="unbounded"/>
    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="TPodatek">
    <xs:all>
      <xs:element name="Koszty" 
                  minOccurs="1"
                  maxOccurs="1">
        <xs:complexType>
          <xs:all>
            <xs:element name="KosztyAutorskie"
                        minOccurs="0"
                        maxOccurs="1">
              <xs:complexType>
                <xs:all>
                  <xs:element name="PodstawaKosztowAutorskich"
                              minOccurs="1"
                              maxOccurs="1">
                    <xs:complexType>
                      <xs:attribute name="SumaSkladnikow" type="xs:string" use="optional"/>
                      <xs:attribute name="SkladkiSpoleczne" type="xs:string" use="optional"/>
                      <xs:attribute name="Wartosc" type="xs:string" use="optional"/>
                    </xs:complexType>
                  </xs:element>
                </xs:all>
                <xs:attribute name="PracownikNalicza" type="TBool" use="optional" />
                <xs:attribute name="Procent" type="xs:string" use="optional"/>
                <xs:attribute name="WartoscWyliczona" type="xs:string" use="optional"/>
                <xs:attribute name="Nadpisano" type="TBool" use="optional"/>
                <xs:attribute name="Wartosc" type="xs:string" use="optional"/>
                <xs:attribute name="KosztyPoprzednie" type="xs:string" use="optional"/>
                <xs:attribute name="ZwolnieniePoprzednie" type="xs:string" use="optional"/>
                <xs:attribute name="Limit" type="xs:string" use="optional"/>
              </xs:complexType>
            </xs:element>
            <xs:element name="KosztyZwykle"
                  minOccurs="0"
                  maxOccurs="1">
              <xs:complexType>
                <xs:attribute name="NaliczaListaPlac" type="TBool" use="optional"/>
                <xs:attribute name="PoZakonczeniuUmowy" type="TBool" use="optional"/>
                <xs:attribute name="RodzajKosztow" type="xs:string" use="optional"/>
                <xs:attribute name="Wyliczone" type="xs:string" use="optional"/>
                <xs:attribute name="JuzUwzglednione" type="xs:string" use="optional"/>
                <xs:attribute name="SumaSkladnikow" type="xs:string" use="optional"/>
                <xs:attribute name="Maksymalne" type="xs:string" use="optional"/>
                <xs:attribute name="Nadpisano" type="TBool" use="optional"/>
                <xs:attribute name="Wartosc" type="xs:string" use="optional"/>
                <xs:attribute name="KosztyMiesieczneOgraniczoneDoZera" type="TBool" use="optional" />
              </xs:complexType>
            </xs:element>
          </xs:all>
          <xs:attribute name="PracownikNalicza" type="TBool" use="optional" />
          <xs:attribute name="Nadpisano" type="TBool" use="optional"/>
          <xs:attribute name="Wartosc" type="xs:string" use="optional"/>
          <xs:attribute name="TypKosztow" type="xs:string" use="optional"/>
          <xs:attribute name="Ryczalt" type="TBool" use="optional"/>
          <xs:attribute name="RodzajKosztow" type="xs:string" use="optional"/>
          <xs:attribute name="Procent" type="xs:string" use="optional"/>
          <xs:attribute name="Podstawa" type="xs:string" use="optional"/>
          <xs:attribute name="Limit" type="xs:string" use="optional"/>
          <xs:attribute name="KosztyPoprzednie" type="xs:string" use="optional"/>
          <xs:attribute name="ZwolnieniePoprzednie" type="xs:string" use="optional"/>
          <xs:attribute name="WartoscWyliczona" type="xs:string" use="optional"/>
        </xs:complexType>
      </xs:element>
      <xs:element name="PodstawaOpodatkowania"
                  minOccurs="1"
                  maxOccurs="1">
        <xs:complexType>
          <xs:attribute name="Brutto" type="xs:string" use="optional"/>
          <xs:attribute name="SkladkiSpoleczneOpodatk" type="xs:string" use="optional"/>
          <xs:attribute name="SkladkiSpoleczneOpodatkUwzgledniajaInneWyplaty" type="TBool" use="optional" />
          <xs:attribute name="SposobStosowaniaZwolnienia" type="xs:string" />
          <xs:attribute name="WplataNaPPK" type="xs:string" use="optional"/>
          <xs:attribute name="ZwolnienieZPodatkuDo26Lat" type="xs:string" use="optional" />
          <xs:attribute name="ZwolnienieZPodatkuOpis" type="xs:string" use="optional" />
          <xs:attribute name="UlgaDlaKlasySredniej" type="xs:string" use="optional" />
          <xs:attribute name="WartoscNiezaokr" type="xs:string" use="optional"/>
          <xs:attribute name="Wartosc" type="xs:string" use="optional"/>
          <xs:attribute name="Ryczalt" type="TBool" use="optional"/>
          <!--Już nieużywane, ale zostawiam, żeby stare śledzie działały.-->
          <xs:attribute name="NieopodPodstawaChorobowa" type="xs:string" use="optional"/>
          <xs:attribute name="NieopodPodstawaEmerytalnoRentowa" type="xs:string" use="optional"/>
          <!--Koniec nieużywanych-->
        </xs:complexType>
      </xs:element>
      <xs:element name="PodatekNaliczony"
                  minOccurs="1"
                  maxOccurs="1">
        <xs:complexType>
          <xs:attribute name="Nalicza" type="TBool" use="optional"/>
          <xs:attribute name="Procent" type="xs:string" use="optional"/>
          <xs:attribute name="WspolneRozliczenie" type="xs:string" use="optional"/>
          <xs:attribute name="WniosekOWyzszaStawkePodatku" type="TBool" use="optional"/>
          <xs:attribute name="PomijaWnioskiPIT2" type="TBool" use="optional" />
          <xs:attribute name="PodatekSposobWyliczenia" type="xs:string" use="optional"/>
          <xs:attribute name="PodstawaBiezaca" type="xs:string" use="optional"/>
          <xs:attribute name="PodstawaSumaryczna" type="xs:string" use="optional"/>
          <xs:attribute name="KwotaWyliczona" type="xs:string" use="optional"/>
          <xs:attribute name="KwotaJuzZaplacona" type="xs:string" use="optional"/>
          <xs:attribute name="Wartosc" type="xs:string" use="optional"/>
        </xs:complexType>
      </xs:element>
      <xs:element name="Ulga"
                  minOccurs="1"
                  maxOccurs="1">
        <xs:complexType>
          <xs:attribute name="NaliczaListaPlac" type="TBool" use="optional"/>
          <xs:attribute name="NaliczaUmowa" type="TBool" use="optional"/>
          <xs:attribute name="NaliczaPracownik" type="TBool" use="optional"/>
          <xs:attribute name="UmowaWaznaWDniuWyplaty" type="TBool" use="optional"/>
          <xs:attribute name="NowaInterpretacjaV22" type="TBool" use="optional"/>
          <xs:attribute name="NieNaliczaBoPrawoDoEmRe" type="TBool" use="optional"/>
          <xs:attribute name="PrzekroczonoProgPodatkowy" type="TBool" use="optional"/>
          <xs:attribute name="PrzekroczonoLimitNiepobieraniaZaliczki" type="TBool" use="optional"/>
          <xs:attribute name="NieNaliczaBoNieSkalaPodatkowa" type="TBool" use="optional" />
          <xs:attribute name="PomijaWnioskiPIT2" type="TBool" use="optional" />
          <xs:attribute name="Indywidualna" type="TBool" use="optional"/>
          <xs:attribute name="CzyUlgaNaRachunku" type="TBool" use="optional"/>
          <xs:attribute name="UlgaMiesieczna" type="xs:string" use="optional"/>
          <xs:attribute name="UlgaPodatkowaMalzonkaLubDziecka" type="xs:string" use="optional" />
          <xs:attribute name="PodatekSumaryczny" type="xs:string" use="optional" />
          <xs:attribute name="CzescKwotyZmniejszajacejPodatek" type="xs:string" use="optional"/>
          <xs:attribute name="UlgaJuzUwzgledniona" type="xs:string" use="optional"/>
          <xs:attribute name="UlgaOgraniczanaDoPodatkuSumarycznego" type="TBool" use="optional"/>
          <xs:attribute name="UlgaUjemnaOgraniczonaDoZera" type="TBool" use="optional"/>
          <xs:attribute name="MiesiecznyLimit" type="xs:string" use="optional"/>
          <xs:attribute name="UlgaJuzUwzglednionaWszystkieWynagrodzenia" type="xs:string" use="optional"/>
          <xs:attribute name="Nadpisano" type="TBool" use="optional"/>
          <xs:attribute name="Wartosc" type="xs:string" use="optional"/>
        </xs:complexType>
      </xs:element>
      <xs:element name="OdroczenieZaliczki" minOccurs="0" maxOccurs="1" type="TOdroczenieZaliczki" />
    </xs:all>
    <xs:attribute name="Rachunek" type="TBool" use="optional"/>
    <!-- Nieużywane, ale zostawiam, żeby można było odpalić stare Śledzie, które mają tu coś wpisane -->
    <xs:attribute name="ZdrOdlNieogr" type="xs:string" use="optional"/>
    <xs:attribute name="PodatekMinusUlga" type="xs:string" use="optional"/>
    <!-- Koniec nieużywanych -->
    <xs:attribute name="ZdrOdl" type="xs:string" use="optional"/>
    <xs:attribute name="NaliczaZaliczke" type="TBool" use="optional"/>
    <xs:attribute name="PracownikNaliczaZaliczke" type="TBool" use="optional"/>
    <xs:attribute name="PomijaWnioskiPIT2" type="TBool" use="optional" />
    <xs:attribute name="PodstawaBiezaca" type="xs:string" use="optional"/>
    <xs:attribute name="PodstawaSumaryczna" type="xs:string" use="optional"/>
    <xs:attribute name="KwotaWyliczona" type="xs:string" use="optional"/>
    <xs:attribute name="KwotaJuzZaplacona" type="xs:string" use="optional"/>
    <xs:attribute name="Nadpisano" type="TBool" use="optional"/>
    <xs:attribute name="Wartosc" type="xs:string" use="optional"/>
    <xs:attribute name="WartoscNiezaokr" type="xs:string" use="optional"/>
    <xs:attribute name="PrzekroczonoLimit" type="TBool" use="optional" />
    <xs:attribute name="PrzekroczonoLimitZaliczkaKomentarz" type="xs:string" use="optional" />
    <xs:attribute name="NadplataPIT40" type="xs:string" use="optional"/>
    <xs:attribute name="KwotaZasilkow" type="xs:string" use="optional"/>
    <xs:attribute name="ObliczaPodatekOdZasilkow" type="TBool" use="optional"/>
    <xs:attribute name="ZaliczkaPrzedOdroczeniem" type="xs:string" use="optional" />
  </xs:complexType>

  <xs:complexType name="TOdroczenieZaliczki">
    <xs:complexContent>
      <xs:extension base="TObliczenia">
        <xs:attribute name="NadpisanaZaliczkaOdroczona" type="xs:string" />
        <xs:attribute name="NadpisanaSplataZaliczkiOdroczonej" type="xs:string" />
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>

  <xs:complexType name="TWplataNaPPK">
    <xs:complexContent>
      <xs:extension base="TObliczeniaZWartoscia">
        <xs:attribute name="Nazwa" type="xs:string" use="optional"/>
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>

  <xs:complexType name="TObliczeniaZWartoscia">
    <xs:complexContent>
      <xs:extension base="TObliczenia">
        <xs:attribute name="Wartosc" type="xs:string" use="optional" />
        <xs:attribute name="Nadpisano" type="TBool" use="optional"/>
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>

  <xs:complexType name="TObliczeniaZKomentarzem">
    <xs:complexContent>
      <xs:extension base="TObliczeniaZWartoscia">
        <xs:attribute name="Komentarz" type="xs:string" use="optional" />
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>
</xs:schema>
