<?xml version="1.0" encoding="utf-8"?>
<xs:schema elementFormDefault="qualified"
           targetNamespace="http://schemas.insert.com.pl/2016/hop/waluty"
           xmlns="http://schemas.insert.com.pl/2016/hop/waluty"
           xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:annotation>
    <xs:documentation>Informacje o walutach.</xs:documentation>
  </xs:annotation>
  <xs:complexType name="TWaluta">
    <xs:annotation>
      <xs:documentation>Informacje o walucie.</xs:documentation>
    </xs:annotation>
    <xs:sequence>
      <xs:annotation>
        <xs:documentation>Dane waluty.</xs:documentation>
      </xs:annotation>
      <xs:element type="xs:string" name="Symbol">
        <xs:annotation>
          <xs:documentation>Symbol.</xs:documentation>
        </xs:annotation>
      </xs:element>
      <xs:element type="xs:string" name="Nazwa">
        <xs:annotation>
          <xs:documentation>Nazwa.</xs:documentation>
        </xs:annotation>
      </xs:element>
      <xs:element type="xs:unsignedByte" name="Precyzja" minOccurs="0" maxOccurs="1" default="2">
        <xs:annotation>
          <xs:documentation>Precyzja, z jaką pamiętane są kwoty w walucie.</xs:documentation>
        </xs:annotation>
      </xs:element>
      <xs:element type="xs:int" name="LiczbaJednostek" minOccurs="0" maxOccurs="1" default="1">
        <xs:annotation>
          <xs:documentation>Liczba jednostek waluty przy podawaniu kursu.</xs:documentation>
        </xs:annotation>
      </xs:element>
      <xs:element type="xs:unsignedByte" name="PrecyzjaCeny" minOccurs="0" maxOccurs="1" default="2">
        <xs:annotation>
          <xs:documentation>Precyzja waluty dla cen.</xs:documentation>
        </xs:annotation>
      </xs:element>
    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="TWaluty">
    <xs:annotation>
      <xs:documentation>Kolekcja walut.</xs:documentation>
    </xs:annotation>
    <xs:sequence>
      <xs:annotation>
    <xs:documentation>Kolekcja walut.</xs:documentation>
  </xs:annotation>
      <xs:element name="Waluta" maxOccurs="unbounded" minOccurs="0" type="TWaluta">
        <xs:annotation>
          <xs:documentation>Waluta.</xs:documentation>
        </xs:annotation>
      </xs:element>
    </xs:sequence>
  </xs:complexType>

  <xs:element name="Waluty" type="TWaluty">
    <xs:annotation>
      <xs:documentation>Kolekcja walut.</xs:documentation>
    </xs:annotation>
  </xs:element>
</xs:schema>