<?xml version="1.0" encoding="utf-8"?>

<xs:schema 
  attributeFormDefault="unqualified" 
  elementFormDefault="qualified" 
  targetNamespace="http://schemas.insert.com.pl/2014/hop/wspolnicy"
  xmlns="http://schemas.insert.com.pl/2014/hop/wspolnicy"
  xmlns:wspolne="http://schemas.insert.com.pl/2013/hop"
  xmlns:rachunki="http://schemas.insert.com.pl/2013/hop/rachunkibankowe"
  xmlns:xs="http://www.w3.org/2001/XMLSchema">
  
  <xs:import id="WspolnePart" namespace="http://schemas.insert.com.pl/2013/hop" schemaLocation="Wspolne.xsd"/>
  <xs:import id="RachunkiBankowe" namespace="http://schemas.insert.com.pl/2013/hop/rachunkibankowe" schemaLocation="RachunkiBankowe.xsd"/>

  <xs:simpleType name="TTypDeklaracjiZUSWspolnika">
    <xs:annotation>
      <xs:documentation>Typ składanej deklaracji ZUS.</xs:documentation>
    </xs:annotation>
    <xs:restriction base="xs:string">
      <xs:enumeration value="RCA">
        <xs:annotation>
          <xs:documentation>Deklaracja RCA.</xs:documentation>
        </xs:annotation>
      </xs:enumeration>
      <xs:enumeration value="RZA">
        <xs:annotation>
          <xs:documentation>Deklaracja RZA.</xs:documentation>
        </xs:annotation>
      </xs:enumeration>
      <xs:enumeration value="DRA">
        <xs:annotation>
          <xs:documentation>Deklaracja DRA.</xs:documentation>
        </xs:annotation>
      </xs:enumeration>
    </xs:restriction>
  </xs:simpleType>

  <xs:simpleType name="TMetodaOplacaniaZaliczekPIT">
    <xs:annotation>
      <xs:documentation>Metoda opłacania zaliczek PIT.</xs:documentation>
    </xs:annotation>
    <xs:restriction base="xs:string">
      <xs:enumeration value="Miesieczna">
        <xs:annotation>
          <xs:documentation>Miesięczna.</xs:documentation>
        </xs:annotation>
      </xs:enumeration>
      <xs:enumeration value="Kwartalna">
        <xs:annotation>
          <xs:documentation>Kwartalna.</xs:documentation>
        </xs:annotation>
      </xs:enumeration>
    </xs:restriction>
  </xs:simpleType>

  <xs:simpleType name="TFormaOpodatkowaniaPIT">
    <xs:annotation>
      <xs:documentation>Forma opodatkowania PIT.</xs:documentation>
    </xs:annotation>
    <xs:restriction base="xs:string">
      <xs:enumeration value="Liniowa">
        <xs:annotation>
          <xs:documentation>Liniowa.</xs:documentation>
        </xs:annotation>
      </xs:enumeration>
      <xs:enumeration value="Progresywna">
        <xs:annotation>
          <xs:documentation>Progresywna.</xs:documentation>
        </xs:annotation>
      </xs:enumeration>
    </xs:restriction>
  </xs:simpleType>

  <xs:complexType name="TDaneDeklaracjiZUS">
    <xs:annotation>
      <xs:documentation>Dane deklaracji ZUS.</xs:documentation>
    </xs:annotation>
    <xs:sequence>
      <xs:element name="TypDeklaracjiZUS" type="TTypDeklaracjiZUSWspolnika" minOccurs="0">
        <xs:annotation>
          <xs:documentation>Typ deklaracji ZUS, gdy jest składana.</xs:documentation>
        </xs:annotation>
      </xs:element>
      <xs:element name="TerminSkladaniaDRA" minOccurs="0" type="wspolne:TerminSkladaniaDeklaracjiZUS">
        <xs:annotation>
          <xs:documentation>Termin składania deklaracji DRA.</xs:documentation>
        </xs:annotation>
      </xs:element>
      <xs:element name="TypDrugiegoIdentyfikatora" minOccurs="0">
        <xs:annotation>
          <xs:documentation>Typ II identyfikatora ZUS.</xs:documentation>
        </xs:annotation>
        <xs:simpleType>
          <xs:restriction base="xs:string">
            <xs:enumeration value="REGON">
              <xs:annotation>
                <xs:documentation>REGON jako drugi identyfikator ZUS.</xs:documentation>
              </xs:annotation>
            </xs:enumeration>
            <xs:enumeration value="PESEL">
              <xs:annotation>
                <xs:documentation>PESEL jako drugi identyfikator ZUS.</xs:documentation>
              </xs:annotation>
            </xs:enumeration>
            <xs:enumeration value="SeriaNrDowoduOs">
              <xs:annotation>
                <xs:documentation>Seria i nr dowodu osobistego jako drugi identyfikator ZUS.</xs:documentation>
              </xs:annotation>
            </xs:enumeration>
            <xs:enumeration value="SeriaNrPaszportu">
              <xs:annotation>
                <xs:documentation>Seria i nr paszportu jako drugi identyfikator ZUS.</xs:documentation>
              </xs:annotation>
            </xs:enumeration>
          </xs:restriction>
        </xs:simpleType>
      </xs:element>
    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="TWartoscSkladkiZUS">
    <xs:annotation>
      <xs:documentation>Określenie wartości składki ZUS z opcjonalnym początkiem okresu obowiązywania.</xs:documentation>
    </xs:annotation>
    <xs:simpleContent>
      <xs:extension base="xs:decimal">
        <xs:attribute name="WazneOd" type="xs:date" use="optional">
          <xs:annotation>
            <xs:documentation>Opcjonalna data rozpoczęcia obowiązywania wartości. Gdy nie podano, wartość obowiązuje od początku (tak zdefiniowana wartość może wystąpić najwyżej raz).</xs:documentation>
          </xs:annotation>
        </xs:attribute>
      </xs:extension>
    </xs:simpleContent>
  </xs:complexType>
  
  <xs:complexType name="TWartosciSkladekZUS">
    <xs:annotation>
      <xs:documentation>Wartości składek ZUS dla wspólnika.</xs:documentation>
    </xs:annotation>
    <xs:sequence>
      <xs:element name="PodstawaUbEmerytRentFP" type="TWartoscSkladkiZUS" maxOccurs="unbounded">
        <xs:annotation>
          <xs:documentation>Wartość podstawy do ubezpieczenia emerytalnego, rentowego, Funduszu pracy i Funduszu Solidarnościowego</xs:documentation>
        </xs:annotation>
      </xs:element>
      <xs:element name="PodstawaUbChorobowegoWypadkowego" type="TWartoscSkladkiZUS" maxOccurs="unbounded">
        <xs:annotation>
          <xs:documentation>Wartość podstawy do ubezpieczenia chorobowego i wypadkowego</xs:documentation>
        </xs:annotation>
      </xs:element>
      <xs:element name="StopaProcentowaUbWypadkowego" type="TWartoscSkladkiZUS" maxOccurs="unbounded">
        <xs:annotation>
          <xs:documentation>Wartość stopy procentowej ubezpieczenia wypadkowego [%].</xs:documentation>
        </xs:annotation>
      </xs:element>
      <xs:element name="PodstawaUbZdrowotnego" type="TWartoscSkladkiZUS" maxOccurs="unbounded">
        <xs:annotation>
          <xs:documentation>Wartość podstawy do ubezpieczenia chorobowego i wypadkowego</xs:documentation>
        </xs:annotation>
      </xs:element>
    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="TWartosciSkladekZUSzParametrow">
    <xs:annotation>
      <xs:documentation>Dodatkowe dane do wartości składek ZUS pobieranych z parametrów.</xs:documentation>
    </xs:annotation>
    <xs:attribute name="KorzystaZPreferencji" type="xs:boolean" use="optional">
      <xs:annotation>
        <xs:documentation>Osoba korzystająca z preferencyjnych wartości składek.</xs:documentation>
      </xs:annotation>
    </xs:attribute>
  </xs:complexType>

  <xs:complexType name="TDaneUbezpieczeniaZUS">
    <xs:annotation>
      <xs:documentation>Informacje o wartościach i naliczaniu składek na ubezpieczenie ZUS.</xs:documentation>
    </xs:annotation>
    <xs:choice>
      <xs:element name="ZParametrow" type="TWartosciSkladekZUSzParametrow">
        <xs:annotation>
          <xs:documentation>Wartości składek będą pobierane z parametrów.</xs:documentation>
        </xs:annotation>
      </xs:element>
      <xs:element name="Indywidualnie" type="TWartosciSkladekZUS">
        <xs:annotation>
          <xs:documentation>Własne (nie pobierane z parametrów) wartości składek dla wspólnika.</xs:documentation>
        </xs:annotation>
      </xs:element>
    </xs:choice>
    <xs:attribute name="Emerytalne" type="xs:boolean" use="optional">
      <xs:annotation>
        <xs:documentation>Określa, czy dla wspólnika mają być naliczane składki emerytalne.</xs:documentation>
      </xs:annotation>
    </xs:attribute>
    <xs:attribute name="Rentowe" type="xs:boolean" use="optional">
      <xs:annotation>
        <xs:documentation>Określa, czy dla wspólnika mają być naliczane składki rentowe.</xs:documentation>
      </xs:annotation>
    </xs:attribute>
    <xs:attribute name="FunduszPracy" type="xs:boolean" use="optional">
      <xs:annotation>
        <xs:documentation>Określa, czy dla wspólnika mają być naliczane składki na Fundusz Pracy i Fundusz Solidarnościowy.</xs:documentation>
      </xs:annotation>
    </xs:attribute>
    <xs:attribute name="FGSP" type="xs:boolean" use="optional" default="false">
      <xs:annotation>
        <xs:documentation>Określa, czy dla wspólnika mają być naliczane składki na Fundusz Gwarantowanych Świadczeń Pracowniczych.</xs:documentation>
      </xs:annotation>
    </xs:attribute>
    <xs:attribute name="Chorobowe" type="xs:boolean" use="optional">
      <xs:annotation>
        <xs:documentation>Określa, czy dla wspólnika mają być naliczane składki chorobowe.</xs:documentation>
      </xs:annotation>
    </xs:attribute>
    <xs:attribute name="Wypadkowe" type="xs:boolean" use="optional">
      <xs:annotation>
        <xs:documentation>Określa, czy dla wspólnika mają być naliczane składki wypadkowe.</xs:documentation>
      </xs:annotation>
    </xs:attribute>
    <xs:attribute name="Zdrowotne" type="xs:boolean" use="optional">
      <xs:annotation>
        <xs:documentation>Określa, czy dla wspólnika mają być naliczane składki zdrowotne.</xs:documentation>
      </xs:annotation>
    </xs:attribute>
  </xs:complexType>

  <xs:element name="Wspolnicy">
    <xs:complexType>
      <xs:sequence>
        <xs:element minOccurs="0" maxOccurs="unbounded" name="Wspolnik">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="Sygnatura" type="xs:string">
                <xs:annotation>
                  <xs:documentation>Symbol wspólnika (unikalny).</xs:documentation>
                </xs:annotation>
              </xs:element>                
              <xs:element name="Imie" type="xs:string" minOccurs="0">
                <xs:annotation>
                  <xs:documentation>Imię.</xs:documentation>
                </xs:annotation>
              </xs:element>
              <xs:element name="Imie2" type="xs:string" minOccurs="0">
                <xs:annotation>
                  <xs:documentation>Drugie imię.</xs:documentation>
                </xs:annotation>
              </xs:element>
              <xs:element name="Nazwisko" type="xs:string">
                <xs:annotation>
                  <xs:documentation>Nazwisko.</xs:documentation>
                </xs:annotation>
              </xs:element>
              <xs:element name="PESEL" type="xs:string" minOccurs="0">
                <xs:annotation>
                  <xs:documentation>PESEL.</xs:documentation>
                </xs:annotation>
              </xs:element>
              <xs:element name="NIP" type="xs:string" minOccurs="0">
                <xs:annotation>
                  <xs:documentation>NIP.</xs:documentation>
                </xs:annotation>
              </xs:element>
              <xs:element name="Udzialy" type="xs:decimal">
                <xs:annotation>
                  <xs:documentation>Wartość z przedziału [0; 1] (1 to 100% udziałów).</xs:documentation>
                </xs:annotation>
              </xs:element>
              <xs:element name="DataUrodzenia" type="xs:date" minOccurs="0">
                <xs:annotation>
                  <xs:documentation>Data urodzenia.</xs:documentation>
                </xs:annotation>
              </xs:element>
              <xs:element name="TypIdentyfikatora" type="wspolne:TypIdentyfikatora">
                <xs:annotation>
                  <xs:documentation>Typ identyfikatora podatkowego.</xs:documentation>
                </xs:annotation>
              </xs:element>
              <xs:element name="PrawoDoEmeryturyRenty" type="xs:string">
                <xs:annotation>
                  <xs:documentation>Kod ZUS prawa do emerytury/renty (0, 1, ...).</xs:documentation>
                </xs:annotation>
              </xs:element>
              <xs:element name="StopienNiepelnosprawnosci" type="xs:string">
                <xs:annotation>
                  <xs:documentation>Kod ZUS stopnia niepełnosprawności (0, 1, ...).</xs:documentation>
                </xs:annotation>
              </xs:element>
              <xs:element name="KodTytuluUbezpieczenia" type="xs:string">
                <xs:annotation>
                  <xs:documentation>Kod ZUS tytułu ubezpieczenia (0110, 0111, ...).</xs:documentation>
                </xs:annotation>
              </xs:element>
              <xs:element name="DaneDeklaracjiZUS" type="TDaneDeklaracjiZUS">
                <xs:annotation>
                  <xs:documentation>Dane deklaracji ZUS.</xs:documentation>
                </xs:annotation>
              </xs:element>
              <xs:element name="DaneUbezpieczeniaZUS" type="TDaneUbezpieczeniaZUS">
                <xs:annotation>
                  <xs:documentation>Dane ubezpieczenia ZUS.</xs:documentation>
                </xs:annotation>
              </xs:element>
              <xs:element name="NazwaUrzeduSkarbowego" type="xs:string" minOccurs="0">
                <xs:annotation>
                  <xs:documentation>Nazwa urzędu skarbowego, w którym rozlicza się wspólnik.</xs:documentation>
                </xs:annotation>
              </xs:element>
              <xs:element name="Kontakty" type="wspolne:Kontakty" minOccurs="0">
                <xs:annotation>
                  <xs:documentation>Kontakty wspólnika.</xs:documentation>
                </xs:annotation>
              </xs:element>
              <xs:element name="Adresy" type="wspolne:Adresy">
                <xs:annotation>
                  <xs:documentation>Adresy wspólnika.</xs:documentation>
                </xs:annotation>
              </xs:element>
              <xs:element minOccurs="0" name="RachunkiBankowe">
                <xs:annotation>
                  <xs:documentation>Lista rachunków bankowych wspólnika.</xs:documentation>
                </xs:annotation>
                <xs:complexType>
                  <xs:sequence>
                    <xs:element minOccurs="0" maxOccurs="unbounded" name="Rachunek" type="rachunki:TRachunekBankowyKlienta">
                      <xs:annotation>
                        <xs:documentation>Rachunek bankowy wspólnika.</xs:documentation>
                      </xs:annotation>
                    </xs:element>
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
              <xs:element minOccurs="0" name="WlasneRozszerzone">
                <xs:annotation>
                  <xs:documentation>Wartości pól własnych wspólnika.</xs:documentation>
                </xs:annotation>
                <xs:complexType>
                  <xs:sequence>
                    <xs:element minOccurs="0" maxOccurs="unbounded" name="PoleRozszerzone">
                      <xs:annotation>
                        <xs:documentation>Pole własne rozszerzone podmiotu. Zawartość tego elementu jest wartością pola.</xs:documentation>
                      </xs:annotation>
                      <xs:complexType>
                        <xs:simpleContent>
                          <xs:extension base="xs:string">
                            <xs:attribute name="Nazwa" type="xs:string" use="required">
                              <xs:annotation>
                                <xs:documentation>Nazwa pola własnego.</xs:documentation>
                              </xs:annotation>
                            </xs:attribute>
                          </xs:extension>
                        </xs:simpleContent>
                      </xs:complexType>
                    </xs:element>
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
              <xs:element minOccurs="0" maxOccurs="1" name="OkresyRozliczenPIT">
                <xs:annotation>
                  <xs:documentation>Okresy rozliczeń PIT</xs:documentation>
                </xs:annotation>
                <xs:complexType>
                  <xs:sequence>
                    <xs:element minOccurs="0" maxOccurs="unbounded" name="OkresRozliczenPIT">
                      <xs:annotation>
                        <xs:documentation>Okres rozliczeń PIT</xs:documentation>
                      </xs:annotation>
                      <xs:complexType>
                        <xs:attribute name="Od" type="xs:int" use="optional">
                          <xs:annotation>
                            <xs:documentation>Rok, od którego parametr jest ważny (lub pusty, jeśli ważny "od zawsze").</xs:documentation>
                          </xs:annotation>
                        </xs:attribute>
                        <xs:attribute name="FormaOpodatkowania" type="TFormaOpodatkowaniaPIT" use="required">
                          <xs:annotation>
                            <xs:documentation>Forma opodatkowania.</xs:documentation>
                          </xs:annotation>
                        </xs:attribute>
                        <xs:attribute name="MetodaOplacaniaZaliczek" type="TMetodaOplacaniaZaliczekPIT" use="required">
                          <xs:annotation>
                            <xs:documentation>Metoda opłacania zaliczek.</xs:documentation>
                          </xs:annotation>
                        </xs:attribute>
                        <xs:attribute name="UwzgledniajRocznaUlgePodatkowa" type="xs:boolean" use="required">
                          <xs:annotation>
                            <xs:documentation>Czy uwzględniać roczną ulgę podatkową.</xs:documentation>
                          </xs:annotation>                          
                        </xs:attribute>
                      </xs:complexType>
                    </xs:element>
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
              <xs:element name="FlagaWlasna" minOccurs="0">
                <xs:annotation>
                  <xs:documentation>Dane flagi własnej.</xs:documentation>
                </xs:annotation>
                <xs:complexType>
                  <xs:all>
                    <xs:element minOccurs="1" maxOccurs="1" name="Kolor" type="xs:string">
                      <xs:annotation>
                        <xs:documentation>Kolor flagi własnej.</xs:documentation>
                      </xs:annotation>
                    </xs:element>
                    <xs:element minOccurs="0" maxOccurs="1" name="Ksztalt" type="xs:string">
                      <xs:annotation>
                        <xs:documentation>Kształt flagi własnej.</xs:documentation>
                      </xs:annotation>
                    </xs:element>
                    <xs:element minOccurs="0" maxOccurs="1" name="Komentarz" type="xs:string">
                      <xs:annotation>
                        <xs:documentation>Komentarz flagi własnej.</xs:documentation>
                      </xs:annotation>
                    </xs:element>
                  </xs:all>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
            <xs:attribute name="Aktywny" type="xs:boolean" use="optional">
              <xs:annotation>
                <xs:documentation>Opcjonalna informacja o aktywności wspólnika (domyślnie importowany jako aktywny).</xs:documentation>
              </xs:annotation>
            </xs:attribute>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  
</xs:schema>