// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: 15.0.0.0
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
namespace DaneArchiwalne
{
    using System.Data;
    using System;
    
    /// <summary>
    /// Class to produce the template output
    /// </summary>
    
    #line 1 "C:\tfs\Moria\Release\25\Src\_Doc\Przyklady\DaneArchiwalne\DaneArchiwalne\PodgladDokumentu.tt"
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "15.0.0.0")]
    public partial class PodgladDokumentu : PodgladDokumentuBase
    {
#line hidden
        /// <summary>
        /// Create the template output
        /// </summary>
        public virtual string TransformText()
        {
            this.Write(@"<!DOCTYPE HTML PUBLIC ""-//W3C//DTD HTML 4.01 Transitional//EN"" ""http://www.w3.org/TR/html4/loose.dtd""> 
<html>
  <head>
    <meta http-equiv=""Content-Type"" content=""text/html; charset=UTF-16"">
    <meta http-equiv=""Content-Language"" content=""pl"">
    <title>Podgląd</title>
    <style>
");
            this.Write("/* Ogolne */\r\n  body { \r\n\tmargin: 5px; font-family: \'Arial CE\', \'Arial\', sans-ser" +
                    "if; \r\n\tbackground-color: window; \r\n\tscrollbar-face-color:window; \r\n\tscrollbar-sh" +
                    "adow-color:window; \r\n\tscrollbar-highlight-color:window; \r\n\tscrollbar-3dlight-col" +
                    "or:threedshadow; \r\n\tscrollbar-darkshadow-color:threedshadow; \r\n\tscrollbar-track-" +
                    "color:threedface; \r\n\toverflow:auto \r\n\t}\r\n  \r\n  #insertgt { border: 0px solid gre" +
                    "en; width: 100%; margin: 0px; padding: 0px; }\r\n  table { border: 0px solid red; " +
                    "margin-bottom: 5px; }\r\n  td, div { font-size: 8pt; vertical-align: top; text-ali" +
                    "gn: left; }\r\n  th { \r\n  \tfont-size: 8pt; \r\n  \tvertical-align: top; \r\n  \ttext-ali" +
                    "gn: left;\r\n  \tbackground-color: threedface;\r\n  }\r\n  tr { background-color: windo" +
                    "w; }\r\n  tr.parzysty { background-color: ThreeDHighlight; }\r\n  .ukryty, #ukryty {" +
                    " display: none; }\r\n  .nowrap, #nowrap { white-space: nowrap; }\r\n\t.bold { font-we" +
                    "ight: bold; }\r\n\t.nobr { white-space: nowrap; padding-right: 5px; }\r\n\r\n/* Podglad" +
                    " dokumentu */    \r\n\r\n  /* Dane wystawienia */\r\n  table.naglowek_daty { border: 0" +
                    "px solid red; margin-bottom: 5px; width: 100%; }\r\n  table.naglowek_daty td.naglo" +
                    "wek { /*width: 75%*/ }\r\n  table.naglowek_daty td.daty { border-bottom: 1px solid" +
                    " threeddarkshadow; /*width: 25%*/ }\r\n  table.naglowek_daty td.daty div { border-" +
                    "top: 1px solid threeddarkshadow; text-align: center; }\r\n  table.naglowek_daty td" +
                    ".daty div.opis { background-color: threedface; }\r\n  \r\n  /* Firmy (Nabywca) */\r\n " +
                    " table.firmy { border: 0px solid threeddarkshadow; width: 100%; }\r\n  table.firmy" +
                    " td.firma { border-top: 1px solid threeddarkshadow; border-bottom: 1px solid thr" +
                    "eeddarkshadow; padding: 0px; }\r\n  table.firmy table.daty td.opis { background-co" +
                    "lor: threedface; border-top: 1px solid threeddarkshadow; border-bottom: 5px soli" +
                    "d window; padding: 0px 2px; }\r\n  table.firmy table.daty td { border-top: 1px sol" +
                    "id threeddarkshadow; border-bottom: 5px solid window; padding: 0px 15px 0px 5px;" +
                    " }\r\n  table.firmy div.opis { background-color: threedface; text-align: center; }" +
                    "\r\n  \r\n  /* Tytul i podtytul */\r\n  h1 { text-align: center; font-weight: normal; " +
                    "font-size: 12pt; margin: 10px; }\r\n  h2 { text-align: center; font-weight: normal" +
                    "; font-size: 10pt; margin: 5px; }\r\n  h3 { text-align: center; font-weight: norma" +
                    "l; font-size: 8pt; margin: 5px; }\r\n\r\n  \r\n  /* Tabela zawartosci */\r\n  table.zawa" +
                    "rtosc { border-left: 1px solid threeddarkshadow; width: 100%; padding: 0px; }\r\n " +
                    " table.zawartosc th { border: 1px solid threeddarkshadow; border-left: 0px solid" +
                    " threeddarkshadow; font-weight: normal; text-align: center; background-color: th" +
                    "reedface; padding: 1px; }\r\n  table.zawartosc td { border-right: 1px solid threed" +
                    "darkshadow; border-bottom: 1px solid threeddarkshadow; font-weight: normal; text" +
                    "-align: right; padding: 1px; }\r\n  table.zawartosc td.center { text-align: center" +
                    "; }\r\n  table.zawartosc td.left { text-align: left; }\r\n  \r\n  /* Tabela VAT */\r\n  " +
                    "div.vat { text-align: right; }\r\n  table.vat { border-left: 1px solid threeddarks" +
                    "hadow; padding: 0px; margin: 10px 0px;  }\r\n  table.vat th { border: 1px solid th" +
                    "reeddarkshadow; border-left: 0px solid threeddarkshadow; font-weight: normal; te" +
                    "xt-align: center; background-color: threedface; padding: 1px; }\r\n  table.vat td " +
                    "{ border-right: 1px solid threeddarkshadow; border-bottom: 1px solid threeddarks" +
                    "hadow; font-weight: normal; text-align: right; padding: 1px 2px; }\r\n  table.vat " +
                    "td.center { text-align: center; }\r\n  table.vat td.left { text-align: left; }\r\n  " +
                    "\r\n  /* Podsumowanie dokumentu */\r\n  table.podsumowanie { border: 0px solid three" +
                    "ddarkshadow; width: 100%; }\r\n  /*table.podsumowanie td { width: 50%; }*/\r\n  tabl" +
                    "e.podsumowanie td.formy_platnosci td { font-weight: normal; padding-right: 10px;" +
                    " }\r\n  table.podsumowanie td.formy_platnosci table#przedplaty { width:100%; borde" +
                    "r-bottom: 1px solid threeddarkshadow; }\r\n  table.podsumowanie td.formy_platnosci" +
                    " table#przedplaty td { padding-right: 0px; }\r\n  table.podsumowanie td.formy_plat" +
                    "nosci td.kwota { font-weight: normal; text-align: right; }\r\n  table.podsumowanie" +
                    " td.do_zaplaty { width: 50%; }\r\n  table.podsumowanie td.do_zaplaty table { width" +
                    ": 100%; border-top: 2px solid threeddarkshadow; border-bottom: 1px solid threedd" +
                    "arkshadow; }\r\n  table.podsumowanie td.do_zaplaty table tr.razem { background-col" +
                    "or: threedface; }\r\n  table.podsumowanie td.do_zaplaty table td.razem { font-size" +
                    ": 11pt; font-weight: bold; }\r\n  table.podsumowanie td.do_zaplaty table td.razem_" +
                    "kwota { font-size: 11pt; font-weight: bold; text-align: right; }\r\n  table.podsum" +
                    "owanie td.do_zaplaty table td span { font-weight: bold; margin-right: 10px; }\r\n " +
                    " \r\n  /* Uwagi */\r\n  table.uwagi { border: 0px solid threeddarkshadow; }\r\n  table" +
                    ".uwagi td.opis { font-weight: bold; }\r\n  \r\n  /* Podpisy */\r\n  table.podpisy { bo" +
                    "rder: 0px solid threeddarkshadow; }\r\n  table.podpisy td.opis { /*font-weight: bo" +
                    "ld;*/ background-color: threedface; border-top: 1px solid threeddarkshadow; bord" +
                    "er-bottom: 5px solid window; padding: 0px 15px 0px 2px; }\r\n  table.podpisy td { " +
                    "border-top: 1px solid threeddarkshadow; border-bottom: 5px solid window; padding" +
                    ": 0px 20px 0px 5px; }\r\n\r\n/* Podglad towaru */\r\n\r\n  /* Symbol i Nazwa */\r\n  table" +
                    ".nazwa { width: 100% }\r\n  table.nazwa td { border-bottom: 1px solid threeddarksh" +
                    "adow; font-size: 12pt; padding-left: 5px; font-weight: bold; }\r\n  table.nazwa td" +
                    ".symbol { background-color: threedface; font-weight: bold; padding-right: 10px; " +
                    "window-space: nowrap; }\r\n\r\n  /* Informacje */\r\n  table.info { width: 100% }\r\n  t" +
                    "able.info td.separator { border-top: 0px solid threeddarkshadow; } \r\n  table.inf" +
                    "o td { border-top: 1px solid threeddarkshadow; border-bottom: 5px solid window; " +
                    "padding-left: 5px;  }\r\n  table.info td.opis { background-color: threedface; font" +
                    "-weight: bold; margin-right: 10px; }\r\n\r\n  /* Ceny */\r\n  table.ceny { width: 100%" +
                    " }\r\n  table.ceny td, th { padding-left: 5px; }\r\n  table.ceny .tytul { font-size:" +
                    " 10pt; padding-left: 0px; padding-right: 5px; window-space: nowrap; font-weight:" +
                    " bold; }\r\n  table.ceny .opis { background-color: threedface; font-weight: bold; " +
                    "padding-left: 5px; border-top: 1px solid threeddarkshadow; border-bottom: 1px so" +
                    "lid threeddarkshadow; }\r\n  table.ceny .nazwa { text-align: left; border-bottom: " +
                    "1px solid threeddarkshadow; }\r\n  table.ceny .kwota { text-align: right; border-b" +
                    "ottom: 1px solid threeddarkshadow; }\r\n  table.ceny .waluta { text-align: center;" +
                    " border-bottom: 1px solid threeddarkshadow; }\r\n\r\n/* Podglad kontrahenta */\r\n\r\n  " +
                    "/* Symbol i Nazwa */\r\n    /* jak dla towaru*/\r\n\r\n  /* Informacje */\r\n    /* jak " +
                    "dla towaru*/\r\n\r\n  /* Adres */\r\n  table.adres { width: 100% }\r\n  table.adres td {" +
                    " padding: 0px; }\r\n  table.adres td.adres { border-top: 1px solid threeddarkshado" +
                    "w; border-bottom: 1px solid threeddarkshadow; }\r\n  table.adres td.adres img { ve" +
                    "rtical-align: middle; margin: 0px 5px 0px 0px; }\r\n  table.adres td.adres span { " +
                    "margin-left: 10px; }\r\n  table.adres td.separator { border-top: 0px solid threedd" +
                    "arkshadow; border-bottom: 0px solid threeddarkshadow; }\r\n  table.adres td div { " +
                    "margin: 0px 5px 2px 5px; }\r\n  table.adres td div.opis { background-color: threed" +
                    "face; margin: 0px; padding-top: 1px; padding-bottom: 1px; text-align: center; fo" +
                    "nt-weight: bold; }\r\n  \r\n  /* Rachunki */\r\n  div.rachunki { font-weight: normal; " +
                    "font-size: 10pt; font-weight: bold; margin: 5px; }\r\n  table.rachunki { width: 10" +
                    "0% }\r\n  table.rachunki th { border-top: 1px solid threeddarkshadow; border-botto" +
                    "m: 1px solid threeddarkshadow; background-color: threedface; padding: 1px 1px 1p" +
                    "x 5px; }\r\n  table.rachunki td { border-bottom: 1px solid threeddarkshadow; paddi" +
                    "ng: 1px 1px 1px 5px; }\r\n\r\n  /* Uwagi */\r\n  table.uwagi { width: 100% }\r\n  table." +
                    "uwagi td { border-top: 1px solid threeddarkshadow; padding: 0px; }\r\n  table.uwag" +
                    "i td div.opis { background-color: threedface; margin: 0px; padding-top: 1px; pad" +
                    "ding-bottom: 1px; text-align: left; padding-left: 5px; font-weight: bold; }\r\n  t" +
                    "able.uwagi td.uwaga { padding-left: 5px; }\r\n\r\n/* Podglad dokumentow kasowych */\r" +
                    "\n\r\n  /* Firma */\r\n  table.firma { width: 100% }\r\n  table.firma td { padding: 0px" +
                    "; }\r\n  table.firma td.adres { border-top: 1px solid threeddarkshadow; border-bot" +
                    "tom: 1px solid threeddarkshadow; }\r\n  table.firma td.adres img { vertical-align:" +
                    " middle; margin: 0px 5px 0px 0px; }\r\n  table.firma td.adres span { margin-left: " +
                    "10px; }\r\n  table.firma td.separator { border-top: 0px solid threeddarkshadow; bo" +
                    "rder-bottom: 0px solid threeddarkshadow; }\r\n  table.firma td.data { border-top: " +
                    "1px solid threeddarkshadow; border-bottom: 0px solid threeddarkshadow; }\r\n  tabl" +
                    "e.firma td.data div.opis { margin: 0px 0px 2px 0px; text-align: left; padding-le" +
                    "ft: 5px; }\r\n  table.firma td.data div.typ { margin: 0px 0px 2px 0px; font-size: " +
                    "16px;  background-color: threedface; margin: 0px; padding-top: 1px; padding-bott" +
                    "om: 1px; text-align: center; font-weight: bold; }\r\n  table.firma td.data div.typ" +
                    "_no { font-size: 16px; font-weight: bold; }\r\n  table.firma td div { margin: 0px " +
                    "5px 2px 5px; }\r\n  table.firma td div.opis { background-color: threedface; margin" +
                    ": 0px; padding-top: 1px; padding-bottom: 1px; text-align: center; font-weight: b" +
                    "old; }\r\n  \r\n  /* Kwota */\r\n  table.kwota { width: 100%; }\r\n  table.kwota td.pust" +
                    "a { background-color: window; border-bottom: 0px solid threeddarkshadow; border-" +
                    "top: 0px solid threeddarkshadow; }\r\n  table.kwota tr.razem { background-color: t" +
                    "hreedface; }\r\n  table.kwota td.razem { font-size: 11pt; font-weight: bold; borde" +
                    "r-top: 2px solid threeddarkshadow; border-bottom: 1px solid threeddarkshadow; pa" +
                    "dding-left: 4px; }\r\n  table.kwota td.razem_kwota { font-size: 11pt; font-weight:" +
                    " bold; text-align: right; border-top: 2px solid threeddarkshadow; border-bottom:" +
                    " 1px solid threeddarkshadow; padding-right: 4px; }\r\n  table.kwota td span { font" +
                    "-weight: bold; margin-right: 10px; }\r\n  \r\n  /* Tytulem */\r\n  table.tytulem { wid" +
                    "th: 100% }\r\n  table.tytulem td { border-top: 1px solid threeddarkshadow; padding" +
                    ": 0px; }\r\n  table.tytulem td div.opis { background-color: threedface; margin: 0p" +
                    "x; padding-top: 1px; padding-bottom: 1px; text-align: left; padding-left: 5px; f" +
                    "ont-weight: bold; }\r\n  table.tytulem td.uwaga { padding-left: 5px; }\r\n  table.ty" +
                    "tulem td.separator { border-top: 0px solid threeddarkshadow; }\r\n  \r\n  /*ogolne*/" +
                    "\r\n  #null, #null *, #null td { color:silver; }\r\n");
            this.Write(@"
    </style>
  </head>
  <body>
    <table id=""insertgt"">
      <tr>
        <td>
          <table class=""firmy"">
            <colgroup>
              <col width=""47%"">
              <col width=""6%"">
              <col width=""47%"">
            </colgroup>
            <tr>
              <td>
                <table cellspacing=""0"" class=""daty"">
                  <tr>
                    <td class=""opis"">Miejsce wystawienia:</td>
                    <td>");
            
            #line 28 "C:\tfs\Moria\Release\25\Src\_Doc\Przyklady\DaneArchiwalne\DaneArchiwalne\PodgladDokumentu.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(_naglowek["MiejsceWystawienia"]));
            
            #line default
            #line hidden
            this.Write("</td>\r\n                  </tr>\r\n<!--                  <tr>\r\n                    <" +
                    "td class=\"opis\">Data magazynowa:</td>\r\n                    <td>");
            
            #line 32 "C:\tfs\Moria\Release\25\Src\_Doc\Przyklady\DaneArchiwalne\DaneArchiwalne\PodgladDokumentu.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Formatuj(_naglowek["DataZakonczeniaDostawy"])));
            
            #line default
            #line hidden
            this.Write("</td>\r\n                  </tr>-->\r\n\t\t\t\t  ");
            
            #line 34 "C:\tfs\Moria\Release\25\Src\_Doc\Przyklady\DaneArchiwalne\DaneArchiwalne\PodgladDokumentu.tt"
 string dataZakonczeniaDostawy = Formatuj(_naglowek["DataZakonczeniaDostawy"]); 
				  if (!string.IsNullOrWhiteSpace(dataZakonczeniaDostawy)) { 
            
            #line default
            #line hidden
            this.Write("                  <tr>\r\n                    <td class=\"opis\">Data zakończenia dos" +
                    "tawy:</td>\r\n                    <td>");
            
            #line 38 "C:\tfs\Moria\Release\25\Src\_Doc\Przyklady\DaneArchiwalne\DaneArchiwalne\PodgladDokumentu.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(dataZakonczeniaDostawy));
            
            #line default
            #line hidden
            this.Write("</td>\r\n                  </tr>\r\n\t\t\t\t  ");
            
            #line 40 "C:\tfs\Moria\Release\25\Src\_Doc\Przyklady\DaneArchiwalne\DaneArchiwalne\PodgladDokumentu.tt"
 } 
            
            #line default
            #line hidden
            this.Write("                  <tr>\r\n                    <td class=\"opis\">");
            
            #line 42 "C:\tfs\Moria\Release\25\Src\_Doc\Przyklady\DaneArchiwalne\DaneArchiwalne\PodgladDokumentu.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(_dataEtykieta));
            
            #line default
            #line hidden
            this.Write(":</td>\r\n                    <td>");
            
            #line 43 "C:\tfs\Moria\Release\25\Src\_Doc\Przyklady\DaneArchiwalne\DaneArchiwalne\PodgladDokumentu.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Formatuj(_naglowek["DataWystawienia"])));
            
            #line default
            #line hidden
            this.Write("</td>\r\n                  </tr>\r\n                </table>\r\n              </td>\r\n  " +
                    "            <td><br></td>\r\n\t\t\t  ");
            
            #line 48 "C:\tfs\Moria\Release\25\Src\_Doc\Przyklady\DaneArchiwalne\DaneArchiwalne\PodgladDokumentu.tt"
 if (_nabywca) { 
            
            #line default
            #line hidden
            this.Write("              <td class=\"firma\">\r\n                <div class=\"opis\">");
            
            #line 50 "C:\tfs\Moria\Release\25\Src\_Doc\Przyklady\DaneArchiwalne\DaneArchiwalne\PodgladDokumentu.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(_firmaEtykieta));
            
            #line default
            #line hidden
            this.Write("</div>\r\n                <div>");
            
            #line 51 "C:\tfs\Moria\Release\25\Src\_Doc\Przyklady\DaneArchiwalne\DaneArchiwalne\PodgladDokumentu.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(_nabywcaNazwa));
            
            #line default
            #line hidden
            this.Write("</div>\r\n                <div>");
            
            #line 52 "C:\tfs\Moria\Release\25\Src\_Doc\Przyklady\DaneArchiwalne\DaneArchiwalne\PodgladDokumentu.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(_naglowek["Nabywca_Adres1"]));
            
            #line default
            #line hidden
            this.Write("</div>\r\n                <div>");
            
            #line 53 "C:\tfs\Moria\Release\25\Src\_Doc\Przyklady\DaneArchiwalne\DaneArchiwalne\PodgladDokumentu.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(_naglowek["Nabywca_Adres2"]));
            
            #line default
            #line hidden
            this.Write("</div>\r\n                <div>NIP: ");
            
            #line 54 "C:\tfs\Moria\Release\25\Src\_Doc\Przyklady\DaneArchiwalne\DaneArchiwalne\PodgladDokumentu.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(_naglowek["Nabywca_NIP"]));
            
            #line default
            #line hidden
            this.Write("</div>\r\n              </td>\r\n\t\t\t  ");
            
            #line 56 "C:\tfs\Moria\Release\25\Src\_Doc\Przyklady\DaneArchiwalne\DaneArchiwalne\PodgladDokumentu.tt"
 } 
            
            #line default
            #line hidden
            this.Write("            </tr>\r\n          </table>\r\n          <h1>");
            
            #line 59 "C:\tfs\Moria\Release\25\Src\_Doc\Przyklady\DaneArchiwalne\DaneArchiwalne\PodgladDokumentu.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(_naglowek["Tytul"]));
            
            #line default
            #line hidden
            this.Write(" ");
            
            #line 59 "C:\tfs\Moria\Release\25\Src\_Doc\Przyklady\DaneArchiwalne\DaneArchiwalne\PodgladDokumentu.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(_naglowek["NumerWewnetrzny_PelnaSygnatura"]));
            
            #line default
            #line hidden
            this.Write("</h1>\r\n\t\t  ");
            
            #line 60 "C:\tfs\Moria\Release\25\Src\_Doc\Przyklady\DaneArchiwalne\DaneArchiwalne\PodgladDokumentu.tt"
 if (_korekta || _zwrot) { 
            
            #line default
            #line hidden
            this.Write("\t\t  <h2>do dokumentu ");
            
            #line 61 "C:\tfs\Moria\Release\25\Src\_Doc\Przyklady\DaneArchiwalne\DaneArchiwalne\PodgladDokumentu.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(_naglowek["NumerKorygowanego"]));
            
            #line default
            #line hidden
            this.Write(" z dnia ");
            
            #line 61 "C:\tfs\Moria\Release\25\Src\_Doc\Przyklady\DaneArchiwalne\DaneArchiwalne\PodgladDokumentu.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Formatuj(_naglowek["DataKorygowanego"])));
            
            #line default
            #line hidden
            this.Write("</h2>\r\n\t\t  ");
            
            #line 62 "C:\tfs\Moria\Release\25\Src\_Doc\Przyklady\DaneArchiwalne\DaneArchiwalne\PodgladDokumentu.tt"
 } else if (_zakupowy && !(_naglowek["NumerZewnetrzny"] is System.DBNull) && !string.IsNullOrEmpty((string)_naglowek["NumerZewnetrzny"])) { 
            
            #line default
            #line hidden
            this.Write("\t\t  <h3>Numer dokumentu dostawcy: ");
            
            #line 63 "C:\tfs\Moria\Release\25\Src\_Doc\Przyklady\DaneArchiwalne\DaneArchiwalne\PodgladDokumentu.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(_naglowek["NumerZewnetrzny"]));
            
            #line default
            #line hidden
            this.Write("\r\n\t\t  ");
            
            #line 64 "C:\tfs\Moria\Release\25\Src\_Doc\Przyklady\DaneArchiwalne\DaneArchiwalne\PodgladDokumentu.tt"
 if (_naglowek.Table.Columns.Contains("DataOryginalu") && !(_naglowek["DataOryginalu"] is System.DBNull)) { 
            
            #line default
            #line hidden
            this.Write("\t\t  z dnia ");
            
            #line 65 "C:\tfs\Moria\Release\25\Src\_Doc\Przyklady\DaneArchiwalne\DaneArchiwalne\PodgladDokumentu.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Formatuj(_naglowek["DataOryginalu"])));
            
            #line default
            #line hidden
            
            #line 65 "C:\tfs\Moria\Release\25\Src\_Doc\Przyklady\DaneArchiwalne\DaneArchiwalne\PodgladDokumentu.tt"
 } 
            
            #line default
            #line hidden
            this.Write("\t\t  </h3>\r\n\t\t  ");
            
            #line 67 "C:\tfs\Moria\Release\25\Src\_Doc\Przyklady\DaneArchiwalne\DaneArchiwalne\PodgladDokumentu.tt"
 } else { 
            
            #line default
            #line hidden
            this.Write("          <h2>");
            
            #line 68 "C:\tfs\Moria\Release\25\Src\_Doc\Przyklady\DaneArchiwalne\DaneArchiwalne\PodgladDokumentu.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(_naglowek["Podtytul"]));
            
            #line default
            #line hidden
            this.Write("</h2>\r\n\t\t  ");
            
            #line 69 "C:\tfs\Moria\Release\25\Src\_Doc\Przyklady\DaneArchiwalne\DaneArchiwalne\PodgladDokumentu.tt"
 } 
            
            #line default
            #line hidden
            this.Write("\t\t  ");
            
            #line 70 "C:\tfs\Moria\Release\25\Src\_Doc\Przyklady\DaneArchiwalne\DaneArchiwalne\PodgladDokumentu.tt"
 if (_naglowek.Table.Columns.Contains("PowstalZHandlowego") && (bool)_naglowek["PowstalZHandlowego"]) { 
            
            #line default
            #line hidden
            this.Write("\t\t  <h2>do dokumentu ");
            
            #line 71 "C:\tfs\Moria\Release\25\Src\_Doc\Przyklady\DaneArchiwalne\DaneArchiwalne\PodgladDokumentu.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Formatuj(_naglowek["NumerPowiazanego"])));
            
            #line default
            #line hidden
            this.Write(" z dnia ");
            
            #line 71 "C:\tfs\Moria\Release\25\Src\_Doc\Przyklady\DaneArchiwalne\DaneArchiwalne\PodgladDokumentu.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Formatuj(_naglowek["DataWystawieniaPowiazanego"])));
            
            #line default
            #line hidden
            this.Write("</h2>\r\n\t\t  ");
            
            #line 72 "C:\tfs\Moria\Release\25\Src\_Doc\Przyklady\DaneArchiwalne\DaneArchiwalne\PodgladDokumentu.tt"
 } 
            
            #line default
            #line hidden
            this.Write(@"          <table class=""zawartosc"" cellspacing=""0px"">
            <tr>
              <th>Lp</th>
              <th>Nazwa</th>
              <th>PKWiU</th>
              <th>Ilość</th>
              <th>j.m.</th>
              <th>Rabat [%]</th>
              <th>Cena netto</th>
              <th>VAT [%]</th>
              <th>Wartość netto</th>
              <th>VAT</th>
              <th>Wartość brutto</th>
			  ");
            
            #line 86 "C:\tfs\Moria\Release\25\Src\_Doc\Przyklady\DaneArchiwalne\DaneArchiwalne\PodgladDokumentu.tt"
 if (_korekta) { 
            
            #line default
            #line hidden
            this.Write("\t\t\t  <th>Przyczyna korekty</th>\r\n\t\t\t  ");
            
            #line 88 "C:\tfs\Moria\Release\25\Src\_Doc\Przyklady\DaneArchiwalne\DaneArchiwalne\PodgladDokumentu.tt"
 } 
            
            #line default
            #line hidden
            this.Write("            </tr>\r\n\t\t\t");
            
            #line 90 "C:\tfs\Moria\Release\25\Src\_Doc\Przyklady\DaneArchiwalne\DaneArchiwalne\PodgladDokumentu.tt"
 int i = 1; foreach (DataRow poz in _pozycje) { 
            
            #line default
            #line hidden
            this.Write("            <tr ");
            
            #line 91 "C:\tfs\Moria\Release\25\Src\_Doc\Przyklady\DaneArchiwalne\DaneArchiwalne\PodgladDokumentu.tt"
 if (i++%2 == 0) { 
            
            #line default
            #line hidden
            this.Write("class=\"parzysty\"");
            
            #line 91 "C:\tfs\Moria\Release\25\Src\_Doc\Przyklady\DaneArchiwalne\DaneArchiwalne\PodgladDokumentu.tt"
 } 
            
            #line default
            #line hidden
            this.Write(">\r\n              ");
            
            #line 92 "C:\tfs\Moria\Release\25\Src\_Doc\Przyklady\DaneArchiwalne\DaneArchiwalne\PodgladDokumentu.tt"
 if (_korekta) { 
            
            #line default
            #line hidden
            this.Write("              <td class=\"center\">");
            
            #line 93 "C:\tfs\Moria\Release\25\Src\_Doc\Przyklady\DaneArchiwalne\DaneArchiwalne\PodgladDokumentu.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(poz["LP"]));
            
            #line default
            #line hidden
            this.Write(".</td>\r\n              <td class=\"left\">");
            
            #line 94 "C:\tfs\Moria\Release\25\Src\_Doc\Przyklady\DaneArchiwalne\DaneArchiwalne\PodgladDokumentu.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(poz["Nazwa"]));
            
            #line default
            #line hidden
            this.Write("<br>Korekta:<br>Po korekcie:</td>\r\n              <td>");
            
            #line 95 "C:\tfs\Moria\Release\25\Src\_Doc\Przyklady\DaneArchiwalne\DaneArchiwalne\PodgladDokumentu.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(poz["PKWiU"]));
            
            #line default
            #line hidden
            this.Write("&nbsp;</td>\r\n              <td><span style=\"white-space: nowrap\">\r\n\t\t\t  ");
            
            #line 97 "C:\tfs\Moria\Release\25\Src\_Doc\Przyklady\DaneArchiwalne\DaneArchiwalne\PodgladDokumentu.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Formatuj(poz["IloscPrzedKorekta"], poz["PrecyzjaPrzedKorekta"])));
            
            #line default
            #line hidden
            this.Write("<br>");
            
            #line 97 "C:\tfs\Moria\Release\25\Src\_Doc\Przyklady\DaneArchiwalne\DaneArchiwalne\PodgladDokumentu.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Formatuj(poz["IloscKorekta"], poz["PrecyzjaKorekta"])));
            
            #line default
            #line hidden
            this.Write("<br>");
            
            #line 97 "C:\tfs\Moria\Release\25\Src\_Doc\Przyklady\DaneArchiwalne\DaneArchiwalne\PodgladDokumentu.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Formatuj(poz["IloscPoKorekcie"], poz["PrecyzjaPoKorekcie"])));
            
            #line default
            #line hidden
            this.Write("\r\n              </span></td>\r\n              <td class=\"center\">");
            
            #line 99 "C:\tfs\Moria\Release\25\Src\_Doc\Przyklady\DaneArchiwalne\DaneArchiwalne\PodgladDokumentu.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Formatuj(poz["JmPrzedKorekta"])));
            
            #line default
            #line hidden
            this.Write("<br>");
            
            #line 99 "C:\tfs\Moria\Release\25\Src\_Doc\Przyklady\DaneArchiwalne\DaneArchiwalne\PodgladDokumentu.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Formatuj(poz["JmKorekta"])));
            
            #line default
            #line hidden
            this.Write("<br>");
            
            #line 99 "C:\tfs\Moria\Release\25\Src\_Doc\Przyklady\DaneArchiwalne\DaneArchiwalne\PodgladDokumentu.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Formatuj(poz["JmPoKorekcie"])));
            
            #line default
            #line hidden
            this.Write("</td>\r\n              <td>");
            
            #line 100 "C:\tfs\Moria\Release\25\Src\_Doc\Przyklady\DaneArchiwalne\DaneArchiwalne\PodgladDokumentu.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(FormatujRabat(poz["RabatProcentPrzedKorekta"])));
            
            #line default
            #line hidden
            this.Write("<br>&nbsp;<br>");
            
            #line 100 "C:\tfs\Moria\Release\25\Src\_Doc\Przyklady\DaneArchiwalne\DaneArchiwalne\PodgladDokumentu.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(FormatujRabat(poz["RabatProcentPoKorekcie"])));
            
            #line default
            #line hidden
            this.Write("</td>\r\n              <td><span style=\"white-space: nowrap\">");
            
            #line 101 "C:\tfs\Moria\Release\25\Src\_Doc\Przyklady\DaneArchiwalne\DaneArchiwalne\PodgladDokumentu.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Formatuj(poz["CenaPrzedKorekta"])));
            
            #line default
            #line hidden
            this.Write("<br>");
            
            #line 101 "C:\tfs\Moria\Release\25\Src\_Doc\Przyklady\DaneArchiwalne\DaneArchiwalne\PodgladDokumentu.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Formatuj(poz["CenaKorekta"])));
            
            #line default
            #line hidden
            this.Write("<br>");
            
            #line 101 "C:\tfs\Moria\Release\25\Src\_Doc\Przyklady\DaneArchiwalne\DaneArchiwalne\PodgladDokumentu.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Formatuj(poz["CenaPoKorekcie"])));
            
            #line default
            #line hidden
            this.Write("</span></td>\r\n              <td class=\"center\">");
            
            #line 102 "C:\tfs\Moria\Release\25\Src\_Doc\Przyklady\DaneArchiwalne\DaneArchiwalne\PodgladDokumentu.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Formatuj(poz["VatPrzedKorekta"])));
            
            #line default
            #line hidden
            this.Write("<br>&nbsp;<br>");
            
            #line 102 "C:\tfs\Moria\Release\25\Src\_Doc\Przyklady\DaneArchiwalne\DaneArchiwalne\PodgladDokumentu.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Formatuj(poz["VatPoKorekcie"])));
            
            #line default
            #line hidden
            this.Write("</td>\r\n              <td><span style=\"white-space: nowrap\">");
            
            #line 103 "C:\tfs\Moria\Release\25\Src\_Doc\Przyklady\DaneArchiwalne\DaneArchiwalne\PodgladDokumentu.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Formatuj(poz["WartoscNettoPrzedKorekta"])));
            
            #line default
            #line hidden
            this.Write("<br>");
            
            #line 103 "C:\tfs\Moria\Release\25\Src\_Doc\Przyklady\DaneArchiwalne\DaneArchiwalne\PodgladDokumentu.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Formatuj(poz["WartoscNettoKorekta"])));
            
            #line default
            #line hidden
            this.Write("<br>");
            
            #line 103 "C:\tfs\Moria\Release\25\Src\_Doc\Przyklady\DaneArchiwalne\DaneArchiwalne\PodgladDokumentu.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Formatuj(poz["WartoscNettoPoKorekcie"])));
            
            #line default
            #line hidden
            this.Write("</span></td>\r\n              <td><span style=\"white-space: nowrap\">");
            
            #line 104 "C:\tfs\Moria\Release\25\Src\_Doc\Przyklady\DaneArchiwalne\DaneArchiwalne\PodgladDokumentu.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Formatuj(poz["WartoscVatPrzedKorekta"])));
            
            #line default
            #line hidden
            this.Write("<br>");
            
            #line 104 "C:\tfs\Moria\Release\25\Src\_Doc\Przyklady\DaneArchiwalne\DaneArchiwalne\PodgladDokumentu.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Formatuj(poz["WartoscVatKorekta"])));
            
            #line default
            #line hidden
            this.Write("<br>");
            
            #line 104 "C:\tfs\Moria\Release\25\Src\_Doc\Przyklady\DaneArchiwalne\DaneArchiwalne\PodgladDokumentu.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Formatuj(poz["WartoscVatPoKorekcie"])));
            
            #line default
            #line hidden
            this.Write("</span></td>\r\n              <td><span style=\"white-space: nowrap\">");
            
            #line 105 "C:\tfs\Moria\Release\25\Src\_Doc\Przyklady\DaneArchiwalne\DaneArchiwalne\PodgladDokumentu.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Formatuj(poz["WartoscBruttoPrzedKorekta"])));
            
            #line default
            #line hidden
            this.Write("<br>");
            
            #line 105 "C:\tfs\Moria\Release\25\Src\_Doc\Przyklady\DaneArchiwalne\DaneArchiwalne\PodgladDokumentu.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Formatuj(poz["WartoscBruttoKorekta"])));
            
            #line default
            #line hidden
            this.Write("<br>");
            
            #line 105 "C:\tfs\Moria\Release\25\Src\_Doc\Przyklady\DaneArchiwalne\DaneArchiwalne\PodgladDokumentu.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Formatuj(poz["WartoscBruttoPoKorekcie"])));
            
            #line default
            #line hidden
            this.Write("</span></td>\r\n\t\t\t  ");
            
            #line 106 "C:\tfs\Moria\Release\25\Src\_Doc\Przyklady\DaneArchiwalne\DaneArchiwalne\PodgladDokumentu.tt"
 string przyczyna = Formatuj(poz["PrzyczynaKorekty"]);
			  if (string.IsNullOrWhiteSpace(przyczyna)) { 
            
            #line default
            #line hidden
            this.Write("\t\t\t  <td class=\"center\" style=\"vertical-align: middle\">-</td>\r\n\t\t\t  ");
            
            #line 109 "C:\tfs\Moria\Release\25\Src\_Doc\Przyklady\DaneArchiwalne\DaneArchiwalne\PodgladDokumentu.tt"
 } else { 
            
            #line default
            #line hidden
            this.Write("\t\t\t  <td class=\"left\">");
            
            #line 110 "C:\tfs\Moria\Release\25\Src\_Doc\Przyklady\DaneArchiwalne\DaneArchiwalne\PodgladDokumentu.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(przyczyna));
            
            #line default
            #line hidden
            this.Write("</td>\r\n\t\t\t  ");
            
            #line 111 "C:\tfs\Moria\Release\25\Src\_Doc\Przyklady\DaneArchiwalne\DaneArchiwalne\PodgladDokumentu.tt"
 } //if isnullorempty 
            
            #line default
            #line hidden
            this.Write("              ");
            
            #line 112 "C:\tfs\Moria\Release\25\Src\_Doc\Przyklady\DaneArchiwalne\DaneArchiwalne\PodgladDokumentu.tt"
 } else { 
            
            #line default
            #line hidden
            this.Write("              <td class=\"center\">");
            
            #line 113 "C:\tfs\Moria\Release\25\Src\_Doc\Przyklady\DaneArchiwalne\DaneArchiwalne\PodgladDokumentu.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(poz["LP"]));
            
            #line default
            #line hidden
            this.Write(".</td>\r\n              <td class=\"left\">");
            
            #line 114 "C:\tfs\Moria\Release\25\Src\_Doc\Przyklady\DaneArchiwalne\DaneArchiwalne\PodgladDokumentu.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(poz["Nazwa"]));
            
            #line default
            #line hidden
            this.Write("</td>\r\n              <td>");
            
            #line 115 "C:\tfs\Moria\Release\25\Src\_Doc\Przyklady\DaneArchiwalne\DaneArchiwalne\PodgladDokumentu.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(poz["PKWiU"]));
            
            #line default
            #line hidden
            this.Write("&nbsp;</td>\r\n              <td><span style=\"white-space: nowrap\">");
            
            #line 116 "C:\tfs\Moria\Release\25\Src\_Doc\Przyklady\DaneArchiwalne\DaneArchiwalne\PodgladDokumentu.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Formatuj(poz["Ilosc"], poz["Precyzja"])));
            
            #line default
            #line hidden
            this.Write("</span></td>\r\n              <td class=\"center\">");
            
            #line 117 "C:\tfs\Moria\Release\25\Src\_Doc\Przyklady\DaneArchiwalne\DaneArchiwalne\PodgladDokumentu.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(poz["Jm"]));
            
            #line default
            #line hidden
            this.Write("</td>\r\n              <td>");
            
            #line 118 "C:\tfs\Moria\Release\25\Src\_Doc\Przyklady\DaneArchiwalne\DaneArchiwalne\PodgladDokumentu.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(FormatujRabat(poz["RabatProcent"])));
            
            #line default
            #line hidden
            this.Write("</td>\r\n              <td><span style=\"white-space: nowrap\">");
            
            #line 119 "C:\tfs\Moria\Release\25\Src\_Doc\Przyklady\DaneArchiwalne\DaneArchiwalne\PodgladDokumentu.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Formatuj(poz["Cena"])));
            
            #line default
            #line hidden
            this.Write("</span></td>\r\n              <td class=\"center\">");
            
            #line 120 "C:\tfs\Moria\Release\25\Src\_Doc\Przyklady\DaneArchiwalne\DaneArchiwalne\PodgladDokumentu.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(poz["Vat"]));
            
            #line default
            #line hidden
            this.Write("</td>\r\n              <td><span style=\"white-space: nowrap\">");
            
            #line 121 "C:\tfs\Moria\Release\25\Src\_Doc\Przyklady\DaneArchiwalne\DaneArchiwalne\PodgladDokumentu.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Formatuj(poz["WartoscNetto"])));
            
            #line default
            #line hidden
            this.Write("</span></td>\r\n              <td><span style=\"white-space: nowrap\">");
            
            #line 122 "C:\tfs\Moria\Release\25\Src\_Doc\Przyklady\DaneArchiwalne\DaneArchiwalne\PodgladDokumentu.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Formatuj(poz["WartoscVat"])));
            
            #line default
            #line hidden
            this.Write("</span></td>\r\n              <td><span style=\"white-space: nowrap\">");
            
            #line 123 "C:\tfs\Moria\Release\25\Src\_Doc\Przyklady\DaneArchiwalne\DaneArchiwalne\PodgladDokumentu.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Formatuj(poz["WartoscBrutto"])));
            
            #line default
            #line hidden
            this.Write("</span></td>\r\n\t\t\t  ");
            
            #line 124 "C:\tfs\Moria\Release\25\Src\_Doc\Przyklady\DaneArchiwalne\DaneArchiwalne\PodgladDokumentu.tt"
 } 
            
            #line default
            #line hidden
            this.Write("            </tr>\r\n\t\t\t");
            
            #line 126 "C:\tfs\Moria\Release\25\Src\_Doc\Przyklady\DaneArchiwalne\DaneArchiwalne\PodgladDokumentu.tt"
 } 
            
            #line default
            #line hidden
            this.Write(@"          </table>
          <div class=""vat"">
            <table class=""vat"" cellspacing=""0px"">
              <tr>
                <th>Według stawki VAT</th>
                <th>Wartość netto</th>
                <th>Kwota VAT</th>
                <th>Wartość brutto</th>
              </tr>
              ");
            
            #line 136 "C:\tfs\Moria\Release\25\Src\_Doc\Przyklady\DaneArchiwalne\DaneArchiwalne\PodgladDokumentu.tt"
 i = 1; foreach (DataRow poz in _pozycjeVat) { 
            
            #line default
            #line hidden
            this.Write("              <tr ");
            
            #line 137 "C:\tfs\Moria\Release\25\Src\_Doc\Przyklady\DaneArchiwalne\DaneArchiwalne\PodgladDokumentu.tt"
 if (i++%2 == 0) { 
            
            #line default
            #line hidden
            this.Write("class=\"parzysty\"");
            
            #line 137 "C:\tfs\Moria\Release\25\Src\_Doc\Przyklady\DaneArchiwalne\DaneArchiwalne\PodgladDokumentu.tt"
 } 
            
            #line default
            #line hidden
            this.Write(">\r\n                ");
            
            #line 138 "C:\tfs\Moria\Release\25\Src\_Doc\Przyklady\DaneArchiwalne\DaneArchiwalne\PodgladDokumentu.tt"
 if (_korekta) { 
            
            #line default
            #line hidden
            this.Write("                <td class=\"left\">");
            
            #line 139 "C:\tfs\Moria\Release\25\Src\_Doc\Przyklady\DaneArchiwalne\DaneArchiwalne\PodgladDokumentu.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(poz["Nazwa"]));
            
            #line default
            #line hidden
            this.Write("<br>Korekta:<br>Po korekcie:</td>\r\n                <td><span style=\"white-space: " +
                    "nowrap\">");
            
            #line 140 "C:\tfs\Moria\Release\25\Src\_Doc\Przyklady\DaneArchiwalne\DaneArchiwalne\PodgladDokumentu.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Formatuj(poz["NettoPrzedKorekta"])));
            
            #line default
            #line hidden
            this.Write("<br>");
            
            #line 140 "C:\tfs\Moria\Release\25\Src\_Doc\Przyklady\DaneArchiwalne\DaneArchiwalne\PodgladDokumentu.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Formatuj(poz["NettoKorekta"])));
            
            #line default
            #line hidden
            this.Write("<br>");
            
            #line 140 "C:\tfs\Moria\Release\25\Src\_Doc\Przyklady\DaneArchiwalne\DaneArchiwalne\PodgladDokumentu.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Formatuj(poz["NettoPoKorekcie"])));
            
            #line default
            #line hidden
            this.Write("</span></td>\r\n                <td><span style=\"white-space: nowrap\">");
            
            #line 141 "C:\tfs\Moria\Release\25\Src\_Doc\Przyklady\DaneArchiwalne\DaneArchiwalne\PodgladDokumentu.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Formatuj(poz["VatPrzedKorekta"])));
            
            #line default
            #line hidden
            this.Write("<br>");
            
            #line 141 "C:\tfs\Moria\Release\25\Src\_Doc\Przyklady\DaneArchiwalne\DaneArchiwalne\PodgladDokumentu.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Formatuj(poz["VatKorekta"])));
            
            #line default
            #line hidden
            this.Write("<br>");
            
            #line 141 "C:\tfs\Moria\Release\25\Src\_Doc\Przyklady\DaneArchiwalne\DaneArchiwalne\PodgladDokumentu.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Formatuj(poz["VatPoKorekcie"])));
            
            #line default
            #line hidden
            this.Write("</span></td>\r\n                <td><span style=\"white-space: nowrap\">");
            
            #line 142 "C:\tfs\Moria\Release\25\Src\_Doc\Przyklady\DaneArchiwalne\DaneArchiwalne\PodgladDokumentu.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Formatuj(poz["BruttoPrzedKorekta"])));
            
            #line default
            #line hidden
            this.Write("<br>");
            
            #line 142 "C:\tfs\Moria\Release\25\Src\_Doc\Przyklady\DaneArchiwalne\DaneArchiwalne\PodgladDokumentu.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Formatuj(poz["BruttoKorekta"])));
            
            #line default
            #line hidden
            this.Write("<br>");
            
            #line 142 "C:\tfs\Moria\Release\25\Src\_Doc\Przyklady\DaneArchiwalne\DaneArchiwalne\PodgladDokumentu.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Formatuj(poz["BruttoPoKorekcie"])));
            
            #line default
            #line hidden
            this.Write("</span></td>\r\n                ");
            
            #line 143 "C:\tfs\Moria\Release\25\Src\_Doc\Przyklady\DaneArchiwalne\DaneArchiwalne\PodgladDokumentu.tt"
 } else { 
            
            #line default
            #line hidden
            this.Write("                <td class=\"left\">");
            
            #line 144 "C:\tfs\Moria\Release\25\Src\_Doc\Przyklady\DaneArchiwalne\DaneArchiwalne\PodgladDokumentu.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(poz["Nazwa"]));
            
            #line default
            #line hidden
            this.Write("</td>\r\n                <td><span style=\"white-space: nowrap\">");
            
            #line 145 "C:\tfs\Moria\Release\25\Src\_Doc\Przyklady\DaneArchiwalne\DaneArchiwalne\PodgladDokumentu.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Formatuj(poz["WartoscNetto"])));
            
            #line default
            #line hidden
            this.Write("</span></td>\r\n                <td><span style=\"white-space: nowrap\">");
            
            #line 146 "C:\tfs\Moria\Release\25\Src\_Doc\Przyklady\DaneArchiwalne\DaneArchiwalne\PodgladDokumentu.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Formatuj(poz["WartoscVat"])));
            
            #line default
            #line hidden
            this.Write("</span></td>\r\n                <td><span style=\"white-space: nowrap\">");
            
            #line 147 "C:\tfs\Moria\Release\25\Src\_Doc\Przyklady\DaneArchiwalne\DaneArchiwalne\PodgladDokumentu.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Formatuj(poz["WartoscBrutto"])));
            
            #line default
            #line hidden
            this.Write("</span></td>\r\n                ");
            
            #line 148 "C:\tfs\Moria\Release\25\Src\_Doc\Przyklady\DaneArchiwalne\DaneArchiwalne\PodgladDokumentu.tt"
 } 
            
            #line default
            #line hidden
            this.Write("              </tr>\r\n\t\t\t  ");
            
            #line 150 "C:\tfs\Moria\Release\25\Src\_Doc\Przyklady\DaneArchiwalne\DaneArchiwalne\PodgladDokumentu.tt"
 } //for each 
            
            #line default
            #line hidden
            this.Write("              <tr>\r\n\t\t\t  ");
            
            #line 152 "C:\tfs\Moria\Release\25\Src\_Doc\Przyklady\DaneArchiwalne\DaneArchiwalne\PodgladDokumentu.tt"
 if (_korekta) { 
            
            #line default
            #line hidden
            this.Write("                <td>Razem przed korektą:<br>Razem korekta:<br>Razem po korekcie:<" +
                    "/td>\r\n                <td><span style=\"white-space: nowrap\">");
            
            #line 154 "C:\tfs\Moria\Release\25\Src\_Doc\Przyklady\DaneArchiwalne\DaneArchiwalne\PodgladDokumentu.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Formatuj(_naglowek["NettoPrzedKorekta"])));
            
            #line default
            #line hidden
            this.Write("<br>");
            
            #line 154 "C:\tfs\Moria\Release\25\Src\_Doc\Przyklady\DaneArchiwalne\DaneArchiwalne\PodgladDokumentu.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Formatuj(_naglowek["Wartosc_NettoPoRabacie"])));
            
            #line default
            #line hidden
            this.Write("<br>");
            
            #line 154 "C:\tfs\Moria\Release\25\Src\_Doc\Przyklady\DaneArchiwalne\DaneArchiwalne\PodgladDokumentu.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Formatuj(_naglowek["NettoPoKorekcie"])));
            
            #line default
            #line hidden
            this.Write("</span></td>\r\n                <td><span style=\"white-space: nowrap\">");
            
            #line 155 "C:\tfs\Moria\Release\25\Src\_Doc\Przyklady\DaneArchiwalne\DaneArchiwalne\PodgladDokumentu.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Formatuj(_naglowek["VatPrzedKorekta"])));
            
            #line default
            #line hidden
            this.Write("<br>");
            
            #line 155 "C:\tfs\Moria\Release\25\Src\_Doc\Przyklady\DaneArchiwalne\DaneArchiwalne\PodgladDokumentu.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Formatuj(_naglowek["Wartosc_VatPoRabacie"])));
            
            #line default
            #line hidden
            this.Write("<br>");
            
            #line 155 "C:\tfs\Moria\Release\25\Src\_Doc\Przyklady\DaneArchiwalne\DaneArchiwalne\PodgladDokumentu.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Formatuj(_naglowek["VatPoKorekcie"])));
            
            #line default
            #line hidden
            this.Write("</span></td>\r\n                <td><span style=\"white-space: nowrap\">");
            
            #line 156 "C:\tfs\Moria\Release\25\Src\_Doc\Przyklady\DaneArchiwalne\DaneArchiwalne\PodgladDokumentu.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Formatuj(_naglowek["BruttoPrzedKorekta"])));
            
            #line default
            #line hidden
            this.Write("<br>");
            
            #line 156 "C:\tfs\Moria\Release\25\Src\_Doc\Przyklady\DaneArchiwalne\DaneArchiwalne\PodgladDokumentu.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Formatuj(_naglowek["Wartosc_BruttoPoRabacie"])));
            
            #line default
            #line hidden
            this.Write("<br>");
            
            #line 156 "C:\tfs\Moria\Release\25\Src\_Doc\Przyklady\DaneArchiwalne\DaneArchiwalne\PodgladDokumentu.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Formatuj(_naglowek["BruttoPoKorekcie"])));
            
            #line default
            #line hidden
            this.Write("</span></td>\r\n\t\t\t  ");
            
            #line 157 "C:\tfs\Moria\Release\25\Src\_Doc\Przyklady\DaneArchiwalne\DaneArchiwalne\PodgladDokumentu.tt"
 } else { 
            
            #line default
            #line hidden
            this.Write("                <td>Razem:</td>\r\n                <td><span style=\"white-space: no" +
                    "wrap\">");
            
            #line 159 "C:\tfs\Moria\Release\25\Src\_Doc\Przyklady\DaneArchiwalne\DaneArchiwalne\PodgladDokumentu.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Formatuj(_naglowek["Wartosc_NettoPoRabacie"])));
            
            #line default
            #line hidden
            this.Write("</span></td>\r\n                <td><span style=\"white-space: nowrap\">");
            
            #line 160 "C:\tfs\Moria\Release\25\Src\_Doc\Przyklady\DaneArchiwalne\DaneArchiwalne\PodgladDokumentu.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Formatuj(_naglowek["Wartosc_VatPoRabacie"])));
            
            #line default
            #line hidden
            this.Write("</span></td>\r\n                <td><span style=\"white-space: nowrap\">");
            
            #line 161 "C:\tfs\Moria\Release\25\Src\_Doc\Przyklady\DaneArchiwalne\DaneArchiwalne\PodgladDokumentu.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Formatuj(_naglowek["Wartosc_BruttoPoRabacie"])));
            
            #line default
            #line hidden
            this.Write("</span></td>\r\n\t\t\t  ");
            
            #line 162 "C:\tfs\Moria\Release\25\Src\_Doc\Przyklady\DaneArchiwalne\DaneArchiwalne\PodgladDokumentu.tt"
 } 
            
            #line default
            #line hidden
            this.Write("              </tr>\r\n            </table>\r\n          </div>\r\n          <table cla" +
                    "ss=\"podsumowanie\">\r\n            <tr>\r\n              <td class=\"formy_platnosci\">" +
                    "\r\n                <table>\r\n                  ");
            
            #line 170 "C:\tfs\Moria\Release\25\Src\_Doc\Przyklady\DaneArchiwalne\DaneArchiwalne\PodgladDokumentu.tt"
 i = 1; if (_platnosciZaplacono.Count > 0) { 
            
            #line default
            #line hidden
            this.Write("                  <tr>\r\n\t\t\t\t    <td colspan=\"2\">Zapłacono</td>\r\n                 " +
                    " </tr>\r\n                  ");
            
            #line 174 "C:\tfs\Moria\Release\25\Src\_Doc\Przyklady\DaneArchiwalne\DaneArchiwalne\PodgladDokumentu.tt"
 foreach (DataRow poz in _platnosciZaplacono) { 
            
            #line default
            #line hidden
            this.Write("                  <tr ");
            
            #line 175 "C:\tfs\Moria\Release\25\Src\_Doc\Przyklady\DaneArchiwalne\DaneArchiwalne\PodgladDokumentu.tt"
 if (i++%2 == 0) { 
            
            #line default
            #line hidden
            this.Write("class=\"parzysty\"");
            
            #line 175 "C:\tfs\Moria\Release\25\Src\_Doc\Przyklady\DaneArchiwalne\DaneArchiwalne\PodgladDokumentu.tt"
 } 
            
            #line default
            #line hidden
            this.Write(">\r\n                    <td class=\"left\">");
            
            #line 176 "C:\tfs\Moria\Release\25\Src\_Doc\Przyklady\DaneArchiwalne\DaneArchiwalne\PodgladDokumentu.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(poz["Nazwa"]));
            
            #line default
            #line hidden
            this.Write(":</td>\r\n                    <td class=\"kwota\"><span style=\"white-space: nowrap\">");
            
            #line 177 "C:\tfs\Moria\Release\25\Src\_Doc\Przyklady\DaneArchiwalne\DaneArchiwalne\PodgladDokumentu.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Formatuj(poz["KwotaPlatnosci"])));
            
            #line default
            #line hidden
            this.Write(" ");
            
            #line 177 "C:\tfs\Moria\Release\25\Src\_Doc\Przyklady\DaneArchiwalne\DaneArchiwalne\PodgladDokumentu.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Formatuj(_naglowek["Waluta"])));
            
            #line default
            #line hidden
            this.Write("</span></td>\r\n                  </tr>\r\n\t\t\t\t  ");
            
            #line 179 "C:\tfs\Moria\Release\25\Src\_Doc\Przyklady\DaneArchiwalne\DaneArchiwalne\PodgladDokumentu.tt"
 } } 
				  if (_platnosciPozostalo.Count > 0) { 
            
            #line default
            #line hidden
            this.Write("                  <tr>\r\n\t\t\t\t    <td colspan=\"2\">Pozostało</td>\r\n                 " +
                    " </tr>\r\n                  ");
            
            #line 184 "C:\tfs\Moria\Release\25\Src\_Doc\Przyklady\DaneArchiwalne\DaneArchiwalne\PodgladDokumentu.tt"
 foreach (DataRow poz in _platnosciPozostalo) { 
            
            #line default
            #line hidden
            this.Write("                  <tr ");
            
            #line 185 "C:\tfs\Moria\Release\25\Src\_Doc\Przyklady\DaneArchiwalne\DaneArchiwalne\PodgladDokumentu.tt"
 if (i++%2 == 0) { 
            
            #line default
            #line hidden
            this.Write("class=\"parzysty\"");
            
            #line 185 "C:\tfs\Moria\Release\25\Src\_Doc\Przyklady\DaneArchiwalne\DaneArchiwalne\PodgladDokumentu.tt"
 } 
            
            #line default
            #line hidden
            this.Write(">\r\n                    <td class=\"left\">");
            
            #line 186 "C:\tfs\Moria\Release\25\Src\_Doc\Przyklady\DaneArchiwalne\DaneArchiwalne\PodgladDokumentu.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(poz["Nazwa"]));
            
            #line default
            #line hidden
            this.Write(":</td>\r\n                    <td class=\"kwota\"><span style=\"white-space: nowrap\">");
            
            #line 187 "C:\tfs\Moria\Release\25\Src\_Doc\Przyklady\DaneArchiwalne\DaneArchiwalne\PodgladDokumentu.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Formatuj(poz["KwotaPlatnosci"])));
            
            #line default
            #line hidden
            this.Write(" ");
            
            #line 187 "C:\tfs\Moria\Release\25\Src\_Doc\Przyklady\DaneArchiwalne\DaneArchiwalne\PodgladDokumentu.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Formatuj(_naglowek["Waluta"])));
            
            #line default
            #line hidden
            this.Write("</span></td>\r\n                  </tr>\r\n\t\t\t\t  ");
            
            #line 189 "C:\tfs\Moria\Release\25\Src\_Doc\Przyklady\DaneArchiwalne\DaneArchiwalne\PodgladDokumentu.tt"
 } } 
            
            #line default
            #line hidden
            this.Write("                </table>\r\n              </td>\r\n              <td class=\"do_zaplat" +
                    "y\">\r\n                <table cellspacing=\"0\">\r\n                  <tr class=\"razem" +
                    "\">\r\n                    ");
            
            #line 195 "C:\tfs\Moria\Release\25\Src\_Doc\Przyklady\DaneArchiwalne\DaneArchiwalne\PodgladDokumentu.tt"
 { decimal kwota = (decimal)_naglowek["KwotaDoZaplaty"]; 
					if (kwota < 0m) {
            
            #line default
            #line hidden
            this.Write("\t\t\t\t\t<td class=\"razem\">Razem do zwrotu:</td>\r\n\t\t\t\t\t");
            
            #line 198 "C:\tfs\Moria\Release\25\Src\_Doc\Przyklady\DaneArchiwalne\DaneArchiwalne\PodgladDokumentu.tt"
 } else { 
            
            #line default
            #line hidden
            this.Write("\t\t\t\t\t<td class=\"razem\">Razem do zapłaty:</td>\r\n\t\t\t\t\t");
            
            #line 200 "C:\tfs\Moria\Release\25\Src\_Doc\Przyklady\DaneArchiwalne\DaneArchiwalne\PodgladDokumentu.tt"
 } 
            
            #line default
            #line hidden
            this.Write("                    <td class=\"razem_kwota\">");
            
            #line 201 "C:\tfs\Moria\Release\25\Src\_Doc\Przyklady\DaneArchiwalne\DaneArchiwalne\PodgladDokumentu.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Formatuj(Math.Abs(kwota))));
            
            #line default
            #line hidden
            this.Write(" ");
            
            #line 201 "C:\tfs\Moria\Release\25\Src\_Doc\Przyklady\DaneArchiwalne\DaneArchiwalne\PodgladDokumentu.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Formatuj(_naglowek["Waluta"])));
            
            #line default
            #line hidden
            this.Write("</td>\r\n\t\t\t\t\t");
            
            #line 202 "C:\tfs\Moria\Release\25\Src\_Doc\Przyklady\DaneArchiwalne\DaneArchiwalne\PodgladDokumentu.tt"
 } 
            
            #line default
            #line hidden
            this.Write("                  </tr>\r\n                </table>\r\n              </td>\r\n         " +
                    "   </tr>\r\n          </table>\r\n          <table cellspacing=\"0\" class=\"podpisy\">\r" +
                    "\n            <tr>\r\n              <td class=\"opis\">Wystawił(a):</td>\r\n           " +
                    "   <td>");
            
            #line 211 "C:\tfs\Moria\Release\25\Src\_Doc\Przyklady\DaneArchiwalne\DaneArchiwalne\PodgladDokumentu.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Formatuj(_naglowek["Wystawil"])));
            
            #line default
            #line hidden
            this.Write("</td>\r\n            </tr>\r\n            <tr>\r\n              <td class=\"opis\">Odebra" +
                    "ł(a):</td>\r\n              <td>");
            
            #line 215 "C:\tfs\Moria\Release\25\Src\_Doc\Przyklady\DaneArchiwalne\DaneArchiwalne\PodgladDokumentu.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Formatuj(_naglowek["Odebral"])));
            
            #line default
            #line hidden
            this.Write("</td>\r\n            </tr>\r\n          </table>\r\n\t\t  ");
            
            #line 218 "C:\tfs\Moria\Release\25\Src\_Doc\Przyklady\DaneArchiwalne\DaneArchiwalne\PodgladDokumentu.tt"
 if (!string.IsNullOrWhiteSpace(Formatuj(_naglowek["Uwagi"]))) { 
            
            #line default
            #line hidden
            this.Write("          <table cellspacing=\"0\" class=\"uwagi\">\r\n            <tr>\r\n              " +
                    "<td class=\"opis\">Uwagi:</td>\r\n              <td>");
            
            #line 222 "C:\tfs\Moria\Release\25\Src\_Doc\Przyklady\DaneArchiwalne\DaneArchiwalne\PodgladDokumentu.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Formatuj(_naglowek["Uwagi"])));
            
            #line default
            #line hidden
            this.Write("</td>\r\n            </tr>\r\n          </table>\r\n\t\t  ");
            
            #line 225 "C:\tfs\Moria\Release\25\Src\_Doc\Przyklady\DaneArchiwalne\DaneArchiwalne\PodgladDokumentu.tt"
}
            
            #line default
            #line hidden
            this.Write("        </td>\r\n      </tr>\r\n    </table>\r\n  </body>\r\n</html>");
            return this.GenerationEnvironment.ToString();
        }
    }
    
    #line default
    #line hidden
    #region Base class
    /// <summary>
    /// Base class for this transformation
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "15.0.0.0")]
    public class PodgladDokumentuBase
    {
        #region Fields
        private global::System.Text.StringBuilder generationEnvironmentField;
        private global::System.CodeDom.Compiler.CompilerErrorCollection errorsField;
        private global::System.Collections.Generic.List<int> indentLengthsField;
        private string currentIndentField = "";
        private bool endsWithNewline;
        private global::System.Collections.Generic.IDictionary<string, object> sessionField;
        #endregion
        #region Properties
        /// <summary>
        /// The string builder that generation-time code is using to assemble generated output
        /// </summary>
        protected System.Text.StringBuilder GenerationEnvironment
        {
            get
            {
                if ((this.generationEnvironmentField == null))
                {
                    this.generationEnvironmentField = new global::System.Text.StringBuilder();
                }
                return this.generationEnvironmentField;
            }
            set
            {
                this.generationEnvironmentField = value;
            }
        }
        /// <summary>
        /// The error collection for the generation process
        /// </summary>
        public System.CodeDom.Compiler.CompilerErrorCollection Errors
        {
            get
            {
                if ((this.errorsField == null))
                {
                    this.errorsField = new global::System.CodeDom.Compiler.CompilerErrorCollection();
                }
                return this.errorsField;
            }
        }
        /// <summary>
        /// A list of the lengths of each indent that was added with PushIndent
        /// </summary>
        private System.Collections.Generic.List<int> indentLengths
        {
            get
            {
                if ((this.indentLengthsField == null))
                {
                    this.indentLengthsField = new global::System.Collections.Generic.List<int>();
                }
                return this.indentLengthsField;
            }
        }
        /// <summary>
        /// Gets the current indent we use when adding lines to the output
        /// </summary>
        public string CurrentIndent
        {
            get
            {
                return this.currentIndentField;
            }
        }
        /// <summary>
        /// Current transformation session
        /// </summary>
        public virtual global::System.Collections.Generic.IDictionary<string, object> Session
        {
            get
            {
                return this.sessionField;
            }
            set
            {
                this.sessionField = value;
            }
        }
        #endregion
        #region Transform-time helpers
        /// <summary>
        /// Write text directly into the generated output
        /// </summary>
        public void Write(string textToAppend)
        {
            if (string.IsNullOrEmpty(textToAppend))
            {
                return;
            }
            // If we're starting off, or if the previous text ended with a newline,
            // we have to append the current indent first.
            if (((this.GenerationEnvironment.Length == 0) 
                        || this.endsWithNewline))
            {
                this.GenerationEnvironment.Append(this.currentIndentField);
                this.endsWithNewline = false;
            }
            // Check if the current text ends with a newline
            if (textToAppend.EndsWith(global::System.Environment.NewLine, global::System.StringComparison.CurrentCulture))
            {
                this.endsWithNewline = true;
            }
            // This is an optimization. If the current indent is "", then we don't have to do any
            // of the more complex stuff further down.
            if ((this.currentIndentField.Length == 0))
            {
                this.GenerationEnvironment.Append(textToAppend);
                return;
            }
            // Everywhere there is a newline in the text, add an indent after it
            textToAppend = textToAppend.Replace(global::System.Environment.NewLine, (global::System.Environment.NewLine + this.currentIndentField));
            // If the text ends with a newline, then we should strip off the indent added at the very end
            // because the appropriate indent will be added when the next time Write() is called
            if (this.endsWithNewline)
            {
                this.GenerationEnvironment.Append(textToAppend, 0, (textToAppend.Length - this.currentIndentField.Length));
            }
            else
            {
                this.GenerationEnvironment.Append(textToAppend);
            }
        }
        /// <summary>
        /// Write text directly into the generated output
        /// </summary>
        public void WriteLine(string textToAppend)
        {
            this.Write(textToAppend);
            this.GenerationEnvironment.AppendLine();
            this.endsWithNewline = true;
        }
        /// <summary>
        /// Write formatted text directly into the generated output
        /// </summary>
        public void Write(string format, params object[] args)
        {
            this.Write(string.Format(global::System.Globalization.CultureInfo.CurrentCulture, format, args));
        }
        /// <summary>
        /// Write formatted text directly into the generated output
        /// </summary>
        public void WriteLine(string format, params object[] args)
        {
            this.WriteLine(string.Format(global::System.Globalization.CultureInfo.CurrentCulture, format, args));
        }
        /// <summary>
        /// Raise an error
        /// </summary>
        public void Error(string message)
        {
            System.CodeDom.Compiler.CompilerError error = new global::System.CodeDom.Compiler.CompilerError();
            error.ErrorText = message;
            this.Errors.Add(error);
        }
        /// <summary>
        /// Raise a warning
        /// </summary>
        public void Warning(string message)
        {
            System.CodeDom.Compiler.CompilerError error = new global::System.CodeDom.Compiler.CompilerError();
            error.ErrorText = message;
            error.IsWarning = true;
            this.Errors.Add(error);
        }
        /// <summary>
        /// Increase the indent
        /// </summary>
        public void PushIndent(string indent)
        {
            if ((indent == null))
            {
                throw new global::System.ArgumentNullException(nameof(indent));
            }
            this.currentIndentField = (this.currentIndentField + indent);
            this.indentLengths.Add(indent.Length);
        }
        /// <summary>
        /// Remove the last indent that was added with PushIndent
        /// </summary>
        public string PopIndent()
        {
            string returnValue = "";
            if ((this.indentLengths.Count > 0))
            {
                int indentLength = this.indentLengths[(this.indentLengths.Count - 1)];
                this.indentLengths.RemoveAt((this.indentLengths.Count - 1));
                if ((indentLength > 0))
                {
                    returnValue = this.currentIndentField.Substring((this.currentIndentField.Length - indentLength));
                    this.currentIndentField = this.currentIndentField.Remove((this.currentIndentField.Length - indentLength));
                }
            }
            return returnValue;
        }
        /// <summary>
        /// Remove any indentation
        /// </summary>
        public void ClearIndent()
        {
            this.indentLengths.Clear();
            this.currentIndentField = "";
        }
        #endregion
        #region ToString Helpers
        /// <summary>
        /// Utility class to produce culture-oriented representation of an object as a string.
        /// </summary>
        public class ToStringInstanceHelper
        {
            private System.IFormatProvider formatProviderField  = global::System.Globalization.CultureInfo.InvariantCulture;
            /// <summary>
            /// Gets or sets format provider to be used by ToStringWithCulture method.
            /// </summary>
            public System.IFormatProvider FormatProvider
            {
                get
                {
                    return this.formatProviderField ;
                }
                set
                {
                    if ((value != null))
                    {
                        this.formatProviderField  = value;
                    }
                }
            }
            /// <summary>
            /// This is called from the compile/run appdomain to convert objects within an expression block to a string
            /// </summary>
            public string ToStringWithCulture(object objectToConvert)
            {
                if ((objectToConvert == null))
                {
                    throw new global::System.ArgumentNullException(nameof(objectToConvert));
                }
                System.Type t = objectToConvert.GetType();
                System.Reflection.MethodInfo method = t.GetMethod("ToString", new System.Type[] {
                            typeof(System.IFormatProvider)});
                if ((method == null))
                {
                    return objectToConvert.ToString();
                }
                else
                {
                    return ((string)(method.Invoke(objectToConvert, new object[] {
                                this.formatProviderField })));
                }
            }
        }
        private ToStringInstanceHelper toStringHelperField = new ToStringInstanceHelper();
        /// <summary>
        /// Helper to produce culture-oriented representation of an object as a string
        /// </summary>
        public ToStringInstanceHelper ToStringHelper
        {
            get
            {
                return this.toStringHelperField;
            }
        }
        #endregion
    }
    #endregion
}
